Detemplated CF books and added a simpler sol
cpinitiative/usaco-guide pull request #1015
Opened 2021-03-22 15:45 UTC by TanishT

the current internal sol has the benq template and was kinda confusing for me. Should I have replaced his sol with mine or should I leave them both there?

2021-03-22 16:42 UTC, bqi343 commented
This is not the same as the previous solution.

2021-03-22 16:43 UTC, bqi343 requested changes

2021-03-22 16:43 UTC, bqi343 commented on solutions/CF Books.mdx
> +	int arr[n];
As noted [here](https://usaco.guide/bronze/intro-ds?lang=cpp), variable length arrays are not part of the C++ standard, so I think vector is preferred?

2021-03-23 15:05 UTC, TanishT commented
I added the previous solution back in and added my solution with a brief explanation at the bottom. Let me know if anything needs to be fixed.

2021-03-23 19:57 UTC, bqi343 requested changes

2021-03-23 19:57 UTC, bqi343 commented on solutions/CF Books.mdx
> +# C++ Implementation
> # C++ Implementation

remove this

2021-03-23 19:57 UTC, bqi343 commented on solutions/CF Books.mdx
> +## Solution 1
Only put code inside of LanguageSection.

2021-03-24 13:50 UTC, bqi343 requested changes

2021-03-24 13:50 UTC, bqi343 commented on solutions/CF Books.mdx
> +Our goal is to find the length of the longest subarray that has a sum of greater than or equal to $t$. In the first sample case, the subarray that has [$1,2,1$] sums to $5$ and has a length of $3$. T
> greater than or equal

less than or equal to?

> `[$1,2,1$]`

$[1,2,1]$ preferred

> The subarray that has [$1,2,1$] sums to $5$ and has a length of $3$.

1+2+1 is not 5?

> The subarray [$3,1,2$] that sums to $6$ also works.

I don't think so

2021-03-24 13:50 UTC, bqi343 commented on solutions/CF Books.mdx
> +Our goal is to find the length of the longest subarray that has a sum of greater than or equal to $t$. In the first sample case, the subarray that has [$1,2,1$] sums to $5$ and has a length of $3$. T
$left$

2021-03-24 13:50 UTC, bqi343 commented on solutions/CF Books.mdx
> +## Solution 1
Please put the implementation directly below the corresponding explanation (as in https://github.com/cpinitiative/usaco-guide/pull/1009/files)

2021-03-24 14:02 UTC, bqi343 requested changes

2021-03-24 14:02 UTC, bqi343 commented on solutions/CF Books.mdx
> +Our goal is to find the length of the longest subarray that has a sum of greater than or equal to $t$. In the first sample case, the subarray that has [$1,2,1$] sums to $5$ and has a length of $3$. T
shouldn't this go above both solutions?

2021-03-26 02:12 UTC, bqi343 commented on solutions/CF Books.mdx
> +## Solution 1
^ not resolved

2021-03-26 02:13 UTC, bqi343 requested changes
see unresolved comment above

2021-04-05 01:06 UTC, bqi343 requested changes

2021-04-05 01:06 UTC, bqi343 commented on solutions/CF Books.mdx
> +
also what's up w/ all these spaces :/

2021-04-20 05:57 UTC, closed without merging