Multiple of 2019 C++ Solution
cpinitiative/usaco-guide pull request #1026
Opened 2021-03-25 16:54 UTC by maggie-j-liu

2021-03-25 17:55 UTC, frodakcin commented
@thecodingwizard It seems that if you search this problem in https://usaco.guide/problems/ it says appears in "More on prefix sums" when it actually appears in intro to prefix sums

2021-03-25 18:02 UTC, maggie-j-liu commented
According to @thecodingwizard,
> the problem might have been moved. our search implementation doesn't update modules automatically yet oops

so it should be fine...?

2021-03-25 18:06 UTC, frodakcin commented
Oh ok

2021-03-26 01:39 UTC, jessechoe10 commented
Ill write a written edi for this problem a bit later. I don't really like official lmao.

2021-03-27 13:22 UTC, bqi343 requested changes

2021-03-27 13:22 UTC, bqi343 commented on solutions/AC Multiple of 2019.mdx
> +		pow = (pow * 10) % 2019;
you don't need parentheses here (`*` and `%` have the same precedence)

2021-03-28 03:13 UTC, HarryWangATX approved these changes

2021-03-28 04:10 UTC, bqi343 approved these changes

2021-03-28 04:17 UTC, merged