Added the working C++ implementation
cpinitiative/usaco-guide pull request #1031
Opened 2021-03-26 01:58 UTC by ascyrax

2021-03-28 03:12 UTC, frodakcin requested changes
Please use tabs instead of spaces. Also, please indent for every scope (including the suraj/solve function). Thanks!

Haven't looked at the implementation details yet, but there's certain things that should probably be addressed first.

2021-03-28 03:12 UTC, frodakcin commented on solutions/USACO dec15-high-card-low-card-gold.mdx
> +#define ioss ios::sync_with_stdio(false);cin.tie(0);
Please use no more macros than what is allowed here:
https://usaco.guide/general/contributing/#c-template

2021-03-28 03:12 UTC, frodakcin commented on solutions/USACO dec15-high-card-low-card-gold.mdx
> +
Unnecessary blank space?

2021-03-28 03:12 UTC, frodakcin commented on solutions/USACO dec15-high-card-low-card-gold.mdx
> +/////////////////////////////////////////////////////////////////
What is this here for?

2021-03-28 03:12 UTC, frodakcin commented on solutions/USACO dec15-high-card-low-card-gold.mdx
> +    suraj();
I think it would be more intuitive to call this function solve() or something?

2021-03-28 03:12 UTC, frodakcin commented on solutions/USACO dec15-high-card-low-card-gold.mdx
> +    such that maxm nos among d,e,f are higher than a corresponding value of a,b,c;
Not properly commented

2021-03-28 03:12 UTC, frodakcin commented on solutions/USACO dec15-high-card-low-card-gold.mdx
> +//////////////////////////////////////////////////////
Why is this line here?

2021-04-05 01:05 UTC, bqi343 commented
Closing due to inactivity.

2021-04-05 01:05 UTC, closed without merging