Added explanation for find centroid algorithm
cpinitiative/usaco-guide pull request #1070
Opened 2021-03-31 02:31 UTC by jeffarjeffar

I think this makes it easier to understand. 
You guys never provided an explanation for how to find the centroid, and jumped directly to the centroid decomp algorithm.

2021-03-31 21:19 UTC, bqi343 requested changes

2021-03-31 21:19 UTC, bqi343 commented on content/5_Plat/Centroid.mdx
> +We can find a centroid in a tree by starting at the root. Each step, loop through all of it's children. If all of it's children have subtree size less than or equal to $\frac{N}{2}$, then it is a cen
its

2021-03-31 21:19 UTC, bqi343 commented on content/5_Plat/Centroid.mdx
> +We can find a centroid in a tree by starting at the root. Each step, loop through all of it's children. If all of it's children have subtree size less than or equal to $\frac{N}{2}$, then it is a cen
> therwise, move to the child whose subtree is more than $\frac{N}{2}$

subtree size

2021-03-31 21:19 UTC, bqi343 commented on content/5_Plat/Centroid.mdx
> +The **centroid** of a tree is a node which, if rooted, results in no other nodes
I think the following is better?

> a node such that rooting the tree at that node results in no other ...

2021-04-05 01:02 UTC, bqi343 requested changes

2021-04-05 01:02 UTC, bqi343 commented on content/5_Plat/Centroid.mdx
> +child whose subtree is more than $\frac{N}{2}$ and repeat until you find a
> whose subtree is more than $\frac{N}{2}$

subtree size is greater than $\frac{N}{2}$?

also pls re-request review next time

2021-04-07 01:40 UTC, bqi343 approved these changes

2021-04-08 15:53 UTC, dolphingarlic requested changes

2021-04-08 15:53 UTC, dolphingarlic commented on content/5_Plat/Centroid.mdx
> +We can find a centroid in a tree by starting at the root. Each step, loop
Move this paragraph to outside the LanguageSection

2021-04-10 12:43 UTC, merged