Puts DP on Bitmasks and Ranges in Gold
cpinitiative/usaco-guide pull request #1111
Opened 2021-04-04 23:23 UTC by Aryansh-S

Moves from plat to gold and updates ordering.ts

2021-04-05 01:08 UTC, bqi343 reviewed
might want to rename DP on Bitmasks / DP on Ranges to Bitmask DP and Range DP respectively to be consistent with "Knapsack DP"?

2021-04-05 01:19 UTC, Aryansh-S commented
> might want to rename DP on Bitmasks / DP on Ranges to Bitmask DP and Range DP respectively to be consistent with "Knapsack DP"?

Done, go ahead and check if this works and merge if everything checks out

2021-04-05 01:27 UTC, bqi343 approved these changes
will wait for some more reviews

2021-04-05 03:39 UTC, dongliu0426 approved these changes

2021-04-05 05:27 UTC, dolphingarlic approved these changes

2021-04-05 05:27 UTC, dolphingarlic commented
Should I merge?

2021-04-05 06:17 UTC, thecodingwizard commented
Can we add redirects from the old URL? Front matter accepts a redirects field that's an array of old URL paths

2021-04-05 06:29 UTC, Aryansh-S commented
> Can we add redirects from the old URL? Front matter accepts a redirects field that's an array of old URL paths
> 
> Also does frequency need to be updated?

Probably a good idea to mention the people who handle that

2021-04-05 06:39 UTC, thecodingwizard requested changes

2021-04-05 06:39 UTC, thecodingwizard commented on content/4_Gold/DP_Bitmasks.mdx
>    - intro-bitwise
Should add a redirect somewhere in the frontmatter:

```
redirects:
  - /plat/dp-bitmasks
```

2021-04-05 06:39 UTC, thecodingwizard commented
@Aryansh-S I think we can just set frequency to 0 for now unless somebody else has a different opinion?

2021-04-05 07:56 UTC, Farrius approved these changes

2021-04-05 14:54 UTC, andrewwangva commented
> @Aryansh-S I think we can just set frequency to 1 for now (for both modules) unless somebody else has a different opinion?

1 seems good

2021-04-06 22:14 UTC, Aryansh-S commented
I've changed the frequencies for both to 1. @thecodingwizard after your review, I think you should merge

2021-04-06 22:53 UTC, merged