Problem Suggestion: Add "subarray squares" to Platinum - Divide & Conquer - DP
cpinitiative/usaco-guide pull request #1294
Opened 2021-04-11 23:42 UTC by jeffkmeng

*Problem Suggestion Issue Migration Bot* (UID PROB_SUGG_MIGRATE_BOT) suggested adding the problem [subarray squares](https://cses.fi/problemset/task/2086) to the `dnc_general` table of the module [Platinum - Divide & Conquer - DP](https://usaco.guide/plat/DC-DP#problemlist-dnc_general).

**Automatically Generated JSON:**
```json
{
  "uniqueId": "cses-2086",
  "name": "subarray squares",
  "url": "https://cses.fi/problemset/task/2086",
  "source": "CSES",
  "difficulty": "Easy",
  "isStarred": false,
  "tags": [
    ""
  ],
  "solutionMetadata": {
    "kind": "none"
  }
}
```
**Additional Notes**:
None
(Closes #1099)

*This PR was automatically generated from a user-submitted problem suggestion on the USACO guide.*

2021-06-08 19:23 UTC, dongliu0426 commented on content/5_Plat/DC-DP.problems.json
> +      "tags": [""],
```suggestion
      "tags": [],
```

2021-06-08 19:23 UTC, dongliu0426 approved these changes

2021-06-08 19:27 UTC, dongliu0426 commented on content/5_Plat/DC-DP.problems.json
> +      "name": "subarray squares",
```suggestion
      "name": "Subarray Squares",
```

2021-06-10 02:21 UTC, bqi343 requested changes
move to convex hull trick

note - this is somewhat similar to circular barn

2021-06-11 19:40 UTC, andrewwangva commented
I agree with ben this is very similar to cbarn - but also how do we differentiate between cht/d&c if they can be solved w both?

2021-06-11 22:59 UTC, bqi343 commented
cht removes a log factor from the complexity

2021-06-19 10:48 UTC, bqi343 requested changes
this is essentially the same as APIO "split the sequence" - do we want to keep both?

2021-07-01 20:47 UTC, closed without merging