Added Java Sol to cses1634 minimum coins
cpinitiative/usaco-guide pull request #1332
Opened 2021-04-14 14:15 UTC by TruaShamu

2021-04-14 15:23 UTC, dongliu0426 requested changes
also update the author list

2021-04-14 15:23 UTC, dongliu0426 commented on solutions/CSES Minimum Coins.mdx
> +		DP[curWeight] = min(DP[curWeight], DP[curWeight - coin[i] + 1). */
```suggestion
		DP[curWeight] = min(DP[curWeight], DP[curWeight - coin[i]] + 1). */
```

2021-04-15 12:32 UTC, TruaShamu commented
done :)

2021-04-16 18:39 UTC, dongliu0426 requested changes

2021-04-16 18:39 UTC, dongliu0426 commented on solutions/CSES Minimum Coins.mdx
> +
```suggestion
```

2021-04-16 18:39 UTC, dongliu0426 commented on solutions/CSES Minimum Coins.mdx
> +## Implementation
move `## Implementation` outside `<LanguageSection>` and add `**Time Complexity**: \mathcal O(N\cdot X)` below it

2021-04-17 00:47 UTC, TruaShamu commented
Sorry. It should be fixed now.

2021-04-17 02:36 UTC, dongliu0426 commented on solutions/CSES Minimum Coins.mdx
> +**Time Complexity**: \mathcal O(N\cdot X)
```suggestion
**Time Complexity**: $\mathcal O(N\cdot X)$
```
oops

2021-04-17 16:45 UTC, dongliu0426 approved these changes

2021-04-19 00:43 UTC, TruaShamu commented
I'm sorry, I'm dumb... but what does this mean?

UI Tests: Unreviewed
1 change must be accepted as baseline to pass UI tests

2021-04-19 00:47 UTC, maggie-j-liu commented
I think those are just for storybook, so you don't have to worry about them. The important checks are the pull request tests and the deployment.

2021-04-19 01:15 UTC, TruaShamu commented
Okay, thanks!

2021-04-20 20:46 UTC, TruaShamu commented
So, if it's passed all checks and has been reviewed, then can the pull request be merged please?

2021-04-20 20:52 UTC, merged