Add General Centroid Code
cpinitiative/usaco-guide pull request #1339
Opened 2021-04-15 12:23 UTC by nirvanarsc

Hello, I've fixed the Java general Centroid code for https://usaco.guide/plat/centroid?lang=java. But I don't know c++, so maybe someone else can reference this and update the c++ code 😛 

I have a successful submission with that code here https://codeforces.com/contest/342/submission/113088188

2021-04-15 13:01 UTC, nirvanarsc commented
> Hey there! 👋 This repository uses the [Prettier](https://prettier.io) code style.
> 
> You forgot to format these files in your pull request:
> 
> * content/5_Plat/Centroid.mdx
> 
> The [Prettier installation guide](https://prettier.io/docs/en/install.html) is a good place to get started with formatting your code properly.
> Thanks!
> 
> ❤️
> 
> Your friendly [Prettifier bot](https://www.prettifier.io).

<img width="1117" alt="Screen Shot 2021-04-15 at 21 56 58" src="https://user-images.githubusercontent.com/1153337/114873208-0426b400-9e36-11eb-9f88-af0f010f3360.png">
Maybe I'm missing something, is this not how you run prettier?

2021-04-15 13:31 UTC, bqi343 commented
> Maybe I'm missing something, is this not how you run prettier?

@thecodingwizard ?

2021-04-15 15:03 UTC, thecodingwizard commented
Either works. You can also do yarn prettier --write filepath

2021-04-15 22:34 UTC, frodakcin requested changes
Looks good. Just one thing: can you switch to tabs instead of spaces in the sample code?

2021-04-15 22:34 UTC, frodakcin commented on content/5_Plat/Centroid.mdx
> +description: 'Decomposing a tree to facilitate path computations.'
Nice catch!

2021-04-19 06:07 UTC, nirvanarsc commented
>Either works. You can also do yarn prettier --write filepath

I see thanks just asking cause I got the message from the bot that I didn't format the file, but then running the command says its already formatted well

>Looks good. Just one thing: can you switch to tabs instead of spaces in the sample code?

Updated could you take another look 🙇

2021-04-22 17:05 UTC, frodakcin approved these changes

2021-04-22 17:05 UTC, merged