Create cpp Solution and Analysis to USACO Snow Cow
cpinitiative/usaco-guide pull request #1389
Opened 2021-04-23 05:14 UTC by dutinmeow

Some of the formatting might be messed up because I'm not too familiar with markdown.

2021-04-23 15:16 UTC, maggie-j-liu commented on solutions/USACO feb19-snowcow.mdx
> +arrays \texttt{LL[x]} and \texttt{RR[x]}. Note that each node's subtree size can be calculated by simply subtracting the bounds of this range.
```suggestion
arrays $\texttt{LL[x]}$ and $\texttt{RR[x]}$. Note that each node's subtree size can be calculated by simply subtracting the bounds of this range.
```

2021-04-23 18:58 UTC, dongliu0426 requested changes
code looks good

2021-04-23 18:58 UTC, dongliu0426 commented on solutions/USACO feb19-snowcow.mdx
> +We then construct a lazy segment tree on an empty array as a base. This will represent the number of distinct colors at each node
add a period

2021-04-23 18:58 UTC, dongliu0426 commented on solutions/USACO feb19-snowcow.mdx
> +Similarly to the official solution, we keep track of updates for each color. For each new update ($c$, $x$), we only update the tree by:
```suggestion
Similarly to the official solution, we keep track of updates for each color. For each new update $(c, x)$, we only update the tree by: 
```

2021-04-26 15:25 UTC, dongliu0426 approved these changes

2021-04-26 16:32 UTC, dolphingarlic commented
Using two BITs is essentially the same as using a lazy segtree for range update range sum though

Also there's no need to repeat what's already in the editorial

2021-06-13 19:45 UTC, dolphingarlic commented
@dutinmeow you still there?

2021-06-16 17:34 UTC, dolphingarlic commented
I guess not...

Feel free to reopen if you come back to this

2021-06-16 17:34 UTC, closed without merging