add java sol to cses array description
cpinitiative/usaco-guide pull request #1459
Opened 2021-05-04 15:31 UTC by TruaShamu

2021-05-04 17:51 UTC, SansPapyrus683 requested changes
just some formatting issues
also, i'd prefer if you used more intuitive variable names `arr` and `maxVal`, this would make it easier to read

2021-05-04 17:51 UTC, SansPapyrus683 commented on solutions/CSES Array Description.mdx
> +public class cses1746 {
Rename this to `ArrayDesc` or something else.

2021-05-04 17:51 UTC, SansPapyrus683 commented on solutions/CSES Array Description.mdx
> +	public static int MOD = (int) 1e9 + 7;
`public static final int` instead?

2021-05-04 17:51 UTC, SansPapyrus683 commented on solutions/CSES Array Description.mdx
> +		r = new BufferedReader(new InputStreamReader(System.in));
You can probably condense these two statements into a single line.

2021-05-04 17:51 UTC, SansPapyrus683 commented on solutions/CSES Array Description.mdx
> +		/* Process the first element in the array. */
use `//` instead of that comment format

2021-05-04 17:51 UTC, SansPapyrus683 commented on solutions/CSES Array Description.mdx
> +					if (1<=k && k <= M) {
add whitespace between operators plz

2021-05-04 17:51 UTC, SansPapyrus683 commented on solutions/CSES Array Description.mdx
> +		int[][] dp = new int[N][M + 1];
perhaps add a short explanation of what this dp array contains
like `dp[i][j] contains (insert whatever here)`

2021-05-04 21:15 UTC, SansPapyrus683 requested changes

2021-05-04 21:15 UTC, SansPapyrus683 commented on solutions/CSES Array Description.mdx
> +					int[] arr = new int[] {j - 1, j, j + 1};
rename this to something like `neighborVals` or something

2021-05-04 21:15 UTC, SansPapyrus683 commented on solutions/CSES Array Description.mdx
> +		st = new StringTokenizer(r.readLine());
maybe rename this to `arr` so it's obvious that it contains the elements?

2021-05-04 21:15 UTC, SansPapyrus683 commented on solutions/CSES Array Description.mdx
> +}
lines 102, 105, and 135 seem to be unnecessary whitespace

2021-05-04 23:05 UTC, SansPapyrus683 approved these changes

2021-05-05 00:34 UTC, jessechoe10 approved these changes

2021-05-05 05:24 UTC, merged