Swap Game C++ Solution
cpinitiative/usaco-guide pull request #1499
Opened 2021-05-10 20:39 UTC by maggie-j-liu

2021-05-10 21:54 UTC, dongliu0426 approved these changes

2021-05-12 08:20 UTC, dolphingarlic requested changes

2021-05-12 08:20 UTC, dolphingarlic commented on solutions/CSES Swap Game.mdx
> +represent each $\texttt{State}$ as the $\texttt{grid}$: an array of $9$ numbers,
Do you really need texttt for state and grid?

2021-05-12 08:20 UTC, dolphingarlic commented on solutions/CSES Swap Game.mdx
> +bool vis[9][9][9][9][9][9][9][9][9];
Could you try encoding each grid as a single base 9 number please? I think it'll look much neater that way

2021-05-14 17:23 UTC, merged