Update CSES Labyrinth.mdx
cpinitiative/usaco-guide pull request #1503
Opened 2021-05-11 19:41 UTC by TruaShamu

add java implementation to cses labyrinth

2021-05-12 17:42 UTC, TruaShamu commented
...Since it's passed all the checks, can we merge the pr?

2021-05-12 17:48 UTC, maggie-j-liu requested changes

2021-05-12 17:48 UTC, maggie-j-liu commented on solutions/CSES Labyrinth.mdx
> +```java
use tabs instead of spaces to indent

2021-05-12 17:48 UTC, maggie-j-liu commented on solutions/CSES Labyrinth.mdx
> +    // Coordinates for point A and B.
```suggestion
    //Coordinates for points A and B.
```

2021-05-12 17:52 UTC, maggie-j-liu commented
Usually you need 1-2 team approvals and 1 core approval to merge; you can request reviews since you're a content author.

2021-05-12 17:53 UTC, TruaShamu commented
ok, thanks.

2021-05-13 15:09 UTC, dongliu0426 approved these changes

2021-05-13 17:20 UTC, maggie-j-liu approved these changes

2021-05-14 01:32 UTC, merged