Create USACO dec20-DoYouKnowYourABCs.mdx
cpinitiative/usaco-guide pull request #1522
Opened 2021-05-14 20:32 UTC by sathu-beep

solution to https://usaco.guide/general/expected?lang=cpp 
in java, since there are a ton of solutions in CPP and the official sol is in cpp

2021-05-15 23:24 UTC, dongliu0426 requested changes

2021-05-15 23:24 UTC, dongliu0426 commented on solutions/USACO dec20-DoYouKnowYourABCs.mdx
> +		for(int i=0; i<array.length; i++){
```suggestion
		for(int i = 0; i<array.length; i++){
```

2021-05-15 23:39 UTC, maggie-j-liu requested changes

2021-05-15 23:39 UTC, maggie-j-liu commented on solutions/USACO dec20-DoYouKnowYourABCs.mdx
> +		b = abc-a-c;
```suggestion
			if(array[i] == bc){
				bcindex = i;
			}
		}
		array[bcindex] = 0;
		largest = 0;
		for(int i = 0; i < array.length; i++){
			if(array[i] >= largest){
				ca = array[i];
				largest = ca;  
			} 
		}
		c = ca - a;
		b = abc - a - c;
```

2021-05-15 23:39 UTC, maggie-j-liu commented on solutions/USACO dec20-DoYouKnowYourABCs.mdx
> +			if(array[i]>=largest){
```suggestion
		for(int i = 0; i < 7; i++){
			array[i] = sc.nextInt();  
		}
		int a = 0, b = 0, c = 0, abc = 0, bc, ba, ca = 0;
		int abcindex = 0, aindex = 0, bcindex = 0;
		int smallest = 1000000000;
		int largest = 0;
		for(int i = 0; i < array.length; i++){
			if(array[i] <= smallest){
				a = array[i];
				smallest = a;
				aindex = i;
			}
			if(array[i] >= largest){
```

2021-05-16 23:32 UTC, maggie-j-liu approved these changes

2021-05-16 23:33 UTC, dongliu0426 approved these changes

2021-05-16 23:34 UTC, thecodingwizard requested changes
wait this code seems too complicated; there's a much easier solution if you just sort the array. this problem is part of the "expected knowledge" section of the Guide, so it would be better if the solution was simpler / less intimidating. Even though sorting isn't necessary for Bronze I think it's acceptable to consider that as prerequisite knowledge...

2021-05-16 23:49 UTC, dongliu0426 approved these changes

2021-05-16 23:50 UTC, maggie-j-liu approved these changes

2021-05-17 00:37 UTC, merged