Update usaco-598.mdx
cpinitiative/usaco-guide pull request #1596
Opened 2021-05-25 17:43 UTC by TruaShamu

Add java implementation to usaco radio contact.

2021-05-25 20:39 UTC, dongliu0426 commented on solutions/usaco-598.mdx
> +public static int[][] bLocs;
could you indent this?

2021-05-25 22:02 UTC, nwatx requested changes

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +		//If FJ stays still, and Bessie moves.
```suggestion
		// If FJ stays still, and Bessie moves.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +				//The current cost at this cell.
```suggestion
				// The current cost at this cell.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +				//Calculate different costs based on who moves.
```suggestion
				// Calculate different costs based on who moves.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +	//Fill the location arrays for FJ and Bessie.
```suggestion
	// Fill the location arrays for FJ and Bessie.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +	//Square of the distance between points a and b.
```suggestion
	// Square of the distance between points a and b.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +		//FJ's original location.
```suggestion
		// FJ's original location.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +		fjLocs = new int[N + 1][2]; //FJ's locations.
```suggestion
		fjLocs = new int[N + 1][2]; // FJ's locations.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +		bLocs = new int[M + 1][2]; //Bessie's locations.
```suggestion
		bLocs = new int[M + 1][2]; // Bessie's locations.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +		//FJ's original location.
```suggestion
		// FJ's original location.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +		//Bessie's original location.
```suggestion
		// Bessie's original location.
```

2021-05-25 22:02 UTC, nwatx commented on solutions/usaco-598.mdx
> +		//Find locations that the two visit.
```suggestion
		// Find locations that the two visit.
```

2021-05-25 23:26 UTC, dongliu0426 approved these changes

2021-05-25 23:34 UTC, nwatx requested changes

2021-05-25 23:34 UTC, nwatx commented on solutions/usaco-598.mdx
> +			//Location chance based on direction.
```suggestion
			// Location chance based on direction.
```
missed one :p

2021-05-26 00:49 UTC, nwatx requested changes

2021-05-26 00:49 UTC, nwatx commented on solutions/usaco-598.mdx
> +		//If FJ moves, and Bessie stays still.
```suggestion
		// If FJ moves, and Bessie stays still.
```

2021-05-26 01:50 UTC, nwatx approved these changes

2021-05-26 03:57 UTC, merged