Bucket Brigade java and python solutions
cpinitiative/usaco-guide pull request #1612
Opened 2021-05-28 20:25 UTC by maggie-j-liu

2021-05-28 22:29 UTC, nathangong approved these changes

2021-05-29 03:11 UTC, HarryWangATX requested changes
I think we are using Kattio for java io for consistency

2021-05-29 03:31 UTC, maggie-j-liu commented
Is Kattio really necessary? This is in general/expected knowledge, i think it's better to keep it simple?

2021-05-29 03:41 UTC, nathangong commented
Wouldn't Kattio make the code more simple and readable? Also, I think it says [here](https://usaco.guide/general/adding-solution?lang=java#java) that Kattio is preferred for consistency/readability.

2021-05-29 04:55 UTC, merged