Added persistent array implementation
cpinitiative/usaco-guide pull request #1618
Opened 2021-05-29 13:36 UTC by dolphingarlic

Also, should we maybe move this before introducing the persistent segtree?

2021-05-29 15:35 UTC, bqi343 commented
I was hoping for a path copying approach for persistent array before persistent segtree

2021-05-29 15:51 UTC, dolphingarlic commented
Would that have the same implementation as a persistent segtree then? (Minus the range query)

2021-06-09 15:55 UTC, bqi343 commented
essentially yes

2021-06-10 02:22 UTC, bqi343 requested changes
^ above

2021-06-11 20:40 UTC, dolphingarlic commented
I kept the fat nodes in because I think it's still worthwhile to know the alternative approaches, even if they are worse

2021-06-11 22:59 UTC, bqi343 requested changes

2021-06-11 22:59 UTC, bqi343 commented on content/6_Advanced/Persistent.mdx
> +	roots[curr_time] = new Node(roots[prev_time]); // First, copy the root
^ isn't this line not necessary?

2021-06-11 22:59 UTC, bqi343 commented on content/6_Advanced/Persistent.mdx
> +	Node(Node *cp) : val(cp->val), l(cp->l), r(cp->r) {}
same as below

2021-06-11 22:59 UTC, bqi343 commented on content/6_Advanced/Persistent.mdx
> +in persistent segment trees, since lazy propagation doesn't play well with path
actually, lazy is possible

2021-06-12 21:10 UTC, bqi343 approved these changes

2021-06-13 10:55 UTC, merged