Angrycows Bronze Fix + Code Simplification
cpinitiative/usaco-guide pull request #1636
Opened 2021-05-31 00:51 UTC by HarryWangATX

2021-05-31 00:56 UTC, maggie-j-liu requested changes

2021-05-31 00:56 UTC, maggie-j-liu commented on solutions/usaco-592.mdx
> +		while(next + direction >= 0 && next + direction < N && abs(positions[next + direction] - positions[prev]) <= radius) {
this line is too long; maybe wrap at the second `&&`?

2021-05-31 00:56 UTC, maggie-j-liu commented on solutions/usaco-592.mdx
> +	for (int i = 0; i < N; i++) {
```suggestion
	for(int i = 0; i < N; i++) {
```
to be consistent

2021-05-31 01:20 UTC, maggie-j-liu approved these changes

2021-05-31 13:55 UTC, merged

2023-07-09 18:12 UTC, bqi343 commented
This PR deleted part of the internal solution, will add back.