4SUM Solution
cpinitiative/usaco-guide pull request #1637
Opened 2021-05-31 02:37 UTC by nwatx

2021-05-31 15:42 UTC, dongliu0426 approved these changes

2021-06-02 06:55 UTC, dolphingarlic requested changes

2021-06-02 06:55 UTC, dolphingarlic commented on solutions/cses-1642.mdx
> +values that we can achieve, and the two numbers that add up to
> all the values that we can achieve

What do you mean by this?

2021-06-02 06:55 UTC, dolphingarlic commented on solutions/cses-1642.mdx
> +and $b$ that sum up to a mapped value such that no indice of $a, b, c, d$ is repeated.
```suggestion
and $b$ that sum up to a mapped value such that no index is repeated.
```

2021-06-03 02:20 UTC, nwatx commented on solutions/cses-1642.mdx
> +that value using a map. Then, the problem is reduced to finding two numbers $a$
```suggestion
values that we can achieve using a pair of numbers, and the indices for both numbers in the pair using a map. Then, the problem is reduced to finding two numbers $a$
```

2021-06-04 20:48 UTC, merged