Created Solution for "CSES 1188 - Bit Inversions"
cpinitiative/usaco-guide pull request #1784
Opened 2021-06-20 23:44 UTC by dutinmeow

2021-06-20 23:52 UTC, sathu-beep requested changes
lmfao it failed vercel find out why

2021-06-20 23:57 UTC, dutinmeow commented
The error message says that the internal solution to the problem is missing. I'm not sure as to if this is a normal problem for changing the JSON file and uploading a new solution or if my file name is just wrong.

2021-06-20 23:58 UTC, bqi343 requested changes

2021-06-20 23:58 UTC, bqi343 commented on solutions/cses-1188.mdx
> +id: CSES-1188
^ should be `cses-1188`

2021-06-20 23:59 UTC, bqi343 commented
> lmfao it failed vercel find out why

not helpful ...

2021-06-21 00:00 UTC, sathu-beep commented
> > lmfao it failed vercel find out why
> 
> not helpful ...

😔 sorry next time I will try to be more helpful

2021-06-21 00:38 UTC, bqi343 requested changes

2021-06-21 00:38 UTC, bqi343 commented on solutions/cses-1188.mdx
> +- $w.L = u.L + v.L$
^ why not use the same names as your code below?

2021-06-21 00:38 UTC, bqi343 commented on solutions/cses-1188.mdx
> +Clearly, a bit flip operation corresponds to a point update on the segment tree and a longest homogeneous subarray query corresponds to the $A$ value of
```suggestion
A bit flip operation corresponds to a point update on the segment tree and a longest homogeneous subarray query corresponds to the $A$ value of 
```

2021-06-21 00:38 UTC, bqi343 commented on solutions/cses-1188.mdx
> +- The length of the subarray (equivalent to $r - l + 1$) (denote this as $L$)
^ this assumes that you are looking for the longest run of a fixed bit value (e.g. the longest run of 1s)

2021-06-21 01:29 UTC, bqi343 requested changes

2021-06-21 01:29 UTC, bqi343 commented on solutions/cses-1188.mdx
> +- If $a.P = u.L$, then $c.P = a.L + b.P$; otherwise, $c.P = a.P$
still occurrences of `u` and `v`

2021-06-21 01:29 UTC, bqi343 commented on solutions/cses-1188.mdx
> +- If $b.S = v.L$, then $c.S = b.S + a.S$; otherwise, $c.S = b.S$
```suggestion
- If $b.S = b.L$, then $c.S = b.L + a.S$; otherwise, $c.S = b.S$
```

so it's consistent w/ code below

2021-06-21 12:58 UTC, bqi343 approved these changes

2021-06-21 17:04 UTC, dongliu0426 approved these changes
Can also be done with one segtree

2021-06-21 17:36 UTC, merged