Alternate Solution to CSES 1621 - Distinct Numbers
cpinitiative/usaco-guide pull request #1789
Opened 2021-06-21 03:32 UTC by dutinmeow

2021-06-21 03:34 UTC, dutinmeow commented
I just saw the set solution in the Introduction to Sets and Maps module, but the alternate solution should still be on the solution page

2021-06-21 03:51 UTC, maggie-j-liu commented
Hmm i don't know if duplicating solutions is a good idea, but can you copy paste the java and python code too?

2021-06-21 05:11 UTC, dutinmeow commented
> Hmm i don't know if duplicating solutions is a good idea, but can you copy paste the java and python code too?

Done, although I'm not sure who wrote the Java or Python codes so I can't credit them

2021-06-21 13:01 UTC, bqi343 commented
> I just saw the set solution in the Introduction to Sets and Maps module, but the alternate solution should still be on the solution page

why not just link to the module?

2021-06-21 18:35 UTC, dutinmeow commented
I've added the link to the module in the solution, but I think it's still nice to have all the methods of solving a problem within the solution page

2021-06-21 18:58 UTC, bqi343 commented
personally, not duplicating material takes priority over that. let's see what others think

2021-06-21 18:59 UTC, bqi343 requested changes

2021-06-21 18:59 UTC, bqi343 commented on solutions/cses-1621.mdx
> +Sets and Maps are introduced [here](https://usaco.guide/bronze/intro-sets?lang=py). Furthermore, using (an unordered set)[https://usaco.guide/gold/unordered?lang=py] will enable an $\mathcal{O}(n)$ c
why `lang=py`?

2021-06-21 18:59 UTC, bqi343 commented on solutions/cses-1621.mdx
> +By using an std::set in C++ or its equivalents in other languages, we can take advantage of the fact that a set only stores a copy of an element once.
```suggestion
By using an `std::set` in C++ or its equivalents in other languages, we can take advantage of the fact that a set only stores a copy of an element once.
```

2021-06-22 02:22 UTC, sathu-beep requested changes
address formatting issues

2021-06-22 02:22 UTC, sathu-beep commented on solutions/cses-1621.mdx
> +import java.util.StringTokenizer;
```suggestion
import java.io*;
import java.util*;
```
There is no reason not to do this it makes the code much nicer to look at

2021-06-22 02:22 UTC, sathu-beep commented on solutions/cses-1621.mdx
> +
```suggestion
```
whitespace 😒

2021-06-22 02:22 UTC, sathu-beep commented on solutions/cses-1621.mdx
> +print(len(distinct_nums))
```suggestion
```py
n = int(input()) # unused
distinct_nums = {int(x) for x in input().split()}
print(len(distinct_nums))
```

just implement the more efficient solution 
its not that much different than the first that it deserves to be an entire new block of code

2021-06-22 02:22 UTC, sathu-beep commented on solutions/cses-1621.mdx
> +print(len(distinct_nums))
oops i think that the ``` at the end of the python code were removed when I formatted this comment make sure to add them back

2021-06-22 02:23 UTC, sathu-beep commented on solutions/cses-1621.mdx
> +print(len(distinct_nums))
@SansPapyrus683 😏 i vow to be more nitpicky than you in the future

2021-06-27 21:57 UTC, bqi343 commented
@maggie-j-liu what do you think? do you want to replace this w/ a link to the module? 

https://usaco.guide/bronze/intro-sets#solution---distinct-numbers

2021-06-27 22:01 UTC, maggie-j-liu commented
> @maggie-j-liu what do you think? do you want to replace this w/ a link to the module?
> 
> https://usaco.guide/bronze/intro-sets#solution---distinct-numbers

Yeah, I think just linking to the module is fine, since it's unnecessary to copy code from one place to another

2021-06-27 22:02 UTC, sathu-beep reviewed
format

2021-06-27 22:02 UTC, sathu-beep commented on solutions/cses-1621.mdx
> +
```suggestion
```
whitespace

2021-06-27 22:02 UTC, sathu-beep commented on solutions/cses-1621.mdx
> +
```suggestion
```

2021-06-27 22:02 UTC, sathu-beep commented on solutions/cses-1621.mdx
> +</CPPSection>
```suggestion
</CPPSection>

```

2021-06-27 22:52 UTC, bqi343 commented
see #1833

2021-06-27 22:52 UTC, closed without merging