More video solutions for silver questions p738
cpinitiative/usaco-guide pull request #1790
Opened 2021-06-21 16:26 UTC by cskitty

2021-06-23 04:35 UTC, nwatx requested changes

2021-06-23 04:35 UTC, nwatx commented on solutions/usaco-738.mdx
> +
would be beneficial to have the code here, but good video.

2021-06-23 04:36 UTC, nwatx commented on solutions/usaco-738.mdx
> +
or at least linked from the video

2021-07-06 00:16 UTC, nwatx requested changes

2021-07-06 00:21 UTC, frodakcin commented on solutions/usaco-738.mdx
> +	sort(cows.begin(), cows.end(), [](pair<ll, ll> a, pair<ll, ll> b) {return a.s < b.s;});
I think an exception can be made here -- It's not exactly practical to shorten this.

2021-07-06 00:24 UTC, maggie-j-liu commented on solutions/usaco-738.mdx
> +	sort(cows.begin(), cows.end(), [](pair<ll, ll> a, pair<ll, ll> b) {return a.s < b.s;});
try putting the function body on a new line like
```cpp
	sort(cows.begin(), cows.end(), [](pair<ll, ll> a, pair<ll, ll> b) {
		return a.s < b.s;
	});
```

2021-07-06 00:25 UTC, nwatx commented on solutions/usaco-738.mdx
> +	sort(cows.begin(), cows.end(), [](pair<ll, ll> a, pair<ll, ll> b) {return a.s < b.s;});
alternatively you could use `auto`

2021-07-06 00:29 UTC, frodakcin commented on solutions/usaco-738.mdx
> +	sort(cows.begin(), cows.end(), [](pair<ll, ll> a, pair<ll, ll> b) {return a.s < b.s;});
mm sure, though personally I think the current way looks the nicest

2021-07-06 00:30 UTC, nwatx requested changes

2021-07-06 00:30 UTC, nwatx commented on solutions/usaco-738.mdx
> +ll N;
```suggestion
int N;
```

2021-07-06 00:30 UTC, frodakcin requested changes

2021-07-06 00:30 UTC, frodakcin commented on solutions/usaco-738.mdx
> +(Because it requires sorting the input, which is $\mathcal{O}(N\log N)$).
```suggestion
**Time Complexity:** $\mathcal{O}(N)$ after sorting
```

2021-07-06 00:31 UTC, maggie-j-liu requested changes
unrelated, but: why's the diff so weird? it looks like you added the whole file but the java code was there before???

2021-07-06 00:31 UTC, maggie-j-liu commented on solutions/usaco-738.mdx
> +author: Sofia Yang
add your name to authors + remove blank line

2021-07-06 00:31 UTC, maggie-j-liu commented on solutions/usaco-738.mdx
> +``` java
```suggestion
```java
```

2021-07-06 00:31 UTC, maggie-j-liu commented on solutions/usaco-738.mdx
> +#define ll long long
would prefer 
```suggestion
using ll = long long;
```

2021-07-06 00:31 UTC, maggie-j-liu commented on solutions/usaco-738.mdx
> +
```suggestion
```

2021-08-01 23:16 UTC, bqi343 commented
@frodakcin @maggie-j-liu

2021-08-01 23:20 UTC, maggie-j-liu approved these changes
i think you might need to fix the merge conflicts though

2021-08-02 03:19 UTC, nwatx approved these changes

2021-08-09 03:51 UTC, maggie-j-liu commented
@cskitty please fix the merge conflicts

2021-08-11 00:57 UTC, HarryWangATX requested changes
add `## Implementation`

2021-08-14 19:06 UTC, maggie-j-liu commented
@cskitty i still see this?
![image](https://user-images.githubusercontent.com/63619830/129457701-d6386309-ad2a-4aab-bcee-71185ed7a349.png)

2021-08-14 23:37 UTC, merged