Alternate Solution for "POI - Cards"
cpinitiative/usaco-guide pull request #1802
Opened 2021-06-23 16:27 UTC by dutinmeow

2021-06-23 16:37 UTC, dutinmeow commented
Solution passes with AC

2021-06-28 22:04 UTC, dongliu0426 requested changes

2021-06-28 22:04 UTC, dongliu0426 commented on solutions/poi-14-cards.mdx
> +    T[t] = MP(llinf, llinf);
use tabs for indentation

2021-06-28 22:04 UTC, dongliu0426 commented on solutions/poi-14-cards.mdx
> +## Alternate Solution ##
extra ##?

2021-06-29 22:33 UTC, dongliu0426 approved these changes

2021-07-01 19:15 UTC, merged