Added Solution for Kattis Cat and Mice
cpinitiative/usaco-guide pull request #1806
Opened 2021-06-23 20:29 UTC by izhang05

2021-06-23 21:34 UTC, dongliu0426 requested changes

2021-06-23 21:34 UTC, dongliu0426 commented on solutions/kattis-catandmice.mdx
> +						long double cur_v = v * p[num_mice], time = dp[pre][j] + dist(a[j], a[i]) / cur_v;
```suggestion
						long double cur_v = v * p[num_mice];
						long double time = dp[pre][j] + dist(a[j], a[i]) / cur_v;
```
lines should contain < 80 characters

2021-06-23 21:34 UTC, dongliu0426 commented on solutions/kattis-catandmice.mdx
> +If it is not possible to reach subset $i$ with $j$ as the last visited mice, let $\texttt{dp}[i][j] = \texttt{INF}$.
can use $\infty$ instead of $\texttt{INF}$

2021-06-23 22:18 UTC, dongliu0426 approved these changes

2021-06-24 21:05 UTC, darren-yao approved these changes

2021-06-24 21:05 UTC, merged