Module Revamp(Alpha) Add Java Support to Basic Complete Search
cpinitiative/usaco-guide pull request #1812
Opened 2021-06-25 01:26 UTC by brad182

Part of the module revamp. Is the contributors thing going to be added soon because I've only provided solutions and not major changes

2021-06-25 02:27 UTC, maggie-j-liu commented
I'll just add you as contributor in my pr

2021-06-25 02:29 UTC, maggie-j-liu requested changes

2021-06-25 02:29 UTC, maggie-j-liu commented on content/2_Bronze/Intro_Complete.mdx
> +				max = Math.max(max, dx*dx + dy*dy);
```suggestion
			for(int j = i + 1; j < n; j++){ // for each second point
				int dx = x[i] - x[j];
				int dy = y[i] - y[j];
				max = Math.max(max, dx * dx + dy * dy);
```

2021-06-25 02:29 UTC, maggie-j-liu commented on content/2_Bronze/Intro_Complete.mdx
> +Rounding suffices (`(int)round(pow(max_dist,2))`), but the takeaway is that you
can you change this to match your java code (and is this true for your code?)

2021-06-27 01:40 UTC, nwatx requested changes

2021-06-27 01:40 UTC, nwatx commented on content/2_Bronze/Intro_Complete.mdx
> +		for(int i = 0; i < n; i++){ // for each first point
```suggestion
		for(int i = 0; i < n; i++) { // for each first point
```

2021-06-27 01:40 UTC, nwatx commented on content/2_Bronze/Intro_Complete.mdx
> +			for(int j = i + 1; j < n; j++){ // for each second point
```suggestion
			for(int j = i + 1; j < n; j++) { // for each second point
```

2021-06-27 21:17 UTC, SansPapyrus683 requested changes
small formatting things

2021-06-27 21:17 UTC, SansPapyrus683 commented on content/2_Bronze/Intro_Complete.mdx
> +				// our current maximum, then update the maximum
put this above that line with the `max`

2021-06-27 21:17 UTC, SansPapyrus683 commented on content/2_Bronze/Intro_Complete.mdx
> +		for(int i = 0; i < n; i++){ // for each first point
```suggestion
		for (int i = 0; i < n; i++) {  // for each first point
```
and the for loop below as well

2021-07-02 16:29 UTC, SansPapyrus683 approved these changes

2021-07-04 17:22 UTC, nwatx commented on content/2_Bronze/Intro_Complete.mdx
> +However, it still fails on the following test case (it outputs 12, but the
I would like it if the fact that it was incorrect was _more_ emphasized (probably bolded or in a spoiler)

2021-07-10 21:33 UTC, nwatx commented on content/2_Bronze/Intro_Complete.mdx
> +Rounding suffices (`(int) Math.pow(maxSquare, 2)`), but the takeaway is that you
shouldn't this be math.round

2021-07-11 06:15 UTC, HarryWangATX commented on content/2_Bronze/Intro_Complete.mdx
> +Rounding suffices (`(int) Math.pow(maxSquare, 2)`), but the takeaway is that you
```suggestion
Rounding suffices (`(int) Math.round(Math.pow(maxSquare, 2))`), but the takeaway is that you
```

2021-07-11 06:33 UTC, merged