Update usaco-616.mdx + add java/cpp code
cpinitiative/usaco-guide pull request #1866
Opened 2021-07-02 16:51 UTC by varunragu23

Java code from official analysis, added both java and cpp code for the cpi video program.

2021-07-02 17:32 UTC, maggie-j-liu requested changes

2021-07-02 17:32 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +int main() {
use tabs instead of spaces to indent

2021-07-02 17:32 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +      // the current barn we are processing is open_barn + pos
use multiline comments?

2021-07-02 17:32 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +				currentDistance += offset * cows[(unlock+offset)%n];
```suggestion
				currentDistance += offset * cows[(unlock + offset) % n];
```

2021-07-02 17:32 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +      curdist += pos * cows[(open_barn + pos)%n];
```suggestion
      curdist += pos * cows[(open_barn + pos) % n];
```

2021-07-02 17:32 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +      // index = (open_barn + pos)
```suggestion
      // index = open_barn + pos
```

2021-07-02 17:32 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
>  ## Implementation
you can add your name to the author list at the top

2021-07-02 18:38 UTC, SansPapyrus683 requested changes

2021-07-02 18:38 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +
```suggestion
  int ret = INT32_MAX;
```

2021-07-02 18:38 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +
```suggestion
  // run a simple brute force algo, checking each possible barn we can open

2021-07-02 18:38 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +    // update the answer
```suggestion
```

2021-07-02 18:38 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +
```suggestion
```

2021-07-02 18:38 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +		// initialize file I/O
```suggestion
```

2021-07-02 18:38 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +public class cbarn {
```suggestion

public class CBarn {
```

2021-07-02 18:38 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +		br.close();
lines 78, 81, 94, 99, and 101 are unnecessary comments (they shouldn't explain what you're doing, but explain _why_ you're doing what you're doing!)

2021-07-02 18:38 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +
```suggestion
```

2021-07-03 01:54 UTC, SansPapyrus683 requested changes

2021-07-03 01:54 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +#include<bits/stdc++.h>
```suggestion
#include <bits/stdc++.h>
```

2021-07-03 01:54 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +
```suggestion
	// run a simple brute force algo that checks each possible barn
	int ret = INT32_MAX;
```

2021-07-03 01:54 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +  return 0;
```suggestion
```

2021-07-03 04:41 UTC, brad182 requested changes

2021-07-03 04:41 UTC, brad182 commented on solutions/usaco-616.mdx
> +		// the answer cannot exceed N * N * 100, since there are at most 100N cows, each of which can move at most N
this line is over the limit

2021-07-03 04:41 UTC, brad182 commented on solutions/usaco-616.mdx
> +			if(currentDistance < ans) {
can be simplified using minimum

2021-07-03 04:41 UTC, brad182 commented on solutions/usaco-616.mdx
> +		pw.close();
i dont think kattio is require but should look nicer its just one close

2021-07-12 04:36 UTC, varunragu23 commented
I just copied the java code from the official analysis, 🤔.

2021-08-06 04:50 UTC, maggie-j-liu requested changes

2021-08-06 04:50 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +  return 0;
indentation here is weird

2021-08-06 04:50 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +## Implementation
move ## Implementation outside languagesection and remove ## Implementation from cppsection

2021-08-06 04:50 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +		PrintWriter pw = new PrintWriter(new BufferedWriter(new FileWriter("cbarn.out")));
don't need these since you're using kattio, right?

2021-08-06 04:50 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +	static class Kattio extends PrintWriter {
replace the entire kattio with `CodeSnip{Kattio}`

2021-08-06 19:19 UTC, maggie-j-liu requested changes

2021-08-06 19:19 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +## Implementation
add time complexity

2021-08-06 19:19 UTC, maggie-j-liu commented on solutions/usaco-616.mdx
> +				currentDistance += offset * cows[(unlock+offset)%n];
bump https://github.com/cpinitiative/usaco-guide/pull/1866/files#r663159957

2021-08-06 22:37 UTC, maggie-j-liu approved these changes
looks good, just address sans's requested changes
https://github.com/cpinitiative/usaco-guide/pull/1866/files#r663189532
https://github.com/cpinitiative/usaco-guide/pull/1866/files#r663189670

2021-08-06 23:12 UTC, SansPapyrus683 commented on solutions/usaco-616.mdx
> +	return 0;
```suggestion
```

2021-08-21 00:42 UTC, closed without merging