Java Solution for Why Did the Cow Cross the Road (Silver February 2017)
cpinitiative/usaco-guide pull request #1880
Opened 2021-07-03 16:33 UTC by brad182

If someone can collapse that IO template in the C++ code that would be great I'm not sure how to do that

2021-07-03 22:28 UTC, SansPapyrus683 commented
or even better you could just detemplify the code

2021-07-03 22:31 UTC, SansPapyrus683 requested changes

2021-07-03 22:31 UTC, SansPapyrus683 commented on solutions/usaco-714.mdx
> +
```suggestion
		
		int count = 0;

2021-07-03 22:31 UTC, SansPapyrus683 commented on solutions/usaco-714.mdx
> +			for(int y = 0; y < numCows; y++){
you put spaces between the for and the paren block up there
![image](https://user-images.githubusercontent.com/55369003/124368191-7deb6400-dc13-11eb-9a9a-f392dec53bfe.png)
why not do it here as well

2021-07-03 22:31 UTC, SansPapyrus683 commented on solutions/usaco-714.mdx
> +		int[] b = new int[numCows];
more explicit names would be nice

2021-07-03 22:31 UTC, SansPapyrus683 commented on solutions/usaco-714.mdx
> +
also maybe rename this to `crossed`?

2021-07-03 22:31 UTC, SansPapyrus683 commented on solutions/usaco-714.mdx
> +public class WhyDidTheCowCrossTheRoad {
```suggestion
public class HelpCross {
```

2021-07-03 22:31 UTC, SansPapyrus683 commented on solutions/usaco-714.mdx
> +		int[] marked = new int[numCows];
if i'm reading the code correctly can't this just be a bool array instead of an int array

2021-07-03 22:32 UTC, HarryWangATX commented on solutions/usaco-714.mdx
> +public class WhyDidTheCowCrossTheRoad {
(optinal)

2021-07-03 22:32 UTC, HarryWangATX commented on solutions/usaco-714.mdx
> +		int[] b = new int[numCows];
^, no 1 letter names.

2021-07-03 22:33 UTC, HarryWangATX commented
> or even better you could just detemplify the code

bruh xD

2021-07-05 05:46 UTC, nathangong requested changes
Make sure to maintain consistent spacing throughout your code

2021-07-05 05:46 UTC, nathangong commented on solutions/usaco-714.mdx
> +		for (int x = 0; x < numCows; x++){
```suggestion
		for (int x = 0; x < numCows; x++) {
```

2021-07-05 05:46 UTC, nathangong commented on solutions/usaco-714.mdx
> +			for(int y = 0; y < numCows; y++){
```suggestion
			for (int y = 0; y < numCows; y++) {
```

2021-07-05 05:46 UTC, nathangong commented on solutions/usaco-714.mdx
> +				if(marked[y] == 0 && chicken[x] >= a[y] && chicken[x] <= b[y]){
```suggestion
				if (marked[y] == 0 && chicken[x] >= a[y] && chicken[x] <= b[y]) { 
```

2021-07-05 05:46 UTC, nathangong commented on solutions/usaco-714.mdx
> +					if(smallest < 0 || b[y] < b[smallest]){
```suggestion
					if (smallest < 0 || b[y] < b[smallest]) {
```

2021-07-07 17:35 UTC, SansPapyrus683 approved these changes
i like this code

2021-07-07 18:41 UTC, nathangong approved these changes

2021-07-10 02:02 UTC, dongliu0426 requested changes
add

```mdx
# Implementation

**Time Complexity**: $\mathcal O(...)$
```

before 
```mdx
<LanguageSection>
```

2021-07-15 04:59 UTC, maggie-j-liu requested changes

2021-07-15 04:59 UTC, maggie-j-liu commented on solutions/usaco-714.mdx
> +**Time Complexity**: $\mathcal O(N*C)$
```suggestion
**Time Complexity:** $\mathcal O(N \cdot C)$
```

2021-07-15 04:59 UTC, maggie-j-liu commented on solutions/usaco-714.mdx
> +					if(smallest < 0 || latest[y] < latest[smallest]){
```suggestion
					if (smallest < 0 || latest[y] < latest[smallest]) {
```

2021-07-15 04:59 UTC, maggie-j-liu commented on solutions/usaco-714.mdx
> +		Kattio io = new Kattio("helpcross");
add kattio codesnip

2021-07-15 05:01 UTC, brad182 commented on solutions/usaco-714.mdx
> +		Kattio io = new Kattio("helpcross");
good catch

2021-07-15 05:02 UTC, maggie-j-liu approved these changes

2021-07-15 05:45 UTC, dongliu0426 approved these changes

2021-07-15 05:45 UTC, merged