Add Intro_DP Focus Problem
cpinitiative/usaco-guide pull request #1885
Opened 2021-07-04 07:02 UTC by nwatx

- [x] Add CPP Editorial
- [ ] Add Java Editorial
- [ ] Comment code
- [ ] Formatting??

2021-07-04 07:09 UTC, dongliu0426 requested changes

2021-07-04 07:09 UTC, dongliu0426 commented on content/4_Gold/Intro_DP.mdx
> +**Time Complexity:** $\mathcal{O}(N)$
describe a solution w/o dp and how dp speeds it up

2021-07-04 16:31 UTC, SansPapyrus683 requested changes

2021-07-04 16:31 UTC, SansPapyrus683 commented on content/4_Gold/Intro_DP.mdx
> +int H[MAX_N], dp[MAX_N];
what's H

2021-07-04 16:31 UTC, SansPapyrus683 commented on content/4_Gold/Intro_DP.mdx
> +
```suggestion
```

2021-07-04 16:31 UTC, SansPapyrus683 commented on content/4_Gold/Intro_DP.mdx
> +
```suggestion
```

2021-07-04 16:31 UTC, SansPapyrus683 commented on content/4_Gold/Intro_DP.mdx
> +
```suggestion
```

2021-07-04 17:01 UTC, nwatx commented on content/4_Gold/Intro_DP.mdx
> +int H[MAX_N], dp[MAX_N];
the height of the stone

2021-07-05 04:13 UTC, maggie-j-liu requested changes

2021-07-05 04:13 UTC, maggie-j-liu commented on content/4_Gold/Intro_DP.mdx
> +const int MAX_N = 1e5+1;
```suggestion
const int MAX_N = 1e5 + 1;
```

2021-07-05 04:13 UTC, maggie-j-liu commented on content/4_Gold/Intro_DP.mdx
> +int H[MAX_N], dp[MAX_N];
no 1 letter variable names D:

2021-07-05 05:52 UTC, dongliu0426 requested changes

2021-07-05 05:52 UTC, dongliu0426 commented on content/4_Gold/Intro_DP.mdx
> +such expensive calculations - in this case, the minimum cost to reach stone $i$.
add that you do this because you don't want to recalculate the same state

2021-07-05 05:58 UTC, maggie-j-liu commented on content/4_Gold/Intro_DP.mdx
> +- Jump one stone, incurring a cost of $|h_i - h_{i+1}|$:
could use height[i] to match the code

2021-07-05 06:30 UTC, dongliu0426 approved these changes

2021-07-05 11:31 UTC, dolphingarlic requested changes

2021-07-05 11:31 UTC, dolphingarlic commented on content/4_Gold/Intro_DP.mdx
> +two, which results in an exponential time complexity. However, this can sped up
```suggestion
two, which results in an exponential time complexity.

However, this can be sped up
```

2021-07-05 11:31 UTC, dolphingarlic commented on content/4_Gold/Intro_DP.mdx
> +redundant calculations. For example, recursively calculating jumps of length
```suggestion
calculating states multiple times. For example, recursively calculating jumps of length
```

2021-07-05 23:08 UTC, nathangong reviewed
I think it might be better if you put the focus problem and the solution all in the same place so it makes more sense to a reader. For example this is what the custom comparators and sorting module does: 
![image](https://user-images.githubusercontent.com/8647920/124523212-00f2f280-ddab-11eb-80c2-27b9d724c990.png)

If you disagree that's fine, you can just resolve my suggestions

2021-07-05 23:08 UTC, nathangong commented on content/4_Gold/Intro_DP.mdx
> +<FocusProblem problem='focus' />
```suggestion
```

2021-07-05 23:08 UTC, nathangong commented on content/4_Gold/Intro_DP.mdx
```suggestion
```

2021-07-05 23:08 UTC, nathangong commented on content/4_Gold/Intro_DP.mdx
> +## Solution - Frog 1
```suggestion
## Example - Frog 1

<FocusProblem problem='focus' />
```

2021-07-10 19:46 UTC, merged