Added Python Solution to Cow Evolution (Bronze)
cpinitiative/usaco-guide pull request #1889
Opened 2021-07-04 18:55 UTC by ryanchou-dev

all test cases pass for this solution.

2021-07-04 22:06 UTC, SansPapyrus683 requested changes
i'd ask you to take the stuff outside `solve` but that would be too much work for you

2021-07-04 22:06 UTC, SansPapyrus683 commented on solutions/usaco-941.mdx
> +	If we find a cow which has the characteristic a,
maybe smth like "check if the tree is evolutionarily proper relative to characteristics a and b" or something then add the original doc comment

2021-07-04 22:06 UTC, SansPapyrus683 commented on solutions/usaco-941.mdx
> +				return 0
just `return` instead of `return 0`

2021-07-04 22:43 UTC, ryanchou-dev commented
> i'd ask you to take the stuff outside `solve` 

got it.

2021-07-04 22:56 UTC, ryanchou-dev commented
Added the suggestions, thanks @SansPapyrus683!

FYI: i had to add an impossible variable since i couldn't return to stop the code.

2021-07-04 23:00 UTC, SansPapyrus683 commented
> FYI: i had to add an impossible variable since i couldn't return to stop the code.

wait wdym by this

2021-07-04 23:03 UTC, ryanchou-dev commented
> > FYI: i had to add an impossible variable since i couldn't return to stop the code.
> 
> wait wdym by this

I had to add these parts:
![image](https://user-images.githubusercontent.com/81596991/124401894-2e736980-dce1-11eb-9cd4-29e6d0ab5e02.png)
since it's going to keep executing the lines after the for loop, so for all of the test cases with no as an answer, the output would be 
`
no
yes
`
so the impossible variable prevents the yes from printing.

2021-07-04 23:06 UTC, maggie-j-liu commented
what about `sys.exit(0)`?

2021-07-04 23:07 UTC, ryanchou-dev commented
> what about `sys.exit(0)`?

oh, that's a better idea.

2021-07-04 23:44 UTC, SansPapyrus683 commented
uh just saying sys.exit() also works

2021-07-05 03:06 UTC, ryanchou-dev commented
> uh just saying sys.exit() also works

it looks cleaner 👍

2021-07-05 04:06 UTC, maggie-j-liu requested changes

2021-07-05 04:06 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +# check if the tree is evolutionarily proper relative to characteristics a and b
```suggestion
# Check if the tree is evolutionarily proper relative to characteristics a and b
```
to be consistent

2021-07-05 04:06 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +# iterating through every pair of characteristics.
```suggestion
# Iterating through every pair of characteristics.
```

2021-07-05 04:06 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
>  [Video Analysis](https://youtu.be/4YTijr0BbrA)
```suggestion
## Video Solution
<Youtube id="4YTijr0BbrA" />
```
we have a way to embed videos (idk why this is not mentioned in the MDX module?)

2021-07-05 04:07 UTC, ryanchou-dev commented on solutions/usaco-941.mdx
> +# check if the tree is evolutionarily proper relative to characteristics a and b
👍

2021-07-05 18:15 UTC, maggie-j-liu approved these changes

2021-07-06 03:57 UTC, ryanchou-dev commented
i think i covered all of the suggestions, did i miss anything?

2021-07-06 04:06 UTC, SansPapyrus683 approved these changes

2021-07-06 04:16 UTC, dongliu0426 approved these changes

2021-07-06 19:25 UTC, ryanchou-dev commented
👍

2021-07-06 20:08 UTC, SansPapyrus683 commented
can mods merge alr

2021-07-06 20:13 UTC, merged