Add Java Solution to Balancing(usaco-624)
cpinitiative/usaco-guide pull request #1907
Opened 2021-07-10 00:59 UTC by timothygao8710

2021-07-10 01:43 UTC, SansPapyrus683 commented
this is a bit sol? thought the usaco guide sol was supposed to use binsearch but ok

2021-07-10 03:37 UTC, timothygao8710 commented
I would use binary search but I have no idea how Benq's solution works lol. Perhaps @bqi343 could provide some insight? What does one binarysearch on and how can one validate that a value works?

2021-07-10 04:02 UTC, bqi343 commented
binary search on the answer

2021-07-10 04:02 UTC, bqi343 commented
if you fix a y-coordinate and an answer, can you find the minimum and maximum x-coordinates that work?

2021-07-25 21:01 UTC, timothygao8710 commented
Hm... The editorial solution iterates through all ys and binary searches on x. How does knowing a fixed answer help? Won't you have to do the same procedure of iterating through ys and binary searching on x regardless?

2021-07-25 22:02 UTC, bqi343 commented
Consider the following simpler problem for a fixed `ans` (and assuming all coordinates are `O(N)`):

For every x-coordinate `x`, find the maximum `y` such that the number of cows `(a,b)` such that `a <= x` and `b <= y` is at most `ans`.

You should be able to do this in `O(N)`.

2021-07-25 22:42 UTC, timothygao8710 commented
Oh wait that's actually humongous brain. Thanks for the explanation.

2021-07-25 23:53 UTC, maggie-j-liu requested changes

2021-07-25 23:53 UTC, maggie-j-liu commented on solutions/usaco-624.mdx
> +        for(int i = 0; i<N; i++){
```suggestion
        for(int i = 0; i < N; i++){
```
add spacing around operators everywhere else, too

2021-07-25 23:53 UTC, maggie-j-liu commented on solutions/usaco-624.mdx
> +```java
use tabs instead of spaces to indent

2021-07-27 04:54 UTC, SansPapyrus683 commented on solutions/usaco-624.mdx
> +
wait nvm lol
327 and 329 are unnecessary lines

2021-07-27 04:55 UTC, SansPapyrus683 requested changes

2021-07-27 04:55 UTC, SansPapyrus683 commented on solutions/usaco-624.mdx
> +public class balancing {
```suggestion
public class Balancing
```

2021-07-27 04:55 UTC, SansPapyrus683 commented on solutions/usaco-624.mdx
> +	static final int maxY = 1_000_001;
change the name to `MAX_Y`, all caps is the convention for constants

2021-08-03 16:58 UTC, SansPapyrus683 approved these changes
kinda gave up lol

2021-08-10 08:01 UTC, dongliu0426 approved these changes

2021-08-11 21:14 UTC, maggie-j-liu commented on solutions/usaco-624.mdx
> +<LanguageSection>
move time complexity under the explanation, and add ## Explanation and ## Implementation headers

2021-08-31 18:01 UTC, timothygao8710 commented on solutions/usaco-624.mdx
> +			coords[i] = new int[] { Integer.parseInt(st.nextToken()), Integer.parseInt(st.nextToken()) };
changed

2021-08-31 18:23 UTC, maggie-j-liu approved these changes

2021-08-31 18:23 UTC, merged