Java Solution for Solve the Maze
cpinitiative/usaco-guide pull request #1914
Opened 2021-07-10 19:28 UTC by brad182

2021-07-10 19:53 UTC, SansPapyrus683 commented
you checked that the lines aren't too long right

2021-07-11 20:04 UTC, nathangong commented
It looks like some of the lines exceed 80 characters

2021-07-11 21:11 UTC, brad182 commented
> you checked that the lines aren't too long right

kind of difficult for this problem because there are a bunch of nested loops and if statements, may you suggest how I can spread out to more lines?

2021-07-12 00:01 UTC, SansPapyrus683 commented
not sure how to elaborate but I think you can unnest some of the if statements with continues

2021-07-15 05:14 UTC, brad182 commented
can to do separate ifs in order to be less than the character limit

2021-07-16 18:37 UTC, maggie-j-liu requested changes

2021-07-16 18:37 UTC, maggie-j-liu commented on solutions/cf-1365D.mdx
> +		ok = true;
shouldn't ok already be true here? so you don't need to set it to true again

and i think you can just return instead of setting ok?

2021-07-16 18:37 UTC, maggie-j-liu commented on solutions/cf-1365D.mdx
> +					break;
i think you can just return instead of setting ok

2021-07-16 22:47 UTC, ryanchou-dev commented on solutions/cf-1365D.mdx
> +		boolean ok = true;
did you forget to remove this?
```suggestion
```

2021-07-16 22:48 UTC, ryanchou-dev requested changes
clean code

2021-07-16 22:56 UTC, ryanchou-dev approved these changes
👍

2021-07-17 06:15 UTC, nwatx approved these changes

2021-07-18 08:33 UTC, dongliu0426 approved these changes

2021-07-19 03:52 UTC, maggie-j-liu approved these changes

2021-07-19 03:52 UTC, merged