Added internal java solution for measuring traffic
cpinitiative/usaco-guide pull request #1920
Opened 2021-07-11 01:04 UTC by sathu-beep

fixed a small error in a pull request that went unnoticed 👀 that I rediscovered today

2021-07-11 01:10 UTC, ar492 approved these changes
Looks good; I trust the code works. however, I don't understand why there's no explanation / why you don't just put it in the "user solutions" section or whatever it's called.

2021-07-11 01:10 UTC, maggie-j-liu commented
#1856 exists...
i think keep that one since it's for cpi video classes

2021-07-11 01:11 UTC, ar492 requested changes
https://github.com/cpinitiative/usaco-guide/pull/1856

2021-07-14 10:41 UTC, dongliu0426 requested changes

2021-07-14 10:41 UTC, dongliu0426 commented on solutions/usaco-917.mdx
> +---
can you delete this file then?

2021-08-01 06:44 UTC, dongliu0426 commented
> #1856 exists...
> i think keep that one since it's for cpi video classes

2021-08-01 06:44 UTC, closed without merging