Python improvements in the "General" section.
cpinitiative/usaco-guide pull request #1927
Opened 2021-07-13 03:10 UTC by phuang1024

* Improved Python IO instructions
* Instructions to run Python
* Formatting

2021-07-18 09:23 UTC, dongliu0426 requested changes

2021-07-28 11:02 UTC, dolphingarlic commented on content/1_General/Running_Code_Locally.mdx
> +(https://stackoverflow.com/questions/11828270/how-do-i-exit-the-vim-editor)
Lmao nice

2021-07-28 11:04 UTC, dolphingarlic commented on content/1_General/Running_Code_Locally.mdx
> +python3 --version  # Python 3.8.1
Maybe keep the previous version to explicitly show that it prints the version?

2021-07-28 11:23 UTC, dongliu0426 commented on content/1_General/Running_Code_Locally.mdx
> +(https://stackoverflow.com/questions/11828270/how-do-i-exit-the-vim-editor)
🙋 lol vim is so difficult to use

2021-07-31 19:10 UTC, dolphingarlic approved these changes
Just resolve the merge conflict and then I can merge

2021-08-07 20:41 UTC, SansPapyrus683 commented on content/4_Gold/BFS.mdx
> +Python has a `queue` built-in module.
queue's synchronized, so it's a bit slow
perhaps just tell them to use deque instead?

2021-08-16 23:15 UTC, thecodingwizard commented
good enough, I'll merge. Feel free anyone to make another PR to address @SansPapyrus683 's comment

2021-08-16 23:16 UTC, merged