Created Divide and Conquer Solution to "Kattio: Closest Pair"
cpinitiative/usaco-guide pull request #1935
Opened 2021-07-14 05:02 UTC by dutinmeow

2021-07-14 05:02 UTC, dutinmeow commented
I'll add the code if needed and the other solution if I have time

2021-07-14 05:03 UTC, dutinmeow commented
Also, shouldn't the other solution say "sweep line " instead of "set"?

2021-07-23 14:42 UTC, dolphingarlic requested changes
There are also a bunch of grammar issues that you should fix

2021-07-23 14:42 UTC, dolphingarlic commented on content/5_Plat/Sweep_Line.mdx
> +<Spoiler title="Solution 1">
No need to mark as a spoiler

2021-07-23 14:42 UTC, dolphingarlic commented on content/5_Plat/Sweep_Line.mdx
> +It can be shown that for each point $p$, there is $\mathcal{O}(1)$ points that satisfy this property. Because each point in $R'$ is at least $\delta_r \geq \delta$ apart, arranging the points in the
> It can be shown that

Can you show this?

2021-07-23 14:42 UTC, dolphingarlic commented on content/5_Plat/Sweep_Line.mdx
> +Because each step now runs in linear time, by the mastern theorem $T(n) = 2T(n / 2) + \mathcal{O}(n)$, our solution now runs in $\mathcal{O}(n\log n)$ (note its similarities to merge sort).
> the mastern theorem

Do you mean the master theorem?

2021-08-06 03:43 UTC, bqi343 commented
Changes requested have not been made. Free free to create a new PR.

2021-08-06 03:43 UTC, closed without merging