Added Python Solution to Back & Forth (Bronze)
cpinitiative/usaco-guide pull request #1960
Opened 2021-07-19 23:16 UTC by ryanchou-dev

also commented out Benjamin Qi's code and added language section tag.

all test cases pass for this solution :)

2021-07-19 23:18 UTC, ryanchou-dev commented
would the title be better as "Back and Forth" instead of "Back & Forth" since USACO lists it with an "and"?
![image](https://user-images.githubusercontent.com/81596991/126239328-d1f29aca-0f61-4f7b-9c89-14fbcdcf400e.png)

2021-07-19 23:26 UTC, dongliu0426 approved these changes
cool

2021-07-20 17:30 UTC, maggie-j-liu approved these changes

2021-07-20 17:34 UTC, SansPapyrus683 requested changes
actually p good for cp standards

2021-07-20 17:34 UTC, SansPapyrus683 commented on solutions/usaco-857.mdx
> +
```suggestion
```

2021-07-21 01:33 UTC, caoash approved these changes

2021-07-21 01:47 UTC, merged