Update cses-1682.mdx, added an alternative solution using SCCs.
cpinitiative/usaco-guide pull request #1967
Opened 2021-07-21 07:49 UTC by Qw3rTy827

2021-07-31 22:37 UTC, bqi343 commented
I don't think it's necessary to include this. Why not just link to the SCC module?

2021-07-31 22:48 UTC, bqi343 requested changes
see above

2021-08-01 04:21 UTC, bqi343 commented
er I meant to link to the advanced module from the solution. I don't see the point of adding this as a problem in the advanced module.

2021-08-01 04:53 UTC, Qw3rTy827 commented
> er I meant to link to the advanced module from the solution. I don't see the point of adding this as a problem in the advanced module.

so like adding a line that says something along the lines of "Strongly Connected Components" in the Advanced section can also be used to solve this problem and provide a hyperlink to the SCC module ?

2021-08-01 14:52 UTC, bqi343 commented
sure

2021-08-14 03:33 UTC, dongliu0426 approved these changes

2021-08-15 03:21 UTC, dongliu0426 commented on solutions/cses-1682.mdx
> +author: Michael Cao, Nathan Gong, Andrew Cheng
```suggestion
author: Michael Cao, Nathan Gong
```

2021-08-15 03:21 UTC, dongliu0426 commented on solutions/cses-1682.mdx
> +The problem can also be solved using strongly connected components (SCC). Check it out in the [SCC](/adv/SCC) module.
```suggestion
The problem can also be solved using [strongly connected components (SCC)](/adv/SCC).
```

2021-08-15 03:25 UTC, merged