Add solution to cses 1093 two sets
cpinitiative/usaco-guide pull request #2019
Opened 2021-07-31 22:08 UTC by TruaShamu

2021-07-31 22:47 UTC, bqi343 requested changes

2021-07-31 22:47 UTC, bqi343 commented on solutions/cses-1093.mdx
> +[Codeforces Editorial](https://codeforces.com/blog/entry/70018)
```suggestion
[Official Editorial](https://codeforces.com/blog/entry/70018)
```

to be consistent with the other solutions. looks like two other solutions w/ "Codeforces Editorial" were already merged in - those should be changed as well.

2021-07-31 22:47 UTC, bqi343 commented on solutions/cses-1093.mdx
> +        long totalSum = (long) (N * (N + 1)) / 2;
why not an `int`?

2021-08-01 02:48 UTC, bqi343 requested changes

2021-08-01 02:48 UTC, bqi343 commented on solutions/cses-1093.mdx
> +        int totalSum = (N * (N + 1)) / 2;
```suggestion
        int totalSum = N * (N + 1) / 2;
```

2021-08-01 02:48 UTC, bqi343 commented on solutions/cses-1093.mdx
> +            System.out.println(0);
Why `System.out.println` here but `io.println` later on?

2021-08-01 03:01 UTC, dongliu0426 commented on solutions/cses-1093.mdx
> +        int[][] dp = new long[N][totalSum + 1];
```suggestion
        int[][] dp = new int[N][totalSum + 1];
```

2021-08-01 14:50 UTC, bqi343 requested changes

2021-08-01 14:50 UTC, bqi343 commented on solutions/cses-1093.mdx
> +            io.println(0);
code no longer prints anything when output is 0 D:

2021-08-01 14:50 UTC, bqi343 commented on solutions/cses-1093.mdx
> +        Kattio io = new Kattio();
include `Kattio` as a codesnip

2021-08-01 15:52 UTC, SansPapyrus683 commented
also indent w/ tabs?

2021-08-01 19:12 UTC, TruaShamu commented
Ok, I fixed it.

2021-08-01 19:14 UTC, bqi343 approved these changes

2021-08-01 19:56 UTC, SansPapyrus683 commented on solutions/cses-1093.mdx
> +public class cses1093 {
TwoSets instead of cses1093?
other than that very cool

2021-08-01 21:47 UTC, SansPapyrus683 approved these changes

2021-08-01 21:48 UTC, merged