Small Floodfill Change
cpinitiative/usaco-guide pull request #2064
Opened 2021-08-07 03:44 UTC by Aadit-Ambadkar

2021-08-07 05:01 UTC, nathangong commented
Since floodfill can also be done using BFS, I think it might be good to explicitly mention that this recursive DFS method is just one algorithm that can be used to perform floodfill.

2021-08-07 14:42 UTC, Aadit-Ambadkar commented
Yeah, edited that in another place where it made more sense.

2021-08-07 15:17 UTC, SansPapyrus683 commented on content/3_Silver/Flood_Fill.mdx
> +A non-recursive implementation of flood fill adds the edgesto a stack or queue, similar to [BFS](https://usaco.guide/gold/bfs), and is usually implemented as follows:
> edgesto

typo?

2021-08-08 00:46 UTC, nathangong requested changes
Just some small grammar/wording stuff

2021-08-08 00:46 UTC, nathangong commented on content/3_Silver/Flood_Fill.mdx
> +above, below, and to the left and right of our current square. Due to it's
```suggestion
above, below, and to the left and right of our current square. Due to its
```

2021-08-08 00:46 UTC, nathangong commented on content/3_Silver/Flood_Fill.mdx
> +recursive nature, you can think of floodfill as a modified version of
Second person isn't used at all in the explanation, so for consistency:
```suggestion
recursive nature, floodfill can be thought of as a modified version of
```

2021-08-08 00:46 UTC, nathangong commented on content/3_Silver/Flood_Fill.mdx
> +A non-recursive implementation of flood fill adds the edges to a stack or queue, similar to [BFS](https://usaco.guide/gold/bfs), and is usually implemented as follows:
I'm pretty sure you add nodes, not edges to the stack/queue in floodfill. This is also the case in the code below.
```suggestion
A non-recursive implementation of flood fill adds adjacent nodes to a stack or queue, similar to [BFS](https://usaco.guide/gold/bfs), and is usually implemented as follows:
```

2021-08-09 01:28 UTC, nwatx approved these changes

2021-08-09 01:29 UTC, nathangong approved these changes

2021-08-09 21:17 UTC, HarryWangATX approved these changes

2021-08-10 04:19 UTC, merged