Adding a Python Solution
cpinitiative/usaco-guide pull request #2071
Opened 2021-08-09 10:12 UTC by Mohammad-Nour-Massri

2021-08-09 15:49 UTC, ryanchou-dev requested changes
nice solution

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
> +authors: Maggie Liu, Mohammad Nour Massri
```suggestion
author: Maggie Liu, Mohammad Nour Massri
```
needs to stay like this

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
> +
```suggestion
```

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
> +#prime factorization for n
```suggestion
# prime factorization for n
```

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
> +for p in range(2,int(n**0.5)):
```suggestion
for p in range(2, int(n ** 0.5)):
```

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
> +	#here p^e divides n
```suggestion
	# here p^e divides n 
```
not sure if this comment is necessary

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
> +	#taking p^1 then p^2 and so on until e < i
```suggestion
	# taking p^1 then p^2 and so on until e < i
```

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
> +		i = i+1
```suggestion
		i += 1
```

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
> +ans += n > 1 # if n>1 then it is a prime factor with e=1
```suggestion
ans += n > 1 # if n > 1 then it is a prime factor with e=1
```

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
> +
```suggestion
```

2021-08-09 15:49 UTC, ryanchou-dev commented on solutions/ac-DivGame.mdx
```suggestion
```

2021-08-10 04:03 UTC, HarryWangATX requested changes
can you also move time complexity to be right below the `## Implementation` header?

2021-08-10 15:04 UTC, SansPapyrus683 commented on solutions/ac-DivGame.mdx
> +ans += n > 1 # if n > 1 then it is a prime factor with e=1
```suggestion
ans += n > 1  # if n > 1 then it is a prime factor with e=1
```

2021-08-11 02:01 UTC, nathangong commented on solutions/ac-DivGame.mdx
```suggestion
```

2021-08-11 02:02 UTC, nathangong commented on solutions/ac-DivGame.mdx
> +**Time Complexity:** $\mathcal{O}(\sqrt{N})$
```suggestion
Each time we decrement the exponent, we can add $1$ to the answer.

## Implementation

**Time Complexity:** $\mathcal{O}(\sqrt{N})$
```

2021-08-19 14:19 UTC, bqi343 commented
@ryanchou-dev @HarryWangATX @SansPapyrus683 @nathangong

2021-08-19 16:13 UTC, SansPapyrus683 approved these changes
think it's acceptable i guess

2021-08-19 16:22 UTC, nathangong approved these changes
Looks good, just 1 spacing change

2021-08-19 16:22 UTC, nathangong commented on solutions/ac-DivGame.mdx
> +ans += n > 1  # if n > 1 then it is a prime factor with e=1
```suggestion
ans += n > 1  # if n > 1 then it is a prime factor with e = 1
```

2021-08-19 16:23 UTC, HarryWangATX approved these changes

2021-08-19 16:26 UTC, merged