Add java implementation to centroid & dp on ranges pages
cpinitiative/usaco-guide pull request #2085
Opened 2021-08-12 00:49 UTC by TruaShamu

2021-08-12 02:14 UTC, SansPapyrus683 requested changes

2021-08-12 02:14 UTC, SansPapyrus683 commented on content/4_Gold/DP_Ranges.mdx
> +public class jazz {
```suggestion
public class Jazz {
```

2021-08-12 02:14 UTC, SansPapyrus683 commented on content/4_Gold/DP_Ranges.mdx
> +char[] A = io.next().toCharArray();
is it just me or is the indentaion kinda messed up here

2021-08-12 02:14 UTC, SansPapyrus683 commented on content/4_Gold/DP_Ranges.mdx
> +char[] A = io.next().toCharArray();
also i'd love it if you gave a better variable name

2021-08-12 13:08 UTC, dongliu0426 requested changes

2021-08-12 13:08 UTC, dongliu0426 commented on content/5_Plat/Centroid.mdx
> +		for (int i=0; i< N; i++) {
```suggestion
		for (int i = 0; i < N; i++) {
```

2021-08-12 13:08 UTC, dongliu0426 commented on content/5_Plat/Centroid.mdx
> +	public static ArrayList<Integer>[] adj;
```suggestion
	public static List<Integer>[] adj;
```

2021-08-12 13:08 UTC, dongliu0426 commented on content/5_Plat/Centroid.mdx
> +		adj = new ArrayList[N];
```suggestion
		adj = new List[N];
```

2021-08-12 13:43 UTC, dongliu0426 approved these changes
nice

2021-08-12 15:11 UTC, SansPapyrus683 commented on content/4_Gold/DP_Ranges.mdx
> +	public static int MAXN = 505;
```suggestion
	public static int MAXN = 500;
```

2021-08-12 16:18 UTC, SansPapyrus683 commented on content/4_Gold/DP_Ranges.mdx
> +								dp[i + 1][k - 1] + dp[k + 1][i + j]);
```suggestion
						dp[i][i + j] = Math.min(
							dp[i][i + j],
							dp[i + 1][k - 1] + dp[k + 1][i + j]
						);
```

2021-08-13 15:24 UTC, maggie-j-liu commented on content/4_Gold/DP_Ranges.mdx
> +		Kattio io = new Kattio();
add kattio codesnip

2021-08-13 15:24 UTC, maggie-j-liu commented on content/4_Gold/DP_Ranges.mdx
> +				for (int k = i + 1; k <= (i + j); k++) {
```suggestion
				for (int k = i + 1; k <= i + j; k++) {
```

2021-08-13 15:24 UTC, maggie-j-liu commented on content/5_Plat/Centroid.mdx
> +			if ((subSize[next] * 2) > N) {
```suggestion
			if (subSize[next] * 2 > N) {
```

2021-08-13 15:25 UTC, ryanchou-dev requested changes

2021-08-13 15:25 UTC, ryanchou-dev commented on content/4_Gold/DP_Ranges.mdx
> +		Kattio io = new Kattio();
did you forget to codesnip kattio 🤔

2021-08-13 15:42 UTC, SansPapyrus683 requested changes

2021-08-13 15:42 UTC, SansPapyrus683 commented on content/5_Plat/Centroid.mdx
> +public class cses2709 {
better name?

2021-08-13 15:42 UTC, SansPapyrus683 commented on content/5_Plat/Centroid.mdx
> +			if ((subSize[next] * 2) > N) {
some comments would be really cool here? idk maybe this is supposed to be prior knowledge relative to the problem but

2021-08-13 18:49 UTC, TruaShamu commented
Alright, I added the codesnippet and also updated the comments on the centroid problem.

2021-08-13 19:55 UTC, SansPapyrus683 requested changes
this should be it

2021-08-13 19:55 UTC, SansPapyrus683 commented on content/5_Plat/Centroid.mdx
> +public class findCentroid {
```suggestion
public class FindCentroid {
```

2021-08-13 19:55 UTC, SansPapyrus683 commented on content/5_Plat/Centroid.mdx
> +	// Codesnip{Kattio}
you sure this works? i thought it was `//CodeSnip{Kattio}` w/o the space in the middle

2021-08-13 20:00 UTC, SansPapyrus683 approved these changes
![image](https://user-images.githubusercontent.com/55369003/129412455-f033dcb1-cf4b-4984-971a-8863b7ea19de.png)

2021-08-13 20:02 UTC, TruaShamu commented
😂🤣

2021-08-14 01:54 UTC, nathangong approved these changes

2021-08-14 01:54 UTC, nathangong commented on content/4_Gold/DP_Ranges.mdx
> +	public static int MAXN = 500;
```suggestion
	public static final int MAXN = 500;
```

2021-08-14 04:08 UTC, maggie-j-liu approved these changes

2021-08-14 04:13 UTC, merged