Update usaco 941
cpinitiative/usaco-guide pull request #2116
Opened 2021-08-19 16:28 UTC by vivianhan404

2021-08-20 16:28 UTC, maggie-j-liu requested changes
if your java solution is the same as the current, you can replace it to keep the code consistent with the video

2021-08-20 16:28 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +![Venn Diagram 1](https://github.com/vivianhan404/usaco-guide/blob/00836815560bdd1e4ece02b5404c097954daf03e/solutions/usaco-941-diagrams/venn_1.png)
```suggestion
![Venn Diagram 1](usaco-941-diagrams/venn_1.png)
```

2021-08-20 16:28 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +![Venn Diagram 2](https://github.com/vivianhan404/usaco-guide/blob/00836815560bdd1e4ece02b5404c097954daf03e/solutions/usaco-941-diagrams/venn_2.png)
```suggestion
![Venn Diagram 2](usaco-941-diagrams/venn_2.png)
```

2021-08-20 16:28 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +![Evolution tree diagram](https://github.com/vivianhan404/usaco-guide/blob/46b61d949f16c4a26f19ee8a2dace22534cd0ebb/solutions/usaco-914-diagrams/tree_1.png)
```suggestion
![Evolution tree diagram](usaco-914-diagrams/tree_1.png)
```

2021-08-20 16:28 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +So, at the end of the day, we actually don't need to build a proper evolutionary tree, but we just need to test of any of our characteristics represent crossing sets; if so (and only if so), a proper
```suggestion
So we actually don't need to build a proper evolutionary tree, but we just need to test if any of our characteristics represent crossing sets; if so (and only if so), a proper tree is impossible to build. This leads to probably the easiest solution of the problem, shown in my code below where I build all the sets of populations having each characteristic and then just test if any pair of these sets is crossing.
```

2021-08-20 16:28 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +In other words, we have a population with just trait $\texttt{A}$, a population with just trait $\texttt{B}$, and a population with both. If we want to build a tree out of this input, we would need t
1 letter variable names don't need `\texttt`

2021-08-20 16:28 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +	if (all_characteristics[k] == s) found = true;
```suggestion
		if (all_characteristics[k] == s) found = true;
```

2021-08-20 16:28 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +	}
use tabs instead of spaces to indent
and i think the indentation is messed up too

2021-08-21 03:21 UTC, maggie-j-liu commented on solutions/usaco-941.mdx
> +In other words, we have a population with just trait A, a population with just trait B, and a population with both. If we want to build a tree out of this input, we would need to split on either A or
oops i meant that you could (and probably should) still latex, just don't need texttt (so do `$A$` instead of `A` or `$\texttt{A}$`

2021-08-21 15:22 UTC, maggie-j-liu approved these changes

2021-08-21 16:21 UTC, SansPapyrus683 commented on solutions/usaco-941.mdx
> +			else if (hasB) onlyB = true;
can you just use braces everywhere

2021-08-23 06:31 UTC, ryanchou-dev approved these changes
yeah just use braces everywhere, but everything else is good. ❤️ the editorial

2021-08-23 16:27 UTC, SansPapyrus683 approved these changes

2021-08-25 04:40 UTC, merged