walls internal solution
cpinitiative/usaco-guide pull request #2118
Opened 2021-08-19 16:50 UTC by SansPapyrus683

someone tell me if the complexity is right all i know is that it works
also i hate java so no java sol

2021-08-19 17:56 UTC, ar492 requested changes

2021-08-19 17:56 UTC, ar492 commented on solutions/ioi-00-walls.mdx
> +Finally, we try all meeting regions and print out the one that minimizes the walls the memebers have to cross.
```suggestion
Finally, we try all meeting regions and print out the one that minimizes the walls the members have to cross.
```

2021-08-20 01:34 UTC, ryanchou-dev approved these changes
geniosity :D

2021-08-20 01:34 UTC, ryanchou-dev commented on solutions/ioi-00-walls.mdx
> +assert member_num == len(members)
```suggestion
```
forgot to remove?

2021-08-20 01:34 UTC, ryanchou-dev commented on solutions/ioi-00-walls.mdx
> +			# dupes might hppen but that doesn't really matter
```suggestion
			# dupes might happen but that doesn't really matter
```

2021-08-20 02:16 UTC, SansPapyrus683 commented on solutions/ioi-00-walls.mdx
> +assert member_num == len(members)
i mean no harm in it being there

2021-08-20 21:22 UTC, nathangong commented on solutions/ioi-00-walls.mdx
> +Finally, we try all meeting regions and print out the one that minimizes the walls the members have to cross.
```suggestion
Finally, we try all meeting regions and print out the one that minimizes the number of walls the members have to cross.
```

2021-08-25 03:40 UTC, nwatx commented on solutions/ioi-00-walls.mdx
> +assert member_num == len(members)
i think this is ok

2021-08-25 03:41 UTC, nwatx requested changes
it seems like some of the comments could potentially be put in the editorial

2021-08-25 03:58 UTC, SansPapyrus683 commented
what's "some"

2021-08-25 04:10 UTC, nwatx commented
> if we've seen this wall before, add that associated region

> dupes might not happen but they don't really matter

probably explaining this would be helpful (if it's not clear already)

2021-08-25 04:15 UTC, SansPapyrus683 commented
1. how would i explain this in the editorial
2. it's just an implementation thing, doesn't really matter

2021-08-28 22:00 UTC, nwatx approved these changes

2021-08-30 02:28 UTC, TruaShamu approved these changes

2021-08-30 02:28 UTC, HarryWangATX approved these changes

2021-08-30 02:29 UTC, merged