Add internal sol to codeforces consecutive subsequence
cpinitiative/usaco-guide pull request #2119
Opened 2021-08-19 20:45 UTC by TruaShamu

2021-08-20 02:08 UTC, nathangong commented on solutions/cf-977F.mdx
> +public class conSub {
```suggestion
public class ConsecutiveSubsequence {
```

2021-08-20 02:08 UTC, nathangong commented on solutions/cf-977F.mdx
> +		HashMap<Integer, Integer> dp = new HashMap<>();
```suggestion
		Map<Integer, Integer> dp = new HashMap<>();
```

2021-08-20 05:43 UTC, ryanchou-dev requested changes

2021-08-20 05:43 UTC, ryanchou-dev commented on solutions/cf-977F.mdx
> +**Time Complexity:** $\mathcal{O}(N\cdot)$
```suggestion
**Time Complexity:** $\mathcal{O}(N)$
```
the solution is just O(n) right?

2021-08-20 16:07 UTC, SansPapyrus683 requested changes

2021-08-20 16:07 UTC, SansPapyrus683 commented on solutions/cf-977F.mdx
> +**Time Complexity:** $\mathcal{O}(N)$
i think you're supposed to put this below implementation?

2021-08-20 16:07 UTC, SansPapyrus683 commented on solutions/cf-977F.mdx
> +				// Start a new subsequence.
```suggestion
				// If not we can just start a new subsequence.
```

2021-08-20 16:07 UTC, SansPapyrus683 commented on solutions/cf-977F.mdx
> +		// Print the indices of the subsequence.
```suggestion
```

2021-08-20 16:09 UTC, SansPapyrus683 commented
also my sol's here: https://codeforces.com/contest/977/submission/120682896
if you want to add it you can (just credit me)

2021-08-20 16:22 UTC, maggie-j-liu commented on solutions/cf-977F.mdx
> +## Solution
i don't think this header is necessary

2021-08-21 00:00 UTC, SansPapyrus683 requested changes

2021-08-21 00:00 UTC, SansPapyrus683 commented on solutions/cf-977F.mdx
> + */
```suggestion
```
crap sorry this is just for me

2021-08-21 00:00 UTC, SansPapyrus683 commented on solutions/cf-977F.mdx
> +	std::map<int, int> come_from;
(not necessary) add comments if you can? i'd comment but i forgot how this problem worked ahahaha

2021-08-23 16:45 UTC, SansPapyrus683 approved these changes

2021-08-23 21:51 UTC, SansPapyrus683 commented on solutions/cf-977F.mdx
> +	std::map<int, int> come_from;
bump

2021-08-23 23:46 UTC, maggie-j-liu approved these changes

2021-08-24 02:16 UTC, nathangong approved these changes

2021-08-24 03:22 UTC, ryanchou-dev approved these changes

2021-08-24 10:31 UTC, dongliu0426 approved these changes

2021-08-24 10:32 UTC, merged