Internal java solution for CSES Movie Festival II
cpinitiative/usaco-guide pull request #2129
Opened 2021-08-22 17:56 UTC by nathangong

2021-08-22 23:46 UTC, SansPapyrus683 requested changes

2021-08-22 23:46 UTC, SansPapyrus683 commented on solutions/cses-1632.mdx
> +	// BeginCodeSnip{FastIO}
i take it kattio doesn't work?

2021-08-22 23:46 UTC, SansPapyrus683 commented on solutions/cses-1632.mdx
> +		int ans = 0;
maybe rename to `maxMovies`

2021-08-22 23:46 UTC, SansPapyrus683 commented on solutions/cses-1632.mdx
> +		endTimes.put(0, k); // initialize all members at time 0
put two spaces after a line of code before you start a comment
```suggestion
		endTimes.put(0, k);  // initialize all members at time 0
```

2021-08-22 23:52 UTC, nathangong commented on solutions/cses-1632.mdx
> +	// BeginCodeSnip{FastIO}
yeah i added a warning block for it

2021-08-23 00:00 UTC, SansPapyrus683 approved these changes
wow didn't think you'd take my `ans` suggestion

2021-08-23 06:18 UTC, brad182 approved these changes
Sanspapyrus683 has nothing more to say so it definitely is good

2021-08-23 10:27 UTC, dongliu0426 requested changes

2021-08-23 10:27 UTC, dongliu0426 commented on solutions/cses-1632.mdx
> +a `TreeMap` in Java). Initially, the collection consists of $k$ zeroes.
```suggestion
([represented](/silver/intro-ordered/#multisets) by
a `TreeMap` in Java or a `multiset` in C++). Initially, the collection consists of $k$ zeroes.
```

2021-08-23 10:30 UTC, dongliu0426 commented
(merging if checks pass)

2021-08-23 10:34 UTC, merged