Python Implementation
cpinitiative/usaco-guide pull request #2139
Opened 2021-08-27 06:23 UTC by nour-massri

2021-08-28 21:54 UTC, nwatx approved these changes

2021-08-31 16:01 UTC, Aadit-Ambadkar requested changes

2021-09-04 02:35 UTC, nwatx commented on solutions/ac-IndependentSet.mdx
> +adj = [[] for i in range(n)]
![image](https://user-images.githubusercontent.com/43394822/132079679-34c0107b-3567-49b5-9644-cea91543dfb5.png)

2021-09-04 02:42 UTC, chezbgone commented on solutions/ac-IndependentSet.mdx
> +adj = [[] for i in range(n)]
If you use `*` for arrays, the elements in the array all have the same reference, which is not what we want.

2021-09-05 01:37 UTC, Aadit-Ambadkar commented
Removed my incorrect revisions, sorry about that. Silly mistake on my part.

2021-09-12 21:22 UTC, Aadit-Ambadkar approved these changes
Looks Good

2021-09-15 09:43 UTC, dongliu0426 approved these changes

2021-09-15 09:44 UTC, merged