add java and cpp sol to cses elevator rides
cpinitiative/usaco-guide pull request #2148
Opened 2021-08-29 19:50 UTC by TruaShamu

2021-08-29 22:14 UTC, nathangong commented on solutions/cses-1653.mdx
> +public class elevators {
```suggestion
public class ElevatorRides {
```

2021-08-29 22:20 UTC, nathangong requested changes

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +	static class state {
```suggestion
	static class State {
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +		public state(int rides, int weight) {
```suggestion
		public State(int rides, int weight) {
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +		dp[0] = new state(1, 0);
```suggestion
		dp[0] = new State(1, 0);
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +	public static state[] dp;
```suggestion
	public static State[] dp;
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +		dp = new state[1 << people];
```suggestion
		dp = new State[1 << people];
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +			dp[mask] = new state(people + 1, maxWeight + 1);
```suggestion
			dp[mask] = new State(people + 1, maxWeight + 1);
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +					state cur = new state(dp[prev].rides, dp[prev].weight);
```suggestion
					Statecur = new State(dp[prev].rides, dp[prev].weight);
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +		public int compareTo(state oState) {
```suggestion
		public int compareTo(State oState) {
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +		*/
```suggestion
		 */
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +		If the ith bit is set, it means the ith person has used the elevator.
```suggestion
		 * dp[bitmask] is the current best state
		 * in terms of the number of rides used, and weight used on the last ride.
		 * The bitmask is used to represent whether the people have used the elevator.
		 * If the ith bit is set, it means the ith person has used the elevator.
```

2021-08-29 22:20 UTC, nathangong commented on solutions/cses-1653.mdx
> +	public static state[] dp;
Is there a need for these to be instance variables? If not, it's probably more efficient to just declare them in the main method

2021-08-30 00:08 UTC, TruaShamu commented
Alright, done.
Sorry for making you fix all of my stuff for me

2021-08-30 03:33 UTC, nathangong commented
Yep no problem

2021-08-31 01:32 UTC, nathangong approved these changes
java code looks good

2021-08-31 19:27 UTC, maggie-j-liu commented on solutions/cses-1653.mdx
> +	*/
can you format this comment like the java one? with `*` in front of every line

2021-08-31 20:12 UTC, TruaShamu commented
alright, done!

2021-08-31 20:19 UTC, maggie-j-liu approved these changes
looks good but i couldn't check the preview since the deployment is kinda broken

2021-09-01 02:04 UTC, dongliu0426 commented on solutions/cses-1653.mdx
> +
can you link the CPH expl? section 10.5

2021-09-01 13:39 UTC, TruaShamu commented on solutions/cses-1653.mdx
> +
done!

2021-09-01 13:52 UTC, merged