Navbar Changes
cpinitiative/usaco-guide pull request #2152
Opened 2021-08-31 00:00 UTC by AAkashyap1

2021-08-31 04:06 UTC, nathangong commented
the nav bar has 2 rows when the user is in a group, also the open icon looks a bit out of place:
![image](https://user-images.githubusercontent.com/8647920/131440056-6bfba52b-08e4-46cf-8989-ea0edba3c6d3.png)

2021-09-01 01:48 UTC, AAkashyap1 commented
> the nav bar has 2 rows when the user is in a group, also the open icon looks a bit out of place:
> ![image](https://user-images.githubusercontent.com/8647920/131440056-6bfba52b-08e4-46cf-8989-ea0edba3c6d3.png)

Ok how does it look now?

2021-09-03 21:24 UTC, thecodingwizard commented
I think the links are too narrow... is there a better navbar layout?

2021-09-03 22:04 UTC, nathangong commented
maybe this one?
![image](https://user-images.githubusercontent.com/8647920/132069182-d0c199b9-3813-48a1-8dd7-49671567704d.png)
I can help work on it if needed since I did the current flyout menu

2021-09-03 22:05 UTC, AAkashyap1 commented
> maybe this one?
> ![image](https://user-images.githubusercontent.com/8647920/132069182-d0c199b9-3813-48a1-8dd7-49671567704d.png)
> I can help work on it if needed since I did the current flyout menu

I think this would look good what do you think @thecodingwizard

2021-09-03 22:09 UTC, AAkashyap1 commented
> I think the links are too narrow... is there a better navbar layout?

<img width="1225" alt="Screen Shot 2021-09-03 at 6 08 48 PM" src="https://user-images.githubusercontent.com/72512284/132069590-9d9e2586-165b-422c-b192-cb3d5a581872.png">
 or maybe this one?

2021-09-03 22:10 UTC, AAkashyap1 commented
<img width="1225" alt="Screen Shot 2021-09-03 at 6 10 16 PM" src="https://user-images.githubusercontent.com/72512284/132069656-21faa240-7a6a-4949-88cc-eae85c4e316b.png">
or maybe this one?

2021-09-03 22:11 UTC, nathangong commented
it might get it bit tall with all those links

2021-09-03 22:12 UTC, AAkashyap1 commented
we could put ide and forum on the bottom thing

2021-09-06 05:37 UTC, ryanchou-dev requested changes

2021-09-06 05:37 UTC, ryanchou-dev commented on src/components/TopNavigationBar/TopNavigationBar.tsx
> +                        <Popover.Panel static className="hidden md:block z-20 shadow-lg absolute left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-md sm:px-0 lg:max-w-3xl">
```suggestion
                        <Popover.Panel static className="hidden md:block z-20 shadow-lg absolute left-1/2 transform -translate-x-1/2 -mt-2 px-2 w-screen max-w-md sm:px-0 lg:max-w-3xl">
```
fix margin

2021-09-06 09:16 UTC, thecodingwizard approved these changes
code seems fine. didn't test UI, I'm on phone. merge if you think it's good :D

2021-09-06 20:56 UTC, ryanchou-dev approved these changes
lgtm!

2021-09-06 22:07 UTC, maggie-j-liu commented
do you think the dark mode background should be a little lighter (compare with sections dropdown)?
![image](https://user-images.githubusercontent.com/63619830/132262795-aa521410-ec09-4e59-b639-7106037ab5a4.png)
![image](https://user-images.githubusercontent.com/63619830/132262799-a4147600-db7b-42de-8120-4cc7e1d0d1c5.png)

2021-09-06 22:13 UTC, AAkashyap1 commented
Yeah it should be I'll change that

2021-09-07 04:13 UTC, maggie-j-liu approved these changes

2021-09-07 04:13 UTC, maggie-j-liu commented
fix the merge conflict, then i can merge

2021-09-09 21:54 UTC, merged