Update Input_Output.mdx - stdin and stdout Python
cpinitiative/usaco-guide pull request #2161
Opened 2021-09-01 06:15 UTC by Garlicbread12

Added stdin and stdout as methods for input and output for the Python section. I might additionally add stdin and stdout to Fast I/O for Python in the future if it would be helpful. There are many grammatical errors/spelling errors that I didn't catch, but I don't know how to change them after pressing the 'commit changes' button. Any tips relating to GitHub, as you could probably tell, would be very much appreciated. 

Grammatical errors/formatting errors:
line 464: 'become' should be 'becomes'

2021-09-01 13:02 UTC, dongliu0426 approved these changes
:clap: :clap:

2021-09-01 14:58 UTC, SansPapyrus683 requested changes

2021-09-01 14:58 UTC, SansPapyrus683 commented on content/1_General/Input_Output.mdx
> +`print()` methods. The
wait why'd you remove the doc links

2021-09-01 14:58 UTC, SansPapyrus683 commented on content/1_General/Input_Output.mdx
> +import sys
```suggestion
import sys

```
do this for the other imports as well

2021-09-01 14:58 UTC, SansPapyrus683 commented on content/1_General/Input_Output.mdx
> +print("sum is",a+b+c)
spaces between ops

2021-09-01 14:58 UTC, SansPapyrus683 commented on content/1_General/Input_Output.mdx
> +
```suggestion
```

2021-09-01 16:08 UTC, Garlicbread12 commented on content/1_General/Input_Output.mdx
> +`print()` methods. The
I'm pretty sure I added them above.

2021-09-02 01:51 UTC, SansPapyrus683 requested changes

2021-09-02 01:51 UTC, SansPapyrus683 commented on content/1_General/Input_Output.mdx
> +import sys
put a newline after the import

2021-09-02 01:51 UTC, SansPapyrus683 commented on content/1_General/Input_Output.mdx
>  print("sum is",a+b+c)
spaces between ops all over here as well
```suggestion
a, b, c = map(int, input().split())
print("sum is", a + b + c)

# stdin and stdout
a, b, c = map(int, sys.stdin.readline().split())
print("sum is", a + b + c)
```

2021-09-02 03:03 UTC, SansPapyrus683 approved these changes
poggers

2021-09-03 01:11 UTC, ryanchou-dev approved these changes

2021-09-03 08:34 UTC, merged