Quiz for Complete Recursion
cpinitiative/usaco-guide pull request #2162
Opened 2021-09-01 15:53 UTC by dutinmeow

2021-09-02 02:38 UTC, SansPapyrus683 commented
wwwait
where's deployment

2021-09-02 02:49 UTC, maggie-j-liu commented
![image](https://user-images.githubusercontent.com/63619830/131773670-3cd2e831-114f-4e14-9938-3598a7f207dd.png)

2021-09-02 02:53 UTC, SansPapyrus683 commented
![image](https://user-images.githubusercontent.com/55369003/131774060-71de30f1-117f-462a-bce4-83199ad17019.png)
soooooo did i get this right?

2021-09-02 02:55 UTC, SansPapyrus683 commented
ok so i didn't
the question is worded kinda poorly because i thought it was just iterating through the permutations and stuff

![image](https://user-images.githubusercontent.com/55369003/131774095-2e4d5325-d2e7-49c4-b5ef-fef96aea9bc4.png)
arrays are kinda niche, use a vector instead

2021-09-02 02:58 UTC, SansPapyrus683 commented
don't expect people in bronze to know about arrays
c arrays in general are just a pain to work with- they're error prone and hard to debug
just use vectors lol

2021-09-02 03:11 UTC, maggie-j-liu commented
wait i'm so confused i thought people learned arrays before vectors??

2021-09-02 03:26 UTC, SansPapyrus683 commented
who the hell would learn arrays before vectors

2021-09-02 04:03 UTC, ryanchou-dev commented
> ![image](https://user-images.githubusercontent.com/55369003/131774060-71de30f1-117f-462a-bce4-83199ad17019.png)
> soooooo did i get this right?

yup, definitely reword this

2021-09-02 04:44 UTC, ryanchou-dev commented
> I tried to make code as general as possible (for java and python users). Arrays are mostly similar across different languages, whereas vectors are completely different (ArrayList in Java vs Lists in Python)

you can do different code for diff languages right? <languagesection>

2021-09-02 04:47 UTC, dutinmeow commented
I think next_permutation only exists in C++ and it defeats the point of the question to generate it with recursion. ~~also i suck with java and python~~. I can write different solutions for the third one tho.

2021-09-02 04:48 UTC, ryanchou-dev commented
> I think next_permutation only exists in C++ and it defeats the point of the question to generate it with recursion. ~also i suck with java and python~. I can write different solutions for the third one tho.

i can help with python! and nathan would be good for java :D

2021-09-02 04:49 UTC, dutinmeow commented
I mean I can do them but idk how to do next_permutation in other languages for the second question

2021-09-02 04:50 UTC, ryanchou-dev commented
> I think next_permutation only exists in C++ and it defeats the point of the question to generate it with recursion. ~also i suck with java and python~. I can write different solutions for the third one tho.



> I think next_permutation only exists in C++

err then i think you shouldn't use it as a question, cuz it'll be irrelevant for python and java users.

2021-09-02 04:52 UTC, dutinmeow commented
But the module itself mentions next_permutation. Also majority of CP people use c++

2021-09-02 04:53 UTC, ryanchou-dev commented
> But the module itself mentions next_permutation. Also majority of CP people use c++

for other languages (since you can change questions for different lang settings)

2021-09-02 04:54 UTC, dutinmeow commented
ok, ill change it. Can you guys write the other languages then? @ryanchou-dev @thecodingwizard

2021-09-02 22:56 UTC, nathangong commented
What happened to the question that involves coding in the python and java sections? Are we not going to include them or are they waiting to be translated into the respective languages?

2021-09-03 03:57 UTC, dutinmeow commented
I think we decide that we'er not going to include them

2021-09-03 03:59 UTC, ryanchou-dev commented
> What happened to the question that involves coding in the python and java sections? Are we not going to include them or are they waiting to be translated into the respective languages?

yeah i think it was too inconsistent across languages, and the `next_permutation` error was more targeted for cpp users. (it wouldn't be necessary for python and java)

2021-09-03 15:48 UTC, caoash commented
I learned arrays before vectors

2021-09-05 01:51 UTC, Aadit-Ambadkar commented
> who the hell would learn arrays before vectors

Language

2021-09-05 02:01 UTC, Aadit-Ambadkar requested changes

2021-09-05 02:01 UTC, Aadit-Ambadkar commented on content/2_Bronze/Complete_Rec.mdx
> +		A hallmark of problems featuring complete search with permutations/subsets is that $n$ is small, usually $\leq 20$. This means that recursion won't go particularly deep, and there won't be any issu
```suggestion
		Incorrect: A hallmark of problems featuring complete search with permutations/subsets is that $n$ is small, usually $\leq 20$. This means that recursion won't go particularly deep, and there won't be any issues with stack size. 
```

2021-09-05 02:01 UTC, Aadit-Ambadkar commented on content/2_Bronze/Complete_Rec.mdx
> +		Having to code your own permutation/subset function can be inefficient in a timed contest environment. It's definitely worth learning iterative methods to save valuable time on debugging.
```suggestion
		Correct: Having to code your own permutation/subset function can be inefficient in a timed contest environment. It's definitely worth learning iterative methods to save valuable time on debugging. 
```

2021-09-05 02:01 UTC, Aadit-Ambadkar commented on content/2_Bronze/Complete_Rec.mdx
> +		Although recursion is slowing than iterative methods, it's still fast enough to pass most problems
```suggestion
		Incorrect: Although recursion is slowing than iterative methods, it's still fast enough to pass most problems
```

2021-09-05 02:01 UTC, Aadit-Ambadkar commented on content/2_Bronze/Complete_Rec.mdx
> +    <JavaSection>
Repeat C++ Comments

2021-09-05 02:01 UTC, Aadit-Ambadkar commented on content/2_Bronze/Complete_Rec.mdx
> +    <CPPSection>
Add Correct and Incorrect for each of these

2021-09-05 02:02 UTC, Aadit-Ambadkar commented
Add Correct and Incorrect to the beginning of each Answer Explanation.

2021-09-05 03:23 UTC, SansPapyrus683 commented
> > who the hell would learn arrays before vectors
> 
> Language

arpan don't say that i've seen you say the f word in the discord

2021-09-07 16:09 UTC, SansPapyrus683 approved these changes
should be good enough
also if we have to add Correct of Incorrect in front of each answer explanation
why not just automate it or something

2021-09-21 17:38 UTC, closed without merging

2021-09-21 18:29 UTC, SansPapyrus683 commented
bruh