Cpinitiative master
cpinitiative/usaco-guide pull request #2171
Opened 2021-09-05 18:58 UTC by nwatx

2021-09-05 18:59 UTC, nwatx commented
wait woops i accidently created a pr

2021-09-05 20:26 UTC, maggie-j-liu commented
![image](https://user-images.githubusercontent.com/63619830/132140485-34e618e1-1e44-47ab-b1f7-975b8ab4055b.png)
where are the groups supposed to show? (i have admin perms and this is on the deployment)

2021-09-05 20:30 UTC, nwatx commented
> ![image](https://user-images.githubusercontent.com/63619830/132140485-34e618e1-1e44-47ab-b1f7-975b8ab4055b.png)
> where are the groups supposed to show? (i have admin perms and this is on the deployment)

strange, on my emulator build it showed. Can you try signing out and back in?

2021-09-05 20:32 UTC, maggie-j-liu commented
still doesn't show, but i can see admin settings so the permissions are working correctly
![image](https://user-images.githubusercontent.com/63619830/132140621-f74ba684-9e2a-467c-a4b2-b5aedc347147.png)

2021-09-05 20:34 UTC, nwatx commented
wtmoo. can you try on this preview build once it finishes and ss console

2021-09-06 09:14 UTC, thecodingwizard commented
what's up with package-lock and yarn lock? In general we should use yarn for everything for guide...

2021-09-09 22:22 UTC, thecodingwizard requested changes
I updated firebase rules such that admins should have read access to everything. Haven't tested fully yet though.

In addition to review comments, I don't think any of the yarn.lock / package-lock.json files need to be touched.

Thanks for working on this! :)

2021-09-09 22:22 UTC, thecodingwizard commented on gatsby-config.js
> +
oops wait why is this needed?

2021-09-09 22:22 UTC, thecodingwizard commented on src/hooks/groups/useUserGroups.tsx
> +  console.log(groups);
probs don't need console.logs

2021-09-09 22:22 UTC, thecodingwizard commented on src/hooks/groups/useUserGroups.tsx
> +              setGroups(queryResults.slice(0, queryResults.length / 3));
don't query three times if admin. you should just query once only.

2021-09-25 03:22 UTC, nwatx commented
too many git errors, continued in new pr

2021-09-25 03:22 UTC, closed without merging