Python Implementation
cpinitiative/usaco-guide pull request #2175
Opened 2021-09-06 18:17 UTC by Mohammad-Nour-Massri

2021-09-06 19:08 UTC, jessechoe10 commented on solutions/ac-MultipleOf2019.mdx
> +```py
```suggestion
<PySection>

```py
```

2021-09-06 19:08 UTC, jessechoe10 commented on solutions/ac-MultipleOf2019.mdx
> +</PySection>
```suggestion
```

</PySection>
```

2021-09-06 19:09 UTC, jessechoe10 commented on solutions/ac-MultipleOf2019.mdx
> +print(ans)
Use tabs instead of spaces to indent

2021-09-06 23:16 UTC, SansPapyrus683 requested changes

2021-09-06 23:16 UTC, SansPapyrus683 commented on solutions/ac-MultipleOf2019.mdx
> +
```suggestion
```

2021-09-06 23:16 UTC, SansPapyrus683 commented on solutions/ac-MultipleOf2019.mdx
> +cnt = [0]*MOD
spaces between operators please

2021-09-06 23:16 UTC, SansPapyrus683 commented on solutions/ac-MultipleOf2019.mdx
> +	    # increase the power of 10
uuuuhhh indentation seems hecked up

2021-09-07 15:59 UTC, SansPapyrus683 approved these changes
think this is good enough
i would like better variable names though

2021-09-09 12:20 UTC, dongliu0426 approved these changes

2021-09-09 12:31 UTC, merged