DFS for Fence Planning
cpinitiative/usaco-guide pull request #2183
Opened 2021-09-09 21:58 UTC by AAkashyap1

2021-09-09 22:50 UTC, SansPapyrus683 requested changes
i don't know why you brought this upon yourself

2021-09-09 22:50 UTC, SansPapyrus683 commented on solutions/usaco-944.mdx
> +vector<int> adj[100001];
put 1e5 in a constant called `MAX_N`
and then when declaring this array use `MAX_N + 1`
or you could be a normal person and use nested vectors

2021-09-09 22:50 UTC, SansPapyrus683 commented on solutions/usaco-944.mdx
> +vector<bool> visited(100001, false);
same here

2021-09-09 22:50 UTC, SansPapyrus683 commented on solutions/usaco-944.mdx
> +int n, m;
these can be made local to `main`

2021-09-09 22:50 UTC, SansPapyrus683 commented on solutions/usaco-944.mdx
> +	long long min_perimeter = 10000000000;
if all you need is a big number
use `INT64_MAX`

2021-09-09 22:50 UTC, SansPapyrus683 commented on solutions/usaco-944.mdx
> +}
comments explaining what these 2 functions do?

2021-09-10 01:35 UTC, nwatx approved these changes

2021-09-12 00:33 UTC, jessechoe10 approved these changes

2021-09-26 01:25 UTC, closed without merging