Make photoshoot changes
cpinitiative/usaco-guide pull request #2189
Opened 2021-09-11 10:17 UTC by Navigator365

Continuing changes from pr that didn't make any

2021-09-11 14:29 UTC, maggie-j-liu commented on solutions/usaco-988.mdx
>  Since $N \leq 1000$, we can simulate every ordering and pick the first valid permutation (since that would be the lexicographical minimum).
you didn't add this part, but it's not really simulating every ordering? maybe change it to "simulate picking every cow as the first one" (but worded better)?

2021-09-11 17:19 UTC, ryanchou-dev requested changes

2021-09-11 17:19 UTC, ryanchou-dev commented on solutions/usaco-988.mdx
> +
```suggestion
```

2021-09-11 17:19 UTC, ryanchou-dev commented on solutions/usaco-988.mdx
> +author: Ananth Kashyap, Ben Dodge
```suggestion
author: Ananth Kashyap, Ryan Chou, Ben Dodge
```
this is for me, forgot to add author name last time:
https://github.com/cpinitiative/usaco-guide/pull/2109

2021-09-11 17:19 UTC, ryanchou-dev commented on solutions/usaco-988.mdx
> +Since the `in` operator in Python takes $\mathcal{O}(N)$ time, this solution is $\mathcal{O}(N^3)$.
i think this is fine, the actual time complexity is right above it, and the info is to let you know that another language would be faster? but up to you

2021-09-11 17:19 UTC, ryanchou-dev commented on solutions/usaco-988.mdx
> +		boolean[] isItThere = new boolean[N];
maybe changed to `used` or smth

2021-09-11 19:38 UTC, SansPapyrus683 commented on solutions/usaco-988.mdx
> +			// We've found a valid permutation since we started from 1, the
```suggestion
			// We've found a valid permutation: since we started from 1, the
```

2021-09-11 19:38 UTC, SansPapyrus683 commented on solutions/usaco-988.mdx
> +					else {
```suggestion
					} else {
```
can you do this for the other if/else's as well
the current brace style is a blight upon this earth

2021-09-11 19:53 UTC, ryanchou-dev approved these changes

2021-09-11 22:00 UTC, SansPapyrus683 approved these changes

2021-09-12 20:31 UTC, nathangong approved these changes
just this

2021-09-12 20:31 UTC, nathangong commented on solutions/usaco-988.mdx
> +				io.print("\n");
```suggestion
				io.println();
```

2021-09-13 08:40 UTC, dongliu0426 approved these changes

2021-09-13 08:40 UTC, merged