Update usaco-1114.mdx
cpinitiative/usaco-guide pull request #2209
Opened 2021-09-19 20:55 UTC by TruaShamu

1. Replaced original cpp code with  new code by @nwatx (old one WAs on all testcases except for the first) 
2. Added java code

2021-09-19 20:58 UTC, nwatx commented on solutions/usaco-1114.mdx
>  //CodeSnip{CPP Short Template}
add your name to authors

2021-09-19 20:58 UTC, TruaShamu commented
@nwatx  The current cpp code on the internal sol gives WA, so I replaced it with the one you dmed me on discord, if that's okay with you?

2021-09-19 21:00 UTC, TruaShamu commented on solutions/usaco-1114.mdx
>  //CodeSnip{CPP Short Template}
ok, done

2021-09-19 21:01 UTC, nwatx commented
> @nwatx The current cpp code on the internal sol gives WA, so I replaced it with the one you dmed me on discord, if that's okay with you?

yes, and I did make a commit fixing this earlier (so I think if you test out the code currently on the website it should still pass)

2021-09-19 21:01 UTC, nwatx approved these changes

2021-09-19 21:13 UTC, SansPapyrus683 requested changes
this is what i can find rn

2021-09-19 21:13 UTC, SansPapyrus683 commented on solutions/usaco-1114.mdx
> +public static int[][] DP = new int[MAXN][MAXN];
1. indentation is really weird
2. rename `inp` to like `painting` or smth
3. rename `DP` to `dp`

2021-09-19 21:13 UTC, SansPapyrus683 commented on solutions/usaco-1114.mdx
> +		for(int s = 1; s <= N; s++) {
can you have spaces for the control statements
like
```suggestion
		for (int s = 1; s <= N; s++) {
```

2021-09-19 21:13 UTC, SansPapyrus683 commented on solutions/usaco-1114.mdx
> +						DP[i][k] = Math.min(DP[i][k], DP[i][j] + DP[j + 1][k] - 1);
comments would be nice

2021-09-19 21:13 UTC, SansPapyrus683 commented on solutions/usaco-1114.mdx
> +	for(int s = 1; s <= n; s++) {
same thing with the spaces and whatnot

2021-09-19 21:13 UTC, SansPapyrus683 commented on solutions/usaco-1114.mdx
> +const int MAX_N = 301;
wait why 301 300 should work perfectly fine

2021-09-19 21:14 UTC, SansPapyrus683 commented on solutions/usaco-1114.mdx
> +public static int[][] DP = new int[MAXN][MAXN];
nvm i fixed 1 myself

2021-09-19 22:52 UTC, SansPapyrus683 commented on solutions/usaco-1114.mdx
> +	public static int[] inp = new int[MAXN];
again, could you rename this to `painting` or smth

2021-09-20 01:07 UTC, TruaShamu commented
Alright, does this look more reasonable now, maybe?

2021-09-20 01:23 UTC, SansPapyrus683 approved these changes

2021-09-20 01:24 UTC, TruaShamu commented
Wait, I broke something

2021-09-20 01:25 UTC, SansPapyrus683 commented
lmao f

2021-09-20 01:27 UTC, TruaShamu commented
MAXN has to be 301 instead of 300 because the forloop runs for(i=0; i<=N; i++)
I'm an idiot :|

2021-09-20 01:28 UTC, TruaShamu commented
So - can I change it back to 301...or...

2021-09-20 01:34 UTC, SansPapyrus683 commented
wait why does it have to be <= N

2021-09-20 11:04 UTC, dongliu0426 approved these changes

2021-09-20 11:04 UTC, dongliu0426 commented on solutions/usaco-1114.mdx
> +	for (int i = 0; i < MAX_N; i++) dp[i][i] = 1;
actually, what's wrong with `i < n;`?

2021-09-20 12:30 UTC, TruaShamu commented
Sorry, I was asleep - I'll go change both versions to < n

2021-09-20 19:39 UTC, TruaShamu commented
Ok, done

2021-09-20 22:36 UTC, SansPapyrus683 commented
now does max n = 300 work?

2021-09-20 23:17 UTC, TruaShamu commented
Yeah, it does!

For your viewing pleasure:

[Java AC](https://ibb.co/nzkc1W2)


[CPP AC](https://ibb.co/H491nhp)

2021-09-21 00:04 UTC, SansPapyrus683 commented
ok cool
now i can rest in pieces

2021-09-21 05:53 UTC, merged