Update Data_Types.mdx
cpinitiative/usaco-guide pull request #2290
Opened 2021-10-31 18:49 UTC by bqi343

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-10-31 18:52 UTC, bqi343 commented on content/1_General/Data_Types.mdx
> +index and take substrings of the string (`charAt()` and `substring()` in Java).
You can't really treat java strings like arraylists ... you can't set the `i`-th character of a string

2021-10-31 18:52 UTC, bqi343 commented on content/1_General/Data_Types.mdx
> +index and take substrings of the string (`charAt()` and `substring()` in Java).
probably should make a note of this but I'm not a Java user so idrc

2021-10-31 20:28 UTC, Aadit-Ambadkar requested changes

2021-10-31 20:28 UTC, Aadit-Ambadkar commented on content/1_General/Data_Types.mdx
> +| Size (bits) | 32                      | 64                      | 32                       | 64                         | 1(\*)            | 16                               |
```suggestion
| Size (bytes) | 4                      | 8                      | 4                       | 8                         | 1 bit(\*)            | 2                               |
```
consistency

2021-11-01 02:40 UTC, Aadit-Ambadkar approved these changes

2021-11-01 03:04 UTC, merged