Fix time complexity of usaco-760.mdx
cpinitiative/usaco-guide pull request #2298
Opened 2021-11-01 21:34 UTC by theMasix

the `find` method has a for O(n) in it. and `find` function executes in another for loop. So the final time complexity is O(n^2) - Checkout line `83` and `56` of the file

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-11-02 01:20 UTC, SansPapyrus683 commented
hold on- the c++ sol is n^2 but the python solution is just n?

2021-11-02 01:56 UTC, nathangong commented
i think we should optimize the C++ one then

2021-11-02 05:35 UTC, theMasix commented
If we wanna optimize the c++ solution, the easiest way is creating a
`revSwapOrder` which holds the orders in reversed. Then each query to get
the origin of the swap executes in O(1). And the total time complexity will
be O(n).

On Tue, Nov 2, 2021, 5:26 AM Nathan Gong ***@***.***> wrote:

> i think we should optimize the C++ one then
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cpinitiative/usaco-guide/pull/2298#issuecomment-957029368>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFOQANIKLVBZSXDL2WFNZSTUJ5AOLANCNFSM5HE7D7OA>
> .
>

2021-11-05 16:22 UTC, dutinmeow approved these changes
If it isn't broken then there's no need to fix the code

2021-11-07 22:35 UTC, Aadit-Ambadkar requested changes
spacing

2021-11-07 22:35 UTC, Aadit-Ambadkar commented on solutions/usaco-760.mdx
```suggestion
## Implementation
```

2021-11-07 22:35 UTC, Aadit-Ambadkar commented on solutions/usaco-760.mdx
> +**Time Complexity:** $\mathcal{O}(N^2)$
```suggestion
**Time Complexity:** $\mathcal{O}(N^2)$

```

2021-11-08 00:14 UTC, dutinmeow commented on solutions/usaco-760.mdx
wait what was changed

2021-11-22 00:52 UTC, closed without merging