Added new mobile nav bar
cpinitiative/usaco-guide pull request #2323
Opened 2021-11-09 04:48 UTC by shaymor

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [✓ ] I have tested my code
- [✓ ] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [✓] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-11-09 19:29 UTC, maggie-j-liu requested changes

2021-11-09 19:29 UTC, maggie-j-liu commented on src/components/TopNavigationBar/TopNavigationBar.tsx
> +      href: '#',
add these links in

2021-11-09 19:29 UTC, maggie-j-liu commented on src/components/TopNavigationBar/TopNavigationBar.tsx
> +                  <a
use gatsby's link for these since they're internal links

2021-11-09 19:29 UTC, maggie-j-liu commented on src/components/TopNavigationBar/TopNavigationBar.tsx
> +                <a
use the Link component here too

2021-11-09 19:29 UTC, maggie-j-liu commented on src/components/TopNavigationBar/TopNavigationBar.tsx
> +                <a
same here

2021-11-10 02:40 UTC, nathangong commented
![image](https://user-images.githubusercontent.com/8647920/141039740-2ae533aa-d4e0-4d23-ba3c-f1204ff0dab8.png)
Colors are a bit wack in light mode

2021-11-10 02:41 UTC, nathangong commented
Maybe make forum, classes, clubs, ide, contests, and workshops open up in a new tab? (similar to desktop)

2021-11-10 02:49 UTC, shaymor commented
> ![image](https://user-images.githubusercontent.com/8647920/141039740-2ae533aa-d4e0-4d23-ba3c-f1204ff0dab8.png) Colors are a bit wack in light mode

i fixed the light mode thing and will be pushing soon

2021-11-10 02:49 UTC, shaymor commented
> Maybe make forum, classes, clubs, ide, contests, and workshops open up in a new tab? (similar to desktop)

will update this

2021-11-10 04:58 UTC, maggie-j-liu commented
very small detail, but the icon colors are pretty similar to the hover color 
![image](https://user-images.githubusercontent.com/63619830/141052575-821835ea-b5d2-4012-b777-58bee12b1b90.png)

maybe have them be a bit lighter when hovering?

otherwise i think it looks good!

2021-11-10 05:02 UTC, shaymor commented
> very small detail, but the icon colors are pretty similar to the hover color ![image](https://user-images.githubusercontent.com/63619830/141052575-821835ea-b5d2-4012-b777-58bee12b1b90.png)
> 
> maybe have them be a bit lighter when hovering?
> 
> otherwise i think it looks good!

is this just on dark mode or also on light mode?

2021-11-14 00:22 UTC, maggie-j-liu approved these changes
i think this looks good! do you want to add the new icons for each section in this pr or do that in a later pr?

2021-11-22 21:02 UTC, shaymor commented
> i think this looks good! do you want to add the new icons for each section in this pr or do that in a later pr?

i think we can merge this pr for now

2021-11-24 01:56 UTC, maggie-j-liu commented
oops one small thing i noticed
![image](https://user-images.githubusercontent.com/63619830/143157336-9eca4a00-a2fe-4b89-ab93-83f89052a91f.png)
on this button (and the contact form button) only the words are clickable. can you make it so that the entire part that turns gray is clickable?

2021-12-06 22:03 UTC, nwatx commented
@maggie-j-liu is this ready to merge?

2021-12-06 22:03 UTC, nwatx commented
(after fixing build)

2021-12-06 23:59 UTC, maggie-j-liu commented
uhh after this is addressed https://github.com/cpinitiative/usaco-guide/pull/2323#issuecomment-977393261

2021-12-10 15:35 UTC, shaymor commented
sorry about that, pushed updates

2021-12-10 16:42 UTC, maggie-j-liu approved these changes

2021-12-13 06:57 UTC, merged