add java implementation to phidias
cpinitiative/usaco-guide pull request #2325
Opened 2021-11-09 15:39 UTC by TruaShamu

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [ ] I have tested my code
- [ ] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [ ] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-11-09 15:49 UTC, TruaShamu commented
Proof that it works
![phidias1](https://user-images.githubusercontent.com/48630514/140957427-22bc7bcf-fc75-4aff-9357-18f63d558912.png)
![phidias2](https://user-images.githubusercontent.com/48630514/140957430-68caa970-4e17-4b53-8f91-21366f7ffa58.png)

2021-11-09 23:11 UTC, jessechoe10 approved these changes

2021-11-09 23:43 UTC, SansPapyrus683 requested changes
too lazy to commit these changees myself

2021-11-09 23:43 UTC, SansPapyrus683 commented on solutions/dmoj-Phidias.mdx
> +
```suggestion
```

2021-11-09 23:43 UTC, SansPapyrus683 commented on solutions/dmoj-Phidias.mdx
> +
```suggestion
```

2021-11-10 00:18 UTC, SansPapyrus683 approved these changes
enough comments to excuse the bad variable names

2021-11-10 19:41 UTC, merged