fix error in rect-geo
cpinitiative/usaco-guide pull request #2331
Opened 2021-11-11 02:54 UTC by ryanchou-dev

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [ ] I have tested my code
- [ ] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [ ] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-11-11 02:58 UTC, nathangong commented
Right now, the "finding area," "checking if rectangles intersect," "finding area of intersection" titles are all smaller than the implementation title, which doesn't make much sense: 
![image](https://user-images.githubusercontent.com/8647920/141229378-dc0b6e27-8db8-4cb7-a7c3-1c6c6107a009.png)
Can you make the implementation titles for those respective sections have three #'s (instead of 2) as well?

2021-11-11 02:59 UTC, nathangong commented
It would also be nice if the min and max functions were part of the latex (using \min and \max)
![image](https://user-images.githubusercontent.com/8647920/141229616-669ae34e-22f8-4bf9-bca0-8c35f4998751.png)

2021-11-11 03:35 UTC, nathangong reviewed
Can you also change the header for the area of intersection implementation section?

2021-11-11 03:35 UTC, nathangong commented on content/2_Bronze/Rect_Geo.mdx
> +$y$ = $\min(tr_{a_y}, tr_{b_y}) - \max(bl_{a_y}, bl_{b_y})$.
```suggestion
$x = \min(tr_{a_x}, tr_{b_x}) - \max(bl_{a_x}, bl_{b_x})$. 
$y = \min(tr_{a_y}, tr_{b_y}) - \max(bl_{a_y}, bl_{b_y})$.
```

2021-11-11 03:48 UTC, nathangong commented
lol sorry i got one more thing:
![image](https://user-images.githubusercontent.com/8647920/141233567-019fb868-7b79-4311-93a8-769bbeed1d59.png)
I feel like calling them the "x and y coordinates" of the rectangle formed by the intersection is incorrect, and I'm not sure what that would even mean. Maybe it means the lengths of the horizontal/vertical sides.

@ content manager?

2021-11-11 03:50 UTC, ryanchou-dev commented
> it means the lengths of the horizontal/vertical sides

yeah i think that's what it means, we should rename to make it more clear.

2021-11-11 05:10 UTC, SansPapyrus683 commented
![image](https://user-images.githubusercontent.com/55369003/141240990-73e5b0fa-6d85-4352-850b-0604ee75087d.png)
completely optional, you might want to tell the viewer what these variables mean

2021-11-11 05:11 UTC, ryanchou-dev commented
> ![image](https://user-images.githubusercontent.com/55369003/141240990-73e5b0fa-6d85-4352-850b-0604ee75087d.png) completely optional, you might want to tell the viewer what these variables mean

like extend them to width and length?

2021-11-11 05:12 UTC, SansPapyrus683 commented
i'll leave that to your discretion
also wrap area in \texttt

2021-11-11 05:13 UTC, nathangong commented
I think more important is explaining that tr and bl correspond to top right and bottom left corners

2021-11-11 05:18 UTC, nathangong commented
> lol sorry i got one more thing: ![image](https://user-images.githubusercontent.com/8647920/141233567-019fb868-7b79-4311-93a8-769bbeed1d59.png) I feel like calling them the "x and y coordinates" of the rectangle formed by the intersection is incorrect, and I'm not sure what that would even mean. Maybe it means the lengths of the horizontal/vertical sides.
> 
> @ content manager?

btw @SansPapyrus683 what do you think of this

2021-11-11 05:20 UTC, ryanchou-dev commented
> > lol sorry i got one more thing: ![image](https://user-images.githubusercontent.com/8647920/141233567-019fb868-7b79-4311-93a8-769bbeed1d59.png) I feel like calling them the "x and y coordinates" of the rectangle formed by the intersection is incorrect, and I'm not sure what that would even mean. Maybe it means the lengths of the horizontal/vertical sides.
> > @ content manager?
> 
> btw @SansPapyrus683 what do you think of this

this is definitely wrong, should i just rename?

2021-11-11 06:12 UTC, nathangong commented
yeah sure

2021-11-11 15:05 UTC, dutinmeow approved these changes
Small thing it would really help if you put $tr$, $bl$, etc. in `\texttt{}` with there being so many subscripts and such

2021-11-11 16:51 UTC, SansPapyrus683 commented
hey ryan
while your pr is still open
do you mind if i also sansify some of the code in there? i'm dm you the editted version of the file

2021-11-11 16:52 UTC, ryanchou-dev commented
yeah sure

On Thu, Nov 11, 2021 at 8:51 AM SansPapyrus683 ***@***.***>
wrote:

> hey ryan
> while your pr is still open
> do you mind if i also sansify some of the code in there? i'm dm you the
> editted version of the file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cpinitiative/usaco-guide/pull/2331#issuecomment-966458889>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATOREP56NZM2JB6YABUOWI3ULPYBZANCNFSM5HZNPGRQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-11 17:22 UTC, SansPapyrus683 approved these changes

2021-11-11 18:45 UTC, nathangong commented
![image](https://user-images.githubusercontent.com/8647920/141351964-da618c75-df4a-4d08-a8df-219ae1158cc5.png)
I feel like some of this stuff is pretty repetitive. The corner stuff is explained twice (maybe just move that before the sections under the common formulas section as a brief note). Also, "so we can just retrieve these lengths with our coordinates" is kind of vague -- it would be easier to explain that if the representation of rectangles is mentioned at the beginning.

2021-11-11 20:57 UTC, Aadit-Ambadkar approved these changes

2021-11-11 23:40 UTC, nathangong requested changes
small rewording

2021-11-11 23:40 UTC, nathangong commented on content/2_Bronze/Rect_Geo.mdx
>  ### Checking if rectangles intersect
```suggestion
### Checking if two rectangles intersect
```

2021-11-11 23:40 UTC, nathangong commented on content/2_Bronze/Rect_Geo.mdx
>  There are only two cases where the rectangles do not intersect:
```suggestion
Given two rectangles $a$ and $b$, there are only two cases where they do not intersect: 
```

2021-11-11 23:40 UTC, nathangong commented on content/2_Bronze/Rect_Geo.mdx
> +Rectangles can be represented by $2$ points each, the top right and the bottom left. We'll call these points $tr_a$ and $tr_b$, and $bl_a$ and $bl_b$, for rectangles $a$ and $b$. In examples with jus
```suggestion
A rectangle can be represented with $2$ points: its top right corner and bottom left corner. We'll label these points $tr$ (top right) and $br$ (bottom right).
```

2021-11-12 02:14 UTC, ryanchou-dev commented
**rewording

2021-11-13 03:05 UTC, nathangong commented
We should also probably specify that these formulas only work when both sides are parallel to the x/y axes

2021-11-13 15:32 UTC, SansPapyrus683 commented
ye still good

2021-11-14 05:09 UTC, nathangong approved these changes
sorry for making u change so much lol

2021-11-14 06:57 UTC, ryanchou-dev commented
> sorry for making u change so much lol

dw abt it, thanks for reviewing! :)

2021-11-14 20:43 UTC, merged

2021-11-14 20:43 UTC, SansPapyrus683 commented
this is totally not mod abuse