internal sol for teamwork
cpinitiative/usaco-guide pull request #2346
Opened 2021-11-19 21:38 UTC by TruaShamu

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [ ] I have tested my code
- [ ] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [ ] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

does this count as a "clear improvement over existing material"?

2021-11-19 21:38 UTC, TruaShamu commented
Proof that the code works
![image](https://user-images.githubusercontent.com/48630514/142694821-0737916c-614e-486a-b820-893c6c9838db.png)

2021-11-19 23:51 UTC, SansPapyrus683 requested changes

2021-11-19 23:51 UTC, SansPapyrus683 commented on solutions/usaco-863.mdx
> +public class teamwork {
```suggestion
public class Teamwork {
```

2021-11-19 23:51 UTC, SansPapyrus683 commented on solutions/usaco-863.mdx
> +        Kattio kattio = new Kattio("teamwork");
tabs pwease uwu

2021-11-19 23:51 UTC, SansPapyrus683 commented on solutions/usaco-863.mdx
> +            /* The max skill of the cows in the new team. */
what just use `//` for this comment

2021-11-19 23:51 UTC, SansPapyrus683 commented on solutions/usaco-863.mdx
> +                int curSize = right - left + 1;
(optional) would love it if you renamed this to `currSize`

2021-11-19 23:51 UTC, SansPapyrus683 commented on solutions/usaco-863.mdx
> +                            dp[left - 1] + maxSkill * curSize);
format this like
```java
int x = Math.min(
    // put random stuff here
    // put other random stuff here
);
```

2021-11-19 23:55 UTC, TruaShamu commented on solutions/usaco-863.mdx
> +        Kattio kattio = new Kattio("teamwork");
aye aye, captain sans!

2021-11-20 00:00 UTC, TruaShamu commented
okay, done!

2021-11-20 00:21 UTC, SansPapyrus683 approved these changes
let's hecking gooo

2021-11-20 02:50 UTC, nathangong approved these changes

2021-11-21 03:07 UTC, bqi343 commented
> does this count as a "clear improvement over existing material"?

Sure, since the analysis doesn't provide a Java solution.

2021-11-21 03:07 UTC, merged