Add java solution for coin combinations II
cpinitiative/usaco-guide pull request #2354
Opened 2021-11-23 03:51 UTC by nathangong

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [ ] I have tested my code
- [ ] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [ ] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-11-23 05:39 UTC, SansPapyrus683 requested changes

2021-11-23 05:39 UTC, SansPapyrus683 commented on solutions/cses-1636.mdx
> +    public static void main(String[] args) {
tabs pwease uwu

2021-11-23 05:39 UTC, SansPapyrus683 commented on solutions/cses-1636.mdx
> +    	int[] dp = new int[x + 1];
short comment explaining what this holds

2021-11-23 05:39 UTC, SansPapyrus683 commented on solutions/cses-1636.mdx
> +    public static void main(String[] args) {
wait nvm you just fixed it

2021-11-23 06:12 UTC, SansPapyrus683 approved these changes

2021-11-23 16:09 UTC, SansPapyrus683 commented on solutions/cses-1636.mdx
> +	static final int MOD = 1000000007;
(optional)
```suggestion
	static final int MOD = (int) 1e9 + 7;
```

2021-11-26 03:27 UTC, dongliu0426 approved these changes

2021-11-26 03:27 UTC, merged