Update cses-1636.mdx
cpinitiative/usaco-guide pull request #2364
Opened 2021-11-25 19:17 UTC by lordboba

Added Java support for the problem. Note: The MOD Calculation is made slightly faster for addition

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [ ] I have tested my code
- [ ] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [ ] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-11-25 23:14 UTC, SansPapyrus683 commented on solutions/cses-1636.mdx
> +//lordboba was here
put your name in the author's field instead

2021-11-25 23:16 UTC, SansPapyrus683 requested changes
nice first pr

2021-11-25 23:16 UTC, SansPapyrus683 commented on solutions/cses-1636.mdx
> +				if(dp[i]>MOD) {dp[i]-=MOD;} //slightly faster mod method for addition
```suggestion
				if (dp[i] > MOD) {
					dp[i]-=MOD;  // slightly faster mod method for addition
				}

2021-11-25 23:16 UTC, SansPapyrus683 commented on solutions/cses-1636.mdx
> +		dp[0] = 1;
put this above the for loop where it's actually used

2021-11-25 23:16 UTC, SansPapyrus683 commented on solutions/cses-1636.mdx
> +	}
use bufferedreader, kattio, or scanner

2021-11-25 23:16 UTC, SansPapyrus683 commented on solutions/cses-1636.mdx
> +		int MOD = (int)1e9 + 7;
make this a constant

2021-12-06 22:04 UTC, nwatx commented on solutions/cses-1636.mdx
> +	}
^

2021-12-06 22:05 UTC, nwatx commented
@SansPapyrus683 if you don't mind, can you format this one, otherwise I'll make a pr later

2021-12-06 22:05 UTC, nwatx commented
uh oh merge conflict :c

2021-12-20 03:17 UTC, nwatx requested changes

2021-12-20 03:17 UTC, nwatx commented on solutions/cses-1636.mdx
> +		int dp[] = new int[K+1];
```suggestion
		int dp[] = new int[K + 1];
```
consistent operator spacing (do for rest as well)

2021-12-24 22:33 UTC, ryanchou-dev requested changes
please resolve the comments above! other than that, it looks good.

yayy! first contribution :)

2022-01-08 01:46 UTC, closed without merging