Reopen Problem Suggestions
cpinitiative/usaco-guide pull request #2367
Opened 2021-11-29 05:28 UTC by nwatx

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [ ] I have tested my code
- [ ] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [ ] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-11-29 05:50 UTC, maggie-j-liu requested changes
it still gives a "must be signed in" popup, can you remove that?

2021-11-29 05:50 UTC, maggie-j-liu commented on src/components/markdown/ProblemsList/ProblemsList.tsx
> +                    {!props.hideSuggestProblemButton && (
can we only reenable on review modules?

2021-11-29 05:52 UTC, nwatx commented on src/components/markdown/ProblemsList/ProblemsList.tsx
> +                    {!props.hideSuggestProblemButton && (
sure

2021-11-29 06:32 UTC, maggie-j-liu commented on src/components/markdown/ProblemsList/SuggestProblemRow.tsx
> +          to={`https://docs.google.com/forms/d/e/1FAIpQLScSnHRAV1ybiwHMBH-byqhAijRlpNKLnxzpMLYUK8mUXyMyEg/viewform?usp=pp_url&entry.1983837292=${path}`}
use `a` instead of `Link` since it's an external link (also make it open in a new tab)

2021-11-29 18:04 UTC, nwatx commented
> sooo how do you suggest problems now?

by clicking the suggestion problems tab!

2021-11-29 18:04 UTC, nwatx commented
it's on review modules only

2021-11-29 23:48 UTC, SansPapyrus683 commented
wait what are review modules lol

2021-11-30 01:40 UTC, nwatx commented
conclusion

2021-11-30 02:03 UTC, SansPapyrus683 commented
i... still can't find them lol
can you send a screenshot or smth

2021-11-30 02:31 UTC, SansPapyrus683 commented
aaaahh ic ic

2021-11-30 04:00 UTC, maggie-j-liu approved these changes

2021-11-30 04:01 UTC, merged

2021-11-30 04:01 UTC, jessechoe10 approved these changes