Why did the cow cross the road sol
cpinitiative/usaco-guide pull request #2412
Opened 2021-12-16 23:38 UTC by HarryWangATX

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-12-17 01:40 UTC, SansPapyrus683 requested changes

2021-12-17 01:40 UTC, SansPapyrus683 commented on solutions/usaco-717.mdx
> +public class visitfj {
```suggestion
public class VisitFJ {
```

2021-12-17 01:40 UTC, SansPapyrus683 commented on solutions/usaco-717.mdx
> +
add braces and remove all whitespace

2021-12-17 01:40 UTC, SansPapyrus683 commented on solutions/usaco-717.mdx
> +			}
spaces.
(also other places as well)

2021-12-17 01:40 UTC, SansPapyrus683 commented on solutions/usaco-717.mdx
> +	static int[][] dist;
globals not needed

2021-12-17 02:20 UTC, nwatx commented on solutions/usaco-717.mdx
> +	static int[][] dist;
^

2021-12-17 02:21 UTC, nwatx commented on solutions/usaco-717.mdx
> +			if(N-1-pos[0] + N-1-pos[1] < 3 && N-1-pos[0] + N-1-pos[1] > 0) {
also, is it possible to make this more readable

2021-12-17 05:37 UTC, SansPapyrus683 commented
comments pwese uwu

2021-12-17 23:46 UTC, nwatx approved these changes

2021-12-17 23:47 UTC, nwatx requested changes

2021-12-17 23:47 UTC, nwatx commented on solutions/usaco-717.mdx
> +		pq.add(new Edge(new int[]{0,0}, 0));
```suggestion
		pq.add(new Edge(new int[]{0, 0}, 0));
```

2021-12-17 23:47 UTC, nwatx commented on solutions/usaco-717.mdx
> +				dist[N-1][N-1] = Math.min(dist[N-1][N-1], cur.w + T * d);
operator spacing

2021-12-20 09:03 UTC, dongliu0426 approved these changes

2021-12-20 20:53 UTC, nwatx approved these changes

2021-12-20 20:53 UTC, merged