Update cses-1196.mdx
cpinitiative/usaco-guide pull request #2420
Opened 2021-12-19 12:54 UTC by aashishpiitk

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-12-19 19:41 UTC, SansPapyrus683 commented
> I have followed the code style guidelines mentioned

well, have you?

2021-12-20 03:16 UTC, nwatx requested changes
Read: https://usaco.guide/general/adding-solution/#code-conventions

2021-12-20 13:40 UTC, aashishpiitk commented
> Read: https://usaco.guide/general/adding-solution/#code-conventions

Is it ok now?

2021-12-20 14:16 UTC, TruaShamu requested changes
Some changes, I hope you won't mind addressing them.
It's likely that the deployment will succeed after this is done, if not, I'll review again.

For some references, feel free to look at this [link](https://usaco.guide/general/adding-solution/#code-conventions) and this [link](https://usaco.guide/general/adding-solution#steps) as well.

2021-12-20 14:16 UTC, TruaShamu commented on solutions/cses-1196.mdx
> +```cpp
```suggestion
<LanguageSection>
<CPPSection>

```cpp
```

Format with opening LanguageSection and CPPSection please

2021-12-20 14:16 UTC, TruaShamu commented on solutions/cses-1196.mdx
> +```
Add closing tags
```
</CPPSection>
</LanguageSection>
```
After line 72 please. (The triple backtick)

2021-12-20 14:16 UTC, TruaShamu commented on solutions/cses-1196.mdx
> +author: Aashish Patel
```suggestion
author: Aashish Patel, Benjamin Qi
```

2021-12-20 14:16 UTC, TruaShamu commented on solutions/cses-1196.mdx
> +Solution 1:
Move ```Solution 1:``` to after the section with the problem information (id, source, title, author)

2021-12-20 14:16 UTC, TruaShamu commented on solutions/cses-1196.mdx
>  ---
Remove this part, please
```
---
id: cses-1196
source: CSES
title: Flight Routes
author: Benjamin Qi
---
```

2021-12-20 18:19 UTC, nwatx requested changes

2021-12-20 18:19 UTC, nwatx commented on solutions/cses-1196.mdx
> +typedef vector<VP> VVP;
usaco.guide coding conventions state that we need to use the following template:

```cpp
//BeginCodeSnip{C++ Short Template}
#include <bits/stdc++.h> // see /general/running-code-locally
using namespace std;

using ll = long long;

using vi = vector<int>;
#define pb push_back
#define all(x) begin(x), end(x)
#define sz(x) (int) (x).size()

using pi = pair<int,int>;
#define f first
#define s second
#define mp make_pair

void setIO(string name = "") {
	cin.tie(0)->sync_with_stdio(0); // see /general/fast-io
	if (sz(name)) {
		freopen((name + ".in").c_str(), "r", stdin); // see /general/input-output
		freopen((name + ".out").c_str(), "w", stdout);
	}
}
//EndCodeSnip

int main() {
  setIO();

}
```

@SansPapyrus683 do you want to detemplify this

2021-12-20 18:20 UTC, nwatx requested changes

2021-12-20 18:20 UTC, nwatx commented on solutions/cses-1196.mdx
> +}
just make this main

2021-12-20 18:20 UTC, nwatx commented on solutions/cses-1196.mdx
> +void solve(){
```suggestion
void solve() {
```

2021-12-20 18:20 UTC, nwatx commented on solutions/cses-1196.mdx
> +{
bracing style not consistent

2022-01-03 18:51 UTC, closed without merging