Add C++ Solution + Short Editorial to Time is Mooney (Gold)
cpinitiative/usaco-guide pull request #2428
Opened 2021-12-21 05:13 UTC by ryanchou-dev

finally a new pr! 

a lot of sols in intro to dp don't have cpp solutions, so ill be adding some throughout this week :)

---
_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [ ] I have tested my code
- [ ] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [ ] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-12-21 05:50 UTC, SansPapyrus683 requested changes

2021-12-21 05:50 UTC, SansPapyrus683 commented on solutions/usaco-993.mdx
> +const int MAX_DAYS = 1000;
i see you learned, nice

2021-12-21 05:50 UTC, SansPapyrus683 commented on solutions/usaco-993.mdx
> +	// dp[i][j] = the maximum money that Bessie can make on day i
where does j come into play then?

2021-12-21 05:50 UTC, SansPapyrus683 commented on solutions/usaco-993.mdx
> +		adj[u].push_back(v);
```suggestion
		adj[--u].push_back(--v);
```

2021-12-21 05:50 UTC, ryanchou-dev commented on solutions/usaco-993.mdx
> +	// dp[i][j] = the maximum money that Bessie can make on day i
j's the city, ill add that in

2021-12-21 05:55 UTC, SansPapyrus683 commented on solutions/usaco-993.mdx
> +	// dp[i][j] = the maximum money that Bessie can make on day i in city j
sorry lol
```suggestion
	// dp[i][j] = the max money that Bessie can make on day i if she ends in city j
```

2021-12-21 14:35 UTC, SansPapyrus683 approved these changes
bing chilling

2021-12-21 14:35 UTC, SansPapyrus683 commented on solutions/usaco-993.mdx
> +We only need to keep track of the number of days that Bessie has been traveling and the amount of mooney that she has made. For every day up to $T_{\text{max}}$, we'll try to travel to each city, and
maybe explain how T_max was calculated?

2021-12-22 02:22 UTC, nwatx approved these changes
looks excellent

2021-12-22 12:49 UTC, TruaShamu approved these changes
looks good to me :)

2021-12-22 20:16 UTC, merged

2021-12-22 20:16 UTC, SansPapyrus683 commented
2 mods & another content author