python support for intro dp
cpinitiative/usaco-guide pull request #2438
Opened 2021-12-25 16:53 UTC by SansPapyrus683

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2021-12-26 00:55 UTC, ar492 requested changes
looks good mostly

2021-12-26 00:55 UTC, ar492 commented on content/4_Gold/Intro_DP.mdx
> +		dp[i] = INT32_MAX;  // initially set our values to INF
```suggestion
		dp[i] = MAX_N;  // initially set our values to INF
```

2021-12-26 00:55 UTC, ar492 commented on content/4_Gold/Intro_DP.mdx
```suggestion
```

2021-12-26 00:56 UTC, ar492 requested changes

2021-12-26 00:56 UTC, ar492 commented on content/4_Gold/Intro_DP.mdx
```suggestion
```

2021-12-26 01:56 UTC, SansPapyrus683 commented on content/4_Gold/Intro_DP.mdx
> +		dp[i] = INT32_MAX;  // initially set our values to INF
what

2021-12-26 12:28 UTC, ar492 approved these changes

2021-12-27 02:03 UTC, dongliu0426 approved these changes

2021-12-27 02:03 UTC, merged