hashing python
cpinitiative/usaco-guide pull request #2447
Opened 2021-12-28 16:22 UTC by SansPapyrus683

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

thinking of rewriting the solutions but that would take way too long given my iq

2021-12-28 20:39 UTC, ryanchou-dev approved these changes
looks good

2021-12-28 21:52 UTC, TruaShamu approved these changes
looks good to me

2021-12-28 23:25 UTC, Aadit-Ambadkar requested changes

2021-12-28 23:25 UTC, Aadit-Ambadkar commented on content/4_Gold/String_Hashing.mdx
> +	pow = [1]
```suggestion
	_pow = [1]
```
According to PEP 8 (https://pep8.org/#descriptive-naming-styles) use an underscore for weak private.

2021-12-28 23:25 UTC, Aadit-Ambadkar commented on content/4_Gold/String_Hashing.mdx
> +			self.pow.append((self.pow[-1] * self.P) % self.M)
```suggestion
		while len(self._pow) < len(s):
			self._pow.append((self._pow[-1] * self.P) % self.M)
```

2021-12-28 23:25 UTC, Aadit-Ambadkar commented on content/4_Gold/String_Hashing.mdx
> +		self.p_hash = [0 for _ in range(len(s) + 1)]
```suggestion
		self._p_hash = [0 for _ in range(len(s) + 1)]
```
Again pep8

2021-12-28 23:25 UTC, Aadit-Ambadkar commented on content/4_Gold/String_Hashing.mdx
> +			) % self.M
```suggestion
		for i in range(len(s)):
			self._p_hash[i + 1] = (
				((self._p_hash[i] * self.P) % self.M + ord(s[i]))
			) % self.M
```

2021-12-28 23:25 UTC, Aadit-Ambadkar commented on content/4_Gold/String_Hashing.mdx
> +		return raw_val % self.M
```suggestion
	def get_hash(self, start: int, end: int) -> int:
		raw_val = (
			self._p_hash[end + 1] - (self._p_hash[start] * self._pow[end - start + 1])
		)
		return raw_val % self.M
```

2021-12-28 23:57 UTC, SansPapyrus683 commented on content/4_Gold/String_Hashing.mdx
> +			self.pow.append((self.pow[-1] * self.P) % self.M)
no need, i can refactor on my own

2021-12-29 01:28 UTC, Aadit-Ambadkar approved these changes
Looks good.

2021-12-29 03:42 UTC, merged

2021-12-29 03:42 UTC, SansPapyrus683 commented
3 content authors alr