lis again
cpinitiative/usaco-guide pull request #2451
Opened 2021-12-30 01:14 UTC by SansPapyrus683

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2022-01-04 07:15 UTC, ryanchou-dev approved these changes
lgtm

2022-01-04 07:20 UTC, nwatx requested changes

2022-01-04 07:20 UTC, nwatx commented on content/4_Gold/LIS.mdx
> -	int n = a.size(), lis = 0;
why remove n?

2022-01-04 07:20 UTC, nwatx commented on content/4_Gold/LIS.mdx
> -	int n = a.length, lis = 0;
why remove n?

2022-01-05 08:23 UTC, dongliu0426 approved these changes

2022-01-08 16:34 UTC, TruaShamu approved these changes

2022-01-10 16:46 UTC, SansPapyrus683 commented on content/4_Gold/LIS.mdx
> -	int n = a.length, lis = 0;
it's just redundant

2022-01-12 01:06 UTC, merged