Add cpp solution to usaco-736.mdx
cpinitiative/usaco-guide pull request #2461
Opened 2021-12-31 21:01 UTC by anirudhc1229

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2022-01-07 01:43 UTC, bqi343 requested changes
mostly good, but

> I have followed the code style guidelines mentioned here

nope

2022-01-07 01:43 UTC, bqi343 commented on solutions/usaco-736.mdx
> +    map<char, int> spottyCt;
why not have these maps inside the loop?

2022-01-07 01:43 UTC, bqi343 commented on solutions/usaco-736.mdx
> +
there's really no need for all these blank lines

https://google.github.io/styleguide/cppguide.html#Vertical_Whitespace

2022-01-07 03:01 UTC, bqi343 requested changes
https://github.com/cpinitiative/usaco-guide/pull/2479#discussion_r779998042 also applies here

2022-01-07 03:01 UTC, bqi343 commented on solutions/usaco-736.mdx
> +	spottyCt['A'] = spottyCt['C'] = spottyCt['G'] = spottyCt['T'] = 0;
these lines are unnecessary

2022-01-07 03:02 UTC, bqi343 requested changes

2022-01-07 03:02 UTC, bqi343 commented on solutions/usaco-736.mdx
>  ## Solution 2 - Hashset
```suggestion
## Solution 2 - Set
```

`std::map` isn't a hashset.

2022-01-11 14:43 UTC, bqi343 commented on solutions/usaco-736.mdx
> +	spottyCt['A'] = spottyCt['C'] = spottyCt['G'] = spottyCt['T'] = 0;
why was this marked as resolved?

2022-01-11 14:43 UTC, bqi343 commented on solutions/usaco-736.mdx
> +
not sure why this empty newline wasn't removed

2022-01-11 14:43 UTC, bqi343 commented on solutions/usaco-736.mdx
> +	// count occurrences of each letter in each string at index M
same, this isn't resolved

2022-01-12 01:07 UTC, SansPapyrus683 commented
if you want i can just format the pr for you

2022-01-26 04:04 UTC, closed without merging