Update usaco-964.mdx
cpinitiative/usaco-guide pull request #2479
Opened 2022-01-05 18:24 UTC by anirudhc1229

Added first c++ solution and first n^2 solution

_If any of the below doesn't apply to this Pull Request, mark the checkbox as
done._

- [x] I have tested my code
- [x] I have followed the code style guidelines mentioned
      [here](https://usaco.guide/general/adding-solution/#code-conventions)
- [x] I have properly formatted the files according to the steps mentioned
      [here](https://usaco.guide/general/adding-solution#steps)

2022-01-07 01:47 UTC, bqi343 requested changes
Same as #2461.

Also, this is not O(N^2).

2022-01-07 02:22 UTC, SansPapyrus683 commented
lol I’d review but I’m on mobile rn

Sent from my iPhone

> On Jan 6, 2022, at 2:40 PM, Benjamin Qi ***@***.***> wrote:
> 
> ﻿
> @bqi343 requested your review on: #2479 Update usaco-964.mdx.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because your review was requested.

2022-01-07 02:59 UTC, bqi343 requested changes

2022-01-07 02:59 UTC, bqi343 commented on solutions/usaco-964.mdx
> +
- No empty lines at the start and end of main
 - Tabs for indentation (as mentioned in the conventions)

2022-01-07 02:59 UTC, bqi343 commented on solutions/usaco-964.mdx
> +**Time Complexity:** $\mathcal{O}((N-K)^2)$
should be N^3

2022-01-12 01:09 UTC, SansPapyrus683 requested changes

2022-01-12 01:09 UTC, SansPapyrus683 commented on solutions/usaco-964.mdx
> +    int N;
tabs

2022-01-26 04:04 UTC, closed without merging