add python solution
cpinitiative/usaco-guide pull request #2495
Opened 2022-01-10 11:44 UTC by jeevesh2002

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which inclues the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-01-10 16:54 UTC, SansPapyrus683 requested changes

2022-01-10 16:54 UTC, SansPapyrus683 commented on solutions/usaco-1059.mdx
> +nums.sort()
just use `sorted`

2022-01-10 17:22 UTC, jeevesh2002 commented on solutions/usaco-1059.mdx
> +nums.sort()
Done.

2022-01-10 18:43 UTC, SansPapyrus683 approved these changes

2022-01-11 01:07 UTC, dongliu0426 approved these changes

2022-01-11 01:08 UTC, dongliu0426 commented
thanks!

2022-01-11 01:08 UTC, merged