Format the codes of Quiz question in secton
cpinitiative/usaco-guide pull request #2501
Opened 2022-01-12 14:27 UTC by KunalSin9h

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which inclues the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-01-12 16:25 UTC, SansPapyrus683 approved these changes
sure?
best for another to review before i merge tho

2022-01-13 00:29 UTC, ryanchou-dev approved these changes
should be ok

2022-01-14 00:56 UTC, bqi343 requested changes

2022-01-14 00:56 UTC, bqi343 commented on content/2_Bronze/Complete_Rec.mdx
>  	    void generateSubsets(int i, vector<int> &subset) {
^ there are still spaces before and after the `generateSubsets` function

2022-01-14 15:39 UTC, bqi343 requested changes
not sure why review was re-requested despite no changes having been made

2022-01-14 16:28 UTC, bqi343 approved these changes

2022-01-15 09:43 UTC, dongliu0426 approved these changes

2022-01-15 09:46 UTC, merged