Update CSES Flight Discount.mdx
cpinitiative/usaco-guide pull request #251
Opened 2020-09-13 17:47 UTC by KWang31

Added formatted explanation

2020-09-15 13:40 UTC, dolphingarlic commented
Could you flesh out the editorial a bit please? It's very bare-bones right now (also please use LaTeX for all variables like N)

2020-09-15 20:55 UTC, KWang31 commented
This is a meet in the middle problem. Take the obvious graph interpretation.

Say I use the discount on edge between A and B, and I use the edge.

There are two cases: I have to go from $1\rightarrow A\rightarrow B\rightarrow N$, or $1\rightarrow B\rightarrow A\rightarrow N$. It turns out that we need the distance between 1 and A, and N and B.

This means we use dijkstra to compute the distance from 1, N to every vertex, then compute $\text{min}_{A\rightarrow B} dist1[A]+c(A,B)+distN[B]$ where $c(A,B)$ is the cost to travel from city A to city B.

2020-09-18 16:03 UTC, thecodingwizard requested changes
looks good, just some minor wording changes that might make the solution more clear?

2020-09-18 16:03 UTC, thecodingwizard commented on solutions/CSES Flight Discount.mdx
> +This means we use dijkstra to compute the distance from 1, N to every vertex, then compute $\text{min}_{A\rightarrow B} dist1[A]+c(A,B)+distN[B]$,
```suggestion
We can use Dijkstra's to compute the distance from $1$ and $N$ to every vertex. Then our answer is $\text{min}_{A\rightarrow B} dist1[A]+c(A,B)+distN[B]$,
```

2020-09-18 16:03 UTC, thecodingwizard commented on solutions/CSES Flight Discount.mdx
> +where $c(A,B)$ is the cost to travel from city A to city B.
```suggestion
where $c(A,B)$ is the cost to travel from city A to city B after applying the coupon to that flight.
```

2020-09-19 01:55 UTC, KWang31 commented on solutions/CSES Flight Discount.mdx
> +Say I use the discount on edge between A and B, and I use the edge.
Yes that is clearer.

2020-09-19 01:57 UTC, KWang31 commented on solutions/CSES Flight Discount.mdx
> +This is a meet in the middle problem. Take the obvious graph interpretation.
Good point and I don't know... Here is supporting evidence from geeksforgeeks.com: "Like divide and conquer it splits the problem into two, solves them individually and then merge them"

2020-09-19 01:57 UTC, KWang31 commented on solutions/CSES Flight Discount.mdx
> +This means we use dijkstra to compute the distance from 1, N to every vertex, then compute $\text{min}_{A\rightarrow B} dist1[A]+c(A,B)+distN[B]$,
Yes

2020-09-19 01:57 UTC, KWang31 commented on solutions/CSES Flight Discount.mdx
> +where $c(A,B)$ is the cost to travel from city A to city B.
Oh yes that was a typo oops

2020-09-19 01:58 UTC, KWang31 commented on solutions/CSES Flight Discount.mdx
> +There are two cases: I have to go from $1\rightarrow A\rightarrow B\rightarrow N$, or $1\rightarrow B\rightarrow A\rightarrow N$. It turns out that we need the distance between 1 and A, and N and B.
yes

2020-09-19 02:11 UTC, thecodingwizard commented
@KWang31 if the changes I made look good to you, I'll merge this PR. Thanks!

2020-09-19 02:11 UTC, thecodingwizard approved these changes

2020-09-19 03:44 UTC, KWang31 commented on solutions/CSES Flight Discount.mdx
> +This is a meet in the middle problem. Take the obvious graph interpretation.
Maybe delete "take the obvious graph interpretation..." it's too formal and unnecessary.

2020-09-19 03:45 UTC, thecodingwizard commented on solutions/CSES Flight Discount.mdx
> +This is a meet in the middle problem. Take the obvious graph interpretation.
I think both sentences are deleted...

2020-09-19 03:45 UTC, merged

2020-09-19 03:46 UTC, KWang31 commented
The changes looks good to me. I will pay more attention to my wording when writing future editorials.

2020-09-19 03:47 UTC, thecodingwizard commented
Awesome, thanks for your contributions!