add dsu solution
cpinitiative/usaco-guide pull request #2520
Opened 2022-01-20 17:01 UTC by derpman23

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-01-21 01:31 UTC, SansPapyrus683 requested changes

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +## Solution 2 - DSU/UF
```suggestion
## Solution 2 - DSU
```

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +We can also find the components of each graph by storing the edges in a Disjoint Set Union/Union Find Structure, and query the elements in O(n) time. Afterward, we can find the answer with a two poin
```suggestion
We can also find the components of each graph by storing the edges in a Disjoint Set Union, and query the elements in O(n) time. Afterward, we can find the answer with a two pointer search.
```

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +	int v[100000];
1. wrap struct in codesnip
2. please use a vector & a proper constructor

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +ll d1[100000], d2[100000], ans;
put these array sizes in constants, or even better make them vectors instead

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +		ans = 5000000000;
just use INT32_MAX

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +			if (r) r--;
braces here and everywhere there isn't any

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +		if (dsu.get(0) == dsu.get(n - 1)) { cout << "0\n"; continue; }
expand these braces

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +	while (t--) {
(optional) use a for loop

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +int t, n, m, l, r;
no need for these globals

2022-01-21 01:31 UTC, SansPapyrus683 commented on solutions/usaco-1159.mdx
> +DSU dsu;
no need for this global either

2022-01-21 02:32 UTC, nathangong commented
https://github.com/cpinitiative/usaco-guide/pull/2480#pullrequestreview-845924681 i think ryan made this PR but he ended up removing the solutions, so what should happen here?

2022-02-03 15:58 UTC, andrewwangva commented on solutions/usaco-1159.mdx
> +We can also find the components of each graph by storing the edges in a Disjoint Set Union/Union Find Structure, and query the elements in O(n) time. Afterward, we can find the answer with a two poin
Maybe expand on it to talk about cost function/outside of how DSU was used.

2022-02-19 07:22 UTC, closed without merging