Update ceoi-10-AHugeTower.mdx because official solution's explanation doesn't go in-depth
cpinitiative/usaco-guide pull request #2524
Opened 2022-01-22 20:02 UTC by Evang144

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-01-22 21:33 UTC, SansPapyrus683 requested changes

2022-01-22 21:33 UTC, SansPapyrus683 commented on solutions/ceoi-10-AHugeTower.mdx
> +
```suggestion

First, let's define some variables.
```

2022-01-22 21:33 UTC, SansPapyrus683 commented on solutions/ceoi-10-AHugeTower.mdx
> +Let $a_1, a_2, ..., a_n$ be the block sizes, sorted from least to greatest (in other words, $a_1 \leq a_2 \leq a_3 \leq ... \leq a_n$.).
```suggestion
Let $a_1, a_2, ..., a_n$ be the block sizes, sorted from least to greatest.
```

2022-01-23 01:17 UTC, SansPapyrus683 approved these changes
yee

2022-02-06 02:12 UTC, ryanchou-dev approved these changes
first time github contributor!!!!!! 🥳

2022-02-06 03:59 UTC, TruaShamu approved these changes
looks good to me :)

2022-02-06 05:46 UTC, merged