jury marks sans
cpinitiative/usaco-guide pull request #2529
Opened 2022-01-24 21:12 UTC by SansPapyrus683

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

can't really find the kattio snipper, it'd be cool if someone tested the new java code for me

2022-01-24 21:30 UTC, SansPapyrus683 commented
damit prettifier

2022-01-24 22:09 UTC, TruaShamu commented on solutions/cf-831C.mdx
>  				flag &= points.contains(p);
Isn't it supposed to be

```suggestion
				pointsContainsScore &= points.contains(p);
```

2022-01-24 22:11 UTC, TruaShamu commented
Also, add your name to the authors please?

2022-01-24 22:13 UTC, TruaShamu commented
Kattio snippet works, btw here is the Kattio section in the guide if you need: [[LINK]](https://usaco.guide/general/input-output/#method-3---io-template)

2022-01-24 22:14 UTC, TruaShamu requested changes
-

2022-01-24 23:48 UTC, SansPapyrus683 commented
> Also, add your name to the authors please?

don't think it's significant enough to wrarrant that

2022-01-25 00:18 UTC, TruaShamu approved these changes
Alright, it looks good to me!
(And yes, I actually do look at the code in the prs 😡  )

2022-01-25 00:35 UTC, ryanchou-dev approved these changes

2022-01-26 05:39 UTC, nwatx requested changes
why are other files being changed

2022-01-26 05:39 UTC, nwatx commented
wait nevermind

2022-01-26 05:39 UTC, nwatx approved these changes

2022-01-26 14:41 UTC, merged