Update More_Prefix_Sums.mdx
cpinitiative/usaco-guide pull request #2553
Opened 2022-02-06 07:37 UTC by Aryansh-S

Added difference arrays

2022-02-11 03:37 UTC, SansPapyrus683 requested changes

2022-02-11 03:37 UTC, SansPapyrus683 commented on content/3_Silver/More_Prefix_Sums.mdx
> +You are given an array $A$ of size $n.$ There are $q$ queries of the form $(i,j,v)$ indicating that you must increment each element in the range $A[i] \dots A[j]$ by $v,$ where $0 \leq i \leq j < n.$
think it's better to use N and Q (uppercase) for consistency

2022-02-11 03:37 UTC, SansPapyrus683 commented on content/3_Silver/More_Prefix_Sums.mdx
> +Constraints: $1 \leq n,q \leq 10^5$
put this in parenthesis maybe?
"we have an array of size n (1 <= n <= 1e5)"

2022-02-11 03:37 UTC, SansPapyrus683 commented on content/3_Silver/More_Prefix_Sums.mdx
> +* Prefix sum to tabulate all the queries at the end in $\mathcal{O}(n)$
1. maybe have some solution code? (i can add it on the cf gym maybe if need be)
2. but anyways, what's this for?

2022-02-12 01:36 UTC, SansPapyrus683 commented
are we assuming people have done all the problems in the previous modules? i still think it's fine tbh

2022-02-12 02:22 UTC, bqi343 commented
> are we assuming people have done all the problems in the previous modules?

Yes, it's starred.

2022-02-18 21:58 UTC, HarryWangATX commented
Yes, I don't think this will be necessary either.

2022-02-18 22:23 UTC, closed without merging