Added Cereal 2 to DFS Module
cpinitiative/usaco-guide pull request #2556
Opened 2022-02-06 23:55 UTC by jessechoe10

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-02-06 23:56 UTC, jessechoe10 commented
For the editorial, I think that the official solution is fine.

2022-02-07 00:49 UTC, bqi343 requested changes

2022-02-07 00:49 UTC, bqi343 commented on content/3_Silver/DFS.problems.json
> +    {
why is lane switching duplicated?

2022-02-07 02:00 UTC, jessechoe10 commented on content/3_Silver/DFS.problems.json
> +    {
copy pasted wrong oops

2022-02-07 02:18 UTC, bqi343 approved these changes

2022-02-07 03:57 UTC, merged