python implementation
cpinitiative/usaco-guide pull request #2558
Opened 2022-02-07 07:43 UTC by knhngchn

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-02-07 21:54 UTC, SansPapyrus683 requested changes
**also did you make sure it AC's? send screenie if it did**

2022-02-07 21:54 UTC, SansPapyrus683 commented on content/4_Gold/MST.mdx
> +input = lambda: sys.stdin.readline().rstrip("\r\n")
please don't do this

2022-02-07 21:54 UTC, SansPapyrus683 commented on content/4_Gold/MST.mdx
> +	print(ans)
```suggestion
print('IMPOSSIBLE' if ans == -1 else ans)
```

2022-02-07 21:54 UTC, SansPapyrus683 commented on content/4_Gold/MST.mdx
> +	a -= 1; b -= 1
statements on one line

2022-02-08 04:34 UTC, knhngchn commented on content/4_Gold/MST.mdx
> +	print(ans)
Updated.

2022-02-08 04:34 UTC, knhngchn commented on content/4_Gold/MST.mdx
> +	a -= 1; b -= 1
Updated.

2022-02-08 04:38 UTC, knhngchn commented
@SansPapyrus683
Thanks for reviewing.
I just updated some of the code, and here's the screenshot:
https://imgur.com/BHQNJG1

2022-02-08 04:39 UTC, knhngchn commented on content/4_Gold/MST.mdx
> +input = lambda: sys.stdin.readline().rstrip("\r\n")
Removed.

2022-02-08 14:57 UTC, SansPapyrus683 approved these changes
don't like the global variables, but other than that it's fine

2022-02-08 15:25 UTC, SansPapyrus683 commented
no i mean like pass the argument (graph, # of nodes, etc.) in the function as arguments

2022-02-09 04:42 UTC, knhngchn commented
@SansPapyrus683
Ok I just fixed it.

2022-02-09 06:27 UTC, SansPapyrus683 commented on content/4_Gold/MST.mdx
> +	main()
you can take this out of main

2022-02-09 07:02 UTC, knhngchn commented on content/4_Gold/MST.mdx
> +	main()
Updated.

2022-02-09 17:02 UTC, dongliu0426 approved these changes

2022-02-09 17:02 UTC, merged