Added c++ solution for Mooyoo Mooyoo (USACO 860)
cpinitiative/usaco-guide pull request #2569
Opened 2022-02-12 18:54 UTC by pranavgithub1

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-02-12 21:25 UTC, SansPapyrus683 commented
> I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following:

![are-you-sure-john-cena](https://user-images.githubusercontent.com/55369003/153728951-9c0d05b5-14f1-4ceb-a57e-37282e8d2f92.gif)

2022-02-13 00:15 UTC, SansPapyrus683 commented
<img width="310" alt="image" src="https://user-images.githubusercontent.com/55369003/153732980-39492d75-efc2-4e3e-a784-107198fbaff9.png">

2022-02-13 00:34 UTC, pranavgithub1 commented
I am stupid apparently and forgot to select anything when I used the 'covert indentation to tabs' command in the editor lol.

2022-02-13 02:20 UTC, pranavgithub1 commented
I retested the code on USACO.

2022-02-13 03:26 UTC, SansPapyrus683 commented on solutions/usaco-860.mdx
> +*/
```cpp
/*
 * format multiline
 * comments something like this
 */
```

2022-02-13 03:26 UTC, SansPapyrus683 commented on solutions/usaco-860.mdx
> +	+ floodfill(i, j - 1, color);
```suggestion
	cnt += (
		floodfill(i + 1, j, color)
		+ floodfill(i - 1, j, color)
		+ floodfill(i, j + 1, color)
		+ floodfill(i, j - 1, color)
	);
```

2022-02-13 16:09 UTC, SansPapyrus683 requested changes

2022-02-13 16:09 UTC, SansPapyrus683 commented on solutions/usaco-860.mdx
> +const int maxCols = 10;
rename to `MAX_ROWS` and `MAX_COLS`

2022-02-13 16:09 UTC, SansPapyrus683 commented on solutions/usaco-860.mdx
> +		i < 0 || j < 0 || i >= n || j >= 10 ||
what does 10 mean?

2022-02-13 16:09 UTC, SansPapyrus683 commented on solutions/usaco-860.mdx
> +		for (int j = 0; j < 10; j++) {
what's this 10?
other places too

2022-02-13 16:54 UTC, pranavgithub1 commented
The 10s are MAX_COLS

2022-02-13 22:14 UTC, SansPapyrus683 approved these changes
optional stuff

2022-02-13 22:14 UTC, SansPapyrus683 commented on solutions/usaco-860.mdx
> +vector<vector<bool>> visited(MAX_ROWS, vector<bool>(MAX_COLS, false));
wow can't believe you actually took my suggestion
but uh
```suggestion
vector<vector<bool>> visited(MAX_ROWS, vector<bool>(MAX_COLS));
```
the default value is false jsyk

2022-02-13 22:14 UTC, SansPapyrus683 commented on solutions/usaco-860.mdx
> +	while (boardChanged) {
(optional) most of the c++ here uses snake_case, so maybe use that in your own code as well?

2022-02-13 22:37 UTC, maggie-j-liu approved these changes

2022-02-13 22:39 UTC, SansPapyrus683 commented
if the build works i'll merge

2022-02-14 06:59 UTC, nathangong commented on solutions/usaco-860.mdx
> +	//CodeSnip{Kattio}
```suggestion
	// CodeSnip{Kattio}
```

2022-02-14 18:54 UTC, SansPapyrus683 commented on solutions/usaco-860.mdx
> +char board[MAX_ROWS][MAX_COLS];
oh uh if you changed `visited` to a vector could you do the same for `board` as well?

2022-02-14 21:07 UTC, SansPapyrus683 commented
uh sorry wait i'll merge after this build has finished

2022-02-16 04:02 UTC, pranavgithub1 commented
Is there anything else I need to do?

2022-02-16 04:12 UTC, merged

2022-02-16 04:12 UTC, SansPapyrus683 commented
no, we chillin :heart: