Shortcut sol
cpinitiative/usaco-guide pull request #2590
Opened 2022-02-20 19:02 UTC by HarryWangATX

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-02-20 19:06 UTC, SansPapyrus683 requested changes

2022-02-20 19:06 UTC, SansPapyrus683 commented on solutions/usaco-899.mdx
> +	}
```suggestion
	}

```

2022-02-20 19:06 UTC, SansPapyrus683 commented on solutions/usaco-899.mdx
> +	private static class Edge implements Comparable<Edge> {
codesnip this

2022-02-20 19:06 UTC, SansPapyrus683 commented on solutions/usaco-899.mdx
> +
```suggestion
```

2022-02-20 19:06 UTC, SansPapyrus683 commented on solutions/usaco-899.mdx
> +		for (int i = 0; i < N; i++) {
extreme lack of comments

2022-02-20 19:06 UTC, SansPapyrus683 commented on solutions/usaco-899.mdx
> +	static long[] farms, dist;
N, M, T, and `dist` don't need to be global

2022-02-21 02:36 UTC, SansPapyrus683 requested changes

2022-02-21 02:36 UTC, SansPapyrus683 commented on solutions/usaco-899.mdx
> +		// I/O Work
```suggestion
```
comments need not state the obvious

2022-02-21 02:36 UTC, SansPapyrus683 commented on solutions/usaco-899.mdx
> +	public static long dfs(int t) {
what does this dfs do?

2022-02-21 02:56 UTC, SansPapyrus683 approved these changes

2022-02-21 18:13 UTC, nwatx approved these changes

2022-02-21 18:13 UTC, merged