Remove misleading hint
cpinitiative/usaco-guide pull request #2591
Opened 2022-02-22 18:53 UTC by timothygao8710

Problems may have more than one correct output as of January 2022, as confirmed by benq on discord.

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-02-22 19:10 UTC, bqi343 requested changes

2022-02-22 19:10 UTC, bqi343 commented on content/4_Gold/PURS.mdx
> +A hint regarding Sleepy Cow Sort: There is only one correct output (however, as of January 2022, USACO problems may have more than one correct output).
```suggestion
A hint regarding Sleepy Cow Sort: There is only one correct output.
```

2022-02-23 00:50 UTC, bqi343 approved these changes

2022-02-23 02:00 UTC, nwatx approved these changes

2022-02-23 02:00 UTC, merged