Add C++ Solution + Editorial to The Great Revegetation (Silver)
cpinitiative/usaco-guide pull request #2621
Opened 2022-03-10 05:30 UTC by ryanchou-dev

yayy

---
_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-03-10 14:36 UTC, SansPapyrus683 commented on solutions/usaco-920.mdx
> +Now, let's look at one of these, which could look something like this:
```suggestion
Let's look at one of these connected components, which could look something like this:
```

2022-03-10 14:37 UTC, SansPapyrus683 commented on solutions/usaco-920.mdx
> +So, for each $K$ connected components, there are $2$ possible ways to arrange them, or $2^k$ ways to arrange the entire graph. Since in binary, $2^k$ is $1$ followed by $k$ zeros, we can simply print
how about
"for each connected component in our graph..."
"thus, if there's k connected components, there's 2^k ways to arrange"

2022-03-10 14:37 UTC, SansPapyrus683 commented on solutions/usaco-920.mdx
> +		return 0;
no need for return 0

2022-03-10 17:54 UTC, nathangong reviewed
same thoughts as sans

2022-03-11 01:25 UTC, ryanchou-dev commented
thanks for reviewing!

2022-03-11 01:26 UTC, ryanchou-dev commented on solutions/usaco-920.mdx
> +However, for all $K$ connected component, the grass types can be "inverted":
oops, yeah now that i read this, it sounds really weird

2022-03-11 01:31 UTC, SansPapyrus683 requested changes

2022-03-11 01:31 UTC, SansPapyrus683 commented on solutions/usaco-920.mdx
> +However, for all $K$ connected component, the grass types can be flipped and still be a valid solution:
> for all $K$ connected component

component**s**

2022-03-11 01:31 UTC, SansPapyrus683 commented on solutions/usaco-920.mdx
> +		// 2^cc in binary is 1, followed by cc zeros.
update this comment

2022-03-11 01:31 UTC, SansPapyrus683 commented on solutions/usaco-920.mdx
> +			while ((int)(todo.size())) {
`!todo.empty()` instead

2022-03-11 01:47 UTC, SansPapyrus683 approved these changes

2022-03-11 20:00 UTC, TruaShamu approved these changes

2022-03-11 20:04 UTC, TruaShamu commented
Also, this is optional but you can use these diagrams if you want:

![connected_component](https://user-images.githubusercontent.com/48630514/157950817-d2bb23db-f9eb-4ff9-bd43-917bece636b1.png)
![inverted_connected_component](https://user-images.githubusercontent.com/48630514/157950820-ed1ae0a5-4a8f-4cfd-bce8-48484d211e56.png)

2022-03-12 04:05 UTC, ryanchou-dev commented
> Also, this is optional but you can use these diagrams if you want:
> 
> ![connected_component](https://user-images.githubusercontent.com/48630514/157950817-d2bb23db-f9eb-4ff9-bd43-917bece636b1.png) ![inverted_connected_component](https://user-images.githubusercontent.com/48630514/157950820-ed1ae0a5-4a8f-4cfd-bce8-48484d211e56.png)

omg this looks so much better.

thanks!

2022-03-12 04:08 UTC, SansPapyrus683 requested changes

2022-03-12 04:08 UTC, SansPapyrus683 commented on solutions/usaco-920.mdx
> +
```suggestion
```
alr thoroughly explained in editorial

2022-03-12 04:08 UTC, SansPapyrus683 commented on solutions/usaco-920.mdx
> +					bool type = (u.second ? nxt.second : !nxt.second);
```suggestion
					bool type = u.second ? nxt.second : !nxt.second;
```

2022-03-12 04:08 UTC, SansPapyrus683 commented on solutions/usaco-920.mdx
> +		if (color[i] == -1) {
comments for this entire part

2022-03-12 04:16 UTC, SansPapyrus683 approved these changes

2022-03-12 04:16 UTC, SansPapyrus683 commented
when build passes i'll merge

2022-03-12 04:21 UTC, merged