Codeforces White Sheet Bronze
cpinitiative/usaco-guide pull request #2622
Opened 2022-03-10 08:19 UTC by back2sqr1

Added python, java, and cpp implementations as well as my explanation of the solution

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-03-10 15:38 UTC, SansPapyrus683 commented
make sure to edit metadata as well

2022-03-11 22:57 UTC, sathu-beep requested changes

2022-03-11 22:57 UTC, sathu-beep commented on solutions/cf-1216C.mdx
> +    int x1,y1,x2,y2;
```suggestion
    int x1, y1, x2, y2;
```
space variables so its easy to read

2022-03-11 22:57 UTC, sathu-beep commented on solutions/cf-1216C.mdx
> +  }
something about the brackets is off putting they aren't aligned with the code so fix it

2022-03-11 22:57 UTC, sathu-beep commented on solutions/cf-1216C.mdx
> +
```suggestion
```

2022-03-11 22:57 UTC, sathu-beep commented on solutions/cf-1216C.mdx
> +  }
wierd indentation

2022-03-11 22:57 UTC, sathu-beep commented on solutions/cf-1216C.mdx
> +    Rect c = new Rect(io.nextInt(), io.nextInt(), io.nextInt(), io.nextInt());
```suggestion
    Kattio io = new Kattio();
    Rect a = new Rect(io.nextInt(), io.nextInt(), io.nextInt(), io.nextInt());
    Rect b = new Rect(io.nextInt(), io.nextInt(), io.nextInt(), io.nextInt());
    Rect c = new Rect(io.nextInt(), io.nextInt(), io.nextInt(), io.nextInt());
```
fix rect a indentation

2022-03-11 22:57 UTC, sathu-beep commented on solutions/cf-1216C.mdx
> +  	if(a.x2-a.x1==0 || a.y2-a.y1==0) //area!=0
```suggestion
  	if(a.x2-a.x1==0 || a.y2-a.y1==0) //area!=0
```
```suggestion
  	if(a.x2 - a.x1 == 0 || a.y2 - a.y1 == 0) //area!=0
```
spacing

2022-03-11 22:57 UTC, sathu-beep commented on solutions/cf-1216C.mdx
> +  	System.out.println("YES");
```suggestion
  	System.out.println("NO");
  	else
  	System.out.println("YES");
```
add brackets and fix indentation of the else

2022-03-12 17:36 UTC, closed without merging

2022-03-12 17:43 UTC, SansPapyrus683 commented
yo what