Add BIT sol for Sleepysort
cpinitiative/usaco-guide pull request #2656
Opened 2022-04-03 06:14 UTC by HarryWangATX

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-04-03 22:23 UTC, SansPapyrus683 requested changes

2022-04-03 22:23 UTC, SansPapyrus683 commented on solutions/usaco-898.mdx
> +		PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter("sleepy.out")));
just use `new PrintWriter("sleepy.out")` and put @ bottom

2022-04-03 22:23 UTC, SansPapyrus683 commented on solutions/usaco-898.mdx
> +		ans = new int[n+1];
spaces

2022-04-03 22:23 UTC, SansPapyrus683 commented on solutions/usaco-898.mdx
> +	static int[] a, c, ans;
better names

2022-04-04 21:34 UTC, ryanchou-dev approved these changes
preferably add comments, but code looks good (after kevin's suggestions)

2022-04-04 21:34 UTC, ryanchou-dev commented on solutions/usaco-898.mdx
> +
```suggestion
```

2022-04-11 02:44 UTC, nwatx approved these changes

2022-04-11 21:38 UTC, HarryWangATX commented
@SansPapyrus683 bump :)

2022-04-11 22:14 UTC, merged

2022-04-11 22:14 UTC, SansPapyrus683 commented
i'd ask you to put it in a class but oh well