Add C++ solution to cses 2428
cpinitiative/usaco-guide pull request #2685
Opened 2022-04-12 20:34 UTC by DarkMenacer

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [done] I have tested my code.
- [done] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [done] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-04-12 22:46 UTC, ryanchou-dev requested changes
https://usaco.guide/general/adding-solution?lang=cpp

2022-04-17 04:11 UTC, brad182 requested changes

2022-04-17 04:11 UTC, brad182 commented on solutions/cses-2428.mdx
> +Pranav Chatur
This part probably isn't necessary

2022-04-17 04:11 UTC, brad182 commented on solutions/cses-2428.mdx
> +            answer += (j-i)*(j-i-1)/2;
if you're going to use a space here, make it consistent between things like +-*/

2022-04-17 04:11 UTC, brad182 commented on solutions/cses-2428.mdx
> +	When j reaches end of the integers, there is no need to subtract 'total subarrays from i+1 to j',
use 
/*
 *
*/
formatting

2022-05-01 16:23 UTC, closed without merging