Add Solution 2
cpinitiative/usaco-guide pull request #2692
Opened 2022-04-16 20:57 UTC by timothygao8710

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [done] I have tested my code.
- [done] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [done] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-04-16 23:34 UTC, SansPapyrus683 requested changes

2022-04-16 23:34 UTC, SansPapyrus683 commented on content/5_Plat/Sweep_Line.mdx
> +As visit point $P$, we utilize the set to consider all points with y-coordiate in $[P_y-\delta, P_y+\delta]$. The set contains $[P_x-\delta, P_x]$ because of how it is maintained as a running window.
> As visit point $P$

?

2022-04-17 04:08 UTC, brad182 approved these changes
good after addressing small fixes

2022-04-17 04:08 UTC, brad182 commented on content/5_Plat/Sweep_Line.mdx
> +For each point, we recalculate $\delta = min(\delta, \delta_p)$, and update our set according. Each point is inserted and removed from the set at most once, so the algorithm yields $\mathcal{O}(n\log
```suggestion
For each point, we recalculate $\delta = min(\delta, \delta_p)$, and update our set accordingly. Each point is inserted and removed from the set at most once, so the algorithm yields $\mathcal{O}(n\log n)$.
```

2022-04-17 05:40 UTC, timothygao8710 commented on content/5_Plat/Sweep_Line.mdx
> +As visit point $P$, we utilize the set to consider all points with y-coordiate in $[P_y-\delta, P_y+\delta]$. The set contains $[P_x-\delta, P_x]$ because of how it is maintained as a running window.
fixed

2022-04-17 17:37 UTC, SansPapyrus683 approved these changes

2022-04-20 02:59 UTC, ryanchou-dev approved these changes

2022-04-20 03:17 UTC, merged