Java Solution for gcd on blackboard
cpinitiative/usaco-guide pull request #2696
Opened 2022-04-17 06:47 UTC by back2sqr1

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-04-17 07:18 UTC, ryanchou-dev approved these changes
looks good (after the suggested changes)

2022-04-17 07:18 UTC, ryanchou-dev commented on solutions/ac-GCDOnBlackboard.mdx
> +    public static void main(String[] args) throws IOException{
space it out like `name {`

2022-04-17 07:18 UTC, ryanchou-dev commented on solutions/ac-GCDOnBlackboard.mdx
> +        {
`for (blabla) {`
format like ^^

2022-04-17 07:18 UTC, ryanchou-dev commented on solutions/ac-GCDOnBlackboard.mdx
> +    // Euclidean Algorithm O(log2(min(a, b)))
unnecessary imo

2022-04-17 07:18 UTC, ryanchou-dev commented on solutions/ac-GCDOnBlackboard.mdx
> +
```suggestion
```

2022-04-17 07:18 UTC, ryanchou-dev commented on solutions/ac-GCDOnBlackboard.mdx
> +    public static void main(String[] args) throws IOException{
+ a more descriptive class name

2022-04-17 07:19 UTC, back2sqr1 commented on solutions/ac-GCDOnBlackboard.mdx
> +    public static void main(String[] args) throws IOException{
ok np

2022-04-17 07:19 UTC, back2sqr1 commented on solutions/ac-GCDOnBlackboard.mdx
> +    // Euclidean Algorithm O(log2(min(a, b)))
got it

2022-04-17 07:20 UTC, back2sqr1 commented on solutions/ac-GCDOnBlackboard.mdx
> +        {
np

2022-04-17 07:20 UTC, ryanchou-dev commented
also could you batch your commits? im getting so many emails 😖

2022-04-17 07:27 UTC, ryanchou-dev commented on solutions/ac-GCDOnBlackboard.mdx
> +
wait oops wrong thingy

2022-04-17 07:28 UTC, ryanchou-dev requested changes
indent with tabs

2022-04-17 07:39 UTC, ryanchou-dev approved these changes

2022-04-17 15:34 UTC, SansPapyrus683 requested changes

2022-04-17 15:34 UTC, SansPapyrus683 commented on solutions/ac-GCDOnBlackboard.mdx
> +public class GCDOnBlackboard {
think AC requires naming your class `Main`

2022-04-17 15:34 UTC, SansPapyrus683 commented on solutions/ac-GCDOnBlackboard.mdx
> +		int a[] = new int[n];
in java you declare arrays like
```suggestion
		int[] a = new int[n];
```

2022-04-17 15:34 UTC, SansPapyrus683 commented on solutions/ac-GCDOnBlackboard.mdx
> +	}
```suggestion
	static int gcd(int a, int b) {
		return b == 0 ? a : gcd(b, a % b);
	}
```

2022-04-17 15:34 UTC, SansPapyrus683 commented on solutions/ac-GCDOnBlackboard.mdx
> +		int s[] = new int[n + 1];
1. same thing with the array decs
2. instead of a comment you _could_ just name the variables `prefGCD` and `suffGCD`

2022-04-17 20:13 UTC, ryanchou-dev commented on solutions/ac-GCDOnBlackboard.mdx
> +public class GCDOnBlackboard {
oops ok

2022-04-19 15:10 UTC, SansPapyrus683 approved these changes

2022-04-19 15:10 UTC, merged