add cpp solution + editorial for circlecross (gold)
cpinitiative/usaco-guide pull request #2707
Opened 2022-04-25 06:20 UTC by ryanchou-dev

o.o

---
_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-04-25 12:52 UTC, jessechoe10 requested changes

2022-04-25 12:52 UTC, jessechoe10 commented on solutions/usaco-719.mdx
> +
just do ```using namespace std;```

2022-04-25 14:50 UTC, SansPapyrus683 commented on solutions/usaco-719.mdx
> +
no

2022-04-25 14:53 UTC, SansPapyrus683 requested changes

2022-04-25 14:53 UTC, SansPapyrus683 commented on solutions/usaco-719.mdx
> +	int ans = 0;
more meaningful name

2022-04-26 00:36 UTC, ryanchou-dev commented on solutions/usaco-719.mdx
> +template<class T> struct Seg {
this is the implementation mentioned in the module, so i think ill leave it like that

2022-04-26 00:36 UTC, ryanchou-dev commented on solutions/usaco-719.mdx
> +	cross.init(2 * n);
^^

2022-04-26 00:41 UTC, SansPapyrus683 commented on solutions/usaco-719.mdx
> +template<class T> struct Seg {
fair enough

2022-04-26 00:41 UTC, SansPapyrus683 commented on solutions/usaco-719.mdx
> +	int ans = 0;
no like for `ans` lol

2022-04-26 00:41 UTC, ryanchou-dev commented on solutions/usaco-719.mdx
> +	int ans = 0;
oops ok

2022-04-26 00:53 UTC, SansPapyrus683 approved these changes
bing chilling

2022-04-27 14:10 UTC, TruaShamu approved these changes
looks good to me :)

2022-04-28 00:08 UTC, RedBlueBird approved these changes
Perfection!
The only comment I have is `using namespace std;` but apparently sans doesn't like that XD

2022-04-28 00:41 UTC, merged