Added solution to usaco-1040
cpinitiative/usaco-guide pull request #2747
Opened 2022-05-10 01:20 UTC by buffering07

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-05-10 01:34 UTC, ryanchou-dev commented
err, yeah, same suggestions | #2746 

you don't have to close a pr to edit it...

2022-05-10 03:02 UTC, ryanchou-dev approved these changes
🎄

2022-05-10 03:02 UTC, ryanchou-dev commented on solutions/usaco-1040.mdx
> +				{
.

2022-05-10 03:02 UTC, ryanchou-dev commented on solutions/usaco-1040.mdx
> +public class TheMooParticle {
```suggestion

public class TheMooParticle {
```

2022-05-10 03:02 UTC, ryanchou-dev commented on solutions/usaco-1040.mdx
> +		ArrayList<Integer> y = new ArrayList<>(); // y coordinates
inline comments should be separated by two spaces

```
code  // comment
```

2022-05-10 03:02 UTC, ryanchou-dev commented on solutions/usaco-1040.mdx
> +			{
.

2022-05-10 03:02 UTC, ryanchou-dev commented on solutions/usaco-1040.mdx
> +		int numComponents = 1;
space this out a bit, it's too hard to read

2022-05-10 03:15 UTC, ryanchou-dev approved these changes
yep! thanks for helping out -w-

2022-05-10 03:17 UTC, buffering07 commented
thank you!

2022-05-23 03:35 UTC, jessechoe10 approved these changes

2022-05-23 04:10 UTC, SansPapyrus683 requested changes

2022-05-23 04:10 UTC, SansPapyrus683 commented on solutions/usaco-1040.mdx
> +public class TheMooParticle {
what this for

2022-05-23 04:10 UTC, SansPapyrus683 commented on solutions/usaco-1040.mdx
> +		ArrayList<Integer> y = new ArrayList<>();  // y coordinates
comments need not state the obvious

2022-05-23 04:10 UTC, SansPapyrus683 commented on solutions/usaco-1040.mdx
> +		ArrayList<Integer> y = new ArrayList<>();  // y coordinates
```suggestion
		List<Integer> x = new ArrayList<>();
		List<Integer> y = new ArrayList<>();
```

2022-05-23 04:10 UTC, SansPapyrus683 commented on solutions/usaco-1040.mdx
> +		ArrayList<Integer> components = new ArrayList<>();
change the arraylist dec to list

2022-05-23 04:10 UTC, SansPapyrus683 commented on solutions/usaco-1040.mdx
> +		int[] maxRight = new int[100000];  // stores max y-coordinate for right comp
put 1e5 in a magic number like MAX_POS or something

2022-05-23 04:10 UTC, SansPapyrus683 commented on solutions/usaco-1040.mdx
> +
```suggestion
```

2022-05-23 04:10 UTC, SansPapyrus683 commented on solutions/usaco-1040.mdx
> +	//CodeSnip{Kattio}
```suggestion

	//CodeSnip{Kattio}
```

2022-06-06 09:06 UTC, closed without merging