add cpp solution for 809
cpinitiative/usaco-guide pull request #2754
Opened 2022-05-10 17:00 UTC by jjliewie

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-05-13 00:59 UTC, ryanchou-dev reviewed
you account for 72% of the prs... 🎄

2022-05-13 00:59 UTC, ryanchou-dev commented on solutions/usaco-809.mdx
> +int main(){
```suggestion
int main() {
```

2022-05-13 00:59 UTC, ryanchou-dev commented on solutions/usaco-809.mdx
> +int x[111], y[111], z[111];
use a named constant instead

2022-05-13 00:59 UTC, ryanchou-dev commented on solutions/usaco-809.mdx
> +	cin.tie(0)->sync_with_stdio(0);
```suggestion
	cin.tie(0) -> sync_with_stdio(0);
```

2022-05-13 00:59 UTC, ryanchou-dev commented on solutions/usaco-809.mdx
> +		if(x[i] >= 0) {
```suggestion
	int n;
	cin >> n;
	for (int i = 1; i <= n; i++) {
		cin >> x[i];
	}

	y[1] = 1;
	for (int i = 1; i <= n; i++) {
		if (x[i] >= 0) {
```

2022-05-13 02:39 UTC, jjliewie commented on solutions/usaco-809.mdx
> +int x[111], y[111], z[111];
okay i'll change it

2022-05-13 02:39 UTC, jjliewie commented
> you account for 72% of the prs... 🎄

nice

2022-05-18 05:52 UTC, ryanchou-dev requested changes
bump ^^

2022-05-18 05:52 UTC, ryanchou-dev commented on solutions/usaco-809.mdx
> +
```suggestion
```

2022-05-18 22:33 UTC, ryanchou-dev commented on solutions/usaco-809.mdx
> +int x[111], y[111], z[111];
bump

2022-05-21 01:41 UTC, envyaims requested changes
uhhh i don't know if I'm missing something but what does any of these variables mean? Comments would be heavily appreciated. Your code also looks nothing like the code from other languages nor the official editorial so I have no idea what's going on.

2022-05-21 03:53 UTC, ryanchou-dev reviewed
yep ^^

adding on to envy's suggestions, a good rule of thumb is that if you don't have any comments/time complexity or any extra information, it's best to keep it as a user solution

2022-06-19 10:28 UTC, jjliewie commented
> uhhh i don't know if I'm missing something but what does any of these variables mean? Comments would be heavily appreciated. Your code also looks nothing like the code from other languages nor the official editorial so I have no idea what's going on.

okay ill add some comments.. python is slow so i took a different approach.

2022-07-03 20:16 UTC, SansPapyrus683 requested changes

2022-07-03 20:16 UTC, SansPapyrus683 commented on solutions/usaco-809.mdx
> +	cin.tie(0) -> sync_with_stdio(0);
remove if runs fine without

2022-07-03 20:16 UTC, SansPapyrus683 commented on solutions/usaco-809.mdx
> +	cout << first << " " << second;
add endl

2022-07-03 20:16 UTC, SansPapyrus683 commented on solutions/usaco-809.mdx
> +	int first = 0, second = 0;
declarations on separate lines

2022-07-03 20:16 UTC, SansPapyrus683 commented on solutions/usaco-809.mdx
> +		if (y[i] && z[i]) {
explicitly say `y[i] != 0` and stuff like that

2022-07-12 05:46 UTC, ryanchou-dev reviewed
@jjliewie please address changes & conflicts 😭

2022-07-12 10:17 UTC, jjliewie commented on solutions/usaco-809.mdx
> +	cin.tie(0) -> sync_with_stdio(0);
okay ill remove

2022-07-12 10:22 UTC, jjliewie commented
> @jjliewie please address changes & conflicts 😭

addressed & resolved

2022-07-12 11:56 UTC, SansPapyrus683 commented on solutions/usaco-809.mdx
> +int x[111], y[111], z[111];
put in constant please

2022-07-21 15:22 UTC, jjliewie commented on solutions/usaco-809.mdx
> +int x[111], y[111], z[111];
done

2022-07-21 15:44 UTC, SansPapyrus683 requested changes

2022-07-21 15:44 UTC, jjliewie commented on solutions/usaco-809.mdx
> +// 111 is maximum size needed (with leeway for edge cases)
changing comment it is the maximum space needed

2022-10-10 01:58 UTC, ryanchou-dev approved these changes
\>W<

2022-10-10 02:01 UTC, SansPapyrus683 commented on solutions/usaco-809.mdx
> +const int MAX_SIZE = 111;
unresolved

2022-11-17 23:43 UTC, SansPapyrus683 commented
still some problems, mind if i just change it myself?

2022-12-02 02:21 UTC, SansPapyrus683 commented
actually i'm just gonna let this die bc of the conflicts

2022-12-02 02:21 UTC, closed without merging