Solve3sum sol
cpinitiative/usaco-guide pull request #2772
Opened 2022-05-15 16:57 UTC by HarryWangATX

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-05-15 18:06 UTC, HarryWangATX commented
😭😭😭

2022-05-15 21:28 UTC, SansPapyrus683 requested changes
actually pretty good

2022-05-15 21:28 UTC, SansPapyrus683 commented on solutions/usaco-994.mdx
> +		int[] cnt = new int[2 * 1000000 + 1];
put 1e6 in a variable like MAX_VAL or smth

2022-05-15 21:28 UTC, SansPapyrus683 commented on solutions/usaco-994.mdx
> +			for (int j = i+1; j <= N; j++) {
spaces

2022-05-16 00:41 UTC, SansPapyrus683 approved these changes

2022-05-16 04:16 UTC, ryanchou-dev requested changes
add comments as well

2022-05-16 04:16 UTC, ryanchou-dev commented on solutions/usaco-994.mdx
> +[Official Analysis](http://www.usaco.org/current/data/sol_threesum_gold_jan20.html)
```suggestion
[Official Analysis (C++ and Java)](http://www.usaco.org/current/data/sol_threesum_gold_jan20.html)
```

2022-05-18 05:37 UTC, ryanchou-dev approved these changes
⭐

2022-05-18 18:09 UTC, merged