Add Python Code for DFS Solution (620)
cpinitiative/usaco-guide pull request #2785
Opened 2022-05-20 00:26 UTC by IceSerpent

For the self-study video for this problem

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-05-20 00:35 UTC, SansPapyrus683 requested changes

2022-05-20 00:35 UTC, SansPapyrus683 commented on solutions/usaco-620.mdx
> +sol = 1e18
use `float('inf')` for effectively infinite values

2022-05-20 00:35 UTC, SansPapyrus683 commented on solutions/usaco-620.mdx
> +vis = [[[False for a in range(101)] for b in range(101)] for c in range(101)]
put 100 in a variable called `MAX_OPS` or something

2022-05-20 00:35 UTC, SansPapyrus683 commented on solutions/usaco-620.mdx
> +def ff (curX, curY, curK):
type annotations

2022-05-20 00:35 UTC, SansPapyrus683 commented on solutions/usaco-620.mdx
> +    # case 1
what are these "cases" you speak of?

2022-05-20 00:36 UTC, SansPapyrus683 commented on solutions/usaco-620.mdx
> +    # case 1
nvm

2022-05-20 01:57 UTC, ryanchou-dev commented on solutions/usaco-620.mdx
> +def ff(curX:'int', curY:'int', curK:'int'):
```suggestion
def ff(curX: 'int', curY: 'int', curK: 'int'):
```

2022-05-20 01:57 UTC, ryanchou-dev commented on solutions/usaco-620.mdx
> +print(sol, file = open("pails.out", "w"))
```suggestion
        ff(curX + curY, 0, curK + 1)


ff(0, 0, 0)
print(sol, file=open("pails.out", "w"))
```

2022-05-20 02:00 UTC, SansPapyrus683 requested changes

2022-05-20 02:00 UTC, SansPapyrus683 commented on solutions/usaco-620.mdx
> +MAX_OPS = 101
change to 100 and use `MAX_OPS + 1`

2022-05-20 02:00 UTC, SansPapyrus683 commented on solutions/usaco-620.mdx
> +vis = [[[False for a in range(MAX_OPS)] for b in range(MAX_OPS)] for c in range(MAX_OPS)]
over 80 chars

2022-05-20 02:00 UTC, SansPapyrus683 commented on solutions/usaco-620.mdx
> +def ff(curX: int, curY: int, curK: int) -> int:
use snake_case

2022-05-20 20:35 UTC, SansPapyrus683 approved these changes

2022-05-21 03:53 UTC, ryanchou-dev approved these changes
⭐

2022-05-21 04:26 UTC, merged