Create usaco-1230.mdx
cpinitiative/usaco-guide pull request #2791
Opened 2022-05-21 21:07 UTC by EulerPascal404

Adding the march silver #1 problem - it is a good application of functional graphs. I will add it to functional graphs module.

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-05-21 21:15 UTC, EulerPascal404 commented
What is the problem, would anyone mind helping me with this?

2022-05-22 02:02 UTC, envyaims requested changes
bruh you just copied the official solution -_-

http://www.usaco.org/current/data/sol_prob1_silver_open22.html

review this from https://usaco.guide/general/contributing
![image](https://user-images.githubusercontent.com/79723780/169675153-67d5fb04-ddd3-4118-b4a5-17e945634f0f.png)

2022-05-22 02:02 UTC, envyaims commented on solutions/usaco-1230.mdx
> +title: Redistributing Gifts
wrong problem name lol

2022-05-22 02:44 UTC, envyaims commented
> Adding the march silver #1 problem - it is a good application of functional graphs. I will add it to functional graphs module.

isnt it already there?

2022-05-22 04:01 UTC, EulerPascal404 commented
Hey envyaims!

I am a new contributor on the site, so I didn't realize the editorial solutions were not supposed to be added directly to the guide. I have changed the commit with my solutions(and added comments for it to be more helpful). As for the functional graphs module, I meant that the solution was not linked there - but I see that I was wrong, it was just linked directly to the editorial.

Thanks!

2022-05-22 05:21 UTC, SansPapyrus683 requested changes

2022-05-22 05:21 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +
```suggestion
```
not really needed

2022-05-22 05:21 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +#include <iostream>
```suggestion
```
you're using `bits` already

2022-05-22 05:21 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +#define int int64_t
dear god please no `#define`

2022-05-22 05:21 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +    return min_v;
tabs

2022-05-22 05:21 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +{
either put the opening brace on the same line or a new line all the time

2022-05-22 05:21 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +    int n, ans = 0;
move `ans` down where you actually use it

2022-05-22 05:21 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +    return 0;
```suggestion
    cout << ans << endl;
```

2022-05-22 05:21 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +
```suggestion
```
what

2022-05-22 05:21 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +vector<bool> visited; //done
> done

what this mean

2022-05-22 10:21 UTC, envyaims commented on solutions/usaco-1230.mdx
> +#define int int64_t
using ll = long long 😎

2022-05-22 10:28 UTC, envyaims requested changes
overall some more comments would be nice

otherwise it's fine

2022-05-22 10:28 UTC, envyaims commented on solutions/usaco-1230.mdx
> +    int min_v = v[y];
some comments throughout here would be nice

and better variable names...

2022-05-22 10:28 UTC, envyaims commented on solutions/usaco-1230.mdx
> +//Applies Floyd's algorithm
space out these comments like:

```
// text
```

2022-05-22 13:17 UTC, EulerPascal404 commented
@envyaims @SansPapyrus683 I think I have made all the requested changes + added more comments. Please merge if it's fine, or if there are other errors, please let me know.

2022-05-22 13:45 UTC, envyaims commented
Fix comment spacing for all other comments and use tabs.

2022-05-22 13:51 UTC, EulerPascal404 commented
I did not know what you meant when adding the tabbing(since it was there in my local IDE). I have fixed it and made the comments uniform.

2022-05-22 13:56 UTC, envyaims requested changes

2022-05-22 13:56 UTC, envyaims commented on solutions/usaco-1230.mdx
> +        	graph[a[i]].push_back(i); //since cow i wants to visit farm a[i]
```suggestion
        	graph[a[i]].push_back(i); // cow i wants to visit farm a[i]
```

2022-05-22 13:56 UTC, envyaims commented on solutions/usaco-1230.mdx
> +	while(y != z){
```suggestion
	while (y != z) {
```

keep your spacings consistent

2022-05-22 13:56 UTC, envyaims commented on solutions/usaco-1230.mdx
> +	while(y != z){
```suggestion
	while (y != z) {
```

2022-05-22 13:56 UTC, envyaims commented on solutions/usaco-1230.mdx
> +    	for(int i = 0; i < n; i++){
```suggestion
    	for (int i = 0; i < n; i++) {
```

2022-05-22 13:56 UTC, envyaims commented on solutions/usaco-1230.mdx
> +    	for (int i = 0; i < n; i++){
```suggestion
    	for (int i = 0; i < n; i++) {
```

2022-05-22 14:09 UTC, EulerPascal404 commented
Committed all the new suggestions.

2022-05-22 14:15 UTC, envyaims approved these changes
great!

2022-05-22 14:15 UTC, envyaims commented on solutions/usaco-1230.mdx
> +vector<int> a,v; // cow i wants to visit cow a[i] and gets v[i] points
```suggestion
vector<int> a, v; // cow i wants to visit cow a[i] and gets v[i] points
```

2022-05-22 14:25 UTC, EulerPascal404 commented
I committed the change(although it seems rather like splitting hairs).

2022-05-22 14:30 UTC, SansPapyrus683 commented
it's best to space out your operators so it's more readable

2022-05-22 14:31 UTC, EulerPascal404 commented
> it's best to space out your operators so it's more readable

Got it.

2022-05-22 14:32 UTC, SansPapyrus683 commented on solutions/usaco-1230.mdx
> +	for (int c : graph[y]) mark(c);
braces

2022-05-22 14:33 UTC, EulerPascal404 commented
Done.

2022-05-22 14:41 UTC, SansPapyrus683 approved these changes

2022-05-22 14:42 UTC, SansPapyrus683 commented
wait for deployment then i'll merge

2022-05-22 16:00 UTC, EulerPascal404 commented
Alright, thank you!

2022-05-22 16:16 UTC, merged