add python solution to cses-1641.mdx
cpinitiative/usaco-guide pull request #2801
Opened 2022-05-23 16:40 UTC by 876pol

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-05-23 22:50 UTC, SansPapyrus683 requested changes

2022-05-23 22:50 UTC, SansPapyrus683 commented on solutions/cses-1641.mdx
> +# sort in ascending order
these 3 comments state the obvious

2022-05-23 22:50 UTC, SansPapyrus683 commented on solutions/cses-1641.mdx
> +        # if the values sum to the target and aren't from the same index, we have found the answer
over 80 chars
```py
"""
do multiline comments
like this
```

2022-05-23 22:50 UTC, SansPapyrus683 commented on solutions/cses-1641.mdx
> +# print impossible if no answer has been found
```suggestion
```

2022-05-23 23:36 UTC, envyaims approved these changes
seems great!

2022-05-23 23:42 UTC, ryanchou-dev approved these changes
address sans' comments and it should be good

2022-05-24 01:45 UTC, SansPapyrus683 requested changes
one last thing

2022-05-24 01:45 UTC, SansPapyrus683 commented on solutions/cses-1641.mdx
> +
```suggestion
```

2022-05-24 01:45 UTC, SansPapyrus683 approved these changes

2022-05-24 16:38 UTC, merged