add ccc firehose
cpinitiative/usaco-guide pull request #2849
Opened 2022-06-18 03:01 UTC by 876pol

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which includes the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-06-18 03:07 UTC, 876pol commented
I'm not sure what difficulty I should list this problem as. I don't know if it should be easy or normal.

2022-06-18 10:47 UTC, envyaims commented
i think @SansPapyrus683 said that we don't need more binary search problems. idk though

2022-06-18 10:49 UTC, envyaims requested changes

2022-06-18 10:49 UTC, envyaims commented on solutions/ccc-Firehose.mdx
> +			int dist = (end - start + 1000000) % 1000000;
make 1000000 a constant

2022-06-18 10:49 UTC, envyaims commented on solutions/ccc-Firehose.mdx
> +int num_houses, num_hydrants, houses[1000];
dont use static arrays

2022-06-19 12:14 UTC, envyaims commented on solutions/ccc-Firehose.mdx
> +int num_houses, num_hydrants, houses[1000];
nvm its fine

2022-06-20 15:08 UTC, SansPapyrus683 requested changes

2022-06-20 15:08 UTC, SansPapyrus683 commented on solutions/ccc-Firehose.mdx
> +	int l = 0, r = STREET_SIZE, ans = 0;
declarations

2022-06-20 15:08 UTC, SansPapyrus683 commented on solutions/ccc-Firehose.mdx
> +	cout << ans << "\n";
```suggestion

	cout << ans << endl;
```

2022-06-20 22:58 UTC, SansPapyrus683 commented
> i think @SansPapyrus683 said that we don't need more binary search problems. idk though

oooh yeah...
i thought this was already in the module for some reason
i'll merge this once it's done, but please don't do any more

2022-06-20 22:58 UTC, SansPapyrus683 approved these changes

2022-06-20 23:44 UTC, envyaims approved these changes
ok

2022-06-20 23:44 UTC, envyaims commented on solutions/ccc-Firehose.mdx
> +**Time Complexity**: $\mathcal O(h^2\times log(1000000))$
```suggestion
**Time Complexity**: $\mathcal O(h^2\times log(\texttt{max}(H_i)))$
```

2022-06-21 21:37 UTC, Aadit-Ambadkar requested changes

2022-06-21 21:37 UTC, Aadit-Ambadkar commented on solutions/ccc-Firehose.mdx
> +
```suggestion
```
Remove unnecessary spaces.

2022-06-21 21:37 UTC, Aadit-Ambadkar commented on solutions/ccc-Firehose.mdx
> +		// Increment needed as we need another hydrant to reach the last houses.
```suggestion

		// Increment needed as we need another hydrant to reach the last houses.
```
Add necessary spaces

2022-06-24 00:18 UTC, Aadit-Ambadkar approved these changes
Looks good!

2022-07-07 02:42 UTC, 876pol commented
can this maybe be merged?

2022-07-07 03:29 UTC, merged