Update cses-1631.mdx - Java Added
cpinitiative/usaco-guide pull request #2874
Opened 2022-06-23 07:21 UTC by Nithya-02

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- I have tested my code.
- I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-06-23 10:18 UTC, envyaims requested changes

2022-06-23 10:18 UTC, envyaims commented on solutions/cses-1631.mdx
> +class mxsm
```suggestion
public class Main
```

2022-06-23 10:18 UTC, envyaims commented on solutions/cses-1631.mdx
> +		Scanner sc = new Scanner(System.in);
use Kattio or buffered reader. This is required in code conventions

2022-06-23 10:18 UTC, envyaims commented on solutions/cses-1631.mdx
> +        for (long j : arr) {
weird indenting. use tabs like above

2022-06-23 10:18 UTC, envyaims commented on solutions/cses-1631.mdx
> +            if (j > maxNum)
use Math.max

2022-06-23 10:18 UTC, envyaims commented on solutions/cses-1631.mdx
> +        for (int j = 0; j<n ; j++) {
keep your spacings consistent...

2022-06-23 10:18 UTC, envyaims commented on solutions/cses-1631.mdx
> +		//max-element
remove these random comments

2022-06-23 10:18 UTC, envyaims commented on solutions/cses-1631.mdx
> +        	sumNum = sumNum + arr[j];
use +=

2022-06-24 22:09 UTC, Aadit-Ambadkar requested changes

2022-06-24 22:09 UTC, Aadit-Ambadkar commented on solutions/cses-1631.mdx
> +		}
```suggestion
		for(int i = 0; i < n; i++)  {  
			arr[i] = sc.nextLong();  
		}  
```

2022-07-08 23:46 UTC, closed without merging