C++ code to usaco-831.mdx
cpinitiative/usaco-guide pull request #2884
Opened 2022-06-25 09:04 UTC by old-School18

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-06-25 10:32 UTC, envyaims requested changes
make the function names more meaningful than "util" and use tabs. Also put comments for what each of the functions do

2022-06-25 10:32 UTC, envyaims commented on solutions/usaco-831.mdx
> +bool teamWinsUtil2(char ch1, char ch2, char x, char y, char z) {
wots this

2022-06-25 18:45 UTC, Aadit-Ambadkar requested changes
So much formatting needed

2022-06-25 18:45 UTC, Aadit-Ambadkar commented on solutions/usaco-831.mdx
> +      return true;
```suggestion
    if (s[i][0] == ch && s[i][0] == s[i][1] && s[i][0] == s[i][2]) {
      return true;
    }
```

2022-06-25 18:45 UTC, Aadit-Ambadkar commented on solutions/usaco-831.mdx
> +      return true;
```suggestion
    if (s[0][i] == ch && s[0][i] == s[1][i] && s[0][i] == s[2][i]) {
      return true;
    }
```

2022-06-25 18:45 UTC, Aadit-Ambadkar commented on solutions/usaco-831.mdx
> +    return true;
```suggestion
  if (s[0][0] == ch && s[0][0] == s[1][1] && s[0][0] == s[2][2]) {
    return true;
  }
  if (s[0][2] == ch && s[0][2] == s[1][1] && s[0][2] == s[2][0]) {
    return true;
  }
```

2022-06-25 18:45 UTC, Aadit-Ambadkar commented on solutions/usaco-831.mdx
> +  }
```suggestion
  if (x == y && x != z) {
    if (x == ch1 && z == ch2) {
      return true;
    }
    if (x == ch2 && z == ch1) {
      return true;
    }
  } else if (x == z && x != y) {
    if (x == ch1 && y == ch2) {
      return true;
    }
    if (x == ch2 && y == ch1) {
      return true;
    }
  } else if (y == z && x != y) {
    if (y == ch1 && x == ch2) {
      return true;
    }
    if (y == ch2 && x == ch1) {
      return true;
    }
  }
```

2022-06-25 18:45 UTC, Aadit-Ambadkar commented on solutions/usaco-831.mdx
> +}
braces

2022-06-25 18:45 UTC, Aadit-Ambadkar commented on solutions/usaco-831.mdx
> +  	cin >> s[i];
```suggestion
  for (int i = 0; i < 3; i++) {
  	cin >> s[i];
  }
```

2022-06-25 18:45 UTC, Aadit-Ambadkar commented on solutions/usaco-831.mdx
> +}
tabs, not spaces! Fix the formatting!

2022-06-27 02:12 UTC, Aadit-Ambadkar approved these changes

2022-06-27 16:07 UTC, SansPapyrus683 requested changes

2022-06-27 16:07 UTC, SansPapyrus683 commented on solutions/usaco-831.mdx
> +//check if the cow ch won in any row or column or diagonal
```suggestion
// check if the cow ch won in any row or column or diagonal
```
do the same for all the other comments

2022-06-27 16:07 UTC, SansPapyrus683 commented on solutions/usaco-831.mdx
> +bool checkSingleCowWinner(char ch, string board[]) {
i'd like it if you used vectors instead of arrays

2022-06-27 16:07 UTC, SansPapyrus683 commented on solutions/usaco-831.mdx
> +	int singleCowWins = 0;
snake_case for c++ instead of camelCase

2022-06-28 03:12 UTC, SansPapyrus683 approved these changes
we gud

2022-07-06 07:12 UTC, old-School18 commented
> make the function names more meaningful than "util" and use tabs. Also put comments for what each of the functions do

the changes you suggested were completed. Anything else?

2022-07-09 22:36 UTC, Aadit-Ambadkar commented
@SansPapyrus683 merge (2 accepted)

2022-07-09 22:56 UTC, merged