cses-2428 C++ solution added
cpinitiative/usaco-guide pull request #2889
Opened 2022-06-26 15:57 UTC by gsvamsi18

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-06-26 17:24 UTC, SansPapyrus683 requested changes

2022-06-26 17:24 UTC, SansPapyrus683 commented on solutions/cses-2428.mdx
> +		cin >> arr[i];
braces

2022-06-26 17:24 UTC, SansPapyrus683 commented on solutions/cses-2428.mdx
> +	int n, k;
declarations on separate lines

2022-06-26 17:24 UTC, SansPapyrus683 commented on solutions/cses-2428.mdx
> +	int left = 0, right = 0;
same here

2022-06-26 17:24 UTC, SansPapyrus683 commented on solutions/cses-2428.mdx
> +				break;
braces here

2022-06-26 17:24 UTC, SansPapyrus683 commented on solutions/cses-2428.mdx
> +	cout << ans;
```suggestion
	cout << ans << endl;
```

2022-06-26 23:58 UTC, gsvamsi18 commented
can I ask why we need to declare the variables on separate lines, is it for better readability?

2022-06-26 23:59 UTC, SansPapyrus683 commented
> can I ask why we need to declare the variables on separate lines, is it for better readability?

yeah

2022-06-27 00:00 UTC, SansPapyrus683 approved these changes

2022-06-27 02:12 UTC, Aadit-Ambadkar approved these changes

2022-06-27 02:12 UTC, Aadit-Ambadkar commented on solutions/cses-2428.mdx
> +
```suggestion
typedef long long ll

```

2022-06-27 02:12 UTC, Aadit-Ambadkar commented on solutions/cses-2428.mdx
> +	long long ans = 0;
```suggestion
	ll ans = 0;
```

2022-06-27 02:34 UTC, SansPapyrus683 commented on solutions/cses-2428.mdx
> +
(optional)

2022-06-27 05:08 UTC, merged