Added internal solution for usaco-1211 Moo Networks
cpinitiative/usaco-guide pull request #2900
Opened 2022-07-03 02:50 UTC by RedBlueBird

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-07-03 15:31 UTC, SansPapyrus683 requested changes

2022-07-03 15:31 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +The subtask of this problem can be solved using brute force: insert all the edges from $N$ points into an edge list and solve using Kruskal's MST algorithm. Upon closer look at our brute force soluti
add a hyperlink to the usaco guide or something for kruskal's

2022-07-03 15:31 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +Given three points $p_1$, $p_2$, and $p_3$, with coordinates $(x_1, y_1)$, $(x_2, y_2)$, and $(x_3, y_3)$ respectively, where $x_1 < x_2 < x_3$. We observe that if $y_1 = y_2$, the length of $p_1 p_3
> and the two pending points have different connected components

how does this relate to kruskal's?

2022-07-03 15:31 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +    if (top[a] == a) {
tabs

2022-07-03 15:31 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +// Following are two Union-Find data structure functions
use a codesnip or smth

2022-07-03 15:31 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +    return 0;
```suggestion
    cout << ans << endl;
```

2022-07-03 17:37 UTC, SansPapyrus683 commented
jeff i don't think you pushed

2022-07-05 01:15 UTC, RedBlueBird commented on solutions/usaco-1211.mdx
> +Given three points $p_1$, $p_2$, and $p_3$, with coordinates $(x_1, y_1)$, $(x_2, y_2)$, and $(x_3, y_3)$ respectively, where $x_1 < x_2 < x_3$. We observe that if $y_1 = y_2$, the length of $p_1 p_3
Kruskal MST uses the disjoint set union data structure. Points are connected in terms of connected components.

2022-07-05 01:20 UTC, RedBlueBird commented
> jeff i don't think you pushed

oops 😅

2022-07-05 02:20 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +Given three points $p_1$, $p_2$, and $p_3$, with coordinates $(x_1, y_1)$, $(x_2, y_2)$, and $(x_3, y_3)$ respectively, where $x_1 < x_2 < x_3$. We observe that if $y_1 = y_2$, the length of $p_1 p_3
hm
how about
> If we follow Kruskal's algorithm, we consider the edges starting from the shortest one, and only add an edge to the tree if it connects two different compoenents.

2022-07-05 02:21 UTC, SansPapyrus683 requested changes
nice

2022-07-05 02:21 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +//EndCodeSnip
no like not this part
the DSU part

2022-07-05 02:21 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +	// Each array stores the point's {x,y,index} values
```suggestion
	// Each array stores the point's {x, y, index} values
```

2022-07-05 05:31 UTC, RedBlueBird commented on solutions/usaco-1211.mdx
> +//EndCodeSnip
ahh

2022-07-05 05:36 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +Given three points $p_1$, $p_2$, and $p_3$, with coordinates $(x_1, y_1)$, $(x_2, y_2)$, and $(x_3, y_3)$ respectively, where $x_1 < x_2 < x_3$. We observe that if $y_1 = y_2$, the length of $p_1 p_3
bump

2022-07-12 21:14 UTC, TruaShamu approved these changes
looks good to me :)

2022-07-12 21:22 UTC, envyaims approved these changes
yo

2022-07-12 21:27 UTC, ryanchou-dev approved these changes
omg i hated this problem, great exp

2022-07-12 21:27 UTC, ryanchou-dev commented on solutions/usaco-1211.mdx
> +[Official Analysis](http://usaco.org/current/data/sol_prob3_gold_feb22.html)
```suggestion
[Official Analysis (Java)](http://usaco.org/current/data/sol_prob3_gold_feb22.html)
```

2022-07-12 22:35 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +		for (int j = 0; j <= 10; j++) {
what does this `10` mean

2022-07-13 10:51 UTC, SansPapyrus683 commented on solutions/usaco-1211.mdx
> +Given three points $p_1$, $p_2$, and $p_3$, with coordinates $(x_1, y_1)$, $(x_2, y_2)$, and $(x_3, y_3)$ respectively, where $x_1 < x_2 < x_3$. We observe that if $y_1 = y_2$, the length of $p_1 p_3
bump

2022-07-20 20:04 UTC, RedBlueBird commented on solutions/usaco-1211.mdx
> +		for (int j = 0; j <= 10; j++) {
I wrote 10 here because according to the constraints given by the problem, the y coordinate of any input point can only exist between 0 and 10

2022-07-27 10:36 UTC, SansPapyrus683 approved these changes

2022-07-27 10:36 UTC, merged