Added Python code in DFS Section
cpinitiative/usaco-guide pull request #2904
Opened 2022-07-06 08:45 UTC by 1a1242

Python code wasn't available in DFS Section so added a code solving Topological sort using DFS

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-07-06 15:52 UTC, SansPapyrus683 commented
tabs

2022-07-06 17:18 UTC, SansPapyrus683 commented
btw can you send AC screen on CSES? just wanna make sure it actually works

2022-07-06 17:22 UTC, 1a1242 commented
> btw can you send AC screen on CSES? just wanna make sure it actually works

Okay!!!
Course Schedule 
<img width="484" alt="image" src="https://user-images.githubusercontent.com/85673838/177607800-90075677-e8a5-4e2e-a3be-84a1500ab2e2.png">
Round Trip II
<img width="472" alt="image" src="https://user-images.githubusercontent.com/85673838/177608023-1f4d5a7a-bd31-450f-b8ef-295ff685d88c.png">

2022-07-06 17:33 UTC, SansPapyrus683 requested changes

2022-07-06 17:33 UTC, SansPapyrus683 commented on content/4_Gold/TopoSort.mdx
> +			visited[i] = 1
use booleans

2022-07-06 17:33 UTC, SansPapyrus683 commented on content/4_Gold/TopoSort.mdx
> +			if cycle != []:
```suggestion
			if not cycle:
```

2022-07-06 17:33 UTC, SansPapyrus683 commented on content/4_Gold/TopoSort.mdx
> +on_stack = [0] * (N + 1)
you used 0-indexing in your other solution, why not this one as well?

2022-07-06 19:21 UTC, SansPapyrus683 approved these changes

2022-07-06 20:38 UTC, ryanchou-dev approved these changes
yayy

2022-07-06 20:38 UTC, ryanchou-dev commented on content/4_Gold/TopoSort.mdx
> +visited = [False] * )
what

2022-07-07 09:23 UTC, 1a1242 commented
@andrewwangva @dongliu0426 seem inactive.
Is there anyway that I can contact them?
Or this pull request might get merged?

2022-07-07 14:40 UTC, merged