Added python code for Space Jazz in DP_Ranges.mdx
cpinitiative/usaco-guide pull request #2913
Opened 2022-07-08 10:55 UTC by 1a1242

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-07-08 14:51 UTC, 1a1242 commented on content/4_Gold/DP_Ranges.mdx
> +dp = [[0] * (n + 5) for _ in range(n + 5)]
Just in case to not access the memory not allocated.

2022-07-08 14:53 UTC, 1a1242 commented on content/4_Gold/DP_Ranges.mdx
> +dp = [[0] * (n + 5) for _ in range(n + 5)]
Changed it to +2

2022-07-08 15:20 UTC, 1a1242 commented on content/4_Gold/DP_Ranges.mdx
> +dp = [[0] * (n + 5) for _ in range(n + 5)]
It doesn't

2022-07-08 16:43 UTC, 1a1242 commented on content/4_Gold/DP_Ranges.mdx
> +dp = [[0] * (n + 5) for _ in range(n + 5)]
we cant use n as in loops i am accessing n+1 th index i used n + 2

2022-07-08 16:48 UTC, 1a1242 commented on content/4_Gold/DP_Ranges.mdx
> +dp = [[0] * (n + 5) for _ in range(n + 5)]
we cant use n as i am accessing nth element so i changed it to n + 1

2022-07-08 17:34 UTC, SansPapyrus683 requested changes
tabs

2022-07-09 02:28 UTC, ryanchou-dev reviewed
space out lines 🙏

2022-07-11 04:26 UTC, 1a1242 commented
Done

2022-07-11 08:21 UTC, 1a1242 commented
> tabs

done

2022-07-11 08:23 UTC, 1a1242 commented
> space out lines 🙏

i did not understand what you meant.

2022-07-11 11:31 UTC, SansPapyrus683 commented
i think he meant to separate segments of your code with new lines & stuff

2022-07-11 16:16 UTC, 1a1242 commented
> i think he meant to separate segments of your code with new lines & stuff

Oh okay thanks.

2022-07-11 17:10 UTC, SansPapyrus683 commented on content/4_Gold/DP_Ranges.mdx
> +				dp[j][i + j] = min(dp[j][i + j], dp[j + 1][k - 1] + dp[k + 1][i + j])
```suggestion
				dp[j][i + j] = min(
					dp[j][i + j],
					dp[j + 1][k - 1] + dp[k + 1][i + j]
				)
```

2022-07-12 05:44 UTC, ryanchou-dev approved these changes

2022-07-12 11:51 UTC, merged