added python code to cses-1644
cpinitiative/usaco-guide pull request #2914
Opened 2022-07-08 14:57 UTC by SuryaBZ

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-07-08 17:50 UTC, SansPapyrus683 commented on solutions/cses-1644.mdx
> +// we can keep a sliding window of size B, then find the lowest pfx[j] using list.sort()
...do you know how python comments work?

2022-07-09 19:24 UTC, SansPapyrus683 commented on solutions/cses-1650.mdx
> +arr = [0] * (n + 2)
why n+2? does n+1 work?

2022-07-09 22:34 UTC, Aadit-Ambadkar requested changes

2022-07-09 22:34 UTC, Aadit-Ambadkar commented on solutions/cses-1644.mdx
> +	pfx[i] = a + pfx[i-1]
```suggestion
	pfx[i] = a + pfx[i - 1]
```

2022-07-09 22:34 UTC, Aadit-Ambadkar commented on solutions/cses-1644.mdx
> +	ms.append(pfx[i-A])
```suggestion
	ms.append(pfx[i - A])
```

2022-07-13 00:29 UTC, Aadit-Ambadkar approved these changes

2022-07-13 00:29 UTC, Aadit-Ambadkar commented on solutions/cses-1644.mdx
> +	cout << ret << endl;
```suggestion
	cout << ret <<"\n";
```
keep it as \n.

2022-07-27 04:08 UTC, closed without merging