Main
cpinitiative/usaco-guide pull request #2930
Opened 2022-07-14 05:19 UTC by Manikanta1432

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-07-15 05:24 UTC, Manibz commented
Please merge if there are no errors

2022-07-15 05:25 UTC, Manikanta1432 commented
please merge if there are no errors

2022-07-16 03:24 UTC, Aadit-Ambadkar requested changes
lots to fix

2022-07-16 03:24 UTC, Aadit-Ambadkar commented on solutions/cses-1662.mdx
> +
fix your spacing according to the guidelines. There is unnecessary spacing.

2022-07-16 03:24 UTC, Aadit-Ambadkar commented on solutions/cses-1662.mdx
> +	ans += x * (x - 1) //2
```suggestion
	ans += x * (x - 1) // 2
```

2022-07-16 03:24 UTC, Aadit-Ambadkar commented on solutions/cses-1662.mdx
> +
```suggestion
```

2022-07-16 03:24 UTC, Aadit-Ambadkar commented on solutions/cses-1662.mdx
> +       #Calculating the # of pairs.
```suggestion
        #Calculating the # of pairs.
```

2022-07-16 03:24 UTC, Aadit-Ambadkar commented on solutions/cses-1662.mdx
> +
also tabs, not spaces!

2022-07-16 03:24 UTC, Aadit-Ambadkar commented
> please merge if there are no errors

lol be patient there wait for at least 3 days before bumping

2022-07-16 05:45 UTC, closed without merging