Add two stacks method to sliding window section
cpinitiative/usaco-guide pull request #2958
Opened 2022-07-28 18:24 UTC by ChuangSheep

I think cpalgo explained the method quite well. But if u wish to have a short explanation of the method, I could write some. 

---

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-07-28 18:56 UTC, SansPapyrus683 requested changes

2022-07-28 18:56 UTC, SansPapyrus683 commented on content/4_Gold/Sliding_Window.mdx
> +		 */
```suggestion
		/**
		 * For each Pair e, e.a is the value of the element and
		 * e.b is the maximum among all elements in that stack under element e.
		 */
```
doc comments start w/ 2 asterisks (same for c++ and stuff)

2022-07-28 18:56 UTC, SansPapyrus683 commented on content/4_Gold/Sliding_Window.mdx
> +		 */
at this point just put it above in an explanation, comments in guide code shouldn't be this long

2022-07-28 22:03 UTC, SansPapyrus683 requested changes

2022-07-28 22:03 UTC, SansPapyrus683 commented on content/4_Gold/Sliding_Window.mdx
> +We use two stacks $s1$ and $s2$ to simulate our maximum queue. Every time we add an element to it, we push the element itself and the maximum in stack $s1$ after adding this element to $s1$. To pop o
`$s_1$` instead of `$s1$`

2022-07-28 22:03 UTC, SansPapyrus683 commented on content/4_Gold/Sliding_Window.mdx
> +Then, we can solve the problem intuitively by removing the first element and adding a new element to the queue to simulate our sliding window. As each operation of our queue takes $\mathcal{O}(1)$ ti
remove "intuitively"

2022-07-28 22:03 UTC, SansPapyrus683 commented on content/4_Gold/Sliding_Window.mdx
> +	// data structure to store two integers
```suggestion
```

2022-07-29 10:46 UTC, SansPapyrus683 reviewed
@envyaims

2022-07-29 12:07 UTC, envyaims approved these changes
nice, pretty applaudable stuff :D

2022-07-29 12:20 UTC, merged