Added CPP code for usaco-1131
cpinitiative/usaco-guide pull request #2978
Opened 2022-08-04 05:40 UTC by RaheezBZ

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-08-04 12:42 UTC, envyaims requested changes
ill let the others fix the spacings...

2022-08-04 12:42 UTC, envyaims commented on solutions/usaco-1131.mdx
> +	while(cin >> x){
? they give you $n$ for a reason

2022-08-06 20:55 UTC, SansPapyrus683 commented
yeah please space out your ops

2022-08-10 12:24 UTC, envyaims requested changes
do the same for others pls

2022-08-10 12:24 UTC, envyaims commented on solutions/usaco-1131.mdx
> +	while(length >= 0 && citations[length-1] < length) length -= 1;
```suggestion
	while (length >= 0 && citations[length-1] < length) {
		length -= 1;
	}
```

2022-08-10 12:24 UTC, envyaims commented on solutions/usaco-1131.mdx
> +	if(cur_h != n){
```suggestion
	if (cur_h != n) {
```

2022-08-10 12:24 UTC, envyaims commented on solutions/usaco-1131.mdx
> +		for(int i = cur_h; i >= 0; i--){
```suggestion
		for (int i = cur_h; i >= 0; i--) {
```

2022-08-10 12:24 UTC, envyaims commented on solutions/usaco-1131.mdx
> +			if(i<= cur_h-1){
```suggestion
			if (i <= cur_h-1) {
```

2022-08-11 03:34 UTC, Aadit-Ambadkar requested changes

2022-08-11 03:34 UTC, Aadit-Ambadkar commented on solutions/usaco-1131.mdx
> +	while(length >= 0 && citations[length-1] < length) length -= 1;
```suggestion
	while (length >= 0 && citations[length - 1] < length) {
		length -= 1;
	}
```

2022-08-11 03:34 UTC, Aadit-Ambadkar commented on solutions/usaco-1131.mdx
> +	for (int i = 0; i < n; i++){
```suggestion
	for (int i = 0; i < n; i++) {
```

2022-08-11 03:34 UTC, Aadit-Ambadkar commented on solutions/usaco-1131.mdx
> +int main(){
```suggestion
int main() {
```

2022-08-11 03:34 UTC, Aadit-Ambadkar commented on solutions/usaco-1131.mdx
> +using namespace std;
```suggestion
using namespace std;

```

2022-08-11 03:34 UTC, Aadit-Ambadkar commented on solutions/usaco-1131.mdx
> +	while(length >= 0 && citations[length-1] < length) length -= 1;
```suggestion
	while (length >= 0 && citations[length - 1] < length) {
		length -= 1;
	}
```

2022-08-16 06:20 UTC, RaheezBZ commented
please do merge my pull request

2022-08-16 15:04 UTC, SansPapyrus683 commented on solutions/usaco-1131.mdx
> +	while(cin >> x){
unresolved

2022-08-28 16:46 UTC, SansPapyrus683 commented on solutions/usaco-1131.mdx
> +#include<bits/stdc++.h>
```suggestion
#include <bits/stdc++.h>
```

2022-08-29 06:00 UTC, RaheezBZ commented on solutions/usaco-1131.mdx
> +#include<bits/stdc++.h>
Fixed spaces now please merge my pull request

2022-08-29 15:02 UTC, merged