cf 245h yo 🤡
cpinitiative/usaco-guide pull request #2984
Opened 2022-08-07 13:52 UTC by envyaims

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-08-07 14:33 UTC, SansPapyrus683 requested changes

2022-08-07 14:33 UTC, SansPapyrus683 commented on solutions/cf-245H.mdx
> +editorial. This loops over the start and end of the substrings rather than the
link official

2022-08-07 14:33 UTC, SansPapyrus683 commented on solutions/cf-245H.mdx
> +	// pal[i][j] = true if [i,j] is a palindrome
put above the relevant variables

2022-08-07 14:33 UTC, SansPapyrus683 commented on solutions/cf-245H.mdx
> +			*/
```suggestion
			/*
			 * We add a character before start and after the end.
			 * If previously was a palindrome and the new characters
			 * are the same, then it is still a palindrome.
			*/

2022-08-07 14:33 UTC, SansPapyrus683 commented on solutions/cf-245H.mdx
> +	while (q--) {
```suggestion
	int q;
	cin >> q;
	for (int i = 0; i < q; i++) {
```

2022-08-07 16:10 UTC, envyaims commented on solutions/cf-245H.mdx
> +editorial. This loops over the start and end of the substrings rather than the
i forgor 🤡

2022-08-07 16:45 UTC, SansPapyrus683 approved these changes
sure

2022-08-09 02:30 UTC, maggie-j-liu approved these changes

2022-08-09 02:30 UTC, merged