Add CerealCodes Problems
cpinitiative/usaco-guide pull request #3002
Opened 2022-08-17 02:55 UTC by jessechoe10

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-08-17 02:55 UTC, jessechoe10 commented
More to come later. Don't merge yet.

2022-08-17 12:18 UTC, SansPapyrus683 commented
aren't there enough combo problems

2022-08-17 12:43 UTC, envyaims commented
> aren't there enough combo problems

there can never be enough problems 🤡

2022-08-18 21:16 UTC, Aadit-Ambadkar commented
No, there can be enough string problems, bitmask problems, etc. But there can never be enough combo problems.

2022-08-19 12:16 UTC, bqi343 requested changes
for consistency with other problems

2022-08-19 12:16 UTC, bqi343 commented on content/6_Advanced/Comb_Sub.problems.json
> +      "tags": ["Tree DP"],
```suggestion
      "tags": ["Tree", "DP"],
```

2022-08-19 14:25 UTC, Aadit-Ambadkar commented
@jessechoe10 if you are still working on the pr, mark it as a draft.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/58674441/185640119-af041e89-8c5c-47b9-b8d3-c0adf7064294.png">

2022-08-20 17:34 UTC, dutinmeow commented
A bit off topic but I can create an editorial for CC Vista, if that's ok with you

2022-08-20 17:34 UTC, jessechoe10 commented
> @jessechoe10 if you are still working on the pr, mark it as a draft. <img alt="image" width="364" src="https://user-images.githubusercontent.com/58674441/185640119-af041e89-8c5c-47b9-b8d3-c0adf7064294.png">

@Aadit-Ambadkar can you or @envyaims get a list of our good problems we can add to the guide (module name and difficulty). You can ask the problem authors if they think the problem is good btw.

2022-08-20 17:35 UTC, jessechoe10 commented
> A bit off topic but I can create an editorial for CC Vista, if that's ok with you

Yeah, can you DM Eric, Envy, or Patrick.

2022-08-20 17:35 UTC, jessechoe10 commented
> > A bit off topic but I can create an editorial for CC Vista, if that's ok with you
> 
> Yeah, can you DM Eric, Envy, or Patrick?

2022-08-30 03:31 UTC, ryanchou-dev commented
lgtm!

2022-08-30 03:34 UTC, merged