Rewrite explanation, refactor CPP and (gonna) add Java for Distinct Values Queries (CSES1734)
cpinitiative/usaco-guide pull request #3004
Opened 2022-08-17 19:20 UTC by ChuangSheep

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-08-19 02:11 UTC, SansPapyrus683 requested changes

2022-08-19 02:11 UTC, SansPapyrus683 commented on solutions/cses-1734.mdx
> +We answer the queries from right to left, sorted by their left indices. By using a BIT, we can keep track of indices that contain distinct values. For every value $arr[i]$, we set the latest (i.e. th
> $a==i$

or just $a=i$?

2022-08-19 02:11 UTC, SansPapyrus683 commented on solutions/cses-1734.mdx
> +	BIT(int n) : size(n), bit(n, 0) {}
```suggestion
	BIT(int n) : size(n), bit(n) {}
```

2022-08-19 02:11 UTC, SansPapyrus683 commented on solutions/cses-1734.mdx
> +struct BIT {
wrap in code segment maybe

2022-08-19 02:11 UTC, SansPapyrus683 commented on solutions/cses-1734.mdx
> +	BIT bit(n + 1);
if the driver code has to do some weird crap to make sure the class works, then the class is implemented wrong
i'd put the +1 in the constructor (see the bit code i wrote for ref)

2022-08-19 14:36 UTC, SansPapyrus683 approved these changes
ily :heart:

2022-08-22 05:21 UTC, ryanchou-dev approved these changes
yes!

2022-08-22 14:43 UTC, merged