Create cf-1462E2
cpinitiative/usaco-guide pull request #3005
Opened 2022-08-18 00:25 UTC by EulerPascal404

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-08-18 01:24 UTC, dongliu0426 requested changes
also please rename the file to `solutions/cf-1462E2.mdx`

2022-08-18 01:38 UTC, EulerPascal404 commented
> also please rename the file to `solutions/cf-1462E2.mdx`

yikes, completely forgot. Fixed that now.

2022-08-18 03:11 UTC, dongliu0426 approved these changes

2022-08-21 06:28 UTC, ryanchou-dev approved these changes

2022-08-21 06:28 UTC, ryanchou-dev commented on solutions/cf-1462E2.mdx
> +		int num_larger_elems = preFreq[max_index] - preFreq[i];  // the number of elements from [i+1, max_index]
over 80 chars

2022-08-21 06:28 UTC, ryanchou-dev commented on solutions/cf-1462E2.mdx
> +	while(t--){
```suggestion
	
	while(t--) {
```

2022-08-21 18:26 UTC, Aadit-Ambadkar commented on solutions/cf-1462E2.mdx
> +using ll = long long;
```suggestion
typedef long long ll;
```
depending on the ide, this does make a difference. But functionally no dif.

2022-08-21 20:52 UTC, EulerPascal404 commented
I think this can be merged now @dongliu0426

2022-09-07 02:16 UTC, dongliu0426 commented on solutions/cf-1462E2.mdx
> +		preFreq[i] = freq[i] + preFreq[i-1];
```suggestion
		preFreq[i] = freq[i] + preFreq[i - 1];
```

2022-09-07 02:16 UTC, dongliu0426 commented on solutions/cf-1462E2.mdx
> +		int num_total_elems = preFreq[max_index] - preFreq[i-1];  // the number of elements from [i, max_index]
```suggestion
		int num_total_elems = preFreq[max_index] - preFreq[i - 1];  // the number of elements from [i, max_index]
```

2022-09-07 02:16 UTC, dongliu0426 commented on solutions/cf-1462E2.mdx
> +	for(int i = 0; i < n; i++) {
```suggestion
	for (int i = 0; i < n; i++) {
```

2022-09-07 02:16 UTC, dongliu0426 commented on solutions/cf-1462E2.mdx
> +	for(int i = 1; i <= n; i++){
```suggestion
	for (int i = 1; i <= n; i++) {
```

2022-09-07 02:16 UTC, dongliu0426 commented on solutions/cf-1462E2.mdx
> +	for(int i = 1; i <= n; i++){
```suggestion
	for (int i = 1; i <= n; i++) {
```

2022-09-07 02:16 UTC, dongliu0426 approved these changes

2022-09-07 02:17 UTC, ryanchou-dev commented
why the request? i already approved.

2022-09-07 02:18 UTC, dongliu0426 commented
idk I'll merge after vercel deploys

2022-09-07 02:23 UTC, merged