Python code for BIT and Segment Tree
cpinitiative/usaco-guide pull request #3012
Opened 2022-08-21 18:47 UTC by thatpythonguys

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ x ] I have tested my code.
- [ x ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ x ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-08-21 23:04 UTC, SansPapyrus683 requested changes

2022-08-21 23:04 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +	def query(self, l, r) -> int:
argument type annotations

2022-08-21 23:04 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +# --- BEGIN SEGMENT TREE---
```suggestion
```

2022-08-21 23:04 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +# --- END SEGMENT TREE ---
```suggestion
```

2022-08-21 23:04 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +def solution():
could you take this out of the function?

2022-08-21 23:04 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +# --- BEGIN FENWICK TREE ---
```suggestion
```

2022-08-21 23:04 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +# --- END FENWICK TREE ---
```suggestion
```

2022-08-21 23:04 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +class FenwickTree:
rename to `BIT`

2022-08-22 00:07 UTC, SansPapyrus683 commented
use tabs to indent

2022-08-22 23:06 UTC, SansPapyrus683 requested changes

2022-08-22 23:06 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +inf = float('inf')
just use `float('inf')` directly

2022-08-22 23:06 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +input = sys.stdin.readline
same with this function

2022-08-22 23:06 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +	def update(self, i: int, v: int) -> None:
add doc comments for `update` and `query` like in the module: https://usaco.guide/gold/PURS
also rename them to better describe what they do

2022-08-22 23:06 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +		print(array_bit.get_sum(min(k, u)-1, max(k, u)-1))
spaces between ops

2022-08-23 23:46 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +class SegmentTree:
```suggestion
class SegmentTree:
	"""A data structure that can answer point update & range minimum queries."""
```
similar things for the other comments

2022-08-24 16:39 UTC, SansPapyrus683 commented on content/4_Gold/PURS.mdx
> +	def add(self, i: int, v: int) -> None:
swap the order
```suggestion
	def add(self, i: int, v: int) -> None:
	"""Adds v to the element at index i."""
```

2022-08-24 17:30 UTC, SansPapyrus683 approved these changes
@envyaims

2022-08-24 17:39 UTC, envyaims approved these changes
el piethon

2022-08-24 17:50 UTC, merged

2022-08-24 18:54 UTC, thatpythonguys commented
Would you be able to add my name to "Contributors" at the top? It's Pramana Saldin

2022-08-24 22:08 UTC, SansPapyrus683 commented
can you make another pr for that

2022-08-24 23:35 UTC, thatpythonguys commented
Sure