simplified cses-1144 code
cpinitiative/usaco-guide pull request #3014
Opened 2022-08-22 05:30 UTC by RedBlueBird

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-08-22 05:30 UTC, RedBlueBird commented
today I have learned you can create more than one pull request at the same time in Github

2022-08-22 20:21 UTC, bqi343 requested changes

2022-08-22 20:21 UTC, bqi343 commented on solutions/cses-1144.mdx
> +	for (; index <= MAX; index += index&(-index)) {
this goes out of bounds. also, the parentheses around `(-index)` are not necessary

2022-08-22 20:21 UTC, bqi343 commented on solutions/cses-1144.mdx
> +	vector<int> salaries(n); // salaries of n employees
> // salaries of n employees

not necessary

2022-08-22 20:21 UTC, bqi343 commented on solutions/cses-1144.mdx
> +	for (i = 1; i < n + 1; ++i) {
this doesn't compile

2022-08-22 20:27 UTC, bqi343 commented on solutions/cses-1144.mdx
> +	for (auto& t: salaries) {
no need for `&` here.

2022-08-22 20:47 UTC, SansPapyrus683 requested changes

2022-08-22 20:47 UTC, SansPapyrus683 commented on solutions/cses-1144.mdx
> +ll bit[MAX]; // binary-indexed tree
```suggestion
ll bit[MAX];  // binary-indexed tree
```same for other comments

2022-08-22 20:47 UTC, SansPapyrus683 commented on solutions/cses-1144.mdx
> +	for (auto& t: vals) {
please don't use `auto`

2022-09-06 02:04 UTC, RedBlueBird commented on solutions/cses-1144.mdx
> +	for (auto& t: vals) {
what should I change it to?

2022-09-06 02:09 UTC, SansPapyrus683 commented on solutions/cses-1144.mdx
> +	for (auto& t: vals) {
use the actual type name please

2022-09-18 23:57 UTC, SansPapyrus683 commented on solutions/cses-1144.mdx
> +	else index = it->second-1;
braces

2022-09-18 23:57 UTC, SansPapyrus683 commented on solutions/cses-1144.mdx
> +	for (; index; index -= index&(-index)) {
spaces between operators

2022-09-19 00:12 UTC, SansPapyrus683 commented on solutions/cses-1144.mdx
> +	for (auto query: queries) {
please don't use `auto`
also do `for (i : y)` instead of `for (i: y)`

2022-09-29 18:12 UTC, SansPapyrus683 commented
jeff can u

2022-10-06 20:06 UTC, SansPapyrus683 commented
nonononono

2022-10-19 02:57 UTC, SansPapyrus683 commented on solutions/cses-1144.mdx
> +	for (auto query: queries) {
```suggestion
for (const pair<int, int>& query : queries) {
```

2022-11-02 23:26 UTC, closed without merging