Added python solution for usaco-1210
cpinitiative/usaco-guide pull request #3022
Opened 2022-08-28 22:45 UTC by Keys9873

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [_] I have tested my code.
- [_] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [_] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-08-28 23:21 UTC, ryanchou-dev commented on solutions/usaco-1210.mdx
> +def skip_submissions(a, b, e, x):
multiline comments?

2022-08-28 23:32 UTC, SansPapyrus683 commented on solutions/usaco-1210.mdx
> +def skip_submissions(a, b, e, x):
not addressed

2022-08-29 03:27 UTC, Keys9873 commented on solutions/usaco-1210.mdx
> +def skip_submissions(a, b, e, x):
done

2022-08-29 03:40 UTC, SansPapyrus683 requested changes

2022-08-29 03:40 UTC, SansPapyrus683 commented on solutions/usaco-1210.mdx
> +'''
double quotes

2022-08-29 03:40 UTC, SansPapyrus683 commented on solutions/usaco-1210.mdx
> +def skip_submissions(a, b, e, x):
type annotations

2022-08-30 21:53 UTC, Keys9873 commented on solutions/usaco-1210.mdx
> +def skip_submissions(a, b, e, x):
wdym?

2022-08-30 21:55 UTC, Keys9873 commented on solutions/usaco-1210.mdx
> +'''
done

2022-08-30 22:07 UTC, SansPapyrus683 commented on solutions/usaco-1210.mdx
> +def skip_submissions(a, b, e, x):
https://realpython.com/lessons/annotations/

2022-08-30 22:19 UTC, Keys9873 commented on solutions/usaco-1210.mdx
> +def skip_submissions(a, b, e, x):
done

2022-08-31 00:07 UTC, SansPapyrus683 approved these changes

2022-09-02 04:03 UTC, Aadit-Ambadkar requested changes

2022-09-02 04:03 UTC, Aadit-Ambadkar commented on solutions/usaco-1210.mdx
> +t, k = map(int,input().split())
```suggestion
t, k = map(int, input().split())
```

2022-09-02 04:03 UTC, Aadit-Ambadkar commented on solutions/usaco-1210.mdx
> +	hi = 1e9
```suggestion
	hi = 10**9
```

2022-09-02 04:03 UTC, Aadit-Ambadkar commented on solutions/usaco-1210.mdx
> +	for j in range(1, t + 1):
```suggestion

	for j in range(1, t + 1):
```

2022-09-03 23:17 UTC, SansPapyrus683 commented on solutions/usaco-1210.mdx
> +	hi = 10**9
```suggestion
	hi = 10 ** 9
```

2022-09-04 02:03 UTC, SansPapyrus683 approved these changes

2022-09-07 02:19 UTC, ryanchou-dev approved these changes
beep beep boop

2022-09-08 18:48 UTC, merged