Added Python code in usaco-1018.mdx
cpinitiative/usaco-guide pull request #3030
Opened 2022-09-04 04:55 UTC by 1a1242

_If any of the below doesn't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making them.

2022-09-04 13:38 UTC, SansPapyrus683 requested changes

2022-09-04 13:38 UTC, SansPapyrus683 commented on solutions/usaco-1018.mdx
> +mod = 1000000007
rename to MOD

2022-09-04 13:38 UTC, SansPapyrus683 commented on solutions/usaco-1018.mdx
> +#reading input from the file
```suggestion
```

2022-09-04 13:38 UTC, SansPapyrus683 commented on solutions/usaco-1018.mdx
> +#If the segment is open the value will be +ve else -ve
```suggestion
# If the segment is open the value will be +ve else -ve
```
same for other comments

2022-09-04 13:38 UTC, SansPapyrus683 commented on solutions/usaco-1018.mdx
> +	a[x] += 1 #open
```suggestion
	a[x] += 1  # open
```
same for other comments

2022-09-04 13:38 UTC, SansPapyrus683 commented on solutions/usaco-1018.mdx
> +#writing the output to the file
```suggestion
```

2022-09-07 12:30 UTC, envyaims requested changes
tbh in python i dont think you even need to precalculate powers of 2 because it has built in modular exponentiation

2022-09-07 12:30 UTC, envyaims commented on solutions/usaco-1018.mdx
> +pow = [1] * n
dont name it pow since that's an actual function name

2022-09-07 12:30 UTC, envyaims commented on solutions/usaco-1018.mdx
> +open_segs = 0 # number of open segments
```suggestion
open_segs = 0
```
extraneous comment

2022-09-07 12:30 UTC, envyaims commented on solutions/usaco-1018.mdx
> +# If the segment is open the value will be +ve else -ve
whats `ve`

2022-09-13 02:33 UTC, 1a1242 commented
The requested changes are done

2022-09-13 03:14 UTC, SansPapyrus683 requested changes

2022-09-13 03:14 UTC, SansPapyrus683 commented on solutions/usaco-1018.mdx
> +fileout.write(str(ans) + '\n')
```suggestion
print(ans, file=open('help.out', 'w'))
```

2022-09-13 03:14 UTC, SansPapyrus683 commented on solutions/usaco-1018.mdx
> +n = int(filein.readline())
```suggestion
n = int(open('help.in'.readline())
```

2022-09-13 03:14 UTC, SansPapyrus683 commented on solutions/usaco-1018.mdx
> +	a[y] -= 1 # close
```suggestion
	a[x] += 1  # open
	a[y] -= 1  # close
```

2022-09-13 03:53 UTC, 1a1242 commented on solutions/usaco-1018.mdx
> +	a[y] -= 1 # close
Done with the changes

2022-09-13 04:43 UTC, SansPapyrus683 approved these changes
@envyaims

2022-09-13 23:12 UTC, envyaims approved these changes
okei

2022-09-14 00:24 UTC, merged