add python solution for usaco: cow at large (790)
cpinitiative/usaco-guide pull request #3130
Opened 2022-10-23 05:43 UTC by Amaryllidaceae

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [X] I have tested my code.
- [X] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

2022-10-23 11:53 UTC, SansPapyrus683 requested changes
yeah this is nice

2022-10-23 11:53 UTC, SansPapyrus683 commented on solutions/usaco-790.mdx
> +INF = float('inf')
just use this directly

2022-10-23 11:53 UTC, SansPapyrus683 commented on solutions/usaco-790.mdx
> +farmers_needed = 0
use a multiline comment

2022-10-23 11:53 UTC, SansPapyrus683 commented on solutions/usaco-790.mdx
> +while queue:
indent w/ tabs

2022-10-23 11:53 UTC, SansPapyrus683 commented on solutions/usaco-790.mdx
> +exits = [node for node, adj_list in enumerate(graph) if len(adj_list) == 1]
what does this do?

2022-10-24 13:56 UTC, SansPapyrus683 approved these changes
@ChuangSheep not sure if you know python?

2022-10-24 15:14 UTC, ChuangSheep commented
> @ChuangSheep not sure if you know python?

let's say I know the basic but have never used it in contest. Since I rarely use it, Id suggest someone else to do the review here

2022-10-24 16:29 UTC, SansPapyrus683 commented
@ryanchou-dev

2022-10-25 02:05 UTC, Amaryllidaceae commented on solutions/usaco-790.mdx
> +queue = deque(exits)
it's a queue for bfs. not really sure how it can be more descriptive

2022-10-25 02:39 UTC, SansPapyrus683 commented on solutions/usaco-790.mdx
> +queue = deque(exits)
i name it `frontier` in my solutions lol, up to you though

2022-10-26 04:55 UTC, Amaryllidaceae commented on solutions/usaco-790.mdx
> +queue = deque(exits)
shouldn't queue be fine though? I guess frontier also makes sense but all the c++ solutions I've seen just use q

2022-10-26 05:03 UTC, merged

2022-10-26 05:21 UTC, Amaryllidaceae commented
thanks :)