add a few solultions and editorials
cpinitiative/usaco-guide pull request #3184
Opened 2022-11-12 05:54 UTC by Amaryllidaceae

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [X] I have tested my code.
- [X] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

Add editorial and python solution to usaco: Angry Cows
Add 1 editorial and 1 python solution to cf: Cellular Network
Add editorial and python solution to usaco: Social Distancing

I had the python docstrings already from months ago so I decided to keep them in

2022-11-12 18:06 UTC, SansPapyrus683 commented
hey man
could you split these into multiple prs next time
it's a pain for reviewers

2022-11-12 18:09 UTC, SansPapyrus683 requested changes
yeah this code is really good

2022-11-12 18:09 UTC, SansPapyrus683 commented on solutions/cf-702C.mdx
> +'''
double quotes

2022-11-12 18:09 UTC, SansPapyrus683 commented on solutions/cf-782b.mdx
> +	"""
```suggestion
	"""
	Checks whether all friends can converge on one point in the specified time interval.
	:param seconds: Amount of seconds given for friends to converge.
	:returns: If the friends can converge to a single point.
	"""
```
doc comment syntax from [here](https://stackoverflow.com/questions/3898572/what-are-the-most-common-python-docstring-formats)

2022-11-12 18:09 UTC, SansPapyrus683 commented on solutions/cf-782b.mdx
> +diff = 10 ** (-6)
are the parens needed?

2022-11-12 18:09 UTC, SansPapyrus683 commented on solutions/cses-1085.mdx
> +	"""
same w/ above

2022-11-12 18:09 UTC, SansPapyrus683 commented on solutions/usaco-594.mdx
> +	Tests if all bales can be blown up with the specified blast radius.
here too

2022-11-12 18:09 UTC, SansPapyrus683 commented on solutions/cf-782b.mdx
> +	"""
oh wait this seems like the google syntax
uh most of the docstrings here follow the reST syntax

2022-11-12 20:24 UTC, Amaryllidaceae commented
To clarify, each solution with editorial should be it's own pull request?

2022-11-12 20:43 UTC, SansPapyrus683 commented on solutions/usaco-1038.mdx
> +	intervals.sort(key=lambda i: i[0])
don't think custom comparator here is necessary

2022-11-12 23:18 UTC, SansPapyrus683 commented
> To clarify, each solution with editorial should be it's own pull request?

ye

2022-11-13 03:10 UTC, SansPapyrus683 approved these changes
all the code still works right

2022-11-13 21:50 UTC, Amaryllidaceae commented
yeup, do you want screenshots again?

2022-11-13 21:55 UTC, SansPapyrus683 commented
nah just wanted to make sure
@ryanchou-dev

2022-11-13 21:57 UTC, ryanchou-dev approved these changes
alr

2022-11-13 21:58 UTC, merged