Update usaco-104.mdx
cpinitiative/usaco-guide pull request #3196
Opened 2022-11-18 16:51 UTC by saa938

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [✔] I have tested my code.
- [✔] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [✔] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

2022-11-18 18:24 UTC, SansPapyrus683 commented
> * I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions)

read them again

2022-11-21 17:05 UTC, ChuangSheep requested changes
and use **tab** to indent

2022-11-21 17:05 UTC, ChuangSheep commented on solutions/usaco-104.mdx
> +print(pref[n//2])
same

2022-11-21 17:05 UTC, ChuangSheep commented on solutions/usaco-104.mdx
> +</PythonSection>
```suggestion
</PySection>
```

2022-11-21 17:46 UTC, closed without merging