added python code
cpinitiative/usaco-guide pull request #3211
Opened 2022-11-21 18:16 UTC by saa938

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [✔] I have tested my code.
- [✔] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [✔] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

2022-11-22 19:43 UTC, ChuangSheep commented
cf. #3196
and just FYI, u don't have to close the PR when u make changes - just push them to the branch

2022-11-22 21:21 UTC, ryanchou-dev requested changes

2022-11-22 21:21 UTC, ryanchou-dev commented on solutions/usaco-104.mdx
> +## Python Implementation
unnecessary

2022-11-22 21:21 UTC, ryanchou-dev commented on solutions/usaco-104.mdx
> +differences = [0] * (n+1) # make a differences array
space out operators

2022-11-22 21:21 UTC, ryanchou-dev commented on solutions/usaco-104.mdx
> +pref = [0] * n # prefix sums array
please split up chunks of code

2022-11-22 22:26 UTC, SansPapyrus683 commented
fixed everything myself lol

2022-11-22 22:41 UTC, saa938 commented
thanks man and ill remember to push them to the branch

2022-11-30 02:42 UTC, SansPapyrus683 commented
can you guys re-review please

2022-11-30 06:33 UTC, ChuangSheep approved these changes
nice

2022-11-30 15:32 UTC, merged