Sleeping in Class solution
cpinitiative/usaco-guide pull request #3302
Opened 2023-01-01 01:33 UTC by yiminghuang47

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

2023-01-01 01:40 UTC, SansPapyrus683 requested changes

2023-01-01 01:40 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +After Elsie has made all the modifications to the log array $A[]$, the log will show that Bessie sleeps the same number of hours every day. Let's call that number $\texttt{numHours}$.
just say A, not A[]

2023-01-01 01:40 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +void solve() {
just put this in main

2023-01-01 01:40 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +	// iterate over numHours from small to large because the smallest possible numHours is optimal
over 80 chars

2023-01-01 01:40 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +bool check(int numHours) {
what this function do

2023-01-01 01:40 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +		if (check(numHours)) {
use snake_case for c++

2023-01-01 02:09 UTC, yiminghuang47 commented
Sorry it's my first time adding solution.I might have undone some changes you made.

2023-01-01 02:16 UTC, yiminghuang47 commented
I did not realize that you already made changes lol. my bad

2023-01-01 02:34 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +		// because the smallest possible num_hours is optimal
```cpp
/* 
 * multiline comments should be
 * formatted like this
 */
```

2023-01-01 03:03 UTC, SansPapyrus683 requested changes

2023-01-01 03:03 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +		 *num_hours is the # of hours of sleep every class AFTER modification
space after asterisk

2023-01-01 03:03 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +	int curr_sum = 0; // keeps track of the current sum
two spaces after line of code before beginning an inline comment

2023-01-01 04:51 UTC, SansPapyrus683 approved these changes
@envyaims

2023-01-01 04:51 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +source: USACO bronze 2022 February
```suggestion
source: USACO Bronze 2022 February
```

2023-01-01 04:51 UTC, SansPapyrus683 commented on solutions/usaco-1203.mdx
> +source: USACO bronze 2022 February
```suggestion
source: USACO Bronze 2022 February
```

2023-01-01 16:11 UTC, ChuangSheep reviewed
looks good

2023-01-01 16:11 UTC, ChuangSheep commented on solutions/usaco-1203.mdx
> +too.
```suggestion
$N$ and $\texttt{sum}$ are constant, so, to minimize $N-\texttt{sum}/\texttt{num\_hours}$, 
we need to minimize $\texttt{num\_hours}$ too.
```

2023-01-01 16:11 UTC, ChuangSheep commented on solutions/usaco-1203.mdx
> +valid.
```suggestion
We iterate over $A$ from left to right and combine values to test if a value 
of $\texttt{num\_hours}$ is valid. If at some point a combined value exceeds 
$\texttt{num\_hours}$ then we know that $\texttt{num\_hours}$ is not
valid.  
```

2023-01-01 17:50 UTC, envyaims approved these changes
gr8

2023-01-01 17:50 UTC, envyaims commented on solutions/usaco-1203.mdx
> +		int sum = 0;  // sum of all values in the vector
```suggestion
		int sum = 0;  
```
a bit extraneous comment

2023-01-01 17:50 UTC, envyaims commented on solutions/usaco-1203.mdx
> +				// check(num_hours) checks if num_hours is a valid answer
```suggestion
```

2023-01-02 10:19 UTC, ChuangSheep approved these changes
nice

2023-01-02 15:38 UTC, merged