Add internal solution for Korney Korneevich and XOR (easy version) (cf-1582F1)
cpinitiative/usaco-guide pull request #3360
Opened 2023-01-14 19:58 UTC by ChuangSheep

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

2023-01-15 02:52 UTC, SansPapyrus683 commented
why dis draft

2023-01-15 19:35 UTC, bqi343 commented
@ChuangSheep Could you move this solution to `/solutions/gold`?

2023-01-15 19:38 UTC, ChuangSheep commented
> @ChuangSheep Could you move this solution to `/solutions/gold/`?

sure, sorry didn't see the refactor

2023-01-15 20:43 UTC, SansPapyrus683 requested changes

2023-01-15 20:43 UTC, SansPapyrus683 commented on solutions/gold/cf-1582F1.mdx
> +To solve this problem, let's notice that the result of performing XOR
```suggestion
To solve this problem, notice that the result of performing XOR
```

2023-01-15 20:43 UTC, SansPapyrus683 commented on solutions/gold/cf-1582F1.mdx
> +Let $dp[x][i]$ represent the feasibility of getting $x$ as a result of XOR of
_bit_ of an abrupt transition, don't you think? (sorry)

2023-01-15 20:43 UTC, SansPapyrus683 commented on solutions/gold/cf-1582F1.mdx
> +const int MAXA = 512;
```suggestion
const int MAXA = 1 << 9
```
also i'd do `MAX_A`

2023-01-15 20:43 UTC, SansPapyrus683 commented on solutions/gold/cf-1582F1.mdx
> +	 * dp[x][i] := whether it is possible to get x using XOR of an increasing
given that every other dp in code comments uses normal equal sign, i'd do away w/ the colon here (optional)

2023-01-15 20:43 UTC, SansPapyrus683 commented on solutions/gold/cf-1582F1.mdx
> +		}
haven't read the problem, but maybe explain this?

2023-01-17 00:21 UTC, SansPapyrus683 approved these changes
yeah

2023-01-21 00:47 UTC, merged