Updated Quiz Questions and Removed Incomplete Section
cpinitiative/usaco-guide pull request #3379
Opened 2023-01-23 08:04 UTC by dustin-miao

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

2023-01-23 08:05 UTC, dustin-miao commented
Addresses #3375

2023-01-23 15:49 UTC, SansPapyrus683 requested changes
wow, dustin actually doing something?

2023-01-23 15:49 UTC, SansPapyrus683 commented on content/2_Bronze/Complete_Rec.mdx
> +	      Using the C++ library function is easier and less buggy.
shouldn't these questions be language agnostic?

2023-01-23 17:06 UTC, SansPapyrus683 commented on content/2_Bronze/Complete_Rec.mdx
> +	      Using the C++ library function is easier and less buggy.
at this point i'd rather just delete the question

2023-02-10 02:05 UTC, bqi343 commented on content/2_Bronze/Complete_Rec.mdx
> +	    Why is using `std::next_permutation` generally preferable to writing your own recursive function?
```suggestion
	    In C++, why is using `std::next_permutation` generally preferable to writing your own recursive function to iterate through permutations?
```

2023-02-10 02:25 UTC, merged