cf919d add c++ and python solutions
cpinitiative/usaco-guide pull request #3382
Opened 2023-01-24 00:35 UTC by 876pol

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

2023-01-24 00:38 UTC, 876pol commented
the python code ACs on pypy 64 bit (https://codeforces.com/contest/919/submission/190263892) but not regular pypy (https://codeforces.com/contest/919/submission/190263898). should i mention something about this on the editorial?

2023-01-27 03:14 UTC, SansPapyrus683 requested changes

2023-01-27 03:14 UTC, SansPapyrus683 commented on solutions/gold/cf-919D.mdx
> +	return 0;
```suggestion
```

2023-01-27 03:14 UTC, SansPapyrus683 commented on solutions/gold/cf-919D.mdx
> +else:
```suggestion
else:  # find the maximum frequency across all nodes and letters.
```
also if you're gonna use periods might as well go all the way & capitalize sentences asw

2023-01-27 03:14 UTC, SansPapyrus683 commented
> the python code ACs on pypy 64 bit (https://codeforces.com/contest/919/submission/190263892) but not regular pypy (https://codeforces.com/contest/919/submission/190263898). should i mention something about this on the editorial?

yes

2023-02-18 02:09 UTC, SansPapyrus683 approved these changes
seems legit

2023-02-18 19:28 UTC, dongliu0426 approved these changes

2023-02-18 19:28 UTC, merged