remove c++ template from cses-1757, add python sol
cpinitiative/usaco-guide pull request #3383
Opened 2023-01-24 00:44 UTC by 876pol

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

2023-01-27 03:13 UTC, SansPapyrus683 requested changes

2023-01-27 03:13 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +vector<int> radj[200005]; // Reverse graph
two spaces

2023-01-27 03:13 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +vector<int> radj[200005]; // Reverse graph
also some of these don't have to be global
or all of them, no functions here

2023-01-27 03:13 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +out = [0] * (200005)  # Number of outgoing nodes
magic number
why not dynamically size based on n/m

2023-01-27 03:13 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +for t in ans:
```suggestion
for t in reversed(ans):
```

2023-01-27 03:13 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +for i in range(1, n+1):
spaces

2023-01-31 15:41 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +	print(t, end=' ')
```suggestion
print(' '.join(str(i) for i in reversed(ans)))
```

2023-01-31 15:41 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +		# Any node with out[i] == 0 can be used, so we store all possible nodes in a max heap to get the node with the maximum id.
over 80?

2023-02-10 03:43 UTC, 876pol commented on solutions/gold/cses-1757.mdx
> +		# Any node with out[i] == 0 can be used, so we store all possible nodes in a max heap to get the node with the maximum id.
oops, fixed

2023-02-10 04:13 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +		nodes in a max heap to get the node with the maximum id."""
```suggestion
		# Any node with out[i] == 0 can be used, so we store all possible
		# nodes in a max heap to get the node with the maximum id.
```

2023-02-11 23:58 UTC, SansPapyrus683 requested changes

2023-02-11 23:58 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +		if (out[i] == 0) pq.push(i);
braces

2023-02-11 23:58 UTC, SansPapyrus683 commented on solutions/gold/cses-1757.mdx
> +print(' '.join(str(i) for i in reversed(ans)))
```suggestion

print(' '.join(str(i) for i in reversed(ans)))
```

2023-02-15 00:12 UTC, SansPapyrus683 approved these changes

2023-02-18 18:59 UTC, dongliu0426 approved these changes

2023-02-18 19:01 UTC, merged