ccc twenty four add recursion and java+python sols
cpinitiative/usaco-guide pull request #3438
Opened 2023-02-18 01:59 UTC by 876pol

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.
 
 fixes #3422

2023-02-25 05:31 UTC, SansPapyrus683 commented
nonononono

2023-03-02 19:26 UTC, SansPapyrus683 commented
@876pol any updates?

2023-03-02 22:18 UTC, 876pol commented
oh oops kinda forgot about this

2023-03-02 22:21 UTC, 876pol commented on solutions/bronze/ccc-Twenty-four.mdx
> +					// If the operation is invalid, continue;
the indent spacing is different on github
the alignment's better on usaco guide: [](https://usaco-guide-flykvef9w-cpinitiative.vercel.app/problems/ccc-twenty-four/solution)

2023-03-03 00:15 UTC, SansPapyrus683 commented on solutions/bronze/ccc-Twenty-four.mdx
> +					// If the operation is invalid, continue;
i'd rather you indent it like
```cpp
int x = really_long_function(
	asdf,
	asdf,
);
```

2023-03-04 03:26 UTC, 876pol commented on solutions/bronze/ccc-Twenty-four.mdx
> +					// If the operation is invalid, continue;
ok i have changed it

2023-03-04 03:30 UTC, SansPapyrus683 requested changes

2023-03-04 03:30 UTC, SansPapyrus683 commented on solutions/bronze/ccc-Twenty-four.mdx
> +		ans = -INF;
replace INF with INT32_MIN

2023-03-04 03:30 UTC, SansPapyrus683 commented on solutions/bronze/ccc-Twenty-four.mdx
> +	static final int INF = (int) 1e9;
same here, but w/ Integer.MIN_VALUE

2023-03-04 03:30 UTC, SansPapyrus683 commented on solutions/bronze/ccc-Twenty-four.mdx
> +INF = int(1e9)
python has `float('inf')`

2023-03-04 03:30 UTC, SansPapyrus683 commented on solutions/bronze/ccc-Twenty-four.mdx
> +for h in range(num_hands):
```suggestion
for _ in range(int(input())):
```

2023-03-04 16:43 UTC, SansPapyrus683 commented on solutions/bronze/ccc-Twenty-four.mdx
> +INF = float('inf')
just remove this variable at this point lmao

2023-03-08 21:54 UTC, SansPapyrus683 commented on solutions/bronze/ccc-Twenty-four.mdx
> +INF = float('inf')
bump

2023-03-10 02:33 UTC, SansPapyrus683 commented
could you add a time complexity?

2023-03-10 05:20 UTC, 876pol commented
the code still works

however, the pre-commit.ci task (what i assume to be an auto-formatter) changed the way the file was formatted previously. should i/is it possible to change it back?

2023-03-10 05:22 UTC, SansPapyrus683 commented
unfortunately no

2023-03-10 05:22 UTC, merged