Added dropdown menu for focus problems.
cpinitiative/usaco-guide pull request #3469
Opened 2023-02-26 03:10 UTC by shaubby

…oblem in the USACO ide

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

This will allow users to open focus problems in the USACO ide.

2023-02-26 19:29 UTC, bqi343 requested changes
good suggestion. can you refactor the code so that the functionality common to `ProblemsListItem` and `FocusProblem` isn't duplicated? Same for `ProblemsListItemDropdown` and `FocusProblemDropdown`.

2023-02-26 19:51 UTC, shaubby commented
> 

The FocusProblem and ProblemsListItem components were already different components, as they have very different functionalities. However, I can try to integrate FocusProblemDropdown into the prexisting ProblemsListItemDropdown class.

2023-02-26 19:52 UTC, shaubby commented
Also, I see that my code had failed one of the tests, do you have any idea what happened?

2023-02-26 19:54 UTC, bqi343 commented
> The FocusProblem and ProblemsListItem components were already different components, as they have very different functionalities.

I was referring to `more`, which should be the same for both components.

> do you have any idea what happened?

idk

2023-02-26 20:12 UTC, shaubby commented
Oh ok, they are slightly different, but I can probably still integrate them both into the ProblemsListItemDropdown component. Also, I was planning on applying to join the CPI web development team, should I finish this and link to it in my application afterwards or just apply now?

2023-02-26 20:37 UTC, mjh316 commented
> Also, I was planning on applying to join the CPI web development team, should I finish this and link to it in my application afterwards or just apply now?

Awesome to see that you're planning on applying! I think it'd be good to finish it first! :)

2023-02-28 05:01 UTC, shaubby reviewed
Cleaned up code and combined files as asked

2023-02-28 05:10 UTC, bqi343 requested changes

2023-02-28 05:10 UTC, bqi343 commented on src/components/markdown/FocusProblem.tsx
> +  const darkMode = useDarkMode();
what's this for?

2023-02-28 05:10 UTC, bqi343 commented on src/components/markdown/ProblemsList/ProblemsListItemDropdown.tsx
> +  console.log(isFocusProblem);
remove

2023-02-28 05:10 UTC, bqi343 commented on src/components/markdown/FocusProblem.tsx
> +  const [isDropdownShown, setIsDropdownShown] = React.useState(false);
these also don't look like they're used

2023-02-28 05:14 UTC, bqi343 commented on src/components/markdown/ProblemsList/ProblemsListItem.tsx
>    const tippyRef = React.useRef<Instance>();
also I think these variables are no longer needed?

2023-03-03 01:16 UTC, shaubby commented
Alright, those variables had been used previously but are no longer used now, I just forgot to get rid of them. It should be good to go now.

2023-03-03 03:08 UTC, thecodingwizard commented
<img width="407" alt="image" src="https://user-images.githubusercontent.com/7865976/222621543-70a54e3a-bdf1-4f13-b3f3-df695eaf1036.png">

I think there's some unwanted padding here

Might be able to be fixed with

```js
const StyledTippy = styled(Tippy)`
  .tippy-content {
    padding: 0;
  }
`;
```

2023-03-03 04:38 UTC, shaubby commented on src/components/markdown/ProblemsList/ProblemsListItemDropdown.tsx
> +          <div className="-mx-2 text-left">
It was actually the -mx-2 that fixed it.

2023-03-03 05:24 UTC, merged