Add prefix sum solution
cpinitiative/usaco-guide pull request #3482
Opened 2023-03-01 04:33 UTC by 96f4

This problem is in More on Prefix Sums

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions), which include the following: 
  - I understand that if it is clear that I have not attempted to follow these guidelines (ex. if I have not used tabs to indent), my PR will be closed.
  - If changes are requested, I will re-request the review after making the changes.

2023-03-02 01:41 UTC, SansPapyrus683 requested changes
start slow

2023-03-02 01:41 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +### Implementation (Prefix Sums)
put this below the previous sol

2023-03-02 01:41 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +)
at this point just use a for loop

2023-03-02 01:41 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +			most_grass = max(most_grass, prefix[i + k + 1][j + k + 1] - prefix[i + k + 1][j - k] - prefix[i - k][j + k + 1] + prefix[i - k][j - k]);
over 80 chars

2023-03-02 01:41 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +	vector<vector<int>> field(new_n, vector<int>(new_n));
ngl don't think this is sufficiently different from the og sol to warrant a diff section?
by "prefix sums" i was thinking storing pref sums for every row and iterating through them for each query

2023-03-02 04:38 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +	vector<vector<int>> field(new_n, vector<int>(new_n));
elaborate?

2023-03-02 04:41 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +)
can i have a screenie of it tle-ing on the last case? just wanna make sure

2023-03-02 04:55 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +)
i'd keep the for loop & add a warning like "may tle on last tc"

2023-03-02 05:21 UTC, SansPapyrus683 requested changes

2023-03-02 05:21 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +		most_grass = prefix[new_n][new_n];
braces

2023-03-02 05:21 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +			prefix[i + 1][j + 1] = field[i][j] + prefix[i + 1][j] + prefix[i][j + 1] - prefix[i][j];
over 80 chars

2023-03-02 05:21 UTC, SansPapyrus683 commented on solutions/silver/usaco-416.mdx
> +		prefix[i + 1][j + 1] = field[i][j] + prefix[i + 1][j] + prefix[i][j + 1] - prefix[i][j]
likewise

2023-03-02 05:45 UTC, SansPapyrus683 approved these changes
@envyaims @ryanchou-dev get in here

2023-03-03 02:57 UTC, envyaims approved these changes
your code looks exactly like something sans would write 😒

2023-03-03 02:58 UTC, merged

2023-03-03 02:58 UTC, SansPapyrus683 commented
cope and seethe envy

2023-03-03 02:58 UTC, ryanchou-dev commented
bro i was js reviewing grrr

2023-03-03 02:59 UTC, SansPapyrus683 commented
sorry ryan!