Add Digit DP Module
cpinitiative/usaco-guide pull request #3522
Opened 2023-03-08 01:54 UTC by jessechoe10

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-03-08 02:00 UTC, SansPapyrus683 commented on content/4_Gold/DP_Digits.mdx
> +ll solveDP(int loc, int k, bool largest, bool started, int targ, int targ2) {
snake_case for c++

2023-03-08 02:29 UTC, bqi343 commented on content/4_Gold/Digit_DP.problems.json
> +      "difficulty": "Very Hard",
I don't get why this is "Very Hard" and the first problem is "Easy" - these problems aren't that different in difficulty IMO. maybe "Hard" for this one and "Normal" for the first one?

2023-03-08 02:30 UTC, bqi343 commented on content/4_Gold/Digit_DP.mdx
> +  - modular
why are modular, combo, knapsack prereqs?

2023-03-08 04:04 UTC, jessechoe10 commented on content/4_Gold/Digit_DP.mdx
> +  - modular
hmm ill just say intro dp then

2023-03-08 18:16 UTC, bqi343 approved these changes
looks okay (but I didn't review the explanation)

2023-03-09 02:03 UTC, SansPapyrus683 requested changes

2023-03-09 02:03 UTC, SansPapyrus683 commented on content/4_Gold/Digit_DP.mdx
> +Let $\texttt{dp[i][und][k][is0]}$ where $i$ is the current position, $und$ is whether you have gone below the actual number, $k$ is a counter to see if you have at least half of the same digit, and $
give a walkthrough of what a transition would look like or smth

2023-03-09 02:03 UTC, SansPapyrus683 commented on content/4_Gold/Digit_DP.mdx
> +
```suggestion
<CPPSection>

Code from
[here](https://raw.githubusercontent.com/thecodingwizard/competitive-programming/master/USACO/2014open/silver/odometer.cpp)

```cpp

2023-03-09 02:03 UTC, SansPapyrus683 commented on content/4_Gold/Digit_DP.mdx
> +ll dp[19][50][2][2];
magic numbers

2023-03-09 02:03 UTC, SansPapyrus683 commented on content/4_Gold/Digit_DP.mdx
> +ll solve(ll x) {
`solve` gives me no info

2023-03-09 02:03 UTC, SansPapyrus683 commented on content/4_Gold/Digit_DP.mdx
> +	ll dup = 0;
add some comments around here

2023-03-09 02:03 UTC, SansPapyrus683 commented on content/4_Gold/Digit_DP.mdx
> +		if (i < lar) isLargest = false;
braces + snake_case

2023-03-11 01:25 UTC, ryanchou-dev approved these changes
looks nice, just do sans' suggestions, and we'll be chillin

2023-03-11 01:25 UTC, ryanchou-dev commented on content/4_Gold/Digit_DP.mdx
> +[here](https://raw.githubusercontent.com/thecodingwizard/competitive-programming/master/USACO/2014open/silver/odometer.cpp).
better as "Code by Nathan Wang", and add link to github instead of just the raw file

2023-03-15 01:53 UTC, ryanchou-dev commented on content/4_Gold/Digit_DP.mdx
> +		if (i < lar) isLargest = false;
should be done ?

2023-03-16 21:26 UTC, SansPapyrus683 commented on content/4_Gold/Digit_DP.mdx
> +ll solve(ll x) {
get this
how about instead of adding a comment, you put the description in the name itself

2023-03-17 01:52 UTC, SansPapyrus683 commented
there's still unresolved comments my man

2023-03-31 12:24 UTC, closed without merging