add cpp implementation to usaco-743
cpinitiative/usaco-guide pull request #3595
Opened 2023-04-12 19:32 UTC by WilliamYuan42

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [X] I have tested my code.
- [X] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-04-13 01:11 UTC, SansPapyrus683 requested changes

2023-04-13 01:11 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +int col[mx], start[mx], fin[mx], n, ans = 0;
declarations on separate lines

2023-04-13 01:11 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +const int mx = 1e5 + 5;
is the +5 needed

2023-04-13 01:11 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +	cin.tie(nullptr);
remove if runs w/o

2023-04-13 01:11 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +	fill(fin, fin + mx, -(1 << 30));
lmao why not just use vectors

2023-04-13 15:23 UTC, WilliamYuan42 commented on solutions/gold/usaco-743.mdx
> +	fill(fin, fin + mx, -(1 << 30));
idk lol

2023-04-13 17:32 UTC, SansPapyrus683 requested changes

2023-04-13 17:32 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +	vector<int> fin(n + 1, -(1 << 30));
use INT32_MAX and INT32_MIN instead of these weird numbers

2023-04-13 17:32 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +		fin[col[i]] = max(fin[col[i]], i);
maybe `end` instead of `fin`

2023-04-13 17:32 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +	start[0] = 0, fin[0] = n + 1;
separate lines

2023-04-13 17:32 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +		// thus, the painting is invalid
```suggestion
```
should be explained in the editorial

2023-04-13 17:32 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +		// thus, the painting is invalid
or copy the comment from the java code, yeah you should do that instead

2023-04-14 02:32 UTC, SansPapyrus683 approved these changes
good enough

2023-04-14 02:32 UTC, SansPapyrus683 commented on solutions/gold/usaco-743.mdx
> +
```suggestion
```

2023-04-14 16:14 UTC, SansPapyrus683 commented
no, i'm just very picky about this kinda stuff
another pm probably would've had it merged in 10 minutes

2023-04-16 09:35 UTC, ChuangSheep approved these changes
nice

2023-04-16 09:35 UTC, ChuangSheep commented on solutions/gold/usaco-743.mdx
> +	cout << ans - 1 << "\n";
```suggestion
	cout << ans - 1 << endl;
```

2023-04-16 09:35 UTC, ChuangSheep commented on solutions/gold/usaco-743.mdx
> +			cout << "-1\n";
```suggestion
			cout << "-1" << endl;
```

2023-04-23 14:01 UTC, ChuangSheep commented
@SansPapyrus683 merge?

2023-04-23 14:33 UTC, merged