Add internal solution for GCD and MST (cf-1513d)
cpinitiative/usaco-guide pull request #3609
Opened 2023-04-16 12:33 UTC by ChuangSheep

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-04-22 19:24 UTC, SansPapyrus683 requested changes

2023-04-22 19:24 UTC, SansPapyrus683 commented on solutions/gold/cf-1513D.mdx
> +	while (t-- > 0) { solve(); }
for loop & put `solve()` in here

2023-04-22 19:24 UTC, SansPapyrus683 commented on solutions/gold/cf-1513D.mdx
> +that we always add edges that cost as less as possible. Let the current element
> add edges that cost as less as possible

*add edges of minimum cost

2023-04-22 19:24 UTC, SansPapyrus683 commented on solutions/gold/cf-1513D.mdx
> +	while (t-- > 0) { solve(); }
```suggestion
	int test_num;
	cin >> test_num;
	for (int t = 0; t < test_num; t++) { solve(); }
```

2023-04-23 14:34 UTC, SansPapyrus683 approved these changes

2023-04-30 17:51 UTC, ryanchou-dev approved these changes
yessir

2023-04-30 17:53 UTC, SansPapyrus683 commented on solutions/gold/cf-1513D.mdx
> +		/**
```suggestion
		/*
```

2023-04-30 18:10 UTC, merged