added hint to cses-1620
cpinitiative/usaco-guide pull request #3613
Opened 2023-04-18 08:28 UTC by RedBlueBird

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-04-18 14:37 UTC, SansPapyrus683 commented
what happened to the other pr lol

2023-04-18 14:46 UTC, SansPapyrus683 requested changes
wait nvm for some reason i can't edit the files?

2023-04-18 14:48 UTC, SansPapyrus683 commented
what the- i'm trying to edit the file but the changes aren't processing

2023-04-18 20:20 UTC, SansPapyrus683 approved these changes
@ryanchou-dev review

2023-04-19 00:19 UTC, ryanchou-dev approved these changes
chillin

2023-04-19 00:19 UTC, ryanchou-dev commented on solutions/silver/cses-1620.mdx
> +**Time Complexity:** $\mathcal{O}(n \log t)$, where $t$ is the largest time we need to consider.
$\max(t_i)$ instead?

2023-04-19 00:21 UTC, SansPapyrus683 commented on solutions/silver/cses-1620.mdx
> +**Time Complexity:** $\mathcal{O}(n \log t)$, where $t$ is the largest time we need to consider.
imo it's fine?

2023-04-19 01:00 UTC, nwatx approved these changes

2023-04-19 02:08 UTC, merged