faster solution for usaco-990
cpinitiative/usaco-guide pull request #3615
Opened 2023-04-19 01:51 UTC by 96f4

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-04-19 02:17 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +## Implementation
can you at least explain how to optimize from the initial solution to this one

2023-04-19 03:52 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +## Implementation
don't tell me that, put that in the editorial

2023-04-27 02:17 UTC, SansPapyrus683 reviewed
god, why is this still pending

2023-04-29 00:39 UTC, SansPapyrus683 requested changes

2023-04-29 00:39 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	cin.tie(0);
remove if runs w/o

2023-04-29 00:39 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +		rand = new Random();
random?

2023-04-29 00:39 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	int B[N];
use a vector

2023-04-29 00:39 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	for (int s = 1;; s++) {
i'd just use a while (true) at this point

2023-04-29 00:39 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +for s in range(1, 1001):
magic number, bad
since the c++ does a while loop do that here as well

2023-04-29 00:39 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +def quickselect(A, i, key):
type annotations & docstring telling the user what this does
also maybe have a default for key, would be nice for ppl to copy this

2023-04-29 00:39 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +Since the order of these elements does not matter, we can use a selection algorithm instead of sorting to reduce the time complexity by a factor of $\log N$.
> selection algorithm

give a hyperlink/source for this, it isn't covered in the guide

2023-04-29 02:25 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	for (int s = 1;; s++) {
yeah, put those outside the loop

2023-04-29 02:33 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	"""
```suggestion
	"""Rearranges A such that A[i] contains the ith smallest element in the list."""
```

2023-04-29 04:32 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	"""
does the "other stuff" affect how the algo runs?

2023-04-29 04:37 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	"""
how's the new one

2023-04-29 04:41 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	"""
check again

2023-04-29 14:42 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	"""
one more time

2023-04-29 19:23 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	It also makes it so that key(A[j]) <= key(A[i]) for all 0 <= j <= i.
add this to the java code as a docstring asw

2023-04-29 21:17 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	 * (mod s) and A[j] % s >= A[i] % s for all 0 <= j <= i.
mod s?

2023-04-30 00:33 UTC, SansPapyrus683 commented on solutions/silver/usaco-990.mdx
> +	cin.tie(0);
so does it run without?

2023-04-30 03:17 UTC, SansPapyrus683 approved these changes
@envyaims

2023-05-07 04:29 UTC, ryanchou-dev approved these changes
awesome!

2023-05-07 04:46 UTC, merged