added Sleepy Cow Herding hints
cpinitiative/usaco-guide pull request #3640
Opened 2023-04-28 19:12 UTC by yiminghuang47

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-04-28 21:13 UTC, SansPapyrus683 requested changes

2023-04-28 21:13 UTC, SansPapyrus683 commented on solutions/bronze/usaco-915.mdx
> +There are only a few possible answers. How many moves does it take at most to group the cows in consecutive locations?
> few possible answers

for what?

2023-04-28 21:13 UTC, SansPapyrus683 commented on solutions/bronze/usaco-915.mdx
> +It takes at most 2 moves.
hints shouldn't just give the answer

2023-04-28 21:13 UTC, SansPapyrus683 commented on solutions/bronze/usaco-915.mdx
> +</Spoiler>
same here

2023-04-28 21:45 UTC, yiminghuang47 commented
I'm not really sure how much info I should reveal in the hints. I might've deleted too much lol

2023-04-28 21:46 UTC, yiminghuang47 commented on solutions/bronze/usaco-915.mdx
> +It takes at most 2 moves.
I see

2023-04-29 15:08 UTC, SansPapyrus683 approved these changes

2023-04-29 15:24 UTC, yiminghuang47 commented on solutions/bronze/usaco-915.mdx
> +author: Sathvik Chundru, Ryan Chou, Vikas Thoutam Yiming Huang
wait why did you delete the comma lol

2023-04-29 15:24 UTC, SansPapyrus683 commented on solutions/bronze/usaco-915.mdx
> +author: Sathvik Chundru, Ryan Chou, Vikas Thoutam Yiming Huang
i thought i deleted the space what

2023-04-29 16:08 UTC, ChuangSheep approved these changes
looks good

2023-04-29 16:42 UTC, merged