add java solution to cf782b
cpinitiative/usaco-guide pull request #3659
Opened 2023-05-15 01:48 UTC by 876pol

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-05-15 14:41 UTC, SansPapyrus683 requested changes

2023-05-15 14:41 UTC, SansPapyrus683 commented on solutions/silver/cf-782b.mdx
> +		    0;  // high will be the location of the farthest north friend
put the comment in a separate line above the variable

2023-05-15 14:41 UTC, SansPapyrus683 commented on solutions/silver/cf-782b.mdx
> +	/*
```suggestion
	/**
```

2023-05-15 14:41 UTC, SansPapyrus683 commented on solutions/silver/cf-782b.mdx
> +	static ArrayList<Double> speeds = new ArrayList<>();
```suggestion
	static List<Double> locations = new ArrayList<>();
	static List<Double> speeds = new ArrayList<>();
```

2023-05-15 14:41 UTC, SansPapyrus683 commented on solutions/silver/cf-782b.mdx
> +public class Solution {
```suggestion
public class MeetingPlace {
```

2023-05-19 04:12 UTC, SansPapyrus683 commented
![deal](https://github.com/cpinitiative/usaco-guide/assets/55369003/ed62edcd-3cb3-47a2-aa6d-06f01b82fab3)

2023-05-20 21:49 UTC, 876pol commented
😭

2023-05-20 21:53 UTC, SansPapyrus683 requested changes

2023-05-20 21:53 UTC, SansPapyrus683 commented on solutions/silver/cf-782b.mdx
> +				    false;  // reset to false, as we have a new maximum
same here

2023-05-20 21:53 UTC, SansPapyrus683 commented on solutions/silver/cf-782b.mdx
> +	static double MAX_ERROR = 10e-7;
put this at the top

2023-05-20 21:53 UTC, SansPapyrus683 commented on solutions/silver/cf-782b.mdx
> +	static double MAX_ERROR = 10e-7;
also declare as final

2023-05-20 21:53 UTC, SansPapyrus683 commented on solutions/silver/cf-782b.mdx
> +		Scanner scanner = new Scanner(System.in);
```suggestion
```

2023-05-20 21:53 UTC, SansPapyrus683 commented on solutions/silver/cf-782b.mdx
> +		double mid;
why not declare this in the loop

2023-05-21 17:42 UTC, SansPapyrus683 approved these changes

2023-05-31 00:36 UTC, envyaims approved these changes
ok

2023-05-31 00:44 UTC, merged