Update usaco-1188.mdx
cpinitiative/usaco-guide pull request #3736
Opened 2023-06-09 20:44 UTC by Keys9873

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [X] I have tested my code.
- [X] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-06-09 21:10 UTC, SansPapyrus683 requested changes

2023-06-09 21:10 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1188.mdx
> +		ArrayList<Integer> vals;
```suggestion
		List<Integer> vals;
```

2023-06-09 21:10 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1188.mdx
> +			lo = (int)1e9;
use integer.min_value/max_value

2023-06-09 21:10 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1188.mdx
> +		PrintWriter pw = new PrintWriter(System.out);
```suggestion
```

2023-06-09 21:10 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1188.mdx
> +		for (int i = 0; i < n; i++) {
space out code

2023-06-10 20:33 UTC, Keys9873 commented
Added comments too

2023-06-10 22:55 UTC, SansPapyrus683 requested changes

2023-06-10 22:55 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1188.mdx
> +			// lexographically optimal position
multiline comments

2023-06-10 22:55 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1188.mdx
> +			// size
```suggestion
			// Split the block if it's too large
```

2023-06-10 22:56 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1188.mdx
> +			if (sqrt.get(j).vals.size() > 300) {
300?

2023-06-11 02:26 UTC, Keys9873 commented on solutions/platinum/usaco-1188.mdx
> +			if (sqrt.get(j).vals.size() > 300) {
sqrt(1e5)

2023-06-11 03:02 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1188.mdx
> +			if (sqrt.get(j).vals.size() > 300) {
call Math.sqrt(n) or smth then

2023-06-11 21:36 UTC, Keys9873 commented on solutions/platinum/usaco-1188.mdx
> +			if (sqrt.get(j).vals.size() > 300) {
i made it a constant

2023-06-11 22:29 UTC, SansPapyrus683 approved these changes

2023-06-12 00:13 UTC, ryanchou-dev approved these changes
great!

2023-06-12 00:24 UTC, merged