Added internal written solution for cses 2185 Prime Multiples
cpinitiative/usaco-guide pull request #3747
Opened 2023-06-13 22:49 UTC by alexyd88

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-06-13 23:00 UTC, alexyd88 commented
pre-commit.ci autofix

2023-06-14 21:24 UTC, SansPapyrus683 requested changes

2023-06-14 21:24 UTC, SansPapyrus683 commented on solutions/silver/cses-2185.mdx
> +If we consider each prime individually and find the number of multiples it has, we will find that there is an overlap
break this giant paragraph up

2023-06-14 21:24 UTC, SansPapyrus683 commented on solutions/silver/cses-2185.mdx
> +Here is the code implementation.
```suggestion
```
also add time complexity

2023-06-14 21:24 UTC, SansPapyrus683 commented on solutions/silver/cses-2185.mdx
> +	for (auto &i : a) cin >> i;
plz don't use auto

2023-06-14 21:24 UTC, SansPapyrus683 commented on solutions/silver/cses-2185.mdx
> +	ll a[K];
just use a vector

2023-06-14 21:24 UTC, SansPapyrus683 commented on solutions/silver/cses-2185.mdx
> +	ll N, K;
make these lowercase

2023-06-14 21:24 UTC, SansPapyrus683 commented on solutions/silver/cses-2185.mdx
> +		ll primeProduct = 1;
snake_case

2023-06-14 21:24 UTC, SansPapyrus683 commented on solutions/silver/cses-2185.mdx
> +	cout << ans << endl;
separate relevant segments w/ whitespace

2023-06-15 11:42 UTC, SansPapyrus683 commented on solutions/silver/cses-2185.mdx
> +ll a[MAX_K];
thought i asked for a vector

2023-06-15 22:13 UTC, SansPapyrus683 approved these changes

2023-06-17 22:09 UTC, ryanchou-dev approved these changes
yessir

2023-06-17 22:09 UTC, ryanchou-dev commented on solutions/silver/cses-2185.mdx
> +		//__builtin_popcount gives the number of 1's in binary representation,
multiline comment this?

2023-06-17 22:11 UTC, SansPapyrus683 commented on solutions/silver/cses-2185.mdx
> +		//__builtin_popcount gives the number of 1's in binary representation,
two lines is fine i think

2023-06-17 22:11 UTC, merged