added sol for usaco-1283
cpinitiative/usaco-guide pull request #3753
Opened 2023-06-17 23:01 UTC by Keys9873

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-06-18 05:10 UTC, SansPapyrus683 requested changes

2023-06-18 05:10 UTC, SansPapyrus683 commented on solutions/gold/usaco-1283.mdx
> +
```suggestion
```

2023-06-18 05:10 UTC, SansPapyrus683 commented on solutions/gold/usaco-1283.mdx
> +			        MOD;
break this up into intermediate values for precommit doesn't kill you

2023-06-18 05:10 UTC, SansPapyrus683 commented on solutions/gold/usaco-1283.mdx
> +	cin.tie(0);
you know the drill

2023-06-18 05:10 UTC, SansPapyrus683 commented on solutions/gold/usaco-1283.mdx
> +long long exp(long long x, long long y, long long p) {
group exp, factorial, inverse, choose, that crap
into combo functions codesnip

2023-06-19 00:19 UTC, SansPapyrus683 requested changes
could you uh use some vector art software to make the drawings look a bit more professional? it's fine if you can't, it's just i feel like your drawings kinda clash w/ the style of the guide

2023-06-19 00:19 UTC, SansPapyrus683 commented on solutions/gold/usaco-1283.mdx
> +// BeginCodeSnip{https://usaco.guide/gold/combo?lang=cpp}
```suggestion
// BeginCodeSnip{Combinatorics Functions (from module)}
```

2023-06-19 00:19 UTC, SansPapyrus683 commented on solutions/gold/usaco-1283.mdx
> +	for (auto &i : a) { cin >> i; }
```suggestion
	for (long long &i : a) { cin >> i; }
```

2023-06-19 08:42 UTC, SansPapyrus683 commented on solutions/gold/usaco-1283.mdx
> +The number of ways to split $\frac{a[i + 1}{2} - \frac{a[i]}{2}$ extra paths into $\frac{a[i]}{2}$ groups (that are potentially empty) is ${\frac{a[i + 1]}{2} - \frac{a[i]}{2} + \frac{a[i]}{2} - 1} \
what
why

2023-06-21 17:46 UTC, bqi343 commented on solutions/gold/usaco-1283.mdx
> +</Spoiler>
the deployment is failing because there is no beginning spoiler tag

2023-06-21 17:46 UTC, bqi343 commented on solutions/gold/usaco-1283/a.mdx
delete

2023-06-22 04:41 UTC, Keys9873 commented on solutions/gold/usaco-1283.mdx
> +The number of ways to split $\frac{a[i + 1}{2} - \frac{a[i]}{2}$ extra paths into $\frac{a[i]}{2}$ groups (that are potentially empty) is ${\frac{a[i + 1]}{2} - \frac{a[i]}{2} + \frac{a[i]}{2} - 1} \
is it better now?

2023-06-22 06:45 UTC, SansPapyrus683 commented
also idk if you checked the deployment
because your numbered list renders as "1." for both items 💀

2023-07-09 12:31 UTC, closed without merging