Added Python DFS code to Silver Graph Traversals
cpinitiative/usaco-guide pull request #3780
Opened 2023-07-01 20:36 UTC by Genius3435

Main changes
- DFS solutions work in Python when submitted in CPython3 (PyPy3 doesn't even pass with FastIO; I assume the JIT compiler is doing something suboptimal on that one testcase)
- Changed `visited` to `vis` for consistency

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [X] I have tested my code.
- [X] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-07-11 07:55 UTC, SansPapyrus683 requested changes

2023-07-11 07:55 UTC, SansPapyrus683 commented on content/3_Silver/Graph_Traversal.mdx
> +vector<bool> vis;
bruh.
change this back

2023-07-11 07:55 UTC, SansPapyrus683 commented on content/3_Silver/Graph_Traversal.mdx
> +def dfs(node):
type annotations + make the structure consistent w/ other langs

2023-07-11 07:55 UTC, SansPapyrus683 commented on content/3_Silver/Graph_Traversal.mdx
> +vector<bool> vis;
(everywhere else too)

2023-07-17 22:03 UTC, ryanchou-dev commented on content/3_Silver/Graph_Traversal.mdx
> +count_components()
```suggestion
rep = []

def dfs(node):
	vis[node] = True
	for u in adj[node]:
		if not vis[u]:
			dfs(u)

def count_components():
	for i in range(1, n + 1):
		if not vis[i]:
			rep.append(i)
			dfs(i)

count_components()
```

2023-07-17 22:03 UTC, ryanchou-dev commented on content/3_Silver/Graph_Traversal.mdx
> +for u in range(n):
```suggestion
color = [-1] * n

def dfs(node, col):
	color[node] = col
	for u in adj[node]:
		if color[u] == -1:
			dfs(u, col ^ 3)
		elif color[u] == col:
			print("IMPOSSIBLE")
			exit(0)

for u in range(n):
```

2023-07-17 22:03 UTC, ryanchou-dev commented on content/3_Silver/Graph_Traversal.mdx
>  # BeginCodeSnip{rest of solution}
```suggestion
# BeginCodeSnip{Rest of solution}
```

2023-08-01 04:40 UTC, closed without merging