add editorial for cf 1368D
cpinitiative/usaco-guide pull request #3781
Opened 2023-07-02 20:46 UTC by 876pol

_If any of the below don't apply to this Pull Request, mark the checkbox as done._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.

2023-07-11 00:30 UTC, ryanchou-dev reviewed
awesome :O

2023-07-11 00:30 UTC, ryanchou-dev commented on solutions/silver/cf-1368D.mdx
> +
it'd be great if you could structure these as hints! (see https://github.com/cpinitiative/usaco-guide/pull/3430)

2023-07-11 00:30 UTC, ryanchou-dev commented on solutions/silver/cf-1368D.mdx
> +	// array.
make multiline + even lines out?

2023-07-11 07:56 UTC, SansPapyrus683 requested changes
poggies

2023-07-11 07:56 UTC, SansPapyrus683 commented on solutions/silver/cf-1368D.mdx
> +	// array.
^

2023-07-11 07:56 UTC, SansPapyrus683 commented on solutions/silver/cf-1368D.mdx
> +class AndOrSquareSum {
```suggestion
public class AndOrSquareSum {
```

2023-07-11 07:56 UTC, SansPapyrus683 commented on solutions/silver/cf-1368D.mdx
> +		Scanner sc = new Scanner(System.in);
use bufferedreader/kattio for consistency

2023-07-11 07:56 UTC, SansPapyrus683 commented on solutions/silver/cf-1368D.mdx
> +	for j in range(20):
put in constant

2023-07-13 01:10 UTC, jessechoe10 commented on solutions/silver/cf-1368D.mdx
> +**Observation 2**: Notice that during each operation, the number and position of the set bits don't change. For instance, let $x = 110_2$, $y = 101_2$. $x \ AND \ y = 100_2$, and $x \ OR \ y = 111_2$
> the number and position of the set bits don't change
and
> Before and after the operation, there are two $1$ bits that are set, one $2$ bit that is set, and one $4$ bit that is set.
doesn't really make sense

2023-07-13 01:12 UTC, jessechoe10 commented on solutions/silver/cf-1368D.mdx
> +**Observation 1**: Notice that $x \ AND \ y + x \ OR \ y = x + y$, so the total sum of all the elements never changes.
It'd be great if you could prove this claim

2023-07-13 01:16 UTC, jessechoe10 commented on solutions/silver/cf-1368D.mdx
> +The optimal configuration can be built by handling each bit separately. This approach takes into account Observation 2, which states that no operations will alter the bits. For instance, consider the
> To structure this array optimally, move all the set bits to one end.

What does set bits mean and also explain exactly how the array is reconfigured given you provided an example

2023-07-13 01:16 UTC, jessechoe10 commented on solutions/silver/cf-1368D.mdx
> +The optimal configuration can be built by handling each bit separately. This approach takes into account Observation 2, which states that no operations will alter the bits. For instance, consider the
```suggestion
The optimal configuration can be built by handling each bit separately. This approach takes into account Observation 2, which states that no operations will alter the bits. For example, consider the array, `[1, 5, 4, 7, 3]`. In binary form, it is represented as `[001, 101, 100, 111, 011]`. To structure this array optimally, move all the set bits to one end. This results in the reconfigured array: `[000, 001, 101, 111, 111]`. In decimal form, this new array reads `[0, 1, 5, 7, 7]`. Finally, find the sum of squares of the elements in this new array. The resulting total provides the desired solution.
```

2023-07-13 01:18 UTC, jessechoe10 commented on solutions/silver/cf-1368D.mdx
> +	// Count the number of set bits at each position.
Reword this

2023-07-13 01:19 UTC, jessechoe10 commented on solutions/silver/cf-1368D.mdx
> +		// new array.
multiline + make each line even

2023-07-17 17:08 UTC, 876pol commented
i made a few changes to the explanation - lmk if some parts are still unclear

2023-07-17 22:00 UTC, ryanchou-dev commented on solutions/silver/cf-1368D.mdx
> +# the sum of the squares of the new array.
mutiline comment this

2023-07-17 23:03 UTC, SansPapyrus683 commented on solutions/silver/cf-1368D.mdx
> +# the sum of the squares of the new array.
if it's two lines it's fine

2023-07-19 18:19 UTC, jessechoe10 commented on solutions/silver/cf-1368D.mdx
> +Notice that before and after each operation, the amount of active bits at each position don't change.
```suggestion
Notice that before and after each operation, the number of active bits at each position don't change.
```

2023-07-19 18:19 UTC, jessechoe10 commented on solutions/silver/cf-1368D.mdx
> +- The second rightmost bit of $x$ is active, as well as the second rightmost bit of $x \ OR \ y$.
same here

2023-07-19 18:20 UTC, jessechoe10 commented on solutions/silver/cf-1368D.mdx
> +- The third rightmost bits of $x$ and $y$ are active, as well as the third rightmost bits of $x \ AND \ y$ and $x \ OR \ y$.
and here

2023-07-24 23:48 UTC, 876pol commented on solutions/silver/cf-1368D.mdx
> +Summing each of these bit positions gives us $x \ AND \ y + x \ OR \ y = x + y$.
i wasn't too sure how to draw it out as a venn diagram, but i added a truth table to make it more clear

2023-07-25 00:50 UTC, SansPapyrus683 commented
<img width="717" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/55369003/a0776476-b3ff-4256-a63a-c59805d27527">

💀

2023-07-26 02:47 UTC, 876pol commented
😳 should work now

2023-07-26 19:06 UTC, jessechoe10 approved these changes
I'll wait for Sans to approve before merging.

2023-08-06 07:33 UTC, ryanchou-dev reviewed
would be cool if you could use `&` and `|` to keep it consistent!

other than that, looks good. we rly don't need 3 content managers to approve, so ill merge afterwards :DD

2023-08-19 19:55 UTC, merged