Add Python Solution to CSES Playlist
cpinitiative/usaco-guide pull request #3874
Opened 2023-08-15 05:14 UTC by MartinLwx

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2023-08-16 16:46 UTC, SansPapyrus683 requested changes
yeah this is fine

2023-08-16 16:46 UTC, SansPapyrus683 commented on content/4_Gold/Sliding_Window.mdx
> +	"""This code is put in a function for performance reasons."""
does it tle outside of main?

2023-08-16 16:46 UTC, SansPapyrus683 commented on content/4_Gold/Sliding_Window.mdx
> +		# To maintain this invariant, shrink the window before inserting nums[right].
```suggestion
		# Notice that all the songs in `unique_songs` are unique in each iteration.
		# We keep this property by shrinking the window before inserting nums[right].
```

2023-08-17 01:24 UTC, MartinLwx commented on content/4_Gold/Sliding_Window.mdx
> +	"""This code is put in a function for performance reasons."""
yeah

2023-08-17 01:24 UTC, MartinLwx commented on content/4_Gold/Sliding_Window.mdx
> +		# To maintain this invariant, shrink the window before inserting nums[right].
Done!

2023-08-17 01:59 UTC, SansPapyrus683 approved these changes

2023-08-23 01:31 UTC, ryanchou-dev approved these changes
FIRE

2023-08-28 16:30 UTC, merged