Add faster solution for Just Stalling (usaco/1085)
cpinitiative/usaco-guide pull request #3947
Opened 2023-09-16 14:25 UTC by ChuangSheep

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2023-09-17 15:28 UTC, SansPapyrus683 requested changes
also why's this file in `gold`?

2023-09-17 15:28 UTC, SansPapyrus683 commented on solutions/gold/usaco-1085.mdx
> +pointers.
since this is in bronze
maybe link to the module?

2023-09-17 15:28 UTC, SansPapyrus683 commented on solutions/gold/usaco-1085.mdx
> +	vector<int> cows(n), stalls(n);
separate lines

2023-09-22 09:11 UTC, ChuangSheep commented
> also why's this file in `gold`?

lol cause it's somehow "combinatoric" I guess

2023-09-25 01:27 UTC, ryanchou-dev approved these changes

2023-09-25 01:27 UTC, ryanchou-dev commented on solutions/gold/usaco-1085.mdx
>  [Official Analysis](http://www.usaco.org/current/data/sol_prob3_bronze_jan21.html)
```suggestion
[Official Analysis (C++ and Java)](http://www.usaco.org/current/data/sol_prob3_bronze_jan21.html)
```

2023-09-26 16:40 UTC, merged