Add Implementation for CF-912E
cpinitiative/usaco-guide pull request #3948
Opened 2023-09-17 00:09 UTC by DenialRiver1434

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2023-09-17 04:38 UTC, SansPapyrus683 requested changes

2023-09-17 04:38 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +	for (auto e : enums) {
can you not use auto

2023-09-17 04:38 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +
```suggestion
```

2023-09-17 04:38 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +		if (MAX / x < odds[i]) break;  // prevent overflow
braces

2023-09-17 04:38 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +void dfsb(ll x, ll pos) {
plz use better names other than `dfsa` and `dfsb`

2023-09-17 04:38 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +	cin >> K;
rename to `n` and `k`

2023-09-17 04:38 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +	test(9);
magic #

2023-09-24 19:43 UTC, SansPapyrus683 requested changes

2023-09-24 19:43 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +		else evens.push_back(x);
braces

2023-09-24 19:43 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +	cin >> k;
```suggestion

	cin >> k;
```

2023-09-24 19:43 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +ll first_true(ll lo, ll hi) {
add link to binsearch module in a doc comment

2023-09-24 19:43 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +const ll MAX = 1e18;
max what?

2023-09-24 19:43 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +```cpp
```suggestion

```cpp
```

2023-09-25 01:26 UTC, ryanchou-dev requested changes

2023-09-25 01:26 UTC, ryanchou-dev commented on solutions/gold/cf-912E.mdx
> +[Official Editorial](https://codeforces.com/blog/entry/56920)
```suggestion
[Official Editorial (C++)](https://codeforces.com/blog/entry/56920)
```

2023-09-25 01:26 UTC, ryanchou-dev commented on solutions/gold/cf-912E.mdx
> +**Time Complexity:** $\mathcal{O}(\log 10^{18} \cdot (|D(A)| + |D(B)|))$
constant factors are omitted from big O right?

maybe add an `<Asterisk>` about it or a small note if it contributes a huge chunk of it?

2023-09-25 01:26 UTC, ryanchou-dev commented on solutions/gold/cf-912E.mdx
> +	// Pre-generate everything
elaborate?

2023-09-25 01:26 UTC, ryanchou-dev commented on solutions/gold/cf-912E.mdx
> +		if (MAX / x < odds[i]) break;  // prevent overflow
not fixed?

2023-09-25 03:18 UTC, DenialRiver1434 commented on solutions/gold/cf-912E.mdx
> +		if (MAX / x < odds[i]) break;  // prevent overflow
sorry I only fixed second one

2023-09-25 03:53 UTC, SansPapyrus683 approved these changes

2023-09-25 03:53 UTC, SansPapyrus683 commented on solutions/gold/cf-912E.mdx
> +/*
```suggestion
/**
```

2023-09-27 05:01 UTC, ryanchou-dev approved these changes

2023-09-27 05:01 UTC, merged

2023-09-27 05:01 UTC, ryanchou-dev commented
exquisite