Mo's algorithm Problem
cpinitiative/usaco-guide pull request #4023
Opened 2023-11-08 15:49 UTC by brebenelmihnea

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2023-11-08 18:00 UTC, SansPapyrus683 requested changes

2023-11-08 18:00 UTC, SansPapyrus683 commented on content/5_Plat/Sqrt.mdx
> +	for (int i = 1; i <= q; i++) {
is 1-indexing needed

2023-11-09 13:22 UTC, brebenelmihnea commented on content/5_Plat/Sqrt.mdx
> +};
Ok

2023-11-09 13:22 UTC, brebenelmihnea commented on content/5_Plat/Sqrt.mdx
> +	int BLOCK_SIZE = (int)sqrt(n);
Ok

2023-11-09 13:24 UTC, brebenelmihnea commented on content/5_Plat/Sqrt.mdx
> +vector<query> queries;
Ok

2023-11-09 13:29 UTC, brebenelmihnea commented on content/5_Plat/Sqrt.mdx
> +	for (int i = 1; i <= q; i++) {
All right

2023-11-09 15:28 UTC, SansPapyrus683 commented
bro why'd u revert all my changes :skull:

2023-11-09 15:31 UTC, brebenelmihnea commented
That was the fastest response :))
I will change it

2023-11-10 14:46 UTC, SansPapyrus683 approved these changes

2023-11-11 07:50 UTC, ryanchou-dev approved these changes
nicee

2023-11-11 14:33 UTC, merged