Fixed time-complexity in cses-1695.mdx
cpinitiative/usaco-guide pull request #4051
Opened 2023-11-26 12:35 UTC by Ayudh-65

Fixes #4050 
Modified usaco-guide/solutions/advanced/cses-1695.mdx

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2023-11-26 15:39 UTC, bqi343 approved these changes

2023-11-26 15:41 UTC, bqi343 requested changes
Actually, since the answer is at most $N$ and each call to `reachable()` takes $O(N^2)$, the time complexity is $O(N^3)$. This can easily be optimized to $O(NM)$.

2023-11-29 21:34 UTC, Ayudh-65 commented
That's right. So the time complexity of the given solution is $O(n^3)$?

2023-11-30 00:21 UTC, bqi343 commented
yes

2023-12-01 01:12 UTC, bqi343 approved these changes

2023-12-01 01:18 UTC, merged