Delegation (Platinum)
cpinitiative/usaco-guide pull request #4111
Opened 2023-12-25 14:40 UTC by envyaims

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2023-12-25 14:40 UTC, envyaims commented
Nerfed from Very Hard to Normal (fight me)

2023-12-25 14:44 UTC, SansPapyrus683 commented
> Nerfed from Very Hard to Normal (fight me)

change it back or no merge for you

2023-12-25 14:44 UTC, envyaims commented
it's suitable

2023-12-25 14:45 UTC, envyaims commented
this wasn't even much harder than the gold one. Exact same observations (just an extra binary search)

2023-12-25 14:46 UTC, SansPapyrus683 requested changes

2023-12-25 14:46 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1020.mdx
> +const int N = 1e5 + 5;
you know what to do

2023-12-25 14:46 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1020.mdx
> +We want to maximize $\mathtt{toBeMerged[i]}$ while evenly pairing all of the children with path lengths $\geq k$. To do this, we can run another binary search over the unpaired path lengths of the ch
> condition  holds

spacing

2023-12-25 14:46 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1020.mdx
> +		if (r == remove) r--;
braces

2023-12-25 14:46 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1020.mdx
> +The following code will also AC because USACO has poo poo test cases, but it is technically $\mathcal{O}(N^2 \log N)$. It exploits the fact that we can break early once we found an index to remove an
> poo poo test cases

💀

2023-12-25 14:46 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1020.mdx
> +```cpp
tell them what you changed here

2023-12-25 14:47 UTC, envyaims commented on solutions/platinum/usaco-1020.mdx
> +```cpp
i did?

2023-12-25 16:08 UTC, SansPapyrus683 commented on solutions/platinum/usaco-1020.mdx
> +```cpp
like in the code

2023-12-25 23:25 UTC, SansPapyrus683 commented
made some modifications, can you test em for me

2023-12-26 01:17 UTC, ryanchou-dev approved these changes

2023-12-27 23:34 UTC, envyaims commented
> made some modifications, can you test em for me

seems fine

2023-12-28 14:38 UTC, merged