add python solution to usaco-788
cpinitiative/usaco-guide pull request #4183
Opened 2024-01-06 17:51 UTC by 876pol

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2024-01-06 18:11 UTC, SansPapyrus683 requested changes

2024-01-06 18:11 UTC, SansPapyrus683 commented on solutions/silver/usaco-788.mdx
> +# Function to search all vertices that can be reached through the current vertex v
use docstring

2024-01-06 18:11 UTC, SansPapyrus683 commented on solutions/silver/usaco-788.mdx
> +num_reachable = 0
you can put these variables above the `with` blocks imo
also `threshold` here is unnecessary

2024-01-07 04:02 UTC, SansPapyrus683 approved these changes
:fire:

2024-01-07 07:03 UTC, ryanchou-dev approved these changes
fire

2024-01-07 07:04 UTC, merged