suffix array
cpinitiative/usaco-guide pull request #4232
Opened 2024-01-18 04:17 UTC by SansPapyrus683

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

no one reads this anyways
might add other languages if i'm feeling up to it

2024-01-18 07:40 UTC, ryanchou-dev submitted a review, later dismissed
wowowow kevin carrying usaco.guide 🔥🔥🔥

very cool content, tables look great!

2024-01-20 03:43 UTC, envyaims approved these changes
this is cool

2024-01-20 04:32 UTC, danielzsh requested changes

2024-01-20 04:32 UTC, danielzsh commented on content/6_Advanced/Suffix_Array.mdx
> +This acts as a tiebreaker of sorts and will ensure we never hit the end of a suffix while comparing two suffixes.
english teacher ahh comment but "of sorts" is repeated twice in close proximity 😅

2024-01-20 04:32 UTC, danielzsh commented on content/6_Advanced/Suffix_Array.mdx
> +| b      | `????` |
Why are both strings `????`? should we provide an example instead?

2024-01-20 04:32 UTC, danielzsh commented on content/6_Advanced/Suffix_Array.mdx
> +| 0         | 7      | `$abcbcba`	     |
umm what happened to the `|` on the right

2024-01-20 04:32 UTC, danielzsh commented on content/6_Advanced/Suffix_Array.mdx
> +Well, the cool thing is that since we just sorted *all* suffixes by the first $2$, we actually have information about the right halves already!
do we? doesn't this give us info about the left halves?

2024-01-20 05:08 UTC, ryanchou-dev approved these changes

2024-01-20 05:44 UTC, danielzsh approved these changes
we up 🔥

2024-01-20 06:24 UTC, merged