Add java solution for CSES Four Sum
cpinitiative/usaco-guide pull request #4239
Opened 2024-01-19 20:02 UTC by andreionoie

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2024-01-19 23:03 UTC, SansPapyrus683 requested changes

2024-01-19 23:03 UTC, SansPapyrus683 commented on solutions/gold/cses-1642.mdx
> +		final Scanner s = new Scanner(System.in);
use `BufferedReader` or `Kattio` for consistency

2024-01-19 23:03 UTC, SansPapyrus683 commented on solutions/gold/cses-1642.mdx
> +		final int[] arr = new int[n + 1];  // 1-indexed array for this problem
`final` not needed

2024-01-19 23:03 UTC, SansPapyrus683 commented on solutions/gold/cses-1642.mdx
> +		final Map<Integer, String> twoSum = new HashMap<>();
yeah

2024-01-19 23:03 UTC, SansPapyrus683 commented on solutions/gold/cses-1642.mdx
> +					                   " " + j);
the line wrapping is ugly- put the result in a variable first, perhaps?

2024-01-19 23:03 UTC, SansPapyrus683 commented on solutions/gold/cses-1642.mdx
> +				twoSum.put(arr[i] + arr[j], i + " " + j);
braces

2024-01-19 23:03 UTC, IDON-TEXIST requested changes

2024-01-19 23:03 UTC, IDON-TEXIST commented on solutions/gold/cses-1642.mdx
> +					                   " " + j);
This looks worse than just going a couple characters over 80.

2024-01-21 21:06 UTC, SansPapyrus683 approved these changes

2024-01-21 22:23 UTC, IDON-TEXIST approved these changes

2024-01-21 23:16 UTC, merged