fix Announcements
cpinitiative/usaco-guide pull request #4241
Opened 2024-01-20 23:21 UTC by shaubby

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x ] I have tested my code.
- [ x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ x] I have linked this PR to any issues that it closes.

Task 1: Swap the order of the announcements and Active problems/modules sections on /dashboard

Task 2: Redirect the home page to dashboard if the user is signed in. Reference this PR: https://github.com/cpinitiative/usaco-guide/pull/3689/files

Task 3: Make the text color and background color of the welcome back card the same as the active problems/modules cards

2024-01-20 23:42 UTC, mjh316 approved these changes
LGTM, ty! @SansPapyrus683 @ryanchou-dev You guys good with how it looks and affects guide? Also, any thoughts on whether we should add an "escape hatch" for those logged but still want to access the home page? like vercel.com/home iirc

2024-01-21 00:02 UTC, shaubby commented
> LGTM, ty! @SansPapyrus683 @ryanchou-dev You guys good with how it looks and affects guide? Also, any thoughts on whether we should add an "escape hatch" for those logged but still want to access the home page? like vercel.com/home iirc

im thinking maybe we should make it so if you click on the usaco guide icon from the dashboard it doesnt automatically redirect so people can view the landing page

2024-01-21 00:08 UTC, mjh316 commented
I think that's a good idea - so in routing if like previous page was /dashboard we don't redirect, because most people coming to home from dashboard probably want to go to home. @shaubby Do you think you could impl this?

2024-01-21 00:10 UTC, mjh316 requested changes

2024-01-21 00:10 UTC, mjh316 commented on src/pages/index.tsx
> +    if (firebaseUser) {
As mentioned, add some check for if the last page (page that the user navigated from) is NOT /dashboard, and then if so, we navigate.

2024-01-21 03:56 UTC, shaubby commented
> I think that's a good idea - so in routing if like previous page was /dashboard we don't redirect, because most people coming to home from dashboard probably want to go to home. @shaubby Do you think you could impl this?

yeah i think i could

2024-01-21 20:35 UTC, SansPapyrus683 approved these changes
very poggers pr

2024-01-22 04:24 UTC, shaubby commented
@mjh316 hows this

2024-01-22 05:10 UTC, mjh316 requested changes

2024-01-22 05:10 UTC, mjh316 commented on src/pages/dashboard.tsx
> +        <TopNavigationBar linkLogoToIndex={true} dashboard={true} />
@shaubby Whoops, I don't know if it pinged but here you go

2024-01-23 02:11 UTC, shaubby commented
Yeah im not gonna lie, it was late at night when i wrote this and i have no clue how and why it worked, but it should make sense not.
The dashboard prop is passed to the topnavigationbar to let it know that we are on the dashboard, and if you click on the usaco guide icon in the corner, it will pass the dashboard information to the location.state.redirect. Then, on the dashboard, if location.state.redirect = false, it will not automativally redirect to the dashboard. The try catch if in case the user goes straight to the landing page without coming from another page on usaco guide, location.state.redirect will not exist, and it will throw an TypeError: Cannot read properties of null exception, the try catch counteracts that.

@mjh316

2024-01-23 02:22 UTC, mjh316 commented
@shaubby That makes sense, could you quickly leave some documentation for the relevant props (maybe change dashboard to "noRedirectToDashboard" or something in case we want to reuse?) and then ping me to approve? Thank you!

2024-01-23 02:38 UTC, shaubby commented
> @shaubby That makes sense, could you quickly leave some documentation for the relevant props (maybe change dashboard to "noRedirectToDashboard" or something in case we want to reuse?) and then ping me to approve? Thank you!

Where do you want me to leave documentation,
I went ahead and renamed it @mjh316

2024-01-23 02:39 UTC, mjh316 commented
@shaubby In the useEffect (e.g.) why try catch

2024-01-23 03:49 UTC, shaubby commented
@mjh316 I mentioned this in my other comment, but it is in case the user opens a link straight to the landing page, and does not come from clicking the icon in the corner of the usaco guide, trying to access location.state.redirect will give the error TypeError: Cannot read properties of null exception, the try catch defaults to redirecting the user if location.state.redirect is undefined.

2024-01-23 04:02 UTC, mjh316 commented
@shaubby To clarify, I understand that you mentioned it in your other comment, I meant that it'd be great if you could document the code with comments in the useEffect and try catch area.

2024-01-23 05:06 UTC, ryanchou-dev commented
> LGTM, ty! @SansPapyrus683 @ryanchou-dev You guys good with how it looks and affects guide? Also, any thoughts on whether we should add an "escape hatch" for those logged but still want to access the home page? like vercel.com/home iirc

i believe you can toggle between the screens logged in by clicking the usaco.guide icon

2024-01-24 04:03 UTC, shaubby commented
Oh ok, I didnt get what you meant the first time,
I added the comments, is this ok?
@mjh316

2024-01-24 08:10 UTC, mjh316 approved these changes

2024-01-24 08:11 UTC, merged

2024-01-24 21:49 UTC, SansPapyrus683 commented
:skull: