Solution for max product
cpinitiative/usaco-guide pull request #4299
Opened 2024-02-10 03:51 UTC by danielzsh

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._
Solution purposely leaves out details to encourage more thinking, although if reader is truly stuck they can consult implementation
- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2024-02-10 03:57 UTC, SansPapyrus683 requested changes
W pr

2024-02-10 03:57 UTC, SansPapyrus683 commented on solutions/gold/cf-100886G.mdx
> +</Spoiler>
uh

2024-02-10 03:57 UTC, SansPapyrus683 commented on solutions/gold/cf-100886G.mdx
> +using ll = long long;
would really appreciate if you didn't use macros

2024-02-10 03:57 UTC, SansPapyrus683 commented on solutions/gold/cf-100886G.mdx
> +	while (l.size() < r.size()) l.insert(l.begin(), '0');
braces

2024-02-10 03:57 UTC, SansPapyrus683 commented on solutions/gold/cf-100886G.mdx
> +		// which contradicts our assumption that the LCP has length i
```cpp
/*
 * yknow, multiline comments
 * are pretty cool
 * in situations like these
 */
```

2024-02-10 03:57 UTC, SansPapyrus683 commented on solutions/gold/cf-100886G.mdx
> +// and returns -1 for empty string
when describing functions, i'd like if you used docstrings
```suggestion
/** @return product of the given string's digits (-1 if empty) */
```

2024-02-10 04:35 UTC, SansPapyrus683 commented on solutions/gold/cf-100886G.mdx
> +	if (!s.length()) return -1;
braces everywehre

2024-02-10 04:35 UTC, SansPapyrus683 commented
(also did you revert my changes or smth)

2024-02-10 04:36 UTC, danielzsh commented
Oh shoot I was just using the usaco.guide github thing and i think it overwrites changes 😭 mb

2024-02-10 06:07 UTC, SansPapyrus683 approved these changes
@ryanchou-dev merge at your recognizance

2024-02-12 15:17 UTC, ryanchou-dev approved these changes
looks good! thanks :)

2024-02-12 15:17 UTC, merged