Update Func_Graphs.mdx
cpinitiative/usaco-guide pull request #4335
Opened 2024-02-21 14:49 UTC by abhideepd

adding the additional solution, below solution 2

Previous pr reference: https://github.com/cpinitiative/usaco-guide/pull/4331#issuecomment-1953027997

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes. https://github.com/cpinitiative/usaco-guide/issues/4330

2024-02-21 16:40 UTC, danielzsh submitted a review, later dismissed

2024-02-21 17:15 UTC, SansPapyrus683 commented
you don't have to make a new pr each time, just commit and push your changes to the og pr

2024-02-21 17:17 UTC, SansPapyrus683 requested changes

2024-02-21 17:17 UTC, SansPapyrus683 commented on content/3_Silver/Func_Graphs.mdx
> +	    new BufferedReader(new InputStreamReader(System.in));
move this in `main`

2024-02-21 17:17 UTC, SansPapyrus683 commented on content/3_Silver/Func_Graphs.mdx
> +	static void getAnswer(int arr[], int n) {
this too

2024-02-21 17:17 UTC, SansPapyrus683 commented on content/3_Silver/Func_Graphs.mdx
> +containing `x` without using adjacency lists.
what do you use in place of adj lists?

2024-02-21 17:54 UTC, danielzsh commented
By the way, @abhideepd make sure to copy the latest changes on this branch into the editor before making further edits so you don't accidentally override our edits; the editor doesn't auto-pull yet 😓

2024-02-22 06:51 UTC, closed without merging

2024-02-22 06:53 UTC, abhideepd commented
> you don't have to make a new pr each time, just commit and push your changes to the og pr

sure will do, hence forth.
pardon me, new to git, still a noob 😅

2024-02-22 06:54 UTC, abhideepd commented
> By the way, @abhideepd make sure to copy the latest changes on this branch into the editor before making further edits so you don't accidentally override our edits; the editor doesn't auto-pull yet 😓

sure will do it, still a noob in bit 😅. 
I wasn't able to use the editor though, edited directly on github itself.

2024-02-22 07:37 UTC, abhideepd commented
shit, i closed it again, by mistake 😓 my bad, while synching my fork, i removed all my commits. sorry, a new pr is coming ahead