feature: Added C++ solution for USACO-380
cpinitiative/usaco-guide pull request #4413
Opened 2024-03-27 06:21 UTC by naveen-khuntey

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2024-03-27 14:42 UTC, SansPapyrus683 requested changes
you can do all this or just have me make the changes for you

2024-03-27 14:42 UTC, SansPapyrus683 commented on solutions/silver/usaco-380.mdx
> +#define MAX 501
is this +1 necessary

2024-03-27 14:42 UTC, SansPapyrus683 commented on solutions/silver/usaco-380.mdx
> +				//    push the cell into the queue
```cpp
/*
 * use multiline comments
 * for thngs like these
 */
```

2024-03-27 14:42 UTC, SansPapyrus683 commented on solutions/silver/usaco-380.mdx
> +		for (int j = 0; j < n; j++) cin >> grid[i][j];
braces

2024-03-27 14:42 UTC, SansPapyrus683 commented on solutions/silver/usaco-380.mdx
> +	cout << l << "\n";
```suggestions
	cout << l << endl;
```

2024-03-27 17:01 UTC, naveen-khuntey commented
I have applied all the changes.

2024-03-27 17:06 UTC, naveen-khuntey commented
I have applied all the changes.

2024-03-27 20:48 UTC, SansPapyrus683 commented
i feel like this can go a lot faster if you just allow me to format your code
so can i?

2024-03-28 02:15 UTC, naveen-khuntey commented
Yes please go ahead

2024-03-28 05:27 UTC, SansPapyrus683 submitted a review, later dismissed

2024-03-28 05:38 UTC, ryanchou-dev approved these changes
looks great! thanks for the contribution :yayy:

2024-03-28 06:10 UTC, merged