Update solutions/gold/sumdiv.mdx
cpinitiative/usaco-guide pull request #4415
Opened 2024-03-28 12:42 UTC by Harshit1927

The previous code for giving WA on the problem, linked correct code which gets AC and updated the explanation for the problem.

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2024-03-28 14:42 UTC, SansPapyrus683 commented
@brebenelmihnea uuuuhhh

2024-03-28 19:14 UTC, brebenelmihnea approved these changes
Nice work.

2024-03-28 20:34 UTC, SansPapyrus683 requested changes

2024-03-29 06:37 UTC, Harshit1927 commented on solutions/gold/sumdiv.mdx
> +         ll &y) {  // Extended euclidean gcd algorithm to find modular inverse
> weird formatting, put comment on top of function?

Is the formatting correct now?

2024-03-29 14:30 UTC, SansPapyrus683 commented
alright did some formatting myself, can you check to see if the code still works?

2024-03-29 14:38 UTC, Harshit1927 commented
> alright did some formatting myself, can you check to see if the code still works?

yes, it works

2024-03-29 18:39 UTC, SansPapyrus683 approved these changes

2024-03-29 18:39 UTC, merged