Update DNQ
cpinitiative/usaco-guide pull request #4435
Opened 2024-04-10 02:35 UTC by RadialFunc

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x ] I have tested my code.
- [x ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x ] I have linked this PR to any issues that it closes.

2024-04-10 16:52 UTC, SansPapyrus683 commented
is this for a bounty

2024-04-10 17:39 UTC, RadialFunc commented
it is

2024-04-10 17:42 UTC, SansPapyrus683 commented
![image](https://github.com/cpinitiative/usaco-guide/assets/55369003/4277e26e-f07e-4d9f-b832-57720666bb17)

this part doesn't seem addressed

2024-04-11 16:43 UTC, RadialFunc commented
ok i think i added the code

2024-04-11 17:50 UTC, SansPapyrus683 requested changes
have you seen my standards before?

2024-04-11 17:50 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +const int INF = 1e18;
use INT32_MAX

2024-04-11 17:50 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +
![image](https://github.com/cpinitiative/usaco-guide/assets/55369003/eaa669ad-4cc1-44ac-ac66-83e377833197)

2024-04-11 17:50 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +V<vi> dp(8, vi(1001,INF));
magic numbers

2024-04-11 17:50 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +signed main(){
```suggestion

int main() {
```

2024-04-11 17:50 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +		a[i+n] = a[i];
spaces between operators

2024-04-11 17:50 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +			for(int j=0; j<n; j++) dp[i][j] = INF;
braces

2024-04-11 18:05 UTC, RadialFunc commented
i fixed everything

2024-04-11 18:42 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +// most array sizes will be doubled to prevent out of bounds
uuuhhh what

2024-04-11 18:42 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +```cpp
oh yeah use language section

2024-04-12 01:38 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +const int INF = 1e18;
oops

2024-04-12 01:42 UTC, SansPapyrus683 requested changes
i'd say we're 70% there

2024-04-12 01:42 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +const int maxk = 7;
rename to `MAX_N`a dn `MAX_K` respectively

2024-04-12 01:42 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +	// dp[i][j] stores the answer for doors 0,1,.., j and i doors open
put this at the top of `dp`?

2024-04-12 01:42 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +	if (begin == end) return;
braces

2024-04-12 01:42 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +	ll bestcost = INF;
just `best` is fine

2024-04-12 02:28 UTC, SansPapyrus683 commented on content/5_Plat/DC-DP.mdx
> +const int INF = 1e18;
don't think this was addressed?

2024-04-12 02:40 UTC, SansPapyrus683 approved these changes
send ss of updated code AC and we're good

2024-04-12 03:59 UTC, ryanchou-dev approved these changes
good 👍

2024-04-12 04:20 UTC, merged