problem finding borders added
cpinitiative/usaco-guide pull request #4452
Opened 2024-04-22 05:19 UTC by pratik-2707

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2024-04-22 11:43 UTC, pratik-2707 commented
I am not getting where this is going wrong ,any help please

2024-04-22 13:50 UTC, SansPapyrus683 commented
@brebenelmihnea do you think this is a good focus problem?

2024-04-23 23:24 UTC, envyaims commented
> @brebenelmihnea do you think this is a good focus problem?

i think its fine

2024-04-24 02:36 UTC, SansPapyrus683 commented
also for the deployment see how focus problems are supposed to be added, i think this modules has other focus problems that you can look to as an example

2024-04-24 03:53 UTC, pratik-2707 commented
this is the issue i am facing 
error Problem cses-1732 claims to have an internal solution but doesn't

what exactly internal solution means ?

2024-04-24 05:24 UTC, SansPapyrus683 commented
> i think this modules has other focus problems that you can look to as an example

2024-05-05 18:31 UTC, ryanchou-dev requested changes

2024-05-05 18:31 UTC, ryanchou-dev commented on content/6_Advanced/String_Search.mdx
> +
time complexity?

2024-05-05 18:31 UTC, ryanchou-dev commented on content/6_Advanced/String_Search.mdx
> +	return 0;
```suggestion
```

2024-05-05 18:31 UTC, ryanchou-dev commented on content/6_Advanced/String_Search.mdx
> +```cpp
can you send ss of this code acing?

2024-05-05 18:31 UTC, ryanchou-dev commented on content/6_Advanced/String_Search.mdx
> +	int p[n] = {0};
use vectors for variable-sized arrays

2024-05-24 01:35 UTC, closed without merging