Added Python Solution for Concert Tickets
cpinitiative/usaco-guide pull request #4474
Opened 2024-05-16 12:30 UTC by freakin23

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2024-05-16 13:57 UTC, SansPapyrus683 requested changes

2024-05-16 13:57 UTC, SansPapyrus683 commented on solutions/silver/cses-1091.mdx
> +
there's an author field at the top of the file

2024-05-16 13:57 UTC, SansPapyrus683 commented on solutions/silver/cses-1091.mdx
> +def get_endpoint(idx):
type annotations

2024-05-16 16:46 UTC, SansPapyrus683 commented
massive
can you send screenshot of ac

2024-05-16 16:48 UTC, freakin23 commented
> massive can you send screenshot of ac

![Screenshot from 2024-05-16 22-17-52](https://github.com/cpinitiative/usaco-guide/assets/79394137/29919803-dd4e-420b-839f-ba225bd56a71)

2024-05-16 18:56 UTC, SansPapyrus683 approved these changes

2024-05-17 02:33 UTC, ryanchou-dev approved these changes

2024-05-17 02:33 UTC, merged

2024-05-17 02:34 UTC, ryanchou-dev commented
awesome, thanks!