[Editorial] Stars and Bars
cpinitiative/usaco-guide pull request #4530
Opened 2024-06-17 13:24 UTC by brebenelmihnea

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [ ] I have tested my code.
- [ ] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [ ] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2024-06-17 13:53 UTC, brebenelmihnea commented
AC proof

https://www.spoj.com/status/MARBLES,mihnea/

<img width="870" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/59292725/db316c33-1c2b-4929-8610-e6a6889f3e39">

2024-06-17 13:58 UTC, envyaims approved these changes
i mean.. i would rather you put a more interesting problem for sample rather than literally what stars and bars is but other than that lgtm

2024-06-18 01:43 UTC, SansPapyrus683 requested changes

2024-06-18 01:43 UTC, SansPapyrus683 commented on content/4_Gold/Combinatorics.mdx
> +distinguishable **non-empty** boxes is: $\binom{n-1}{k-1}$
put this above the problem..

2024-06-18 01:43 UTC, SansPapyrus683 commented on content/4_Gold/Combinatorics.mdx
> +non-empty. Thus, the answer is obtained by the second formula: $\binom{n-1}{k-1}$
and this in the explanation header

2024-06-18 01:43 UTC, SansPapyrus683 commented on content/4_Gold/Combinatorics.mdx
> +		return ans;
just make this its own function

2024-06-18 01:43 UTC, SansPapyrus683 commented on content/4_Gold/Combinatorics.mdx
> +	cin >> T;
rename to `test_num`

2024-06-18 02:21 UTC, envyaims commented on content/4_Gold/Combinatorics.mdx
> +	cin >> T;
💀

2024-06-18 04:41 UTC, brebenelmihnea commented on content/4_Gold/Combinatorics.mdx
> +distinguishable **non-empty** boxes is: $\binom{n-1}{k-1}$
done

2024-06-18 04:41 UTC, brebenelmihnea commented on content/4_Gold/Combinatorics.mdx
> +		return ans;
done

2024-06-18 04:41 UTC, brebenelmihnea commented on content/4_Gold/Combinatorics.mdx
> +non-empty. Thus, the answer is obtained by the second formula: $\binom{n-1}{k-1}$
ok

2024-06-18 04:42 UTC, brebenelmihnea commented on content/4_Gold/Combinatorics.mdx
> +	cin >> T;
done

2024-06-18 05:07 UTC, ryanchou-dev approved these changes
like envy said, would recommend a more interesting problem

2024-06-18 05:07 UTC, ryanchou-dev commented on content/4_Gold/Combinatorics.mdx
> +	if (k > n - k) k = n - k;
braces

2024-06-18 07:33 UTC, brebenelmihnea commented on content/4_Gold/Combinatorics.mdx
> +	if (k > n - k) k = n - k;
done

2024-06-18 08:52 UTC, SansPapyrus683 approved these changes
formatting seems fine lol

2024-06-18 08:54 UTC, merged