cf581D- Solution added in Java and Python
cpinitiative/usaco-guide pull request #4555
Opened 2024-06-26 06:10 UTC by shuklaji23

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2024-06-26 08:24 UTC, shuklaji23 commented
Sure, @SansPapyrus683 here is the link to the accepted submissions on codeforces.

2024-06-26 13:13 UTC, SansPapyrus683 requested changes

2024-06-26 13:13 UTC, SansPapyrus683 commented on solutions/bronze/cf-581D.mdx
> +		char let[] = new char[] {'A', 'B', 'C'};
```suggestion
		char[] let = new char[] {'A', 'B', 'C'};
```
same for other array declarations

2024-06-26 13:13 UTC, SansPapyrus683 commented on solutions/bronze/cf-581D.mdx
> +			io.flush();
flush not needed

2024-06-26 13:13 UTC, SansPapyrus683 commented on solutions/bronze/cf-581D.mdx
> +		io.flush();
sae here

2024-06-26 13:13 UTC, SansPapyrus683 commented on solutions/bronze/cf-581D.mdx
> +while n**2 < n2:
```suggestion
while n * n < n2:
```

2024-06-26 13:13 UTC, SansPapyrus683 commented on solutions/bronze/cf-581D.mdx
> +if l[2][0] != n:
space out your code please

2024-06-28 04:18 UTC, shuklaji23 commented
@SansPapyrus683 Made all the requested changes. Please let me know if any other change is required.

2024-06-28 23:10 UTC, SansPapyrus683 approved these changes
crappy problem anyways, who cares

2024-06-29 02:38 UTC, ryanchou-dev reviewed
could you add comments? otherwise looks OK

2024-07-01 12:25 UTC, SansPapyrus683 commented
unfortunately i think we'll be taking #4569 over this, sorry about that!
feel free to submit prs for other problems tho :)

2024-07-01 12:25 UTC, closed without merging