py sol for cf-1851F
cpinitiative/usaco-guide pull request #4718
Opened 2024-08-27 08:09 UTC by freakin23

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2024-08-27 08:09 UTC, freakin23 commented
AC: https://codeforces.com/contest/1851/submission/278352706

2024-08-27 15:31 UTC, SansPapyrus683 requested changes

2024-08-27 15:31 UTC, SansPapyrus683 commented on solutions/silver/cf-1851F.mdx
> +	for i in range(n - 1):
can you make the names in line w/ c++

2024-08-27 15:31 UTC, SansPapyrus683 commented on solutions/silver/cf-1851F.mdx
> +		"{} {} {}".format(
f-strings exist

2024-08-27 15:57 UTC, freakin23 commented on solutions/silver/cf-1851F.mdx
> +	for i in range(n - 1):
done

2024-08-27 15:57 UTC, freakin23 commented on solutions/silver/cf-1851F.mdx
> +		"{} {} {}".format(
ok

2024-08-27 17:00 UTC, freakin23 commented
AC: https://codeforces.com/contest/1851/submission/278411536

2024-08-28 21:50 UTC, SansPapyrus683 approved these changes

2024-08-28 21:57 UTC, merged