py sol for matching
cpinitiative/usaco-guide pull request #4781
Opened 2024-09-13 15:26 UTC by freakin23

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2024-09-13 15:27 UTC, freakin23 commented
AC: https://atcoder.jp/contests/dp/submissions/57707254

2024-09-13 18:04 UTC, SansPapyrus683 requested changes

2024-09-13 18:04 UTC, SansPapyrus683 commented on solutions/gold/ac-matching.mdx
> +N = int(input())
rename to `n`

2024-09-13 18:04 UTC, SansPapyrus683 commented on solutions/gold/ac-matching.mdx
> +MOD = int(1e9 + 7)
```suggestion
MOD = 10 ** 9 + 7
```

2024-09-13 18:04 UTC, SansPapyrus683 commented on solutions/gold/ac-matching.mdx
> +MAX_N = 21
21? or just 20?

2024-09-13 18:07 UTC, freakin23 commented on solutions/gold/ac-matching.mdx
> +MAX_N = 21
It was 21 in C++ version

2024-09-14 05:00 UTC, freakin23 commented on solutions/gold/ac-matching.mdx
> +N = int(input())
done

2024-09-14 05:01 UTC, freakin23 commented
AC: https://atcoder.jp/contests/dp/submissions/57717496

2024-09-15 00:07 UTC, SansPapyrus683 approved these changes

2024-09-15 00:07 UTC, merged