py sol for elevator rides
cpinitiative/usaco-guide pull request #4782
Opened 2024-09-13 16:32 UTC by freakin23

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2024-09-13 16:34 UTC, freakin23 commented
AC:
![Screenshot from 2024-09-13 22-02-55](https://github.com/user-attachments/assets/a512111b-a9f4-4394-a4b3-ec534bc386be)
![Screenshot from 2024-09-13 22-03-03](https://github.com/user-attachments/assets/dfeef4a9-dd2a-4a9e-9dea-ab706a8b583d)

2024-09-13 18:03 UTC, SansPapyrus683 requested changes

2024-09-13 18:03 UTC, SansPapyrus683 commented on solutions/gold/cses-1653.mdx
> +people, maxWeight = map(int, input().split())
python uses snake_case

2024-09-13 18:03 UTC, SansPapyrus683 commented on solutions/gold/cses-1653.mdx
> +for mask in range(1, (1 << people)):
unnecessary parens

2024-09-13 18:09 UTC, freakin23 commented on solutions/gold/cses-1653.mdx
> +people, maxWeight = map(int, input().split())
Sorry, it just slips

2024-09-14 03:17 UTC, ryanchou-dev approved these changes
address kevin's comments first, but yeah looks good

2024-09-14 05:00 UTC, freakin23 commented
AC:
![Screenshot from 2024-09-14 10-29-33](https://github.com/user-attachments/assets/842e0a56-3b8a-4273-971d-bfb34dcde6de)
![Screenshot from 2024-09-14 10-29-39](https://github.com/user-attachments/assets/9d82ef8b-e3c1-456a-82bd-1ecd78897795)

2024-09-15 00:07 UTC, SansPapyrus683 approved these changes

2024-09-15 00:07 UTC, merged