C++ code rfc / py sol for max collinear
cpinitiative/usaco-guide pull request #4876
Opened 2024-10-28 15:56 UTC by freakin23

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

AC (C++): https://open.kattis.com/submissions/14757865
AC (Py): https://open.kattis.com/submissions/14757862

2024-10-28 23:59 UTC, SansPapyrus683 requested changes
freakin i'm curious if you actually know what "rfc" means

2024-10-28 23:59 UTC, SansPapyrus683 commented on solutions/platinum/kattis-maxcolinear.mdx
> +	mp = defaultdict(int)
better name

2024-10-29 03:37 UTC, freakin23 commented
> freakin i'm curious if you actually know what "rfc" means

'refactoring`

2024-10-29 03:46 UTC, freakin23 commented on solutions/platinum/kattis-maxcolinear.mdx
> +	mp = defaultdict(int)
done.

2024-10-29 04:11 UTC, freakin23 commented
AC (Py): https://open.kattis.com/submissions/14762546
AC (C++): https://open.kattis.com/submissions/14762545

2024-10-29 04:17 UTC, SansPapyrus683 commented
oh
usually it means this: https://en.wikipedia.org/wiki/Request_for_Comments

2024-10-29 04:19 UTC, SansPapyrus683 approved these changes

2024-10-29 04:20 UTC, freakin23 commented
> oh usually it means this: https://en.wikipedia.org/wiki/Request_for_Comments

It's my first time looking at this.

2024-10-29 04:25 UTC, merged