py sols for Cowpatibility
cpinitiative/usaco-guide pull request #4907
Opened 2024-11-06 14:05 UTC by freakin23

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2024-11-06 18:41 UTC, SansPapyrus683 requested changes

2024-11-06 18:46 UTC, freakin23 commented on content/5_Plat/PIE.mdx
> +</Warning>
Changed.

2024-11-07 01:39 UTC, envyaims approved these changes
i like my cheese drippy bruh 🔥

2024-11-07 04:27 UTC, SansPapyrus683 approved these changes

2024-11-07 04:33 UTC, merged