Icy Perimeter Editorial
cpinitiative/usaco-guide pull request #4967
Opened 2024-12-07 05:04 UTC by JoltedCowIceCream

- added editorial to problem solution
- rewrote c++/java/python solutions so they are all consistent in implementation/comments/structure
- fixed python solution to pass ALL test cases (old solution TLE)

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [x] I have linked this PR to any issues that it closes.

2024-12-07 05:08 UTC, TheGamingMousse commented
🐐 🐐 🐐

2024-12-07 05:23 UTC, TheGamingMousse commented on solutions/silver/usaco-895.mdx
> +	    {0, 1}};  // Movement directions (up, down, left, right)
move this comment to being right above the `directions` declaration

2024-12-07 05:23 UTC, TheGamingMousse commented on solutions/silver/usaco-895.mdx
> +			int curX = current[0], curY = current[1];  // Current cell
how about just `row` and `col`, and for `newX` and `newY` just `nextRow` and `nextCol` or something like that

2024-12-07 05:23 UTC, TheGamingMousse commented on solutions/silver/usaco-895.mdx
> +		return new int[] {area, perimeter};
why not `int[]{area, perimeter}`?

2024-12-07 05:23 UTC, TheGamingMousse commented on solutions/silver/usaco-895.mdx
> +pair<int, int> bfs(int x, int y) {
hmm i personally would rather just put this in `main()` because making it its own function kind of forces u to have a bunch of global variables

2024-12-07 05:23 UTC, TheGamingMousse commented on solutions/silver/usaco-895.mdx
> +				auto [area, perimeter] = bfs(i, j);
surely `const auto` (it doesn't really matter lol but why not ig)

2024-12-07 05:31 UTC, TheGamingMousse commented on solutions/silver/usaco-895.mdx
> +pair<int, int> bfs(int x, int y) {
oh wait ic why u did it this way

hmm in that case it's fine, altho i would personally write a lambda

2024-12-07 07:23 UTC, ryanchou-dev reviewed
great work!

2024-12-07 07:23 UTC, ryanchou-dev commented on solutions/silver/usaco-895.mdx
> +	main()
take code out of main

2024-12-07 07:23 UTC, ryanchou-dev commented on solutions/silver/usaco-895.mdx
> +				):  # If the neighbor (next_row, next_col) is part of the same blob
the comments are making the formatting weird - have it on a separate line?

2024-12-07 07:23 UTC, ryanchou-dev commented on solutions/silver/usaco-895.mdx
> +	perimeter = 0
nitpick but keep var names the same?

2024-12-07 15:47 UTC, SansPapyrus683 requested changes

2024-12-07 15:47 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +		int area = 0, perimeter = 0;
declarations on sep lines

2024-12-07 15:47 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +		Queue<int[]> q = new LinkedList<>();
usually we just use arraydeque here

2024-12-07 15:47 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +with open("perimeter.out", "w") as fout:
you can use the `file` argument to `print` to turn this into a one liner

2024-12-08 00:40 UTC, SansPapyrus683 requested changes

2024-12-08 00:40 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +reducing the count for each shared edge with neighboring '#' cells.
i think the calculation of the perimeter warrants a bit more explanation

2024-12-08 00:40 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +			area, perimeter = bfs(i, j, grid, visited, n)
you can invert the condition and use `continue` for less indentation

2024-12-08 00:40 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +def bfs(row, col, grid, visited, n):
type annotations

2024-12-08 02:43 UTC, TheGamingMousse reviewed
just a few nitpicks 💀 (sorry)

2024-12-08 02:43 UTC, TheGamingMousse commented on solutions/silver/usaco-895.mdx
> +pair<int, int> bfs(int row, int col, vector<vector<char>> &grid,
i think a lambda would be a lot cleaner

granted its syntax might be slightly confusing, but i think it's nicer than having to pass in `n`, `grid`, and `visited`

2024-12-08 02:43 UTC, TheGamingMousse commented on solutions/silver/usaco-895.mdx
> +			int next_row = row + dx, next_col = col + dy;
ideally put these on separate lines

2024-12-08 03:58 UTC, TheGamingMousse approved these changes
🔥

2024-12-08 03:58 UTC, TheGamingMousse commented on solutions/silver/usaco-895.mdx
> +			    4;  // Each cell starts with 4 sides contributing to the perimeter
hmm precommit is tweaking out, can u move this comment to a be above the variable declaration?

2024-12-08 04:19 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +const vector<pair<int, int>> directions = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};
since it's constant i'd make this all caps

2024-12-08 04:47 UTC, SansPapyrus683 requested changes

2024-12-08 04:47 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +	row: int, col: int, grid: List[List[str]], visited: List[List[bool]], n: int
you can probably just read in `grid` as a list of strings since you can index them asw

2024-12-08 04:47 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +                   vector<vector<bool>> &visited, int n) {
1. can `grid` be made a const ref
2. `n` seems redundant given that you can determine it from grid size, but idk

2024-12-08 18:39 UTC, SansPapyrus683 commented on solutions/silver/usaco-895.mdx
> +                   vector<vector<bool>> &visited, int n) {
passing in `n` seems a little redundant since you can deduce it from `grid`

2024-12-08 20:02 UTC, SansPapyrus683 approved these changes
peak

2024-12-08 20:05 UTC, ryanchou-dev approved these changes

2024-12-08 20:10 UTC, merged