update Baltic Editor
cpinitiative/usaco-guide pull request #4987
Opened 2024-12-16 15:23 UTC by Sosuke23

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [x] I have tested my code.
- [x] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [x] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

The previous solution resulted in `RE` because the range of `max_n` was only taken until `2e5`, when it should be `3e5`, as mentioned in the problem.

AC (C++): https://oj.uz/submission/1127122
AC (PY): https://oj.uz/submission/1127124

2024-12-16 17:56 UTC, dongliu0426 commented on solutions/platinum/baltic-15-editor.mdx
> +MAX_D = 19  # ceil(log2(3*(10^5)))
```suggestion
MAX_D = 19  # ceil(log2(3 * (10^5)))
```

2024-12-17 01:17 UTC, SansPapyrus683 commented on solutions/platinum/baltic-15-editor.mdx
> +#include <assert.h>
use cassert instead

2024-12-17 04:33 UTC, Sosuke23 commented on solutions/platinum/baltic-15-editor.mdx
> +#include <assert.h>
ok

2024-12-28 00:06 UTC, dongliuu approved these changes

2024-12-31 23:16 UTC, SansPapyrus683 requested changes
back from vacay

2024-12-31 23:16 UTC, SansPapyrus683 commented on solutions/platinum/baltic-15-editor.mdx
> +// get last op on active path of x with lev <= maxLev
1. make doc comment
2. maxLev -> max_lev

2024-12-31 23:16 UTC, SansPapyrus683 commented on solutions/platinum/baltic-15-editor.mdx
> +MAX_N = 300001
is +1 necessary

2024-12-31 23:16 UTC, SansPapyrus683 commented on solutions/platinum/baltic-15-editor.mdx
> +MAX_D = 19  # ceil(log2(3 * (10^5)))
just calculate it directly

2024-12-31 23:16 UTC, SansPapyrus683 commented on solutions/platinum/baltic-15-editor.mdx
> +	# get last op on active path of x with lev <= maxLev
yeah same thing about doc comments here

2025-01-01 05:07 UTC, Sosuke23 commented on solutions/platinum/baltic-15-editor.mdx
> +MAX_N = 300001
not really, it was included in prev solution so I just want to keep it real.

2025-01-01 11:19 UTC, SansPapyrus683 commented on solutions/platinum/baltic-15-editor.mdx
> + */
```suggestion
/** get last op on active path of x with lev <= max_lev */
```

2025-01-01 11:19 UTC, SansPapyrus683 commented on solutions/platinum/baltic-15-editor.mdx
> +	"""
```suggestion
	"""get last op on active path of x with lev <= max_lev"""
```

2025-01-01 16:32 UTC, SansPapyrus683 approved these changes

2025-01-01 16:33 UTC, merged