Cpp Solution: Connecting Two Barns
cpinitiative/usaco-guide pull request #4990
Opened 2024-12-16 23:08 UTC by TheRickyZhang

_Place an "x" in the corresponding checkbox if it is done or does not apply to this pull request._

- [X] I have tested my code.
- [X] I have added my solution according to the steps [here](https://usaco.guide/general/adding-solution#steps).
- [X] I have followed the code conventions mentioned [here](https://usaco.guide/general/adding-solution/#code-conventions).
  - I understand that if it is clear that I have not attempted to follow these conventions, my PR will be closed.
  - If changes are requested, I will re-request a review after addressing them.
- [ ] I have linked this PR to any issues that it closes.

2024-12-17 01:15 UTC, SansPapyrus683 commented on solutions/silver/usaco-1159.mdx
> +#define sz(x) (int)(x).size()
could you not use these macros

2024-12-17 01:19 UTC, TheRickyZhang commented
I thought these were allowed under [here](https://github.com/cpinitiative/usaco-guide/issues/806) but I can fix them

2024-12-17 04:46 UTC, Sosuke23 requested changes

2024-12-17 04:46 UTC, Sosuke23 commented on solutions/silver/usaco-1159.mdx
> +	vector<ll> startComponent = components[vis[0]];
use an underscore to separate the variable name. ex. `start_component`

2024-12-23 01:55 UTC, ryanchou-dev reviewed
thank you for your contribution!

2024-12-23 01:55 UTC, ryanchou-dev commented on solutions/silver/usaco-1159.mdx
> +	ll n, m;
nitpick, but don't use long longs unnecessarily.

2024-12-23 01:55 UTC, ryanchou-dev commented on solutions/silver/usaco-1159.mdx
> +	cin.tie(nullptr);
needed to ac? if not, remove

2024-12-23 01:55 UTC, ryanchou-dev commented on solutions/silver/usaco-1159.mdx
> +	vector<ll> vis(n, -1);
(optional)
naming this array `color` or `id` might be more appropriate if you're labeling connected components

2024-12-27 16:02 UTC, envyaims approved these changes
some minor changes
gj

2024-12-27 16:02 UTC, envyaims commented on solutions/silver/usaco-1159.mdx
> +	// Adjacency list
```suggestion
```

2024-12-27 16:02 UTC, envyaims commented on solutions/silver/usaco-1159.mdx
> +	// Connected components parent and count
```suggestion
	// vis[i] stores the component label for node i
```

2024-12-27 16:02 UTC, envyaims commented on solutions/silver/usaco-1159.mdx
> +	int cnt = 0;
rename to `num_components` or something

2024-12-27 16:02 UTC, envyaims commented on solutions/silver/usaco-1159.mdx
> +	// Mapping each component to its nodes
```suggestion
	// components[i] stores all nodes with component label i
```

2024-12-31 23:19 UTC, SansPapyrus683 approved these changes
ok i made some changes if you could test it again that'd be great

2025-01-02 07:05 UTC, TheRickyZhang commented
Not sure what testing means but it still passes the problem submission. Should I be the one updating the branch?

2025-01-02 11:39 UTC, SansPapyrus683 commented
uh no i just made some changes that would've been easier to make myself

2025-01-07 22:20 UTC, SansPapyrus683 approved these changes

2025-01-09 01:02 UTC, merged