Merged Pull Request
cpinitiative/usaco-guide pull request #508
Opened 2020-12-21 03:27 UTC by KWang31

I have closed a pull request and opened a new one because I don't know how to change more files without starting a new one.

2020-12-21 04:28 UTC, bqi343 commented
What happened to the [frontmatter](https://github.com/cpinitiative/usaco-guide/blob/master/docs/Content%20Documentation.md#3-frontmatter)?

2020-12-21 04:34 UTC, KWang31 commented
> What happened to the [frontmatter](https://github.com/cpinitiative/usaco-guide/blob/master/docs/Content%20Documentation.md#3-frontmatter)?

Fixed.

2020-12-21 04:35 UTC, bqi343 commented
Doesn't render properly with liveupdate.

2020-12-21 04:49 UTC, KWang31 commented
> Doesn't render properly with liveupdate.

Fixed, I won't start files from scratch again.

2020-12-21 14:54 UTC, bqi343 commented
You should explain what A, B, C are. One line is missing a period. Use $\mathcal{O}$ instead of $O$. Use 

```java
java code

public static
``` 

instead of 

```
java code

public static
```

2020-12-21 15:01 UTC, dolphingarlic requested changes
Some grammar and style changes

2020-12-21 20:00 UTC, KWang31 commented
Sorry for making 3 commits. Please only check the last one.

2020-12-22 01:05 UTC, bqi343 commented on solutions/JOI 18-snake-escaping.mdx
> +source: JOI 18 Final Round Problem 5
`JOI 2018 Final Round` for source is also fine

2020-12-22 01:14 UTC, bqi343 commented
Still haven't resolved all the comments.

2020-12-22 14:41 UTC, bqi343 requested changes

2020-12-22 14:41 UTC, bqi343 commented on solutions/JOI 18-snake-escaping.mdx
> +For a query, let $A$ be the set of $0$'s, $B$ be the set of $1$'s, and $C$ be the set of $?$'s. By Pigeonhole principle, $min\{A,B,C\}\le 6$, and I claim we can answer queries in $O(2^{min\{A,B,C\}})
Use \min instead of min

2020-12-22 14:41 UTC, bqi343 commented on solutions/JOI 18-snake-escaping.mdx
> +Otherwise, we can answer queries with the principle of inclusion-exclusion. The answer is simply $\sum\limits_{a\in A} super[B | a] (-1)^{|a|}$, which we can calculate in $\mathcal{O}(2^{|A|})$
missing a period

2020-12-22 14:41 UTC, bqi343 commented on solutions/JOI 18-snake-escaping.mdx
> +The overall time complexity is $\mathcal{O}(2^L\cdot L+2^{\frac{L}{3}}Q)$ since we compute $super$ and $sub$ in $\mathcal{O}(2^L\cdot L)$ with SOS DP, and we process each query in $\mathcal{O} (2^{\f
The other modules (ex. https://github.com/cpinitiative/usaco-guide/blob/ee78824031eb37302c8eade6e732a56f4e8f63c2/solutions/USACO%20feb19-cowland.mdx) put "Time Complexity"  in bold, do that here as well.

2020-12-22 14:41 UTC, bqi343 commented on solutions/JOI 18-snake-escaping.mdx
> +The answer is also $\sum\limits_{b\in B} sub[C | b] (-1)^{|B|-|b|}$, which we can calculate in $\mathcal{O}(2^{|B|})$. They can be computed efficiently with submask enumeration. For a detailed explan
Use `[description](link)` instead of just pasting the link.

2020-12-26 22:33 UTC, merged