Solution for CSES Monsters (Gold, BFS section)
cpinitiative/usaco-guide pull request #555
Opened 2020-12-31 20:53 UTC by IsaacNoel

2021-01-01 15:14 UTC, bqi343 commented
Didn't do step 3 of 

https://usaco.guide/general/contributing#adding-a-solution.

Also, the time complexity should be stated at the top in the same format as described by that module.

2021-01-01 17:23 UTC, IsaacNoel commented
I've implemented those changes, lmk if I need to do anything else.

2021-01-02 01:17 UTC, bqi343 requested changes

2021-01-02 01:17 UTC, bqi343 commented on solutions/CSES Sliding Median.mdx
> +Finding the median of a sliding window by maintaining two multisets in $N\log N$
No need to restate the complexity here.

2021-01-02 01:17 UTC, bqi343 commented on solutions/CSES Sliding Median.mdx
> +# Abstract
Use second-tier headings (## instead of #) to be consistent with how other solutions are formatted.

2021-01-02 02:12 UTC, merged