Add 3 more solutions for the Silver Greedy section
cpinitiative/usaco-guide pull request #568
Opened 2021-01-02 04:44 UTC by tachithanhdanh

2021-01-02 07:33 UTC, tachithanhdanh commented
I added the C++ implementation for this problem https://usaco.guide/silver/prefix-sums#problem-https://cses.fi/problemset/task/1650

2021-01-03 05:34 UTC, tachithanhdanh commented
Could someone please review these solutions?
I think they are detailed enough

2021-01-04 01:32 UTC, bqi343 commented
What about step 3 of https://usaco.guide/general/contributing?lang=cpp#adding-a-solution ?

2021-01-04 01:44 UTC, tachithanhdanh commented
Do I have to remove the spoiler in that file too?

2021-01-04 01:45 UTC, bqi343 commented
Remove what spoiler?

2021-01-04 01:46 UTC, tachithanhdanh commented
Oops I misread the file

2021-01-04 01:46 UTC, tachithanhdanh commented
Do I need to add the tags?

2021-01-04 01:47 UTC, bqi343 commented
If you want.

2021-01-04 02:01 UTC, bqi343 requested changes

2021-01-04 02:01 UTC, bqi343 commented on solutions/CSES Stick Lengths.mdx
> +In this problem, we are given an array with n elements. We want to find the minimum cost to make all of the elements equal.
$n$ instead of n

2021-01-04 02:03 UTC, tachithanhdanh commented on solutions/CSES Stick Lengths.mdx
> +In this problem, we are given an array with n elements. We want to find the minimum cost to make all of the elements equal.
I have changed that, thanks

2021-01-04 02:13 UTC, merged