Adding CSES solution
cpinitiative/usaco-guide pull request #587
Opened 2021-01-05 03:41 UTC by AK-I-RA

2021-01-05 13:56 UTC, andrewwangva commented
> _No description provided._

Check #3 on [https://usaco.guide/general/contributing?lang=cpp#adding-a-solution](https://usaco.guide/general/contributing?lang=cpp#adding-a-solution) to link the solution

2021-01-05 20:05 UTC, dolphingarlic commented
Please also add an explanation for your solution

2021-01-09 08:29 UTC, dolphingarlic requested changes
You still didn't make the changes we requested. Also, since the unofficial editorial already has explanations and code, these editorials seem a bit redundant

2021-01-09 09:32 UTC, AK-I-RA commented
So what should i do??
Remove unofficial editorial or better explanation.

2021-01-09 19:04 UTC, thecodingwizard commented
If the unofficial editorial already has a good explanation, then it's not necessary to add an explanation of our own (unless there are substantial differences). From the Contributing module on the USACO Guide:

> It is not necessary to add an alternative implementation in the same language as the official analysis (unless the alternative implementation takes a different approach or is written better / differently from the official implementation).

It's probably best to only include link to the unofficial editorial. Adding an additional explanation / C++ code seems unnecessary...

2021-01-10 01:59 UTC, AK-I-RA commented
Ok

2021-01-12 03:47 UTC, frodakcin requested changes
Oh, did I forget to click the "Submit review" button?

2021-01-12 03:48 UTC, frodakcin commented
Yes I did... I am still very much a github noob

2021-01-19 07:15 UTC, frodakcin approved these changes
I trust these have been AC'd

2021-01-19 18:00 UTC, dolphingarlic requested changes
You still haven't linked to the solutions in the modules

2021-01-19 18:04 UTC, frodakcin commented on solutions/CSES Dice Combinations.mdx
> +    k[0]=1;
how would you not do this?

2021-01-19 18:14 UTC, dolphingarlic commented on solutions/CSES Dice Combinations.mdx
> +    k[0]=1;
Just don't set ` = {0}` I think

2021-01-19 18:39 UTC, frodakcin commented on solutions/CSES Dice Combinations.mdx
> +    k[0]=1;
well you might as well just set the entire thing to 0.

Honestly i'm not sure why = {0} works, personally i'd have added `memset(k, 0, sizeof k);`

2021-01-20 08:39 UTC, frodakcin commented on solutions/CSES Projects.mdx
> +  map<int,int> mp;
because its coord compressing. actually, its done in quite a clever way ive never seen before

2021-01-20 08:54 UTC, frodakcin requested changes

2021-01-20 08:54 UTC, frodakcin commented on solutions/CSES Dice Combinations.mdx
> +            k[0] % =mod;
```suggestion
            k[0] %= mod;
```

2021-01-20 08:54 UTC, frodakcin commented on solutions/CSES Dice Combinations.mdx
> +            k[0] % =mod;
Thanks dolphin! I have figured it out!

2021-01-20 08:55 UTC, frodakcin commented
Otherwise, I think it's all set.

2021-01-20 17:26 UTC, frodakcin approved these changes
Seems good. Does dolphin have suggestions?

2021-01-20 17:27 UTC, dolphingarlic commented
The solutions still aren't linked in the problems' modules though :(

2021-01-20 17:28 UTC, dolphingarlic commented
Otherwise yeah the code looks fine

2021-01-20 17:31 UTC, frodakcin commented
> The solutions still aren't linked in the problems' modules though :(

oh, totally missed that. thanks!

2021-01-21 00:31 UTC, dongliu0426 requested changes

2021-01-21 00:31 UTC, dongliu0426 commented on solutions/CSES Dice Combinations.mdx
> +#include <iostream>
no need to include `iostream` (its included in `stdc++.h`)

2021-01-21 03:07 UTC, dongliu0426 reviewed
as dolphingarlic and frodakcin said, please link this solution to a module

2021-01-21 11:29 UTC, tachithanhdanh commented
The dice combinations has the solution already, so no need to add a new one

2021-01-21 11:35 UTC, tachithanhdanh commented
The code implementation is also included in the Codeforces Unofficial Editorial, so do we need to create a new .mdx file? @dolphingarlic

2021-01-21 11:44 UTC, tachithanhdanh commented
https://github.com/cpinitiative/usaco-guide/pull/643
I create a new pull request to add the codeforces unofficial editorial, so this pull request should be closed now

2021-01-21 16:24 UTC, dongliu0426 commented
@AK-I-RA you can still open a PR for your CSES Projects solution

2021-01-22 02:27 UTC, tachithanhdanh commented
> @AK-I-RA you can still open a PR for your CSES Projects solution

The CSES Projects solution is already in the CF Unofficial Editorial, isn't it?

2021-01-22 02:50 UTC, dongliu0426 commented
> > @AK-I-RA you can still open a PR for your CSES Projects solution
> 
> The CSES Projects solution is already in the CF Unofficial Editorial, isn't it?

the editorial isn't linked with the problem (https://usaco.guide/adv/springboards?lang=cpp#problem-https://cses.fi/problemset/task/1140).

2021-01-23 06:45 UTC, dolphingarlic requested changes
https://usaco.guide/general/contributing?lang=cpp#adding-a-solution step 3

2021-01-23 07:04 UTC, AK-I-RA commented
> https://usaco.guide/general/contributing?lang=cpp#adding-a-solution step 3

why it is not success on links.

2021-01-24 22:13 UTC, dongliu0426 commented
> > @AK-I-RA you can still open a PR for your CSES Projects solution
> 
> The CSES Projects solution is already in the CF Unofficial Editorial, isn't it?

yeah, plus the code here and the code in the CF Blog is very similar :eyes:

2021-01-27 14:17 UTC, closed without merging