Berry Picking, java sol
cpinitiative/usaco-guide pull request #588
Opened 2021-01-05 19:27 UTC by HarryWangATX

2021-01-05 21:21 UTC, frodakcin requested changes
All good, just some minor typos.

2021-01-05 21:21 UTC, frodakcin commented on solutions/USACO jan20-berry-picking.mdx
> +                //If count can only account of Elsie and some of Bessie, then we can take from the left overs.
Typo "account of Elsie" and "left overs"

Probably should be
`//If count can only account for Elsie and some of Bessie, then we can take from the leftovers.`

2021-01-06 09:24 UTC, frodakcin approved these changes
All set.

2021-01-06 09:24 UTC, merged

2021-01-06 09:56 UTC, dolphingarlic reviewed
Just one more minor thing

2021-01-06 09:56 UTC, dolphingarlic commented on solutions/USACO jan20-berry-picking.mdx
> +**Time Complexity:** $\mathcal{O}(max(B_i) \cdot N\log N)$
```suggestion
**Time Complexity:** $\mathcal{O}(\max(B_i) \cdot N\log N)$
```