CSES Increasing Subsequences II Revision II
cpinitiative/usaco-guide pull request #604
Opened 2021-01-07 17:20 UTC by timothygao8710

If someone could tell me how to make edits in a pull request that would be great lol

2021-01-07 17:59 UTC, frodakcin commented
If you push to the branch or repository where you performed the initial pull request, it will automatically update the PR

2021-01-07 18:00 UTC, frodakcin commented
Is it fine to close https://github.com/cpinitiative/usaco-guide/pull/593 ?

2021-01-07 18:01 UTC, frodakcin commented
lol is https://github.com/cpinitiative/usaco-guide/pull/598 also from the same update chain?

2021-01-07 21:33 UTC, timothygao8710 commented
Yea lol I'm pretty new to github. Feel free to close the duplicates.

2021-01-07 21:49 UTC, frodakcin commented
no worries

2021-01-08 13:24 UTC, dolphingarlic requested changes
Just some grammar/style corrections and then you should be good to go

2021-01-08 13:24 UTC, dolphingarlic commented on solutions/CSES Increasing Subsequence II.mdx
> +More specifically, we sort all numbers in $x$ and map each distinct number to its index in the sorted array. This way, we effectively coordinate compress the numbers.
```suggestion
More specifically, we sort all numbers in $x$ and map each distinct number to its index in the sorted array. This is known as coordinate compression, and it makes the range of the numbers significantly smaller.
```

2021-01-08 13:24 UTC, dolphingarlic commented on solutions/CSES Increasing Subsequence II.mdx
> +Let $dp[i]$ be the number of increasing subsequences of $x$ ending on the right at index $i$.
```suggestion
Let $dp[i]$ be the number of increasing subsequences of $x$ ending on the right of index $i$.
```

2021-01-08 13:24 UTC, dolphingarlic commented on solutions/CSES Increasing Subsequence II.mdx
> +Notice that $dp[i]$ can be calculated as the summation of all $dp[j]$ such that $j < i$ and $x_j < x_i$.
```suggestion
Notice that $dp[i]$ can be calculated as the summation of all $dp[j]$ where $j < i$ and $x_j < x_i$.
```

2021-01-08 13:24 UTC, dolphingarlic commented on solutions/CSES Increasing Subsequence II.mdx
> +**Time Complexity:** $\mathcal{O}(NlogN)$
Move this line to the top of the solution

2021-01-08 13:24 UTC, dolphingarlic commented on solutions/CSES Increasing Subsequence II.mdx
> +With this, we can create a [BIT](https://usaco.guide/gold/PURS), which intially starts with all 0s. As we run through $x$ from left to right, $dp[i]$ would be summation of all $j<k$ in the BIT, where
```suggestion
With this, we can create a [BIT](https://usaco.guide/gold/PURS), where each value is initially 0. As we iterate through $x$, $dp[i]$ would be the sum of the values at positions $j<k$ in the BIT, where $k$ is the index that $x_i$ maps to. We then increase position $k$ in the BIT by $dp[i]$ as preparation for the next element of $x$. 
```

2021-01-08 17:22 UTC, merged