Renamed OI problems for consistency
cpinitiative/usaco-guide pull request #620
Opened 2021-01-13 18:15 UTC by dolphingarlic

- File names are of the format "{Olympiad in uppercase} {Last two digits of year}-{Problem name joined by underscores}.mdx"
- Problem IDs are of the format "{Olympiad in lowercase}-{Last two digits of year}-{Problem name joined by underscores}"
- If the problem has a "code" (e.g. POI/BOI 2015/CEOI 2018) or a name in a different language (e.g. LMiO), then we use that as the name instead

I might've left stuff out, so please double-check

2021-01-13 19:01 UTC, dongliu0426 requested changes
- https://usaco-guide-klg3e1b8q.vercel.app/gold/stacks?lang=cpp#problem-https://codeforces.com/contest/1402/problem/A
- https://usaco-guide-klg3e1b8q.vercel.app/gold/stacks?lang=cpp#problem-https://oj.uz/problem/view/COI15_zarulje

Add years to the problem name

2021-01-13 21:41 UTC, dongliu0426 approved these changes
Looks good for the gold content (oops)

2021-01-14 05:45 UTC, dolphingarlic reviewed
Oops I still left out a few

2021-01-14 05:45 UTC, dolphingarlic commented on content/4_Gold/DP_Trees.mdx
>  			'contest/1387/problem/B1',
Oops I should fix these links too

2021-01-14 05:45 UTC, dolphingarlic commented on content/5_Plat/DC-DP.mdx
> +			'Two Sawmills',
And this one

2021-01-14 05:45 UTC, dolphingarlic commented on content/6_Advanced/LCT.mdx
>  			'contest/1386/problem/C',
And this link

2021-01-14 05:45 UTC, dolphingarlic commented on content/6_Advanced/Offline_Del.mdx
>  			'contest/1386/problem/C',
And this link

2021-01-14 06:53 UTC, dolphingarlic commented
@dongliu0426 should I merge?

2021-01-14 16:41 UTC, dongliu0426 requested changes
oops there's still some stuff left out
- Silver bipartite -- Baltic OI Graph
- Silver intro-tree -- POI Hotels
- Adv CntMin -- IOI Pyramid Base
- Adv Slope -- LMiO Potatoes & Fertilizers
- Adv BCC - 2CC -- POI Blockade
- Adv SCC -- POI Bike Paths
- Adv LCT -- IOI Dancing Elephants
- Adv comb-sub -- COCI Dzumbus

2021-01-14 17:01 UTC, dongliu0426 approved these changes

2021-01-14 17:23 UTC, merged