Add editorial for hps
cpinitiative/usaco-guide pull request #625
Opened 2021-01-16 03:47 UTC by MrinallU

2021-01-18 16:59 UTC, andrewwangva commented on solutions/USACO jan17-hoof-paper-scissors.mdx
> +Editorial: As opposed to the official editorial there also exists a simpler solution in which one does not need to get involved with multiple 2D arrays, instead there is also a fairly straightforward
> Editorial: As opposed to the official editorial there also exists a simpler solution in which one does not need to get involved with multiple 2D arrays, instead there is also a fairly straightforward solution using prefix sums with 1D arrays.
unnecessary

2021-01-18 17:01 UTC, andrewwangva reviewed
Clean up the explanation a bit. Try to shorten it and make it more straightforward.

2021-01-18 17:01 UTC, andrewwangva commented on solutions/USACO jan17-hoof-paper-scissors.mdx
> +Editorial: As opposed to the official editorial there also exists a simpler solution in which one does not need to get involved with multiple 2D arrays, instead there is also a fairly straightforward
> Now the problem is narrowed down to two questions. How do we efficiently calculate the best place we need to change the gesture or if we need to change it at all? And how do we calculate the number of wins of a certain gesture given the range of turns the gesture is played? Well 

Also unnecessary

2021-01-18 17:35 UTC, MrinallU commented
@andrewwangva Sorry, I went on a bit of a ramble when explaining the problem. It should be more straightforward now.

2021-01-18 17:36 UTC, HarryWangATX commented
I think someone replaced your code with theirs some time ago

2021-01-18 17:46 UTC, MrinallU commented
Both of our code is the same as he just changed the variable names, we
follow the exact same logic.

On Mon, Jan 18, 2021 at 12:37 PM Qi Wang <notifications@github.com> wrote:

> I think someone replaced your code with theirs some time ago
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cpinitiative/usaco-guide/pull/625#issuecomment-762387983>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOVN6SJJUGX4G4WELWHU6KDS2RWUHANCNFSM4WE5UG3Q>
> .
>

2021-01-19 07:32 UTC, frodakcin requested changes
Still quite unclear. Maybe try paragraph breaks?

The reader shouldn't need to think very hard to understand the solution.

2021-01-19 13:36 UTC, closed without merging