USACO Plat friendcross solution
cpinitiative/usaco-guide pull request #634
Opened 2021-01-18 22:02 UTC by dongliu0426

2021-01-18 22:25 UTC, bqi343 requested changes

2021-01-18 22:25 UTC, bqi343 commented on solutions/USACO feb17-friendcross.mdx
> +Let us consider an easier version: where we're just asked to count number of crossing pairs (ignoring whether the cows are friendly or not). To calculate the number of crossing pairs, we can add the
> Let us consider an easier version: where we're just asked to count number of crossing pairs (ignoring whether the cows are friendly or not).

Let us consider an easier version; suppose that we just want to count the number of crossing pairs (ignoring whether the cows are friendly or not).

2021-01-18 22:25 UTC, bqi343 commented on solutions/USACO feb17-friendcross.mdx
> +](https://usaco.guide/gold/PURS?lang=cpp#order-statistic-tree) in C++ to represent the cow breeds. Since each update takes $\log N$ operations, it would allocate $\log N$ nodes, thus resulting with $
not $\mathcal O(N\log N)$ time

2021-01-18 23:10 UTC, dongliu0426 commented
honestly idk if this is a good solution; it passes with `1957ms` on test case 13

2021-01-19 01:10 UTC, bqi343 requested changes

2021-01-19 01:10 UTC, bqi343 commented on solutions/USACO feb17-friendcross.mdx
> +To count the number of unfriendly crossings, instead of keeping track of the count for each BIT node, we keep track a list representing the cow breeds. Now to query the range for a breed $b$, we coun
> keep track a list

of a sorted set?

2021-01-19 01:10 UTC, bqi343 commented on solutions/USACO feb17-friendcross.mdx
> +To count the number of unfriendly crossings, instead of keeping track of the count for each BIT node, we keep track a list representing the cow breeds. Now to query the range for a breed $b$, we coun
> Now to query the range for a breed $b$, we count the num ...

For a breed $b$, we query the number of breeds ...

2021-01-19 01:11 UTC, bqi343 commented
> honestly idk if this is a good solution; it passes with `1957ms` on test case 13

Then add a note.

2021-01-20 03:06 UTC, bqi343 requested changes

2021-01-20 03:06 UTC, bqi343 commented on solutions/USACO feb17-friendcross.mdx
> +To count the number of unfriendly crossings, instead of keeping track of the count for each BIT node, we keep track a sorted set representing the cow breeds. For a breed $b$, we query the number of b
keep track **of** a sorted set (or "maintain a sorted set")

2021-01-20 03:06 UTC, bqi343 commented on solutions/USACO feb17-friendcross.mdx
> +](https://usaco.guide/gold/PURS?lang=cpp#order-statistic-tree) in C++ to represent the cow breeds. Since each update takes $\log N$ operations, it would allocate $\log N$ nodes each update, thus resu
> thus resulting with 

resulting in?

2021-01-20 03:42 UTC, merged