Add some Windows-specific information for Running Code Locally
cpinitiative/usaco-guide pull request #669
Opened 2021-01-29 17:34 UTC by Mastermind497

This includes how to get the header bits/stdc++ on windows, as well as the different compiler options available. This was made with the help of @wastingtime#1534

2021-01-30 18:38 UTC, thecodingwizard commented
C++ With the Command Line also includes installation instructions for G++, etc. Should we move installation instructions into "Running Code Locally"? I think it fits better there anyway.

@cpinitiative/core-team

2021-01-30 19:47 UTC, bqi343 commented
sure

2021-01-31 22:14 UTC, bqi343 requested changes

2021-01-31 22:14 UTC, bqi343 commented on content/1_General/Running_Code_Locally.mdx
> +author: Benjamin Qi, Hankai Zhang, Anthony Wang, Nathan Wang, Nathan Chen, Owen Wang, Shourya Bansal, @wastingtime#1534
`@wastingtime#1534`

real name?

2021-02-01 01:58 UTC, thecodingwizard approved these changes
This is perfect. Thanks :heart:

2021-02-01 03:04 UTC, merged