Add C++ solution to USACO jan20-berry-picking.mdx
cpinitiative/usaco-guide pull request #699
Opened 2021-02-06 16:43 UTC by 23danielsuh

2021-02-06 19:53 UTC, frodakcin requested changes
The code is all tabs, but there are spaces before the comments. Can we stick to all tabs?

2021-02-06 19:53 UTC, frodakcin commented on solutions/USACO jan20-berry-picking.mdx
> +            //If there is enough "i" sections for both Bessie and Ellie, then just have (K / 2) * i for Bessie
```suggestion
            //If there are enough "i" sections for both Bessie and Ellie, then Bessie can collect (K / 2) * i berries
```

2021-02-06 19:59 UTC, 23danielsuh commented
> The code is all tabs, but there are spaces before the comments. Can we stick to all tabs?

Just changed it to tabs, and revised one of the comments. Not sure what happened, I think I edited the old file in a different text editor that defaults to spaces instead of tabs.

2021-02-06 20:03 UTC, frodakcin commented
Yea, probably. It'd normally be impossible to notice but conveniently github uses super large tabs which makes it obvious.

2021-02-06 20:05 UTC, frodakcin approved these changes
Looks good.

2021-02-06 20:09 UTC, frodakcin requested changes
Actually, one more thing. I think using parentheses is more standard

2021-02-06 20:09 UTC, frodakcin commented on solutions/USACO jan20-berry-picking.mdx
> +author: Qi Wang {java}, Daniel Suh {C++}
```suggestion
author: Qi Wang (Java), Daniel Suh (C++)
```

2021-02-06 20:17 UTC, 23danielsuh commented
Yeah, that makes more sense. Just committed the changes.

2021-02-06 20:19 UTC, frodakcin approved these changes

2021-02-06 20:22 UTC, 23danielsuh commented
Sorry for all of the commits, but I just changed 2 of the comments to make more sense.

2021-02-06 20:36 UTC, frodakcin commented
No worries! Feel free to keep making changes

2021-02-07 01:59 UTC, frodakcin commented
Will merge after @HarryWangATX 's review

2021-02-07 03:47 UTC, HarryWangATX commented
K reviewing rn

2021-02-07 03:49 UTC, HarryWangATX approved these changes
doesn't the official sol include C++? welp ig its commented so doesn't hurt.

2021-02-07 18:48 UTC, merged