Div Game C++ Solution
cpinitiative/usaco-guide pull request #753
Opened 2021-02-11 06:21 UTC by maggie-j-liu

I added a C++ solution to AC Div Game. I linked the [editorial for the problem](https://atcoder.jp/contests/abc169/tasks/abc169_d/editorial), but there is no editorial there yet. Should I link the [overall editorial](https://img.atcoder.jp/abc169/editorial.pdf) instead?

2021-02-11 07:15 UTC, dolphingarlic commented
Could you just link to the overall editorial (with the page number in the URL) in the problem link? Since there's already an editorial and you can view other people's submissions on AC, I don't think a whole new file is necessary

2021-02-11 07:17 UTC, thecodingwizard commented
~~additional solutions don't hurt right?~~ actually idrk :P

2021-02-11 16:46 UTC, maggie-j-liu commented
Isn't it better to have the solution and the explanation in the same place so it's more convenient? If not, I can just close this.

2021-02-11 16:52 UTC, maggie-j-liu commented
There is an English explanation if you scroll down a few pages.

2021-02-11 16:58 UTC, dongliu0426 commented
oh I didn't see that.

2021-02-14 16:41 UTC, maggie-j-liu commented
Is it okay to have my solution and explanation here, or should I just link to the editorial? I think it's more convenient but I don't know. @dolphingarlic @dongliu0426

2021-02-16 15:00 UTC, dolphingarlic commented
I think you should just link the editorial, but I don't mind having your explanation there

2021-02-16 17:08 UTC, maggie-j-liu commented
Ok, the editorial is linked, is there anything else I need to change?

2021-02-16 18:01 UTC, dolphingarlic requested changes
Just change the ID for consistency, and then it should be good to merge

2021-02-16 18:01 UTC, dolphingarlic commented on solutions/AC Div Game.mdx
> +id: div-game
```suggestion
id: AC-DivGame
```

2021-02-16 18:01 UTC, dolphingarlic commented on content/4_Gold/Divis.mdx
> +			'div-game'
```suggestion
			'AC-DivGame'
```

2021-02-16 18:13 UTC, merged