Mootube java sol
cpinitiative/usaco-guide pull request #769
Opened 2021-02-14 07:17 UTC by HarryWangATX

Added Java sol

2021-02-14 07:20 UTC, HarryWangATX commented
@frodakcin i can change vector bool to array if u want as well

2021-02-14 07:20 UTC, HarryWangATX commented
^ referring to previous cpp code

2021-02-14 07:24 UTC, frodakcin commented
Sure.

2021-02-14 07:24 UTC, frodakcin commented
Actually I feel like it would be more helpful to mention in data structure section if it isn't alr

2021-02-14 07:24 UTC, frodakcin commented
Because using it is fine for the most part.

2021-02-14 07:27 UTC, frodakcin commented
So in other words, if you want to change it you can, but I don't think it's necessary

2021-02-14 16:43 UTC, HarryWangATX commented
@frodakcin ill leave it as is then

2021-02-14 21:37 UTC, bqi343 approved these changes
tabs?

2021-02-14 21:38 UTC, bqi343 requested changes
whoops wrong button

2021-02-14 23:56 UTC, frodakcin requested changes
Minor qol formatting change

2021-02-14 23:56 UTC, frodakcin commented on solutions/USACO jan18-mootube-silver.mdx
> +
Delete empty line

2021-02-14 23:57 UTC, frodakcin commented on solutions/USACO jan18-mootube-silver.mdx
> +
I'm not sure what the standard is when leaving empty lines between ```s and code, but there definitely shouldn't be a double empty line at the bottom and a single empty line on top.

2021-02-16 21:34 UTC, frodakcin approved these changes

2021-02-16 22:38 UTC, bqi343 requested changes

2021-02-16 22:38 UTC, bqi343 commented on solutions/USACO jan18-mootube-silver.mdx
> +<JavaSection>
Add `## Java Implementation`

2021-02-16 22:47 UTC, bqi343 requested changes

2021-02-16 22:47 UTC, bqi343 commented on solutions/USACO jan18-mootube-silver.mdx
> +			a = io.nextInt();
just do `int a = io.nextInt()`?

2021-02-16 22:47 UTC, bqi343 commented on solutions/USACO jan18-mootube-silver.mdx
> +			S=0;
spacing not consistent with how you assign variables elsewhere

2021-02-17 17:35 UTC, merged