Create USACO open20-cereal.mdx
cpinitiative/usaco-guide pull request #774
Opened 2021-02-14 23:37 UTC by Aadit-Ambadkar

2021-02-14 23:41 UTC, HarryWangATX requested changes

2021-02-14 23:41 UTC, HarryWangATX commented on solutions/USACO open20-cereal.mdx
> +```
did not close.

2021-02-14 23:41 UTC, HarryWangATX commented on solutions/USACO open20-cereal.mdx
> +## Java Recursive Implementation
Make this a solution explanation, bring outside and rename heading.

2021-02-14 23:42 UTC, HarryWangATX commented
also where is this problem linked on guide???

2021-02-15 15:04 UTC, bqi343 commented
Please follow *all* of the instructions [here](https://usaco.guide/general/contributing?lang=cpp#adding-a-solution).

2021-02-16 22:28 UTC, dongliu0426 commented
also please use tabs instead of spaces

2021-02-20 22:38 UTC, bqi343 commented
Closing, please make a new PR when requested changes have been made.

2021-02-20 22:38 UTC, closed without merging