Cow Checklist C++ Solution
cpinitiative/usaco-guide pull request #779
Opened 2021-02-16 18:43 UTC by maggie-j-liu

I added a C++ solution to Cow Checklist (December 2016 Gold).

2021-02-16 21:03 UTC, bqi343 requested changes

2021-02-16 21:03 UTC, bqi343 commented on solutions/USACO dec16-cow-checklist.mdx
> +	pair<int, int> hcows[h], gcows[g];
As noted [here](https://usaco.guide/bronze/intro-ds?lang=cpp#dynamic-arrays) variable-length arrays aren't part of the C++ standard, so I would prefer using a vector for this purpose.

2021-02-16 21:03 UTC, bqi343 commented on solutions/USACO dec16-cow-checklist.mdx
> +	return pow(a.first - b.first, 2) + pow(a.second - b.second, 2);
Not relevant for this problem, but `pow` wouldn't be accurate enough for `long long`'s. Ex.

```cpp
int main() {
	const ll x = 2039593823;
	cout << (ll)pow(x,2) << "\n";
	cout << x*x << "\n";
	// 4159942962819755520
	// 4159942962819755329
}
```

Would prefer it if you used your own function to square an integer.

2021-02-16 22:27 UTC, dongliu0426 requested changes

2021-02-16 22:27 UTC, dongliu0426 commented on solutions/USACO dec16-cow-checklist.mdx
> +	dp[0][1][0] = 0;
make a note here that farmer john has to start with the first holstein

2021-02-16 22:47 UTC, maggie-j-liu commented on solutions/USACO dec16-cow-checklist.mdx
> +**Time Complexity:** $\mathcal{O}(H \cdot G)$
Sure, but [here](https://usaco.guide/general/contributing?lang=cpp#adding-a-solution) the time complexity is inside the CPPSection, so you might want to change that?

2021-02-16 22:54 UTC, bqi343 commented on solutions/USACO dec16-cow-checklist.mdx
> +**Time Complexity:** $\mathcal{O}(H \cdot G)$
Good point.

2021-02-17 02:12 UTC, bqi343 requested changes

2021-02-17 02:12 UTC, bqi343 commented on solutions/USACO dec16-cow-checklist.mdx
> +	long long dp[2][h + 1][g + 1];
same comment here as above. either make it constant size or use `vector`s.

```cpp
using ll = long long;
array<vector<vector<ll>>,2> dp;
for (int i = 0; i < 2; ++i) 
  dp[i].assign(h+1,vector<ll>(g+1,1e18));
```

2021-02-17 03:07 UTC, dongliu0426 approved these changes

2021-02-17 03:11 UTC, bqi343 approved these changes

2021-02-17 03:13 UTC, bqi343 requested changes

2021-02-17 03:13 UTC, bqi343 commented on solutions/USACO dec16-cow-checklist.mdx
> +	return (a.first - b.first) * (a.first - b.first) + (a.second - b.second) * (a.second - b.second);
actually some of these lines are > 80 chars

2021-02-17 04:42 UTC, merged