General - Silver Content Videos
cpinitiative/usaco-guide pull request #793
Opened 2021-02-17 20:06 UTC by jessechoe10

2021-02-17 20:17 UTC, HarryWangATX requested changes

2021-02-17 20:17 UTC, HarryWangATX commented on content/1_General/Learning_to_Code.mdx
> +	<Resource title="YouTube" url="https://www.youtube.com/watch?v=VCnuPywb9iU&list=PLtLxhThTxJMVMvWJoE2p8Z84tA8suGzvn&index=2">
one resource for all languages is fine

2021-02-17 20:17 UTC, HarryWangATX commented on content/2_Bronze/Intro_Graphs.mdx
> +		A video that explains what graphs are, the different types of graphs, and the different ways to represent them using code. He briefly describes how to represent these graphs in C++ as well as how t
Just say like intro to graphs or smth short

2021-02-17 20:17 UTC, HarryWangATX commented on content/2_Bronze/Intro_Sorting.mdx
> +		A video source that demonstrates how to sort an array in C++, Java, and Python. Start at time 0:49 and end at 5:42.
demonstrates how to sort arrays

2021-02-17 20:17 UTC, HarryWangATX commented on content/2_Bronze/Time_Comp.mdx
> +	</Resource>
is this necessary?

2021-02-17 20:17 UTC, HarryWangATX commented on content/3_Silver/2P.mdx
> +		A video explanation of common problems that the two-pointer technique could be applied to. Has a bit of Python code but mostly consists of the intuition and problem-solving approach for these probl
video tutorial for two pointers

2021-02-17 20:17 UTC, HarryWangATX commented on content/3_Silver/Binary_Search.mdx
> +		A video explanation to Binary Search and the internal C++ library functions. Begin at time 5:50 and end at 10:19.
video tutorial for binary search

2021-02-17 20:17 UTC, HarryWangATX commented on content/3_Silver/DFS.mdx
> +		A video explaining the intuition behind DFS as well as the iterative and recursive implementation of DFS.
dfs video explanation

2021-02-17 20:17 UTC, HarryWangATX commented on content/3_Silver/Greedy_Sorting.mdx
> +		A video demonstrating classic greedy problems such as the scheduling problem. He codes the solutions to some of the problems in Python, while mostly explaining the intuition and problem-solving str
video demonstration of greedy

2021-02-17 20:17 UTC, HarryWangATX commented on content/3_Silver/Sorting_Custom.mdx
> +			'Normal',
???

2021-02-17 20:17 UTC, HarryWangATX commented on content/3_Silver/Sorting_Custom.mdx
> +			'Hard',
???

2021-02-17 20:21 UTC, HarryWangATX commented
i havent watch the videos yet

2021-02-17 20:56 UTC, thecodingwizard commented
Oops I personally think we can find better videos (I think williamfiset videos or others are of a higher quality). But if others think the videos are fine then sure :)

2021-02-17 21:06 UTC, HarryWangATX commented
> Oops I personally think we can find better videos (I think williamfiset videos or others are of a higher quality). But if others think the videos are fine then sure :)

yea i just took a look i feel like those vids are a little un serious xD

2021-02-17 23:53 UTC, jessechoe10 commented
> > Oops I personally think we can find better videos (I think williamfiset videos or others are of a higher quality). But if others think the videos are fine then sure :)
> 
> yea i just took a look i feel like those vids are a little un serious xD

Sure. I would agree. However, I think adding some humor makes watching much more interesting. Also, he has a lot of USACO problem walkthroughs so could I add his vids for those?

2021-02-17 23:59 UTC, HarryWangATX commented
i think usaco editorials are well written for all their problems

2021-02-18 00:02 UTC, nwatx commented
> 
> 
> > > Oops I personally think we can find better videos (I think williamfiset videos or others are of a higher quality). But if others think the videos are fine then sure :)
> > 
> > 
> > yea i just took a look i feel like those vids are a little un serious xD
> 
> Sure. I would agree. However, I think adding some humor makes watching much more interesting. Also, he has a lot of USACO problem walkthroughs so could I add his vids for those?

personally I find that humor to be quite distracting from the essence of the video

2021-02-18 00:40 UTC, frodakcin commented on content/3_Silver/Sorting_Custom.mdx
> +			'Hard',
We told him to do this in the other PR

2021-02-18 00:41 UTC, frodakcin commented on content/3_Silver/Sorting_Custom.mdx
> +			'Normal',
idk how hard out of sorts is

2021-02-18 00:42 UTC, HarryWangATX commented on content/3_Silver/Sorting_Custom.mdx
> +			'Hard',
Ah

2021-02-21 00:14 UTC, closed without merging