Added solutions for the CCC string hashing focus problem
cpinitiative/usaco-guide pull request #814
Opened 2021-02-20 05:34 UTC by dolphingarlic

Two solutions:
- Sliding window + polynomial hash
- Modified hash + polynomial hash

2021-02-20 09:23 UTC, frodakcin reviewed
I think it's OK, just a few possible things to address:

2021-02-20 09:23 UTC, frodakcin commented on content/4_Gold/String_Hashing.mdx
> +**Time Complexity:** $\mathcal O(|N| + |H|)$.
log(mod) factor or K (# of characters) factor?

2021-02-20 14:38 UTC, bqi343 requested changes

2021-02-20 14:38 UTC, bqi343 commented on content/4_Gold/String_Hashing.mdx
> +The two base-modulo pairs $(9973, 10^9 + 9)$ and $(69420, 998244353)$ work for this problem.
using the same modulo twice with different bases, or the same base twice with different modulos suffices

2021-02-21 13:34 UTC, dolphingarlic commented
Also closes https://github.com/cpinitiative/usaco-guide/issues/813 now

2021-02-21 14:56 UTC, bqi343 requested changes

2021-02-21 14:56 UTC, bqi343 commented on content/4_Gold/String_Hashing.mdx
>  ## Tutorial
under Implementation - Single Base, mention the max probability of collision as given in the blog below. Also mention what exactly the single base implementation is calculating.

2021-02-21 14:56 UTC, bqi343 commented on content/4_Gold/String_Hashing.mdx
>  ## Tutorial
In particular, mention that both two bases and two mods are fine?

2021-02-21 14:56 UTC, bqi343 commented on content/4_Gold/String_Hashing.mdx
> +<Optional title="Probability of Collisions + Hashing a Tree">
I guess there isn't actually a need to mention this since it's already linked in the blog linked above.

2021-02-21 14:56 UTC, bqi343 commented on content/4_Gold/String_Hashing.mdx
>  ## Tutorial
update the list of authors

2021-02-22 00:26 UTC, frodakcin approved these changes
I think it's good (after you address benq)

2021-02-25 01:11 UTC, bqi343 requested changes

2021-02-25 01:11 UTC, bqi343 commented on content/4_Gold/String_Hashing.mdx
> +Since $10^9 + 9$ and $9973$ are both prime, the probability of collision when using this hash
it doesn't have anything to do with 9973 being prime.

2021-02-25 01:11 UTC, bqi343 commented on content/4_Gold/String_Hashing.mdx
> +is at most $\frac{N}{10^9 + 9} < 10^{-4}$, by the Schwarz-Zippel lemma.
Specify what the probability of collision means? If you select any two strings of length `<= N` and a random base modulo $10^9+9$ the probability that they hash to the same thing is at most $10^{-4}$.

2021-02-25 13:23 UTC, bqi343 requested changes

2021-02-25 13:23 UTC, bqi343 commented on content/4_Gold/String_Hashing.mdx
> +This means that if you select any two strings of length at most $N$ and a random base modulo $10^9 + 9$ (e.g. $9973$ in the code), the probability that they
(distinct) strings

2021-02-26 14:49 UTC, bqi343 approved these changes

2021-02-26 14:54 UTC, bqi343 commented
Though I don't think genetics qualifies as very hard if you know that it's hashing.

2021-02-26 17:17 UTC, dolphingarlic commented
Ok I'll change it to just 'Hard' then, and make the second COCI problem 'Very Hard'

2021-02-26 17:19 UTC, dongliu0426 approved these changes

2021-02-26 20:33 UTC, merged