Psums sol
cpinitiative/usaco-guide pull request #854
Opened 2021-02-24 20:23 UTC by HarryWangATX

2021-02-24 20:49 UTC, dongliu0426 requested changes
tabs :eyes:

2021-02-24 20:49 UTC, dongliu0426 commented on content/3_Silver/Prefix_Sums_2.mdx
> +    private static class Kattio extends PrintWriter {
replace this with `CodeSnip{Kattio}`?

2021-02-24 21:41 UTC, dongliu0426 approved these changes
spacing stuff

2021-02-24 21:41 UTC, dongliu0426 commented on content/3_Silver/Prefix_Sums_2.mdx
> +public class ForestQueries{
```suggestion
public class ForestQueries {
```

2021-02-24 21:41 UTC, dongliu0426 commented on content/3_Silver/Prefix_Sums_2.mdx
> +	public static void main(String[] args){
```suggestion
	public static void main(String[] args) {
```

2021-02-24 21:41 UTC, dongliu0426 commented on content/3_Silver/Prefix_Sums_2.mdx
> +				if(line.charAt(j) == '*'){
```suggestion
				if(line.charAt(j) == '*') {
```

2021-02-25 07:09 UTC, frodakcin commented on content/3_Silver/Prefix_Sums_2.mdx
> +	CodeSnip{Kattio}
```suggestion

	CodeSnip{Kattio}
```

Looks nicer with extra space.

Also, this doesn't compile... Kattio needs to be declared as "static"

2021-02-25 07:11 UTC, frodakcin commented on content/3_Silver/Prefix_Sums_2.mdx
> +	CodeSnip{Kattio}
However that will be a tomorrow problem (unless sm1 else takes care of it) cuz I gon go to sleep

2021-02-25 20:36 UTC, frodakcin approved these changes

2021-02-25 20:37 UTC, merged