C++ solution to Icy Perimeter
cpinitiative/usaco-guide pull request #894
Opened 2021-03-04 02:08 UTC by aldew5

2021-03-04 17:22 UTC, HarryWangATX requested changes
might have to change up program a bit.

2021-03-04 17:22 UTC, HarryWangATX commented on solutions/USACO feb19-perimeter-silver.mdx
> +}
can u be consitent with code style here?

2021-03-04 17:22 UTC, HarryWangATX commented on solutions/USACO feb19-perimeter-silver.mdx
> +int a, p;
just combine a,p with the first line.

2021-03-04 17:22 UTC, HarryWangATX commented on solutions/USACO feb19-perimeter-silver.mdx
> +#define FOR(i, a, b) for (int i = a; i < b; i++)
no loop macro

2021-03-04 17:22 UTC, HarryWangATX commented on solutions/USACO feb19-perimeter-silver.mdx
> +                }
this part can be more streamlined check official analysis

2021-03-04 17:22 UTC, HarryWangATX commented on solutions/USACO feb19-perimeter-silver.mdx
> +                }
might require some code changes in previous sections as well

2021-03-04 17:22 UTC, HarryWangATX commented on solutions/USACO feb19-perimeter-silver.mdx
> +        p ++;
official sol has a rly good impl for this

2021-03-04 17:24 UTC, HarryWangATX commented
this is rly simiar to offical sol 👀 🤷

2021-03-04 17:35 UTC, maggie-j-liu commented
Please follow the steps [here](https://usaco.guide/general/contributing?lang=cpp#adding-a-solution), in particular, make sure to modify the problem constructor and only use the macros mentioned there.

2021-03-04 20:19 UTC, jessechoe10 requested changes

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +#define check(x) cout<<(#x)<<": "<<x<<" " << endl;
remove this.

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +#define line cout << "--------------" << endl;
remove this aw

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +typedef unsigned long long ull;
remove this

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +int pct(int x) { return __builtin_popcount(x); }
remove this

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +    ff(r + 1, c);
`ff(r+1, c);`

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +    ff(r -1, c);
`ff(r-1, c);`

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +    ff(r, c + 1);
`ff(r, c+1);`

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +    ff(r, c -1);
`ff(r, c-1);`

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +    a ++;
`a++;`

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +        p ++;;
`p++;`

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +        p ++;
`p++;`

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +        p ++;
`p++;`

2021-03-04 20:19 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +    if (c + 1 < n && grid[r][c + 1] == '.' || c + 1 >= n)
put parentheses around your conditions so people aren't confused by the order of operations...

2021-03-04 20:20 UTC, jessechoe10 commented
I'm gonna try submitting my solution a bit later, so don't merge yet lol.

2021-03-04 23:05 UTC, maggie-j-liu commented
Also, use tabs instead of spaces.

2021-03-07 21:19 UTC, jessechoe10 commented
I think we can close this for now. When you fix the changes we requested, then submit another PR...

2021-03-07 21:19 UTC, closed without merging