Hide spoilers
cpinitiative/usaco-guide pull request #895
Opened 2021-03-04 02:45 UTC by MrinallU

2021-03-04 02:55 UTC, MrinallU commented
Proof of concept/intial logic seems to work fine.

2021-03-04 14:43 UTC, MrinallU commented
I think this should work.

2021-03-04 14:57 UTC, MrinallU commented
@thecodingwizard Resolved Issue #789

2021-03-04 17:52 UTC, thecodingwizard requested changes
Wait what we want is that if a code block is the only element of a spoiler, then the *code block* should not be expandable (it should just always be expanded). The *spoiler* should still function as normal, defaulting to collapsed and being able to expand/collapse when the user clicks on it. So you'll probably have to modify both the spoiler and the code block.

Also, there's two ways that there will only be a singular code block inside the spoiler:
- the child is a singular code block
- the child is a singular language section and each language section only has a singular child that's a code block

2021-03-04 18:00 UTC, MrinallU commented
Where can I find the code for the individual language section?

2021-03-04 18:05 UTC, thecodingwizard commented
https://github.com/cpinitiative/usaco-guide/blob/master/src/components/markdown/LanguageSection.tsx

2021-03-04 18:14 UTC, MrinallU commented
Actually I kinda meant the code for the code blocks inside the language
section so I can make the code block non expandable.

On Thu, Mar 4, 2021 at 12:52 PM Nathan Wang <notifications@github.com>
wrote:

> *@thecodingwizard* requested changes on this pull request.
>
> Wait what we want is that if a code block is the only element of a
> spoiler, then the *code block* should not be expandable (it should just
> always be expanded). The *spoiler* should still function as normal,
> defaulting to collapsed and being able to expand/collapse when the user
> clicks on it. So you'll probably have to modify both the spoiler and the
> code block.
>
> Also, there's two ways that there will only be a singular code block
> inside the spoiler:
>
>    - the child is a singular code block
>    - the child is a singular language section and each language section
>    only has a singular child that's a code block
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cpinitiative/usaco-guide/pull/895#pullrequestreview-604387074>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOVN6SLG6ECYQSOKKNBXZ23TB7CHLANCNFSM4YSMOFIQ>
> .
>

2021-03-04 18:26 UTC, thecodingwizard commented
https://github.com/cpinitiative/usaco-guide/blob/master/src/components/markdown/CodeBlock/CodeBlock.tsx

2021-03-04 22:31 UTC, MrinallU commented
> Wait what we want is that if a code block is the only element of a spoiler, then the _code block_ should not be expandable (it should just always be expanded). The _spoiler_ should still function as normal, defaulting to collapsed and being able to expand/collapse when the user clicks on it. So you'll probably have to modify both the spoiler and the code block.
> 
> Also, there's two ways that there will only be a singular code block inside the spoiler:
> 
> * the child is a singular code block
> * the child is a singular language section and each language section only has a singular child that's a code block

Will do.

2021-03-08 04:09 UTC, dongliu0426 commented
closes #789

2021-03-13 01:26 UTC, MrinallU commented
@thecodingwizard So I'm able to pass the expandable prop from the Spoiler to the language section pretty fine but then the new prop does not seem to be transferred to the code block. As a result, I'm fairly sure that the children of the LanguageSection.tsx don't directly go to the CodeBlock.tsx component. As such,  do you know where the children and props of the LanguageSection.tsx file go to next?

2021-03-13 02:17 UTC, thecodingwizard commented
probably here: https://github.com/cpinitiative/usaco-guide/pull/895/files#diff-8996b64bdddc8b53b263fe009ad522143714ec06c36b45f17bf1b78d452d3076R111-R121

2021-03-21 20:25 UTC, closed without merging