Various problems
cpinitiative/usaco-guide pull request #906
Opened 2021-03-05 18:39 UTC by dolphingarlic

Just some problems from OIs (many have official editorials, but I didn't link them yet)

2021-03-05 18:45 UTC, jessechoe10 commented
Fix the failed checks...

2021-03-05 20:43 UTC, bqi343 requested changes

2021-03-06 08:50 UTC, dolphingarlic commented on content/4_Gold/MST.mdx
> +			'2008 - Information',
I think the official editorial has one: https://www.ceoi2008.de/files/short-spoiler.pdf

I never actually tried this problem yet

2021-03-06 08:50 UTC, dolphingarlic commented on content/4_Gold/MST.mdx
> +		new Problem(
Should I just mark them as "Insane" then? I think they're great problems for practice and there isn't really anywhere else to put them

2021-03-06 13:49 UTC, bqi343 reviewed
> I think the official editorial has one:

https://codeforces.com/blog/entry/68131

Doesn't seem like anyone has a simple implementation?

> I think they're great problems for practice

I disagree ... I think adding the IOI 2016 problem, in particular, is sort of a spoiler (and isn't really useful to anyone)? I also don't think directed MST is relevant to undirected MST.

2021-03-07 19:32 UTC, dolphingarlic commented
@bqi343 I removed IOI Railroad and CEOI Information, but kept APIO Toll and just marked it as "Insane"

2021-03-07 19:33 UTC, dolphingarlic commented
Also, should I display the radial sweep problems or should I leave that for another PR?

2021-03-08 00:12 UTC, bqi343 commented
Display them.

2021-03-09 17:16 UTC, dolphingarlic commented
@bqi343 is it good to merge? I can't re-request a review from you for some reason

2021-03-09 17:56 UTC, bqi343 approved these changes

2021-03-09 18:03 UTC, merged