CPP Solution to Icy Perimeter
cpinitiative/usaco-guide pull request #932
Opened 2021-03-09 03:58 UTC by aldew5

Revised

2021-03-09 04:17 UTC, maggie-j-liu commented
> Please follow the steps [here](https://usaco.guide/general/contributing?lang=cpp#adding-a-solution), in particular, make sure to modify the problem constructor and only use the macros mentioned there.
> Also, use tabs instead of spaces.

Your solution for revegetate is also included; could you delete it?

2021-03-09 18:27 UTC, aldew5 commented
@maggie-j-liu the other file has been deleted.  In terms of updating the constructor, I looked at it and wasn't sure what to include.  The step shown in the contributing section of the guide seemed to already have been completed.  Also, I did you use tabs.  I think when I pasted my code into the template it formatted as spaces.  I can probably figure out how to correct this if that's necessary.

2021-03-09 18:45 UTC, andrewwangva requested changes

2021-03-13 23:27 UTC, dongliu0426 commented
marking this as a draft for now; open this after the requested changes are fixed.

2021-03-19 20:37 UTC, jessechoe10 commented on solutions/USACO feb19-perimeter-silver.mdx
> +This problem can be solved using [Flood Fill](/silver/flood fill) (a Silver topic).
We don't need this unless you're addressing a topic from a higher division

2021-03-19 20:38 UTC, jessechoe10 commented
I'm gonna close this PR for now. We can implement your PR once you address the changes.

2021-03-19 20:38 UTC, closed without merging