DFS/Bipartite (Silver) the great revegetation solution
cpinitiative/usaco-guide pull request #941
Opened 2021-03-09 22:42 UTC by TruaShamu

1. Made new markdown file for the great revegetation (usaco920) with java solution
2. Added the new solution link to the problem constructor in bipartite/dfs

This is my first pull so if I did anything wrong please let me know

2021-03-09 23:00 UTC, frodakcin commented
Thanks for contributing! Your solution file should match the format shown here: https://usaco.guide/general/contributing/#adding-a-solution

Specifically, you need the "header"

ex:
```
---
id: usaco-920
source: USACO Silver [year?] [Month?]
title: ???
author: ???
---
```

2021-03-09 23:25 UTC, maggie-j-liu commented
Also, use tabs instead of spaces to indent.

2021-03-10 00:06 UTC, maggie-j-liu commented
The change to tabs was reverted by the next commit...

2021-03-10 00:11 UTC, TruaShamu commented
Sorry, it should be fixed now.
Thanks @dongliu0426 for helping me :)

2021-03-10 00:46 UTC, maggie-j-liu commented
I still don't see it... did you commit?

2021-03-10 01:26 UTC, TruaShamu commented
It's [here](https://usaco-guide-lhtmer38o-cpinitiative.vercel.app/solutions/usaco-920?lang=cpp)?

2021-03-10 01:36 UTC, dongliu0426 commented
> It's [here](https://usaco-guide-lhtmer38o-cpinitiative.vercel.app/solutions/usaco-920?lang=cpp)?

Maggie meant the commit changing spaces to tabs got reverted (i.e. [this commit](https://github.com/cpinitiative/usaco-guide/pull/941/commits/fe4f7e45d48429b3647379056c46f39c49a18a9e)).

2021-03-10 01:56 UTC, TruaShamu commented
Sorry, I fixed the indentation now.

2021-03-10 02:03 UTC, maggie-j-liu requested changes

2021-03-10 03:30 UTC, dongliu0426 requested changes

2021-03-10 03:30 UTC, dongliu0426 commented on solutions/USACO feb19-the-great-revegetation.mdx
> +		for (int i = 0; i < N + 1; i++) {
```suggestion
		for (int i = 0; i <= N; i++) {
```
inconsistent formatting (used `for (int i = 0; i <= N; i++)` below) change this or the one below

2021-03-10 16:16 UTC, maggie-j-liu approved these changes

2021-03-10 18:28 UTC, merged