Removed template from solution for CSES Planets Queries II
cpinitiative/usaco-guide pull request #982
Opened 2021-03-16 16:24 UTC by izhang05

2021-03-16 18:45 UTC, dongliu0426 requested changes
use tabs

2021-03-16 20:25 UTC, izhang05 commented
ok I changed to tabs

2021-03-16 20:31 UTC, dongliu0426 approved these changes

2021-03-16 22:08 UTC, bqi343 requested changes

2021-03-16 22:08 UTC, bqi343 commented on solutions/CSES Planets Queries II.mdx
> +	for (int i = 1; i < n + 1; ++i) {
replace `< n+1` with `<= n` everywhere

2021-03-16 22:08 UTC, bqi343 commented on solutions/CSES Planets Queries II.mdx
> +	for (int i = (18) - 1; i >= 0; --i) {
why parentheses around 18?

2021-03-19 23:31 UTC, frodakcin commented
I feel like those are more of personal preference? I think they don't cause any confusion

2021-04-02 03:01 UTC, bqi343 commented
> I feel like those are more of personal preference? I think they don't cause any confusion

Well, I'm still waiting for these changes ... why would you prefer `< n+1` over `<= n` ^_^

2021-04-06 00:22 UTC, frodakcin commented
Well I'd prefer `<=n` but don't think it's significant enough to warrant requesting author to change?

2021-04-06 00:27 UTC, frodakcin commented
Ohhh I see: A direct demacrofier was used so the weird code style is to be consistent with the macro as opposed to being author's choice.

Yea, in that case, it does makes sense to request getting rid of the extra stuff.

2021-04-09 00:51 UTC, bqi343 commented
Closing due to inactivity.

2021-04-09 00:51 UTC, closed without merging