Mini editorial for IOI 2013 Game
cpinitiative/usaco-guide pull request #995
Opened 2021-03-19 16:20 UTC by dolphingarlic

There's not a lot to say about this problem...

2021-03-19 16:56 UTC, bqi343 commented
segment tree of sparse segment trees was intended though (using the optional note here - https://usaco.guide/plat/sparse-seg?lang=cpp#solution)

2021-03-19 17:11 UTC, bqi343 requested changes

2021-03-19 17:11 UTC, bqi343 commented on solutions/IOI 13-game.mdx
> +It's possible (and probably intended) to solve this problem using a segment trees
It \*is\* intended. I'm pretty sure I remember reading about this, though I can't find it ...

Preferably include such a solution

2021-03-22 16:50 UTC, bqi343 requested changes

2021-03-22 16:50 UTC, bqi343 commented on solutions/IOI 13-game.mdx
> +$\mathcal O(N \log N)$ to $\mathcal O(N)$.
Wouldn't it be N log(max value), not N log N?

2021-03-26 15:53 UTC, dolphingarlic commented
@bqi343 bump

2021-03-26 16:03 UTC, bqi343 requested changes

2021-03-26 16:03 UTC, bqi343 commented on solutions/IOI 13-game.mdx
> +Although BBSTs use 4 times less memory than segment trees, a BBST of BBSTs is
> a BBST of BBSTs is not possible

er actually range trees are BBSTs of BBSTs https://en.wikipedia.org/wiki/Range_tree

if the tree gets too unbalanced after a certain # of insertions then you end up rebuilding an entire subtree I think

2021-03-27 13:24 UTC, bqi343 approved these changes

2021-03-27 13:29 UTC, merged